// Auto-generated by Antigravity Script
import { Question } from '../../../../types';

export const MODERN_CHAPTER_14_MCQS: any[] = [
  {
    id: '13-56',
    question: "The 'Home Rule League' movement is considered a precursor to the Gandhian mass movements because:",
    options: ["It for the first time used the methods of fast-unto-death and picketing.", "It created a network of local branches and trained political workers who later formed the backbone of the Non-Cooperation movement.", "It was the first movement to be led by Mahatma Gandhi himself.", "It successfully abolished the Salt Tax."],
    correctAnswer: 1,
    explanation: "It created a network and trained political workers.",
    chapterId: 13,
    difficulty: 'Hard'
  },
  {
    id: '14-2',
    question: "Mahatma Gandhi returned to India from South Africa on:",
    options: ["January 9, 1914", "January 9, 1915", "January 26, 1915", "October 2, 1915"],
    correctAnswer: 1,
    explanation: "January 9, 1915",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-3',
    question: "Who was considered the political guru of Mahatma Gandhi in India?",
    options: ["Bal Gangadhar Tilak", "Gopal Krishna Gokhale", "Dadabhai Naoroji", "Pherozeshah Mehta"],
    correctAnswer: 1,
    explanation: "Gopal Krishna Gokhale",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-4',
    question: "Gandhi founded the Sabarmati Ashram in Ahmedabad in:",
    options: ["1915", "1916", "1917", "1918"],
    correctAnswer: 0,
    explanation: "1915 (Initially at Kochrab, shifted to Sabarmati in 1917)",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-5',
    question: "The 'Champaran Satyagraha' (1917) was related to the grievances of the cultivators of:",
    options: ["Cotton", "Indigo", "Opium", "Sugar"],
    correctAnswer: 1,
    explanation: "Indigo",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-6',
    question: "Under the Tinkathia system in Champaran, peasants were forced to grow indigo on:",
    options: ["3/10th of their land", "3/20th of their land", "1/3rd of their land", "5/20th of their land"],
    correctAnswer: 1,
    explanation: "3/20th of their land",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-7',
    question: "Who invited Gandhi to Champaran to look into the problems of the peasants?",
    options: ["Raj Kumar Shukla", "Brajkishore Prasad", "Rajendra Prasad", "J.B. Kripalani"],
    correctAnswer: 0,
    explanation: "Raj Kumar Shukla",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-8',
    question: "The 'Ahmedabad Mill Strike' (1918) involved a dispute between workers and owners over:",
    options: ["Working hours", "Plague Bonus", "Housing allowance", "Salt tax"],
    correctAnswer: 1,
    explanation: "Plague Bonus",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-9',
    question: "In which of the following movements did Gandhi use the weapon of 'Hunger Strike' for the first time in India?",
    options: ["Champaran Satyagraha", "Ahmedabad Mill Strike", "Kheda Satyagraha", "Rowlatt Satyagraha"],
    correctAnswer: 1,
    explanation: "Ahmedabad Mill Strike",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-10',
    question: "The 'Kheda Satyagraha' (1918) was launched because the government refused to remit land revenue despite:",
    options: ["A plague epidemic", "Failure of crops due to drought", "Excess of taxes", "Fall in global prices"],
    correctAnswer: 1,
    explanation: "Failure of crops due to drought",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-11',
    question: "Who was Gandhi\u2019s main lieutenant during the Kheda Satyagraha?",
    options: ["Jawaharlal Nehru", "Vallabhbhai Patel", "Mahadev Desai", "Narhari Parikh"],
    correctAnswer: 1,
    explanation: "Vallabhbhai Patel",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-12',
    question: "The Rowlatt Act (1919) was officially known as the:",
    options: ["Seditious Meetings Act", "Anarchical and Revolutionary Crimes Act", "Defence of India Act", "Indian Press Act"],
    correctAnswer: 1,
    explanation: "Anarchical and Revolutionary Crimes Act",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-13',
    question: "The Rowlatt Act allowed the government to imprison people without trial for a period of:",
    options: ["One year", "Two years", "Three years", "Five years"],
    correctAnswer: 1,
    explanation: "Two years",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-14',
    question: "Gandhi formed the 'Satyagraha Sabha' to protest against the:",
    options: ["Partition of Bengal", "Rowlatt Act", "Simon Commission", "Hunter Commission"],
    correctAnswer: 1,
    explanation: "Rowlatt Act",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-15',
    question: "The Jallianwala Bagh Massacre took place on which festival day?",
    options: ["Holi", "Baisakhi", "Diwali", "Eid"],
    correctAnswer: 1,
    explanation: "Baisakhi (April 13, 1919)",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-16',
    question: "Who was the British officer responsible for ordering the firing at Jallianwala Bagh?",
    options: ["General Dyer", "Michael O'Dwyer", "Lord Chelmsford", "General Hudson"],
    correctAnswer: 0,
    explanation: "General Dyer",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-17',
    question: "Who renounced his Knighthood in protest against the Jallianwala Bagh Massacre?",
    options: ["Mahatma Gandhi", "Rabindranath Tagore", "S. Subramania Aiyar", "Motilal Nehru"],
    correctAnswer: 1,
    explanation: "Rabindranath Tagore",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-18',
    question: "Which commission was appointed by the government to investigate the Jallianwala Bagh incident?",
    options: ["Simon Commission", "Hunter Commission", "Butler Commission", "Whitley Commission"],
    correctAnswer: 1,
    explanation: "Hunter Commission (Disorders Inquiry Committee)",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-19',
    question: "Gandhi returned which medal, given for his work in the Boer War, in protest against the Jallianwala Bagh tragedy?",
    options: ["Knighthood", "Kaiser-i-Hind", "Victoria Cross", "Legion of Honour"],
    correctAnswer: 1,
    explanation: "Kaiser-i-Hind",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-20',
    question: "The 'Servants of India Society' was founded by G.K. Gokhale. Which of the following leaders did NOT join it because of ideological differences with Gokhale?",
    options: ["Mahadev Desai", "Mahatma Gandhi", "Srinivasa Sastri", "N.M. Joshi"],
    correctAnswer: 1,
    explanation: "Mahatma Gandhi (Though he wanted to, the members were divided on his membership).",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-21',
    question: "In South Africa, Gandhi set up which farm to house his Satyagrahis?",
    options: ["Phoenix Farm", "Tolstoy Farm", "Sabarmati Farm", "Both A and B"],
    correctAnswer: 3,
    explanation: "Both A and B",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-22',
    question: "The journal Indian Opinion was started by Gandhi in:",
    options: ["India", "South Africa", "England", "USA"],
    correctAnswer: 1,
    explanation: "South Africa",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-23',
    question: "The passive resistance organization founded by Gandhi in South Africa in 1894 was:",
    options: ["Natal Indian Congress", "South African Indian Congress", "Transvaal Indian Association", "Satyagraha Sabha"],
    correctAnswer: 0,
    explanation: "Natal Indian Congress",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-24',
    question: "Which British judge presided over the Rowlatt Committee?",
    options: ["Justice Rowlatt", "Justice Hunter", "Justice Strachey", "Justice Broomfield"],
    correctAnswer: 0,
    explanation: "Justice Rowlatt",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-25',
    question: "The term 'Satyagraha' was coined by Gandhi to distinguish his method from:",
    options: ["Armed Revolution", "Passive Resistance", "Non-Cooperation", "Constitutional Agitation"],
    correctAnswer: 1,
    explanation: "Passive Resistance (He felt Satyagraha was more active and based on soul-force).",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-26',
    question: "Who was the Lieutenant Governor of Punjab during the Jallianwala Bagh Massacre?",
    options: ["General Dyer", "Michael O'Dwyer", "Lord Curzon", "Sir John Simon"],
    correctAnswer: 1,
    explanation: "Michael O'Dwyer",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-27',
    question: "Gandhi\u2019s first all-India political movement was the:",
    options: ["Champaran Satyagraha", "Rowlatt Satyagraha", "Non-Cooperation Movement", "Civil Disobedience Movement"],
    correctAnswer: 1,
    explanation: "Rowlatt Satyagraha (Champaran, Ahmedabad, and Kheda were local/regional).",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-28',
    question: "The slogan \"No Dalal, No Vakil, No Appeal\" was associated with the protest against:",
    options: ["Vernacular Press Act", "Rowlatt Act", "Ilbert Bill", "Simon Commission"],
    correctAnswer: 1,
    explanation: "Rowlatt Act",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-29',
    question: "In Champaran, Gandhi was assisted by which future President of India?",
    options: ["Jawaharlal Nehru", "Dr. Rajendra Prasad", "S. Radhakrishnan", "V.V. Giri"],
    correctAnswer: 1,
    explanation: "Dr. Rajendra Prasad",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-30',
    question: "Following the Jallianwala Bagh Massacre, Gandhi called off the Rowlatt Satyagraha on April 18, 1919, calling it a:",
    options: ["\"Successful experiment\"", "\"Himalayan Blunder\"", "\"Divine intervention\"", "\"Temporary setback\""],
    correctAnswer: 1,
    explanation: "\"Himalayan Blunder\"",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-31',
    question: "Who was the only Indian member of the Hunter Committee who submitted a minority report?",
    options: ["Chimanlal Setalvad", "Pandit Jagat Narayan", "Sultan Ahmed Khan", "All of the above (These three were the Indian members)"],
    correctAnswer: 3,
    explanation: "All of the above (The three Indian members signed a separate, more critical report).",
    chapterId: 14,
    difficulty: 'Easy'
  },
  {
    id: '14-32',
    question: "Mahatma Gandhi\u2019s experience in South Africa was the 'laboratory' for his later movements in India. Which of the following techniques did he develop and refine during his struggle against the 'Apartheid' regime?",
    options: ["The use of the 'Charkha' as a symbol of economic protest.", "The concept of 'Satyagraha'\u2014a non-violent struggle based on truth and soul-force, involving civil disobedience and the ready acceptance of suffering.", "The formation of secret societies to carry out assassinations of high-ranking officials.", "The demand for a separate state for Indian immigrants in Africa."],
    correctAnswer: 1,
    explanation: "The concept of 'Satyagraha'. Gandhi evolved Satyagraha through his struggle against the $3$ pound poll tax, the invalidation of non-Christian marriages, and the Asiatic Registration Act in South Africa.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-33',
    question: "Consider the following statements regarding the 'Champaran Satyagraha' (1917):\n1. It was Gandhi\u2019s first experiment with Satyagraha on Indian soil.\n2. The primary issue was the Tinkathia system, where peasants were forced to grow indigo on $3/20$th of their holdings.\n3. Gandhi demanded and successfully achieved the complete abolition of all taxes for the peasants of Champaran. Which of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2, and 3"],
    correctAnswer: 0,
    explanation: "1 and 2 only Statement 3 is incorrect. Gandhi reached a compromise where the planters were to refund $25\\%$ of the money they had illegally taken from the peasants, rather than a total tax abolition.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-34',
    question: "The 'Ahmedabad Mill Strike' (1918) saw Gandhi intervening in a localized industrial dispute. What was the unique outcome of this intervention?",
    options: ["It led to the nationalization of all textile mills in Gujarat.", "It was the first time Gandhi used a 'Fast unto Death' to exert pressure on the mill owners, eventually securing a $35\\%$ wage hike for the workers.", "It resulted in the workers taking over the ownership of the mills.", "The British government arrested all the mill owners immediately."],
    correctAnswer: 1,
    explanation: "First use of a hunger strike to secure a $35\\%$ wage hike.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-35',
    question: "During the 'Kheda Satyagraha' (1918), the government insisted on full revenue collection despite a total crop failure. What was Gandhi\u2019s advice to the peasants?",
    options: ["To burn the government records and move to the forests.", "To refuse to pay the revenue and remain non-violent even in the face of confiscation of property.", "To seek an alliance with the Ghadarites to launch an armed revolt.", "To pay the taxes under protest and file a case in the London High Court."],
    correctAnswer: 1,
    explanation: "Refuse to pay revenue and remain non-violent.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-36',
    question: "Consider the following regarding the 'Rowlatt Act' (1919): Statement-I: The Act was based on the recommendations of the Sedition Committee headed by Justice Rowlatt. Statement-II: It aimed at curbing the revolutionary activities by allowing the detention of political prisoners without trial for up to two years. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 0,
    explanation: "Both statements are correct.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-37',
    question: "The 'Satyagraha Sabha' formed by Gandhi to protest the Rowlatt Act marked a shift in Indian politics because it:",
    options: ["Was the first time a major political movement ignored the urban areas and focused only on villages.", "Mobilized the youth, students, and artisans, shifting the struggle from purely constitutional methods to mass action.", "Was supported by the British Viceroy Lord Chelmsford.", "Aimed at making India a province of the United States."],
    correctAnswer: 1,
    explanation: "Shifting the struggle to mass action.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-38',
    question: "The Jallianwala Bagh Massacre (April 13, 1919) was a turning point. Why were the people gathered in the Bagh on that day?",
    options: ["To celebrate the victory of the British in World War I.", "To celebrate the Baisakhi festival and to protest against the arrest of their local leaders, Dr. Saifuddin Kitchlew and Dr. Satyapal.", "To plan a secret armed raid on the Amritsar treasury.", "To welcome Mahatma Gandhi to Punjab."],
    correctAnswer: 1,
    explanation: "Celebrate Baisakhi and protest the arrest of leaders.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-39',
    question: "How did the 'Hunter Commission' (1919) handle the investigation into the Jallianwala Bagh massacre?",
    options: ["It recommended the immediate hanging of General Dyer.", "It essentially exonerated Dyer by calling his actions a \"grave error of judgment\" rather than a crime, though he was eventually removed from active service.", "it rewarded General Dyer with the title of 'Knight of the Garter'.", "It completely ignored the incident and focused only on the Rowlatt Act."],
    correctAnswer: 1,
    explanation: "Exonerated him as a \"grave error of judgment\".",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-40',
    question: "Rabindranath Tagore renounced his Knighthood in response to the Punjab wrongs. How did Gandhi react officially?",
    options: ["He renounced his title of 'Mahatma'.", "He returned the Kaiser-i-Hind gold medal, which had been awarded to him for his humanitarian work in the Boer War.", "He joined the British Army to change it from within.", "He moved to London to practice law again."],
    correctAnswer: 1,
    explanation: "Returned the Kaiser-i-Hind medal.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-41',
    question: "Consider the following regarding the early Gandhian movements:\n1. Champaran \u2014 First Civil Disobedience\n2. Ahmedabad \u2014 First Hunger Strike\n3. Kheda \u2014 First Non-Cooperation How many of the above pairs are correctly matched in their 'type' of struggle?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-42',
    question: "The 'Rowlatt Satyagraha' was eventually called off by Gandhi on April 18, 1919. What was the primary reason?",
    options: ["The British government repealed the Act immediately.", "The movement turned violent in several places, and Gandhi felt the people were not yet trained in the discipline of non-violence.", "The Muslim League withdrew its support.", "Gandhi was appointed to the Viceroy's Executive Council."],
    correctAnswer: 1,
    explanation: "Movement turned violent and lack of training in non-violence.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-43',
    question: "What was the primary difference between Gandhi\u2019s 'Satyagraha' and the earlier 'Passive Resistance' used by the Extremists?",
    options: ["There was no difference; they were identical.", "Passive resistance was a political weapon used by the weak, while Satyagraha was a moral weapon used by the strong that renounced all forms of hatred.", "Satyagraha allowed for the use of small weapons if necessary.", "Passive resistance was only used in villages."],
    correctAnswer: 1,
    explanation: "Satyagraha was a moral weapon of the strong.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-44',
    question: "In the 'Kheda Satyagraha', who among the following emerged as a prominent leader and organized the peasants to stand firm?",
    options: ["Jawaharlal Nehru", "Vallabhbhai Patel", "Subhash Chandra Bose", "Bhagat Singh"],
    correctAnswer: 1,
    explanation: "Vallabhbhai Patel.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-45',
    question: "The 'Tinkathia' system in Champaran was replaced by which arrangement after Gandhi\u2019s intervention?",
    options: ["Complete ownership of land by the peasants.", "An agreement where planters could take only $1/20$th of the land for indigo.", "The abolition of the forced indigo cultivation and a partial refund of the illegal dues collected from the peasants.", "A new tax on British cloth."],
    correctAnswer: 2,
    explanation: "Abolition of forced cultivation and partial refund.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-46',
    question: "Ultimately, the 'Emergence of Gandhi' (1915-1919) changed the character of the Indian National Congress by:",
    options: ["Making it a purely pro-British administrative body.", "Transforming it into a mass-based revolutionary organization that utilized a unique blend of morality and politics to challenge the British Empire.", "Restricting its membership only to those who knew Sanskrit.", "Moving its headquarters to London."],
    correctAnswer: 1,
    explanation: "Transforming it into a mass-based organization.",
    chapterId: 14,
    difficulty: 'Moderate'
  },
  {
    id: '14-47',
    question: "Consider the following statements regarding the 'Champaran Satyagraha' (1917):\n1. It was the first time Gandhi used the method of 'Civil Disobedience' in India by refusing to obey an official order to leave the district.\n2. The Tinkathia system required peasants to cultivate indigo on $3/20$th of their total landholdings under pain of illegal exactions.\n3. The European planters eventually agreed to refund the entire amount of illegally collected money to the peasants to avoid further unrest. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 2 are correct. Statement 3 is incorrect; as a compromise, the planters agreed to refund only 25% of the money taken illegally, a move Gandhi accepted to break the planters' prestige.",
    chapterId: 14,
    difficulty: 'Hard'
  },
  {
    id: '14-48',
    question: "With reference to the 'Ahmedabad Mill Strike' (1918) and 'Kheda Satyagraha' (1918), consider the following: Statement-I: In the Ahmedabad strike, Gandhi\u2019s primary demand was a 35% wage increase for the workers to compensate for the withdrawal of the 'Plague Bonus'. Statement-II: In the Kheda Satyagraha, the struggle was against the British government's refusal to grant revenue remission despite a crop yield of less than one-fourth. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 1,
    explanation: "Both Statement-I and Statement-II are correct Both statements are factually correct descriptions of the respective movements, but the issues (industrial vs. agrarian) are independent of each other.",
    chapterId: 14,
    difficulty: 'Hard'
  },
  {
    id: '14-49',
    question: "Arrange the following events related to the early Gandhian phase in correct chronological order:\n1. Foundation of the Satyagraha Sabha.\n2. The Ahmedabad Mill Strike.\n3. The Kheda Satyagraha.\n4. The Champaran Satyagraha. Select the correct answer using the code given below:",
    options: ["4 \u2014 2 \u2014 3 \u2014 1", "4 \u2014 3 \u2014 2 \u2014 1", "2 \u2014 4 \u2014 3 \u2014 1", "4 \u2014 2 \u2014 1 \u2014 3"],
    correctAnswer: 0,
    explanation: "4 \u2014 2 \u2014 3 \u2014 1 Champaran (1917) -> Ahmedabad (March 1918) -> Kheda (June 1918) -> Satyagraha Sabha (Feb 1919).",
    chapterId: 14,
    difficulty: 'Hard'
  },
  {
    id: '14-50',
    question: "Consider the following pairs of leaders and the early Gandhian movements they were associated with:\n1. Raj Kumar Shukla \u2014 Champaran Satyagraha\n2. Anusuya Sarabhai \u2014 Ahmedabad Mill Strike\n3. Indulal Yagnik \u2014 Kheda Satyagraha\n4. Mahadev Desai \u2014 Rowlatt Satyagraha How many of the above pairs are correctly matched?",
    options: ["Only one pair", "Only two pairs", "Only three pairs", "All four pairs"],
    correctAnswer: 3,
    explanation: "All four pairs",
    chapterId: 14,
    difficulty: 'Hard'
  },
  {
    id: '14-51',
    question: "Regarding the 'Rowlatt Act' (1919), consider the following statements:\n1. It allowed the government to search any premises without a warrant and detain suspects for two years without trial.\n2. The Act was passed unanimously by the Imperial Legislative Council with the support of both Indian and British members.\n3. Gandhi organized the first all-India 'Hartal' (strike) on April 6, 1919, as a form of non-violent protest against the Act. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 3 are correct. Statement 2 is incorrect; every single Indian member of the council (including Jinnah, Malaviya, and Mazhar-ul-Haq) voted against it.",
    chapterId: 14,
    difficulty: 'Hard'
  },
  {
    id: '14-52',
    question: "\"He was a former president of the Muslim League who resigned from the Imperial Legislative Council in protest against the Rowlatt Act, stating that a government that passes such a law in peacetime forfeits its claim to be called a civilized government.\" The above description refers to:",
    options: ["Maulana Abul Kalam Azad", "Muhammad Ali Jinnah", "Mazhar-ul-Haq", "Hakim Ajmal Khan"],
    correctAnswer: 1,
    explanation: "Muhammad Ali Jinnah",
    chapterId: 14,
    difficulty: 'Hard'
  },
  {
    id: '14-53',
    question: "With reference to the 'Hunter Committee' (Disorders Inquiry Committee) appointed after the Jallianwala Bagh massacre, consider the following: Statement-I: The Committee consisted of both British and Indian members. Statement-II: The Indian members, including Sir Chimanlal Setalvad, submitted a minority report that was more critical of General Dyer's actions than the majority report. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 1,
    explanation: "Both Statement-I and Statement-II are correct",
    chapterId: 14,
    difficulty: 'Hard'
  },
  {
    id: '14-54',
    question: "Match the following 'Firsts' of Gandhi's political career in India:\n1. First Civil Disobedience \u2014",
    options: ["Kheda Satyagraha 2. First Hunger Strike \u2014", "Rowlatt Satyagraha 3. First Non-Cooperation \u2014", "Champaran Satyagraha 4. First All-India Mass Strike \u2014", "Ahmedabad Mill Strike Select the correct matching code:"],
    correctAnswer: 0,
    explanation: "1-C, 2-D, 3-A, 4-B",
    chapterId: 14,
    difficulty: 'Hard'
  },
  {
    id: '14-55',
    question: "Consider the following regarding Gandhi's struggle in South Africa (1893-1914):\n1. He founded the Natal Indian Congress and started the journal Indian Opinion.\n2. He used the method of 'Passive Resistance' for the first time against the Asiatic Registration Act.\n3. The struggle culminated in the Indian Relief Act, which abolished the $3$ pound poll tax and recognized Indian marriages. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three",
    chapterId: 14,
    difficulty: 'Hard'
  },
];