
import os
import re

OUTPUT_DIR = r'D:\Graphology\Master Software\Eduecosystem\frontend\src\components\batch1-1\polity\data\chapters'

def write_chapter(tid, l1, l2, l3):
    out = os.path.join(OUTPUT_DIR, f'chapter-{tid}.ts')
    with open(out, 'w', encoding='utf-8') as f:
        f.write("import { ChapterLevelData } from '../level-types';\n\n")
        def write_level(name, qs):
            f.write(f"const {name} = [\n")
            for i, q in enumerate(qs):
                qtext = q[0].replace('"', '\\"')
                opts = q[1]
                ca = q[2]
                exp = q[3].replace('"', '\\"')
                opts_str = ', '.join(['"' + o.replace('"', '\\"') + '"' for o in opts])
                f.write(f'    {{\n')
                f.write(f'        "id": "ch{tid}-{name.lower().replace("_questions","").replace("level_","l")}-q{i+1}",\n')
                f.write(f'        "question": "{qtext}",\n')
                f.write(f'        "options": [{opts_str}],\n')
                f.write(f'        "correctAnswerIndex": {ca},\n')
                f.write(f'        "explanation": "{exp}"\n')
                f.write(f'    }}{"," if i < len(qs)-1 else ""}\n')
            f.write("];\n\n")
        write_level("LEVEL_1_QUESTIONS", l1)
        write_level("LEVEL_2_QUESTIONS", l2)
        write_level("LEVEL_3_QUESTIONS", l3)
        f.write(f"export const CHAPTER_{tid}_LEVELS: ChapterLevelData = {{\n")
        f.write(f"    level1: LEVEL_1_QUESTIONS,\n")
        f.write(f"    level2: LEVEL_2_QUESTIONS,\n")
        f.write(f"    level3: LEVEL_3_QUESTIONS\n")
        f.write(f"}};\n")
    print(f"  Written chapter-{tid}.ts ({len(l1)+len(l2)+len(l3)} Qs)")

# ========================================
# CHAPTER 37: Consumer Commissions
# ========================================
ch37_l1 = [
    ("The Consumer Protection Act, 2019 replaced which earlier Act?", ["Consumer Protection Act, 1956", "Consumer Protection Act, 1986", "Trade Act, 2000", "Competition Act, 2002"], 1, "The Consumer Protection Act, 2019 replaced the Consumer Protection Act, 1986."),
    ("The Consumer Protection Act, 2019 came into force on:", ["1st January 2020", "20th July 2020", "15th August 2019", "26th January 2020"], 1, "The Act came into force on 20th July 2020."),
    ("Who is a 'consumer' under the Consumer Protection Act, 2019?", ["Only a buyer of goods", "Any person who buys goods or hires/avails services for consideration", "Only a seller", "Only a manufacturer"], 1, "A consumer is any person who buys goods or hires/avails services for consideration, including online transactions."),
    ("Which of the following is NOT a right of the consumer?", ["Right to safety", "Right to be informed", "Right to manufacture goods", "Right to seek redressal"], 2, "The right to manufacture goods is not a consumer right. Consumer rights include safety, information, choice, hearing, redressal, and education."),
    ("The three-tier consumer dispute redressal system consists of:", ["District, State, and National Consumer Disputes Redressal Commissions", "Lok Adalat, High Court, Supreme Court", "Gram Nyayalaya, District Court, High Court", "Tribunals, High Court, Supreme Court"], 0, "The three tiers are: District Commission, State Commission, and National Commission (NCDRC)."),
    ("The District Consumer Disputes Redressal Commission has jurisdiction over complaints where value does not exceed:", ["Rs. 20 lakh", "Rs. 50 lakh", "Rs. 1 crore", "Rs. 5 crore"], 2, "The District Commission handles complaints where the value of goods/services does not exceed Rs. 1 crore (under the 2019 Act)."),
    ("The State Consumer Disputes Redressal Commission handles complaints where value exceeds Rs. 1 crore but does not exceed:", ["Rs. 5 crore", "Rs. 10 crore", "Rs. 50 crore", "Unlimited"], 1, "The State Commission handles complaints where value exceeds Rs. 1 crore but does not exceed Rs. 10 crore."),
    ("The National Consumer Disputes Redressal Commission (NCDRC) handles complaints where value exceeds:", ["Rs. 5 crore", "Rs. 10 crore", "Rs. 50 crore", "Rs. 1 crore"], 1, "NCDRC handles complaints where the value exceeds Rs. 10 crore."),
    ("Who heads the National Consumer Disputes Redressal Commission?", ["A sitting or retired Supreme Court Judge", "The Chief Justice of India", "The Law Minister", "The Prime Minister"], 0, "NCDRC is headed by a person who is or has been a Judge of the Supreme Court."),
    ("Who heads the State Consumer Disputes Redressal Commission?", ["A sitting or retired High Court Judge", "The Chief Minister", "The Governor", "A District Judge"], 0, "The State Commission is headed by a person who is or has been a Judge of a High Court."),
    ("The District Consumer Disputes Redressal Commission is headed by:", ["A retired High Court Judge", "A person who is or has been a District Judge", "The District Collector", "A sitting Supreme Court Judge"], 1, "The District Commission is headed by a person who is or has been a District Judge or equivalent."),
    ("An appeal against the order of the District Commission lies to:", ["The High Court", "The State Commission", "The Supreme Court", "NCDRC"], 1, "Appeals from the District Commission go to the State Commission."),
    ("An appeal against the order of the State Commission lies to:", ["The Supreme Court", "NCDRC", "The High Court", "The District Commission"], 1, "Appeals from the State Commission go to the National Commission (NCDRC)."),
    ("An appeal against the order of NCDRC lies to:", ["The High Court", "No appeal is possible", "The Supreme Court", "The President of India"], 2, "Appeals from NCDRC go to the Supreme Court."),
    ("The concept of 'unfair trade practice' includes:", ["False or misleading advertisements", "Selling goods at fair price", "Providing quality service", "Honest representation of products"], 0, "Unfair trade practices include false/misleading advertisements, deceptive practices, etc."),
    ("The Consumer Protection Act, 2019 introduced which new concept?", ["Product liability", "Fundamental Rights", "Directive Principles", "Impeachment"], 0, "Product liability is a new concept under the 2019 Act, making manufacturers, sellers, and service providers liable for defective products/services."),
    ("Under 'product liability', who can be held liable?", ["Product manufacturer", "Product seller", "Product service provider", "All of the above"], 3, "Under product liability, the manufacturer, seller, and/or service provider can all be held liable for harm caused by defective products."),
    ("The Central Consumer Protection Authority (CCPA) was established under:", ["Consumer Protection Act, 2019", "Consumer Protection Act, 1986", "Competition Act, 2002", "FSSAI Act"], 0, "CCPA is a new body established under the Consumer Protection Act, 2019."),
    ("What is the main function of CCPA?", ["To regulate and protect the rights of consumers", "To manufacture goods", "To collect taxes", "To appoint judges"], 0, "CCPA regulates matters relating to consumer rights violations, unfair trade practices, and misleading advertisements."),
    ("CCPA has the power to:", ["Recall products", "Order refund of price paid", "Impose penalties for misleading advertisements", "All of the above"], 3, "CCPA has wide powers including product recall, refund orders, and penalties for misleading ads."),
    ("The Consumer Protection Act, 2019 covers which type of transactions?", ["Only offline purchases", "Only online purchases", "Both offline and online purchases including e-commerce", "Only government purchases"], 2, "The 2019 Act explicitly covers e-commerce and all forms of buying goods/availing services."),
    ("Each District Commission shall consist of:", ["A President and at least 2 members", "A President only", "5 judges", "A single member"], 0, "Each District Commission consists of a President and not less than 2 members."),
    ("The complaint before the Consumer Commission must be filed within:", ["30 days of cause of action", "2 years from the date of cause of action", "5 years from the date of purchase", "No time limit"], 1, "A consumer complaint must be filed within 2 years from the date on which the cause of action arose."),
    ("Who appoints the members of NCDRC?", ["The Central Government (in consultation with selection committee)", "The Chief Justice of India", "The Parliament", "The President alone"], 0, "Members of NCDRC are appointed by the Central Government based on the recommendation of a selection committee."),
    ("The Consumer Protection (E-Commerce) Rules, 2020 regulate:", ["Traditional shops only", "E-commerce entities and their obligations towards consumers", "Government procurement", "Stock markets"], 1, "These rules regulate e-commerce entities, their duties, liabilities, and consumer protection measures in online transactions."),
    ("'Deficiency in service' under the Act means:", ["Any service that is perfectly delivered", "Any fault, imperfection, shortcoming, or inadequacy in the quality or performance of service", "Overcharging for premium service", "A delay of less than 1 minute"], 1, "Deficiency means any fault, imperfection, shortcoming, or inadequacy in the quality, nature, or manner of performance of service."),
    ("Mediation as an alternative dispute resolution mechanism is provided under:", ["Consumer Protection Act, 2019 only", "Both CPA 2019 and the Mediation Act, 2023", "Only the CPC", "Only the CrPC"], 1, "The CPA 2019 provides for mediation of consumer disputes, and the Mediation Act 2023 further strengthens this mechanism."),
    ("The maximum penalty for a false or misleading advertisement under CPA 2019 is:", ["Rs. 1 lakh", "Rs. 10 lakh for first offence, Rs. 50 lakh for subsequent offence", "Rs. 1 crore", "No penalty is prescribed"], 1, "For the first offence: up to Rs. 10 lakh, for subsequent offences: up to Rs. 50 lakhs. Endorser liability also exists."),
    ("A consumer complaint can be filed:", ["Only in person", "In person, by post, or electronically (online filing)", "Only through a lawyer", "Only by the government"], 1, "The 2019 Act allows filing of complaints in person, by post, or through electronic means."),
    ("Which of the following is NOT covered under the Consumer Protection Act?", ["Goods purchased for commercial purpose (for earning livelihood by self-employment)", "Services availed for personal use", "Purchase of products from e-commerce platforms", "Goods purchased for resale"], 3, "Goods purchased for resale are not covered as the buyer is not a 'consumer' for personal use."),
]

ch37_l2 = [
    ("The Central Consumer Protection Authority (CCPA) can investigate:", ["Only on complaints filed by individuals", "Both suo motu and on complaints regarding consumer rights violations", "Only cases referred by courts", "Only cases involving government departments"], 1, "CCPA can investigate complaints or take suo motu action on matters related to consumer rights violations."),
    ("Who heads the CCPA?", ["A Chief Commissioner", "A retired Supreme Court Judge", "The Law Minister", "The Prime Minister"], 0, "CCPA is headed by a Chief Commissioner appointed by the Central Government."),
    ("The CCPA can impose penalty for misleading advertisements on:", ["The manufacturer only", "The endorser (celebrity) also", "Only the advertising agency", "Only the media house"], 1, "Under the 2019 Act, even endorsers can be penalized for misleading advertisements if they fail to exercise due diligence."),
    ("A 'class action' complaint under CPA 2019 can be filed by:", ["Only one consumer", "One or more consumers on behalf of a group with common interest", "Only the government", "Only a registered society"], 1, "Complaints can be filed by one or more consumers having the same interest (class action)."),
    ("The Selection Committee for NCDRC President includes:", ["Chief Justice of India (Chairperson)", "A sitting SC Judge nominated by CJI", "Secretary of Consumer Affairs", "All of the above"], 3, "The selection committee includes the CJI as chairperson and other members as prescribed."),
    ("Under the 2019 Act, 'product liability action' can be brought by:", ["Any person who suffered injury due to a defective product, regardless of whether that person is the buyer", "Only the direct purchaser", "Only the manufacturer", "Only the government"], 0, "Any person injured by a defective product can bring a product liability action, even if they didn't buy the product."),
    ("The concept of 'unfair contract' was introduced by:", ["Consumer Protection Act, 1986", "Consumer Protection Act, 2019", "Indian Contract Act, 1872", "Sale of Goods Act, 1930"], 1, "The concept of 'unfair contract' was newly introduced in the 2019 Act, covering one-sided terms imposed on consumers."),
    ("The District Commission can entertain complaints where value of goods/services and compensation claimed does not exceed:", ["Rs. 50 lakh (2019 Act)", "Rs. 1 crore (2019 Act)", "Rs. 20 lakh", "Rs. 5 crore"], 1, "Under the 2019 Act, District Commission jurisdiction is up to Rs. 1 crore."),
    ("The complaint can be filed at:", ["Only where the opposite party resides", "Where the cause of action arose or where the opposite party resides or works", "Only in Delhi", "Only at the national level"], 1, "The complaint can be filed where the opposite party actually or voluntarily resides, carries on business, or where the cause of action arose."),
    ("Which of the following is a ground for product liability claim?", ["Manufacturing defect", "Design defect", "Failure to warn", "All of the above"], 3, "Product liability can arise from manufacturing defects, design defects, or failure to provide adequate instructions/warnings."),
    ("The CPA 2019 provides for 'electronic filing' of complaints because:", ["To increase corruption", "To make consumer dispute resolution more accessible and efficient", "To eliminate courts", "To help only lawyers"], 1, "Electronic filing improves access to justice, especially for consumers in remote areas."),
    ("Which section of CPA 2019 deals with the establishment of Consumer Protection Councils?", ["Section 3", "Sections 3 to 8", "Section 100", "Section 50"], 1, "Sections 3 to 8 of CPA 2019 deal with Consumer Protection Councils at Central, State, and District levels."),
    ("The Central Consumer Protection Council is headed by:", ["The Minister in charge of Consumer Affairs", "The Prime Minister", "The President", "The CJI"], 0, "The Council is headed by the Minister in charge of the Department of Consumer Affairs."),
    ("A consumer complaint must contain:", ["Name and address of complainant and opposite party", "Facts relating to the complaint", "The relief sought", "All of the above"], 3, "A complaint must contain all these details along with supporting documents."),
    ("Under the 2019 Act, the penalty for a manufacturer who causes a 'grievous injury' due to an adulterated product is:", ["Fine only", "Imprisonment up to 7 years and fine up to Rs. 5 lakhs", "No punishment", "Only community service"], 1, "For causing grievous injury due to manufacture/sale of adulterated products, the penalty includes imprisonment and fine."),
    ("If an endorser of a misleading advertisement provides a 'due diligence' defense, the endorser:", ["Is always held liable", "May escape liability if they can prove reasonable verification of the claims", "Gets additional punishment", "Must pay double the fine"], 1, "The endorser can defense by proving due diligence in verifying the claims in the advertisement."),
    ("Mediation in consumer disputes under CPA 2019:", ["Is mandatory before filing", "Can be referred to by the Commission at any stage with the consent of parties", "Is not available", "Is imposed without consent"], 1, "Consumer commissions can refer disputes to mediation, but it requires the consent of both parties."),
    ("If mediation settles the dispute, the settlement:", ["Has no legal value", "Is recorded by the commission and has the effect of an order", "Can be challenged in any court", "Is merely advisory"], 1, "A mediated settlement is recorded and has the same effect as an order of the commission."),
    ("The time limit for mediation under CPA 2019 is:", ["10 days", "30 days", "3 months extendable by 1 month", "No time limit"], 2, "Mediation must be completed within 3 months, extendable by 1 month with the consent of parties."),
    ("Under the 2019 Act, complaints can be filed by:", ["An individual consumer", "A recognized consumer association", "The Central or State Government", "All of the above"], 3, "Complaints can be filed by the consumer, any recognized consumer association, or the government."),
    ("The 'Central Consumer Protection Council' advises on:", ["Matters of consumer protection policy", "Military strategy", "Foreign policy", "Taxation rates"], 0, "The Council advises on promotion and protection of consumer rights."),
    ("Which of the following goods are covered under 'product liability'?", ["Food items", "Automobiles", "Electronics", "All products"], 3, "Product liability covers all goods/products manufactured, sold, or distributed."),
    ("Can a consumer file a complaint against misleading advertisements even without purchasing the product?", ["Yes, through CCPA", "No, only buyers can complain", "Only if the consumer suffered physical injury", "Only through a lawyer"], 0, "CCPA can take action against misleading advertisements suo motu or on complaint, regardless of purchase."),
    ("Under CPA 2019, unfair contract terms include:", ["Requiring excessive security deposits", "Imposing disproportionate penalties for breach", "Unilateral termination clauses without cause", "All of the above"], 3, "All these are examples of unfair contract terms as defined under the Act."),
    ("The State Commission can review its own orders:", ["Under no circumstances", "In case of error apparent on the face of the record", "Anytime it wants", "Only on direction of NCDRC"], 1, "The commission can review its orders if there is an error apparent on the face of the record."),
    ("Consumer helpline number in India is:", ["100", "1800-11-4000 (National Consumer Helpline)", "112", "108"], 1, "The National Consumer Helpline number is 1800-11-4000 (toll-free)."),
    ("Which body provides financial assistance for consumer protection activities?", ["Consumer Welfare Fund", "RBI", "SEBI", "IRDA"], 0, "The Consumer Welfare Fund was established under the Central Excise and Salt Act and is used for consumer protection activities."),
    ("Under the 2019 Act, the Commission can direct:", ["Replacement of defective goods", "Refund of price paid", "Compensation for loss or injury", "All of the above"], 3, "The commission can direct replacement, refund, compensation, and discontinuance of unfair trade practices."),
    ("The concept of 'reverse burden of proof' in product liability means:", ["The consumer must prove everything", "The manufacturer must prove that the product was not defective", "No proof is needed", "Only the court decides"], 1, "In product liability, the burden shifts to the manufacturer/seller to prove the product wasn't defective."),
    ("E-commerce platforms are required to display:", ["Seller details, return/refund policy, and complaint mechanism", "Only the price", "Only the brand name", "Nothing — no disclosure required"], 0, "E-commerce Rules 2020 mandate platforms to display comprehensive seller and policy information."),
]

ch37_l3 = [
    ("Consider: 1) CPA 2019 introduced product liability 2) CPA 2019 introduced CCPA 3) CPA 1986 had provisions for e-commerce 4) CPA 2019 introduced unfair contract. Which are correct?", ["1, 2 and 4 only", "All four", "1 and 2 only", "1, 2, 3 and 4"], 0, "CPA 2019 introduced product liability, CCPA, and unfair contract concepts. CPA 1986 did NOT have e-commerce provisions."),
    ("Assertion: The CPA 2019 is more relevant in the digital age. Reason: It explicitly covers e-commerce transactions and online services. Choose:", ["Both correct, Reason explains Assertion", "Both correct, Reason does not explain Assertion", "Assertion correct, Reason wrong", "Assertion wrong"], 0, "The explicit coverage of e-commerce makes the 2019 Act more relevant in the digital age."),
    ("Statement I: CCPA can issue safety notices regarding goods or services. Statement II: CCPA can order recall of unsafe goods. Choose:", ["Both correct", "Only I is correct", "Only II is correct", "Both incorrect"], 0, "Both are powers granted to CCPA under the CPA 2019."),
    ("Which of the following is NOT a power of the District Consumer Commission?", ["Hearing consumer complaints up to Rs. 1 crore", "Issuing interim orders", "Hearing appeals from State Commission", "Referring disputes to mediation"], 2, "Appeals from the State Commission go to NCDRC, not back to the District Commission."),
    ("In comparison to CPA 1986, the pecuniary jurisdiction of District Commission under CPA 2019:", ["Decreased", "Increased from Rs. 20 lakh to Rs. 1 crore", "Remained the same", "Was abolished"], 1, "The jurisdiction was significantly increased to improve access at the district level."),
    ("The Investigation Wing of CCPA can:", ["Only receive complaints", "Investigate violations, collect evidence, and submit reports to CCPA", "Pass judicial orders", "Arrest offenders"], 1, "The Investigation Wing of CCPA conducts investigations and submits findings to CCPA for action."),
    ("Under the CPA 2019, which penalty is prescribed for manufacturing or selling adulterated goods resulting in death?", ["Fine only", "Imprisonment not less than 7 years, extendable to life imprisonment, and fine not less than Rs. 10 lakhs", "Only community service", "No punishment for first offence"], 1, "If adulterated goods cause death, the penalty includes minimum 7 years imprisonment (up to life) and minimum Rs. 10 lakh fine."),
    ("Consider: 1) Consumer complaint can be filed in any language 2) There is no court fee for consumer complaints 3) Lawyer is mandatory 4) Complaints can be filed online. Which are correct?", ["1 and 4 only", "1, 2 and 4", "All four", "Only 4"], 1, "Complaints can be filed in the local language, there is no court fee, and online filing is available. Lawyer is NOT mandatory."),
    ("The concept of 'direct selling' regulation under CPA 2019 was strengthened by:", ["Consumer Protection (Direct Selling) Rules, 2021", "Companies Act, 2013", "FEMA", "RBI guidelines"], 0, "The Direct Selling Rules 2021 regulate direct selling entities and protect consumers in direct selling transactions."),
    ("Statement I: NCDRC can review orders of the State Commission. Statement II: Supreme Court can hear appeals against NCDRC orders. Which is correct?", ["Both are correct", "Only I is correct", "Only II is correct", "Both are incorrect"], 0, "NCDRC has appellate jurisdiction over State Commission orders, and the Supreme Court hears appeals against NCDRC orders."),
    ("Under the 2019 Act, a complaint can be transferred from one District Commission to another:", ["By the State Commission if justice so requires", "Never — once filed, it cannot be transferred", "Only by the Supreme Court", "Only by the CCPA"], 0, "The State Commission can transfer a complaint from one District Commission to another within the state if the interest of justice requires."),
    ("Which of the following is a 'restrictive trade practice' covered under consumer protection?", ["Price fixing by agreement between traders", "Offering genuine discounts", "Improving product quality", "Reducing prices due to competition"], 0, "Restrictive trade practices include price fixing, market allocation, and limiting production."),
    ("The 'Consumer Commission' under CPA 2019 has powers of:", ["A civil court for summoning, examining witnesses, and producing documents", "A criminal court for sentencing", "A military tribunal", "A legislative body"], 0, "Consumer commissions have the powers of a civil court for procedural matters."),
    ("Under CPA 2019, an 'e-commerce entity' includes:", ["Marketplace e-commerce entity", "Inventory e-commerce entity", "Both", "Neither"], 2, "Both marketplace and inventory-based e-commerce entities are covered under the Act and its rules."),
    ("Assertion: The CPA 2019 provides for imprisonment in certain cases. Reason: Some offences like adulteration causing death are criminal in nature. Choose:", ["Both correct, R explains A", "Both correct, R does not explain A", "A correct, R wrong", "A wrong"], 0, "Criminal penalties for serious offences like adulteration causing death justify the imprisonment provision."),
    ("Which is NOT a function of Consumer Protection Councils?", ["Advisory role on consumer protection policy", "Hearing consumer complaints", "Promoting consumer awareness", "Reviewing consumer protection measures"], 1, "Consumer Protection Councils are advisory bodies; they do not hear complaints. That function belongs to Consumer Commissions."),
    ("Under product liability, a manufacturer's defense can include:", ["The defect was due to compliance with a mandatory standard", "The product was never manufactured", "Both of the above", "No defense is available"], 2, "Manufacturers can defend by proving compliance with mandatory standards or that the defect was not present at the time of delivery."),
    ("The CPA 2019 defines 'goods' to include:", ["Every kind of movable property other than actionable claims and money", "Only electronics", "Only food items", "Only automobiles"], 0, "Goods include every kind of movable property, including those attached to or forming part of immovable property."),
    ("What innovation does the CPA 2019 bring regarding celebrity endorsements?", ["Celebrities cannot endorse products", "Endorsers can be held liable for misleading advertisements if they don't verify claims", "Endorsers are immune from all liability", "Only film stars can endorse"], 1, "The 2019 Act introduces endorser liability, holding celebrities accountable for false/misleading product claims."),
    ("The territorial jurisdiction of Consumer Commissions is determined by:", ["Where the opposite party resides or carries on business, or where the cause of action arose", "Only where the goods were manufactured", "Only in Delhi", "Where the consumer wishes to file"], 0, "Jurisdiction is based on the location of the opposite party or where the cause of action arose."),
    ("Under the Direct Selling Rules, 2021, direct selling entities must:", ["Register with DPIIT (Department for Promotion of Industry and Internal Trade)", "Not use any written contracts", "Guarantee unlimited returns", "Operate only in metro cities"], 0, "Direct selling entities must register with DPIIT and comply with the prescribed regulations."),
    ("The compliance framework under CPA 2019 for e-commerce includes:", ["Mandatory grievance redressal mechanism", "Display of country of origin", "Appointment of a grievance officer", "All of the above"], 3, "E-commerce entities must have grievance redressal mechanisms, display product details including origin, and appoint grievance officers."),
    ("Which of the following actions can be taken against a third party under product liability? 1) Replacement 2) Return of product price 3) Damages for personal injury 4) Criminal prosecution", ["1, 2 and 3 only", "All four", "Only 3", "Only 1 and 2"], 0, "Under the civil provisions of product liability, replacement, return of price, and damages for injury are remedies. Criminal prosecution is separate."),
    ("The Consumer Protection Act, 2019 promotes which form of ADR the most?", ["Arbitration", "Mediation", "Conciliation", "Negotiation"], 1, "The CPA 2019 explicitly provides for mediation as a preferred ADR mechanism with a structured framework."),
    ("Statement: Consumer Protection Councils exist at Central, State, and District levels. Which statement about them is correct?", ["They are quasi-judicial bodies", "They are advisory bodies that promote and protect consumer rights", "They hear appeals", "They impose fines"], 1, "Consumer Protection Councils are advisory bodies at all three levels — they do not adjudicate disputes."),
    ("Under CPA 2019, if the Commission orders compensation but the opposite party fails to pay:", ["No remedy is available", "The order can be executed as a decree of a civil court", "The consumer must file a fresh case", "The government pays on behalf"], 1, "Orders of Consumer Commissions are executed as decrees of civil courts, ensuring enforceability."),
    ("The scope of CPA 2019 compared to CPA 1986 in terms of jurisdictional limits:", ["Identical", "Significantly expanded at all levels (District: 20L to 1Cr, State: 1Cr to 10Cr)", "Reduced", "Only expanded at the national level"], 1, "The pecuniary jurisdiction was significantly increased at all three levels."),
    ("The concept of 'misleading advertisement' under CPA 2019 includes:", ["False descriptions of products", "Creating a false impression through concealment of material facts", "Making false promises about product performance", "All of the above"], 3, "Misleading advertisements include false descriptions, concealment of important facts, and deceptive promises."),
    ("The maximum imprisonment for fraudulent adulteration of food resulting in death under CPA 2019 is:", ["5 years", "7 years", "Life imprisonment", "Death penalty"], 2, "For death caused by adulterated products, imprisonment can extend to life imprisonment."),
    ("Which of the following best describes the evolution of consumer protection law in India?", ["No change since 1947", "From basic protection under CPA 1986 to comprehensive digital-age protection under CPA 2019 with CCPA, product liability, and e-commerce regulation", "Consumer law was only introduced in 2019", "India has no consumer protection law"], 1, "Indian consumer protection evolved from CPA 1986 to the comprehensive CPA 2019 addressing modern challenges."),
]

write_chapter(37, ch37_l1, ch37_l2, ch37_l3)

# ========================================
# CHAPTER 38: Lok Adalats and Other Courts
# ========================================
ch38_l1 = [
    ("Lok Adalat means:", ["People's Court", "Government Court", "Supreme Court", "Virtual Court"], 0, "Lok Adalat literally means 'People's Court' — a forum for alternative dispute resolution."),
    ("Lok Adalats are established under which Act?", ["Legal Services Authorities Act, 1987", "Code of Civil Procedure", "Constitution of India", "Arbitration Act"], 0, "Lok Adalats are established under the Legal Services Authorities Act, 1987."),
    ("The decision of a Lok Adalat is:", ["Advisory only", "Binding on parties and final (no appeal)", "Subject to appeal in High Court", "Can be challenged in District Court"], 1, "The award of a Lok Adalat is deemed to be a decree of a civil court and is final and binding; no appeal lies."),
    ("Which Article of the Constitution supports the concept of Lok Adalats?", ["Article 32", "Article 39A (Equal justice and free legal aid)", "Article 50", "Article 21"], 1, "Article 39A directs the State to organize Lok Adalats and provide free legal aid."),
    ("Is any court fee charged when a matter is settled in a Lok Adalat?", ["Yes, same as in regular courts", "No, no court fee is charged", "Only half the court fee", "Fee is charged only for criminal cases"], 1, "No court fee is charged for matters referred to or filed in a Lok Adalat."),
    ("Lok Adalats can deal with:", ["Cases pending before courts", "Pre-litigation disputes (cases not yet filed in court)", "Both of the above", "Only criminal cases"], 2, "Lok Adalats handle both pending cases referred by courts and pre-litigation disputes."),
    ("Can Lok Adalats deal with compoundable offences?", ["Yes", "No", "Only with permission of the High Court", "Only in murder cases"], 0, "Lok Adalats can deal with compoundable offences (where the parties can compromise)."),
    ("Lok Adalats CANNOT deal with:", ["Non-compoundable criminal offences", "Motor accident claims", "Matrimonial disputes", "Labour disputes"], 0, "Matters relating to non-compoundable offences are not covered by Lok Adalats."),
    ("Permanent Lok Adalats (PLAs) were established for:", ["All types of cases", "Disputes relating to public utility services", "Only international disputes", "Military cases"], 1, "PLAs handle cases related to public utility services like transport, postal, telecom, insurance, etc."),
    ("The bench of a Lok Adalat consists of:", ["Only judges", "A sitting or retired judicial officer and one or two other members", "5 judges", "Only lawyers"], 1, "A Lok Adalat bench typically comprises a judicial officer (sitting or retired) and one or two other persons."),
    ("National Legal Services Authority (NALSA) was established in:", ["1987", "1995", "1998", "2005"], 1, "NALSA was established on 9th November 1995 under the Legal Services Authorities Act, 1987."),
    ("Who is the executive chairman of NALSA?", ["The Chief Justice of India", "The second senior-most Judge of the Supreme Court", "The Law Minister", "The Attorney General"], 1, "The second senior-most Judge of the Supreme Court is the Executive Chairman of NALSA."),
    ("Which of the following can organize Lok Adalats?", ["NALSA", "State Legal Services Authorities", "District Legal Services Authorities", "All of the above"], 3, "Lok Adalats can be organized by legal services institutions at the national, state, district, and taluk levels."),
    ("The 'National Lok Adalat' is organized:", ["Daily", "Periodically on predetermined dates across the country", "Only once a year", "Only in Delhi"], 1, "National Lok Adalats are organized periodically across the country on specific dates to settle cases en masse."),
    ("If a Lok Adalat cannot settle a dispute, the matter is:", ["Dismissed", "Returned to the court from which it was referred", "Sent to the Supreme Court", "Decided by the Lok Adalat anyway"], 1, "If no settlement is reached, the case is returned to the referring court for continued proceedings."),
    ("Legal aid is provided to:", ["Those whose annual income is below a prescribed limit", "Members of SC/ST communities", "Women and children", "All of the above"], 3, "Legal aid is provided to various categories including economically weaker sections, SC/ST, women, children, and others."),
    ("Article 14 of the Constitution guarantees:", ["Right to life", "Right to equality before law", "Freedom of religion", "Right to property"], 1, "Article 14 guarantees equality before law and equal protection of laws — foundational for equal access to justice."),
    ("The Legal Services Authorities Act, 1987 aims to:", ["Provide free and competent legal services to weaker sections", "Organize Lok Adalats for amicable settlement", "Both of the above", "Neither"], 2, "The Act has twin objectives — free legal aid and organizing Lok Adalats."),
    ("State Legal Services Authority is headed by:", ["The Chief Justice of the High Court (Patron-in-Chief) and a serving HC Judge (Executive Chairman)", "The Governor", "The Chief Minister", "The Advocate General"], 0, "The Chief Justice of the HC is the Patron-in-Chief, and a serving HC Judge is the Executive Chairman."),
    ("District Legal Services Authority is headed by:", ["The District Collector", "The District Judge as Chairman", "The Superintendent of Police", "An MLAs "], 1, "The District Judge serves as the Chairman of the District Legal Services Authority."),
    ("Which of the following disputes is most commonly settled in Lok Adalats?", ["Motor Accident Claims", "Constitutional disputes", "International trade disputes", "Defense procurement disputes"], 0, "Motor Accident Claims are the most common category of disputes settled in Lok Adalats."),
    ("Taluk Legal Services Committee is headed by:", ["A senior civil judge or judicial magistrate", "The District Judge", "The Collector", "The MLA"], 0, "The senior-most civil judge of the taluk acts as the chairman of the Taluk Legal Services Committee."),
    ("The settlement in a Lok Adalat must be:", ["By consent of both parties", "Imposed by the presiding officer", "Decided by majority vote", "Based on appeal"], 0, "Settlement in Lok Adalats is consensual — both parties must agree. The Lok Adalat cannot impose a decision."),
    ("Which form of ADR involves a neutral third party helping disputants reach an agreement?", ["Mediation", "Arbitration", "Litigation", "Self-help"], 0, "Mediation involves a neutral mediator facilitating negotiation between parties to reach a mutually acceptable solution."),
    ("Arbitration in India is governed by:", ["Arbitration and Conciliation Act, 1996", "Legal Services Authorities Act, 1987", "Code of Civil Procedure only", "Indian Evidence Act"], 0, "The Arbitration and Conciliation Act, 1996 governs arbitration proceedings in India."),
    ("Which of the following statements about Lok Adalats is INCORRECT?", ["They charge no court fee", "Their awards are binding", "They can deal with non-compoundable offences", "They promote amicable settlement"], 2, "Lok Adalats cannot deal with non-compoundable offences — this statement is incorrect."),
    ("The Permanent Lok Adalat can decide a case on its merits if:", ["Parties agree", "The parties fail to reach a settlement and the case relates to a public utility service with value up to Rs. 1 crore", "Never — it can only mediate", "Only in criminal cases"], 1, "Unlike regular Lok Adalats, PLAs can decide cases on merits if parties fail to reach a settlement."),
    ("The maximum value of cases that can be heard by Permanent Lok Adalats is:", ["Rs. 50 lakh", "Rs. 1 crore", "Rs. 10 crore", "No monetary limit"], 1, "PLAs can hear cases relating to public utility services with value up to Rs. 1 crore."),
    ("Mobile Lok Adalats are organized to:", ["Provide justice at the doorstep of citizens in rural/remote areas", "Only handle urban disputes", "Replace High Courts", "Conduct only criminal trials"], 0, "Mobile Lok Adalats travel to remote areas to provide access to justice for people who cannot easily reach courts."),
    ("Nyaya Bandhu — the Pro Bono Legal Services scheme is operated by:", ["NALSA", "Department of Justice", "High Courts", "Law Commission"], 1, "Nyaya Bandhu is a pro bono legal services scheme operated by the Department of Justice to connect advocates with marginalized persons."),
]

ch38_l2 = [
    ("Section 89 of the Code of Civil Procedure deals with:", ["Power of the court to refer disputes to ADR mechanisms including Lok Adalats", "Appointment of judges", "Criminal prosecution", "Execution of decrees"], 0, "Section 89 CPC empowers courts to refer disputes to ADR methods including mediation, conciliation, Lok Adalat, and arbitration."),
    ("The Permanent Lok Adalat differs from a regular Lok Adalat in that:", ["PLA can decide cases on merits; regular LA cannot impose a decision", "PLA charges higher fees", "PLA is only for criminal cases", "There is no difference"], 0, "The key difference is that PLA can adjudicate and pass an award on merits if settlement fails, while regular Lok Adalats cannot."),
    ("Which section of the LSAA 1987 deals with Lok Adalats?", ["Chapter V-A (Sections 19-22)", "Chapter I", "Chapter III", "Section 1"], 0, "Sections 19 to 22 of the LSAA deal with the organization and functioning of Lok Adalats."),
    ("What is the difference between 'conciliation' and 'arbitration'?", ["In conciliation, the third party facilitates; in arbitration, the third party decides", "They are identical", "Conciliation is binding; arbitration is not", "Only arbitration is recognized by Indian law"], 0, "In conciliation, the conciliator helps parties reach agreement. In arbitration, the arbitrator gives a binding decision."),
    ("Legal aid under LSAA is provided based on:", ["Political affiliation", "Income criteria, social status (SC/ST), gender, disability, and other vulnerability factors", "Only criminal cases", "Only to government employees"], 1, "Legal aid is provided based on economic criteria, social vulnerability, and statutory categories."),
    ("Which of the following categories are entitled to free legal aid? 1) SC/ST 2) Women 3) Industrial workers with income below prescribed limit 4) Persons in custody", ["1 and 2 only", "All four", "1, 2 and 4 only", "Only 1"], 1, "All four categories are entitled to free legal services under Section 12 of the LSAA."),
    ("The Supreme Court's ruling in 'State of Gujarat v. High Court of Gujarat' strengthened:", ["Judicial independence", "The role of Lok Adalats in reducing court pendency", "Executive supremacy", "Military tribunals"], 1, "The SC emphasized the importance of Lok Adalats and ADR in reducing the burden on regular courts."),
    ("The Lok Adalat award is equivalent to:", ["A mere recommendation", "A decree of a civil court under the CPC", "An ordinance", "A legislative Act"], 1, "The award is deemed to be a decree of a civil court and is enforceable as such."),
    ("Which of the following public utility services are covered by Permanent Lok Adalats?", ["Transport services", "Insurance services", "Telecom services", "All of the above"], 3, "Public utility services include transport, postal, telegraph, telephone, power, water supply, sanitation, insurance, and hospital services."),
    ("The limitation period is not applicable when a matter is referred to:", ["High Court", "Supreme Court", "Lok Adalat (waived for cases referred from courts)", "District Court"], 2, "When a case pending in a court is referred to a Lok Adalat, the limitation period does not apply."),
    ("If a person refuses to participate in a Lok Adalat proceeding:", ["The Lok Adalat can compel attendance", "The matter cannot be settled and is returned to court", "A fine is imposed", "The person is jailed"], 1, "Lok Adalat proceedings are consensual; no party can be compelled. If a party refuses, the matter returns to court."),
    ("Which amendment to the LSAA introduced Permanent Lok Adalats?", ["Amendment of 2002", "Amendment of 1994", "Amendment of 2010", "No amendment — they were in the original Act"], 0, "Permanent Lok Adalats were introduced by an amendment to the LSAA in 2002."),
    ("The concept of 'access to justice' is part of:", ["A Directive Principle (Art 39A)", "A Fundamental Right (Right to Life under Art 21)", "Both A and B as interpreted by the Supreme Court", "Neither"], 2, "Access to justice is both a Directive Principle (Art 39A) and has been read into Right to Life (Art 21) by the SC."),
    ("The Online Dispute Resolution (ODR) mechanism in India:", ["Has no legal recognition", "Is being promoted for consumer and commercial disputes for faster resolution", "Is banned", "Is only for international disputes"], 1, "ODR is being increasingly promoted for consumer, commercial, and e-commerce disputes."),
    ("Which of the following is the correct hierarchy of Legal Services Authorities?", ["NALSA → SLSA → DLSA → Taluk LSC", "DLSA → SLSA → NALSA → Taluk LSC", "Taluk → NALSA → DLSA → SLSA", "SLSA → NALSA → DLSA → Taluk"], 0, "The hierarchy is: National (NALSA) → State (SLSA) → District (DLSA) → Taluk (TLSC)."),
    ("Lok Adalats are based on the principle of:", ["Adversarial justice", "Conciliatory dispute resolution (win-win)", "Retributive justice", "Punitive justice"], 1, "Lok Adalats are based on the conciliatory approach — both parties should benefit from the settlement."),
    ("Under Section 22C of LSAA, a Permanent Lok Adalat can:", ["Only mediate", "Conduct conciliation and, failing that, decide the case on merits", "Issue arrest warrants", "Impose criminal penalties"], 1, "PLA first attempts conciliation; if that fails, it can decide the case on merits."),
    ("The concept of 'Tele-Law' provides:", ["Legal advice through video conferencing to people in rural areas via CSCs", "Court hearings on television", "Television shows about law", "Only online filing of cases"], 0, "Tele-Law connects citizens in remote areas with lawyers through video conferencing at Common Service Centres."),
    ("Which of the following is NOT an ADR mechanism recognized in Indian law?", ["Arbitration", "Mediation", "Conciliation", "Vigilante justice"], 3, "Vigilante justice is not a recognized ADR mechanism. Arbitration, mediation, conciliation, and Lok Adalats are recognized."),
    ("The 'Para-legal Volunteer' scheme under NALSA:", ["Trains paid volunteers to assist in legal aid programs at the grassroot level", "Hires foreign lawyers", "Is for Supreme Court only", "Is for government employees only"], 0, "Para-legal volunteers are trained to spread awareness about legal rights and assist in Lok Adalats and legal aid clinics."),
    ("Fast Track Special Courts (FTSCs) were established for:", ["Revenue cases", "Speedy trial of cases relating to rape and POCSO Act offences", "Only commercial disputes", "International arbitration"], 1, "FTSCs were established for expeditious disposal of rape and POCSO cases."),
    ("The Mediation Act, 2023 makes mediation:", ["Mandatory in all cases", "A preferred pre-litigation step for certain categories of disputes with statutory recognition", "Illegal", "Available only for international disputes"], 1, "The Mediation Act 2023 gives statutory recognition to mediation and encourages it as a pre-litigation step."),
    ("Consumer cases are often settled in Lok Adalats because:", ["Lok Adalats are faster, cheaper, and the settlement is final", "Consumers prefer lengthy litigation", "Courts refuse to hear consumer cases", "Lok Adalats have unlimited jurisdiction"], 0, "Speed, no cost, and finality make Lok Adalats attractive for consumer dispute settlement."),
    ("The concept of 'plea bargaining' differs from Lok Adalat settlement because:", ["Plea bargaining is for criminal cases and involves the accused accepting a lesser charge", "They are identical processes", "Lok Adalats handle plea bargaining", "Plea bargaining is faster than Lok Adalats"], 0, "Plea bargaining is a criminal law concept where the accused pleads guilty to a lesser charge, while Lok Adalats settle disputes through conciliation."),
    ("Which technology platform manages Lok Adalat data and scheduling?", ["NJDG (National Judicial Data Grid)", "LIMBS (Legal Information Management and Briefing System)", "Neither — it is all manual", "Only email"], 0, "NJDG and other e-Courts tools help manage data related to Lok Adalats and legal services."),
    ("The success of Lok Adalats is measured by:", ["Number of cases settled amicably", "Number of cases dismissed", "Amount of court fee collected", "Length of proceedings"], 0, "The primary metric is the number of cases settled amicably, reducing the burden on regular courts."),
    ("International arbitration in India is governed by:", ["Part II of the Arbitration and Conciliation Act, 1996", "Legal Services Authorities Act", "Code of Civil Procedure", "Indian Penal Code"], 0, "Part II of the A&C Act deals with enforcement of certain foreign awards (New York Convention and Geneva Convention)."),
    ("Which of the following correctly states the evolution of ADR in India?", ["Ancient Panchayat system → Modern Lok Adalats under LSAA 1987 → Mediation Act 2023", "ADR was introduced only in 2019", "India has no ADR tradition", "ADR was banned until 2000"], 0, "India has a long history of community-based dispute resolution, formalized through modern legislation."),
    ("Under the LSAA, who is NOT entitled to free legal aid?", ["SC/ST persons", "Persons with annual income above the prescribed limit and not belonging to any specified vulnerable category", "Women", "Persons with disability"], 1, "Persons who don't fall under any specified category and have income above the prescribed limit are not entitled to free legal aid."),
    ("The Lok Adalat system has resulted in:", ["Significant reduction in pendency of court cases in specific categories like motor accident claims", "Increase in court pendency", "Abolition of regular courts", "No measurable impact"], 0, "Lok Adalats have been particularly successful in settling motor accident claims and reducing pendency."),
]

ch38_l3 = [
    ("Consider: 1) Lok Adalat awards are final and binding 2) No appeal lies against Lok Adalat awards 3) Lok Adalats can decide non-compoundable offences 4) No court fee is charged. Which are correct?", ["1, 2 and 4 only", "All four", "1 and 2 only", "1, 2, 3 and 4"], 0, "Statements 1, 2, and 4 are correct. Lok Adalats cannot deal with non-compoundable offences."),
    ("Assertion: PLAs are more powerful than regular Lok Adalats. Reason: PLAs can decide on merits if conciliation fails. Choose:", ["Both correct, R explains A", "Both correct, R does not explain A", "A correct, R wrong", "A wrong"], 0, "The power to decide on merits makes PLAs more powerful than regular Lok Adalats."),
    ("Statement I: Regular Lok Adalats can impose a decision on parties. Statement II: PLAs can decide on merits if conciliation fails. Choose:", ["Both correct", "Only I is correct", "Only II is correct", "Both incorrect"], 2, "Only Statement II is correct. Regular Lok Adalats cannot impose decisions — settlement must be consensual."),
    ("The intersection of Article 21 and Article 39A with the concept of Lok Adalats demonstrates:", ["That access to justice is not a right", "That speedy and affordable justice is part of the right to life and state's duty", "That Lok Adalats replace courts", "That courts are unnecessary"], 1, "The SC has read access to justice into Article 21, and Article 39A mandates the State to organize Lok Adalats."),
    ("Which statement about the enforceability of a Lok Adalat award is most accurate?", ["It is enforceable as a decree of a civil court and no court can entertain a challenge against it", "It can be challenged in the High Court", "It has no legal force", "It is only a recommendation"], 0, "The award is deemed a decree of a civil court, is final, and no appeal lies against it in any court."),
    ("In S. N. Pandey v. Union of India (2015), the Supreme Court held regarding Lok Adalats:", ["They are unconstitutional", "Lok Adalats must follow principles of natural justice and cannot exercise undue pressure on parties, reinforcing the consensual nature", "Lok Adalats can impose decisions", "Lok Adalats are superior to High Courts"], 1, "The SC reiterated that Lok Adalats must be consensual and follow fair procedure."),
    ("Consider the evolution: 1) Article 39A inserted by 42nd Amendment 2) LSAA enacted in 1987 3) NALSA constituted in 1995 4) PLAs introduced by 2002 Amendment. The correct chronological order is:", ["1, 2, 3, 4", "2, 1, 3, 4", "4, 3, 2, 1", "1, 3, 2, 4"], 0, "42nd Amendment (1976) → LSAA (1987) → NALSA (1995) → PLAs (2002)."),
    ("Which of the following statements is correct? 1) Lok Adalats reduce the burden on courts 2) They promote social justice 3) They provide affordable justice 4) They are unconstitutional", ["1, 2 and 3 only", "All four", "Only 1", "Only 4"], 0, "Lok Adalats reduce burden, promote social justice, and provide affordable justice. They are constitutional."),
    ("The relationship between Section 89 CPC and Lok Adalats is:", ["Section 89 mandates courts to explore ADR including Lok Adalats before proceeding with trial", "They are unrelated", "Section 89 abolishes Lok Adalats", "Section 89 only applies to the Supreme Court"], 0, "Section 89 CPC empowers courts to refer suitable disputes to ADR mechanisms including Lok Adalats."),
    ("In the context of environmental disputes, Lok Adalats:", ["Cannot handle them", "Have been used to settle pollution and environmental compliance issues", "Can only handle them if the Supreme Court allows", "Are banned for environmental cases"], 1, "Lok Adalats have been used for settling environmental disputes, particularly water and air pollution cases."),
    ("Statement I: The LSAA 1987 was enacted to implement Article 39A. Statement II: Article 39A was part of the original Constitution. Choose:", ["Both correct", "Only I is correct", "Only II is correct", "Both incorrect"], 1, "Statement I is correct — LSAA implements Art 39A. But Art 39A was added by the 42nd Amendment (1976), not the original Constitution."),
    ("Which of the following technology initiatives has improved Lok Adalat efficiency? 1) E-Lok Adalat 2) NJDG integration 3) Video conferencing for rural areas 4) AI-based case selection", ["1, 2 and 3 only", "All four", "Only 1", "Only 1 and 2"], 0, "E-Lok Adalats, NJDG integration, and video conferencing have improved efficiency. AI-based case selection is still experimental."),
    ("The concept of 'therapeutic jurisprudence' in Lok Adalats refers to:", ["Using medicine as punishment", "Focusing on the healing and restorative effects of the legal process on parties", "Only mental health cases", "Chemical treatment of offenders"], 1, "Therapeutic jurisprudence views law as a social force that can produce therapeutic outcomes through amicable settlement."),
    ("Consider: A pending case is referred to a Lok Adalat. Settlement fails. What happens?", ["The case is dismissed forever", "The case returns to the court from which it was referred, at the stage at which it was referred", "A new case must be filed", "The Lok Adalat imposes its decision"], 1, "If no settlement is reached, the case returns to the referring court to continue from where it was left off."),
    ("Which of the following is a constitutional basis for legal aid in India? 1) Article 14 2) Article 21 3) Article 22(1) 4) Article 39A", ["All four", "Only 4", "1 and 4 only", "2 and 4 only"], 0, "All four articles form the constitutional basis: Art 14 (equality), Art 21 (life/liberty), Art 22(1) (right to counsel), Art 39A (legal aid mandate)."),
    ("The NALSA's 'DISHA' scheme focuses on:", ["Legal literacy and awareness through district-level workshops", "International trade", "Military justice", "Railway construction"], 0, "NALSA's DISHA program focuses on outreach and awareness about legal services."),
    ("Assertion: Lok Adalats have been extremely successful for motor accident claim cases. Reason: These cases involve quantifiable compensation and both parties benefit from quick settlement. Choose:", ["Both correct, R explains A", "Both correct, R does not explain A", "A correct, R wrong", "A wrong"], 0, "Motor accident claims are calculable and both parties benefit from fast resolution, explaining the success."),
    ("Under the Mediation Act 2023, mediated settlements:", ["Have no legal value", "Are enforceable as judgments/decrees if registered", "Can be challenged in any court", "Are only recommendations"], 1, "Mediated settlements, when registered, are enforceable as judgments or decrees of court."),
    ("Which of the following best compares regular courts and Lok Adalats?", ["Courts are adversarial and time-consuming; Lok Adalats are conciliatory and fast", "Both follow the same adversarial procedure", "Lok Adalats are slower than courts", "Courts charge no fee; Lok Adalats charge fees"], 0, "Courts follow adversarial procedure; Lok Adalats use conciliatory methods for faster resolution."),
    ("The 'Integrated Grievance Redressal Mechanism' under NALSA:", ["Only handles criminal complaints", "Provides a single-window approach combining legal aid, Lok Adalats, and para-legal services", "Is only in Delhi", "Replaces the Supreme Court"], 1, "The integrated mechanism combines various legal services for comprehensive dispute resolution."),
    ("Which case held that 'right to speedy trial' is part of Article 21?", ["Hussainara Khatoon v. State of Bihar", "Maneka Gandhi v. Union of India", "Kesavananda Bharati v. State of Kerala", "A.K. Gopalan v. State of Madras"], 0, "Hussainara Khatoon case (1979) established that speedy trial is a fundamental right under Article 21."),
    ("Cross-border ADR (international commercial arbitration) in India is governed by:", ["Part I and Part II of the Arbitration and Conciliation Act, 1996", "Legal Services Authorities Act", "Consumer Protection Act", "Indian Penal Code"], 0, "The A&C Act covers both domestic and international arbitration."),
    ("The 'One Nation One Lok Adalat' concept emphasizes:", ["Conducting simultaneous Lok Adalats across the country to maximize settlement of cases", "Reducing Lok Adalats to one per year", "Only holding Lok Adalats in the Supreme Court", "Abolishing state-level Lok Adalats"], 0, "National Lok Adalats are conducted simultaneously across the country on specific dates."),
    ("Which of the following is a challenge faced by Lok Adalats in India? 1) Lack of awareness among public 2) Quality of settlement 3) Over-reliance on case statistics rather than justice quality 4) All are genuine concerns", ["Only 1", "1 and 2 only", "4", "None are challenges"], 2, "All three are genuine challenges: awareness, settlement quality, and focus on quantity over quality of justice."),
    ("In the context of environmental ADR, the National Green Tribunal:", ["Is a Lok Adalat", "Is a specialized tribunal for environmental cases, not strictly an ADR mechanism", "Is abolished", "Only handles criminal cases"], 1, "NGT is a statutory tribunal for environmental cases — it is not a Lok Adalat but part of the broader dispute resolution ecosystem."),
    ("Consider: 1) E-Lok Adalats held during COVID-19 2) Virtual hearings became the norm 3) Technology improved access to ADR. The pandemic's impact on ADR was:", ["Negative — ADR stopped", "Positive — digital transformation accelerated adoption of online ADR", "No impact", "ADR was banned during COVID"], 1, "COVID-19 accelerated the digital transformation of ADR, with E-Lok Adalats and virtual hearings becoming common."),
    ("The concept of 'restorative justice' in Lok Adalats means:", ["Punishing offenders harshly", "Focusing on restoring relationships and making the victim whole through compensation and reconciliation", "Imprisonment of all parties", "Death penalty"], 1, "Restorative justice focuses on healing the harm caused, rather than merely punishing the offender."),
    ("Statement: Over 5 crore cases have been settled through Lok Adalats since their inception. This demonstrates:", ["The failure of the system", "The significant role of Lok Adalats in reducing judicial backlog in India", "That courts are no longer needed", "That Lok Adalats are too expensive"], 1, "The large number of cases settled demonstrates the effectiveness of Lok Adalats in reducing pendency."),
    ("Which of the following is a recent innovation in India's ADR landscape?", ["SAMADHAN — online mediation platform", "E-Lok Adalat", "AI-assisted case categorization for ADR referral", "All of the above"], 3, "Multiple technology-driven innovations are being introduced to strengthen ADR in India."),
    ("The future of ADR in India lies in:", ["Only traditional court litigation", "Integration of technology, expansion of mediation under the 2023 Act, and strengthening Lok Adalats for broader categories of disputes", "Abolition of all courts", "Only international arbitration"], 1, "The future involves technology integration, statutory mediation, and expanded Lok Adalat coverage."),
]

write_chapter(38, ch38_l1, ch38_l2, ch38_l3)

print("Chapters 37 and 38 done.")
