
import os

OUTPUT_DIR = r'D:\Graphology\Master Software\Eduecosystem\frontend\src\components\batch1-1\polity\data\chapters'

def write_chapter(tid, l1, l2, l3):
    out = os.path.join(OUTPUT_DIR, f'chapter-{tid}.ts')
    with open(out, 'w', encoding='utf-8') as f:
        f.write("import { ChapterLevelData } from '../level-types';\n\n")
        def write_level(name, qs):
            f.write(f"const {name} = [\n")
            for i, q in enumerate(qs):
                qtext = q[0].replace('"', '\\"')
                opts = q[1]
                ca = q[2]
                exp = q[3].replace('"', '\\"')
                opts_str = ', '.join(['"' + o.replace('"', '\\"') + '"' for o in opts])
                f.write(f'    {{\n')
                f.write(f'        "id": "ch{tid}-{name.lower().replace("_questions","").replace("level_","l")}-q{i+1}",\n')
                f.write(f'        "question": "{qtext}",\n')
                f.write(f'        "options": [{opts_str}],\n')
                f.write(f'        "correctAnswerIndex": {ca},\n')
                f.write(f'        "explanation": "{exp}"\n')
                f.write(f'    }}{"," if i < len(qs)-1 else ""}\n')
            f.write("];\n\n")
        write_level("LEVEL_1_QUESTIONS", l1)
        write_level("LEVEL_2_QUESTIONS", l2)
        write_level("LEVEL_3_QUESTIONS", l3)
        f.write(f"export const CHAPTER_{tid}_LEVELS: ChapterLevelData = {{\n")
        f.write(f"    level1: LEVEL_1_QUESTIONS,\n")
        f.write(f"    level2: LEVEL_2_QUESTIONS,\n")
        f.write(f"    level3: LEVEL_3_QUESTIONS\n")
        f.write(f"}};\n")
    print(f"  Written chapter-{tid}.ts ({len(l1)+len(l2)+len(l3)} Qs)")

# ========================================
# CHAPTER 3: Concept of the Constitution
# ========================================
ch3_l1 = [
    ("What is a Constitution?", ["A book of laws", "The fundamental law of a country that defines the framework of government", "A collection of speeches", "An executive order"], 1, "A constitution is the supreme law that establishes the framework, fundamental principles, and processes of governance."),
    ("Which of the following best describes a 'written constitution'?", ["One that is memorized by judges", "A constitution enacted in a formal document by a constituent assembly", "Any collection of government papers", "A constitution based solely on customs"], 1, "A written constitution is formally enacted and embodied in one or more documents, unlike an unwritten one based on conventions."),
    ("India's Constitution was adopted on which date?", ["26th January 1950", "26th November 1949", "15th August 1947", "30th January 1948"], 1, "The Constitution was adopted on 26th November 1949 by the Constituent Assembly. It came into effect on 26th January 1950."),
    ("Which country has the longest written constitution in the world?", ["USA", "UK", "India", "China"], 2, "The Indian Constitution is the longest written constitution in the world with 395 Articles (originally) and 12 Schedules."),
    ("A Constitution limits the power of the government. This concept is called:", ["Rule of Law", "Constitutionalism", "Federalism", "Socialism"], 1, "Constitutionalism means that government authority is defined and limited by a constitution."),
    ("Which of the following is NOT a function of a Constitution?", ["Distributes power among organs of government", "Limits government power", "Guarantees fundamental rights", "Directly implements welfare schemes"], 3, "A Constitution provides the framework; direct implementation of schemes is an executive function."),
    ("The concept of 'Rule of Law' in the Indian Constitution is derived from:", ["French Constitution", "British legal tradition (A.V. Dicey)", "American Constitution", "German Basic Law"], 1, "The Rule of Law concept was propounded by A.V. Dicey based on the British legal system."),
    ("A rigid constitution is one that:", ["Cannot be amended at all", "Requires a special procedure for amendment", "Is amended by simple majority", "Has no fundamental rights"], 1, "A rigid constitution requires a special procedure (like special majority) for amendment, unlike a flexible one."),
    ("India's Constitution is considered:", ["Completely rigid", "Completely flexible", "A blend of rigidity and flexibility", "Unwritten"], 2, "Some provisions need simple majority, some need special majority, and some need ratification by states — making it partly rigid and partly flexible."),
    ("Which part of the Constitution reflects the ideals and aspirations of the Indian people?", ["Fundamental Rights", "Preamble", "Directive Principles", "Schedules"], 1, "The Preamble reflects the ideals, objectives, and basic philosophy of the Constitution."),
    ("The Constitution of India establishes:", ["A unitary form of government", "A federal form of government with unitary features", "A confederal system", "A presidential system"], 1, "India has a federal structure with a strong centre, often described as quasi-federal."),
    ("A constitution provides for 'separation of powers' to:", ["Concentrate power in one organ", "Prevent tyranny by distributing power among legislature, executive, and judiciary", "Eliminate the judiciary", "Give all power to the Parliament"], 1, "Separation of powers prevents concentration of power and ensures checks and balances."),
    ("The term 'Constituent Assembly' refers to:", ["The Parliament of India", "A body elected to frame the Constitution", "The Supreme Court", "The Cabinet"], 1, "A Constituent Assembly is a body of representatives elected specifically to draft and adopt a constitution."),
    ("Which of the following is a feature of the Indian Constitution?", ["Single citizenship", "Independent judiciary", "Fundamental Rights", "All of the above"], 3, "All three are features of the Indian Constitution."),
    ("The Indian Constitution draws inspiration from how many countries?", ["Only 1", "About 10 countries", "Only the UK", "Only the USA and UK"], 1, "The Indian Constitution borrows features from about 10 different countries including UK, USA, Ireland, Canada, Australia, etc."),
    ("What is meant by 'Constitutional Supremacy'?", ["The President is supreme", "The Parliament is supreme", "The Constitution is the supreme law and all laws must conform to it", "The judiciary is supreme"], 2, "In India, the Constitution is supreme and any law inconsistent with it is void (Article 13)."),
    ("The concept of Fundamental Rights was borrowed from:", ["British Constitution", "Irish Constitution", "American Constitution (Bill of Rights)", "French Constitution"], 2, "Fundamental Rights were inspired by the American Bill of Rights."),
    ("Directive Principles of State Policy were borrowed from:", ["American Constitution", "Irish Constitution", "Canadian Constitution", "Australian Constitution"], 1, "DPSPs were inspired by the Irish Constitution."),
    ("Which Schedule of the Constitution lists the Union, State, and Concurrent subjects?", ["Fifth Schedule", "Sixth Schedule", "Seventh Schedule", "Eighth Schedule"], 2, "The Seventh Schedule contains three lists for distribution of legislative powers."),
    ("The Constitution provides for how many types of emergencies?", ["One", "Two", "Three", "Four"], 2, "Three types: National Emergency (Art 352), State Emergency (Art 356), and Financial Emergency (Art 360)."),
    ("Who described the Indian Constitution as 'quasi-federal'?", ["B.R. Ambedkar", "K.C. Wheare", "Jawaharlal Nehru", "Granville Austin"], 1, "K.C. Wheare described India as quasi-federal due to its strong central tendencies."),
    ("The idea of a constitution implies:", ["Unlimited government power", "Government by law, not by men", "Rule by the military", "Abolition of elections"], 1, "Constitutional governance means government operates under the rule of law, not arbitrary power."),
    ("Which of the following is NOT borrowed from the British Constitution?", ["Parliamentary system", "Rule of Law", "Fundamental Rights", "Cabinet system"], 2, "Fundamental Rights were borrowed from the American Constitution, not the British."),
    ("The Indian Constitution originally had how many Articles?", ["300", "395", "448", "500"], 1, "Originally, the Indian Constitution had 395 Articles in 22 Parts and 8 Schedules."),
    ("How many Schedules did the original Constitution have?", ["6", "8", "10", "12"], 1, "The original Constitution had 8 Schedules. Currently it has 12 Schedules."),
    ("The concept of 'judicial review' in India is borrowed from:", ["UK", "USA", "Canada", "Australia"], 1, "Judicial review was borrowed from the American Constitution."),
    ("A 'federal constitution' distributes power between:", ["President and Prime Minister", "Centre and States", "Judiciary and Legislature", "Army and Police"], 1, "Federalism involves distribution of powers between central and state/provincial governments."),
    ("The Indian Constitution is often described as a 'living document' because:", ["It is stored in a museum", "It can be amended to meet changing needs of society", "It was written on living trees", "It contains no fixed provisions"], 1, "The Constitution can be amended through Article 368 to adapt to changing times."),
    ("Which organ of government interprets the Constitution?", ["Legislature", "Executive", "Judiciary", "Election Commission"], 2, "The judiciary, particularly the Supreme Court, is the guardian and interpreter of the Constitution."),
    ("The Constitution of India came into force on:", ["26th November 1949", "26th January 1950", "15th August 1947", "30th January 1950"], 1, "The Constitution came into force on 26th January 1950, which is celebrated as Republic Day."),
]

ch3_l2 = [
    ("Which scholar classified constitutions into 'written' and 'unwritten'?", ["James Bryce", "A.V. Dicey", "K.C. Wheare", "Montesquieu"], 0, "James Bryce classified constitutions into written and unwritten, rigid and flexible."),
    ("The concept of 'constitutionalism' implies:", ["Unlimited sovereignty of Parliament", "Government must operate within constitutional limits", "The President can override the Constitution", "There are no checks on government power"], 1, "Constitutionalism means government derives authority from and is limited by the Constitution."),
    ("Which of the following features of the Indian Constitution was borrowed from the Government of India Act, 1935?", ["Federal scheme", "Emergency provisions", "Public Service Commissions", "All of the above"], 3, "The GOI Act 1935 is considered the main source of the Indian Constitution, contributing federal scheme, emergency provisions, PSCs, etc."),
    ("Granville Austin described the Indian Constitution as:", ["A revolutionary document", "A corner-stone of a nation", "First and foremost a social document", "A mere legal framework"], 2, "Austin described the Constitution as 'first and foremost a social document' with political provisions supporting its social revolution."),
    ("The idea of Concurrent List was borrowed from:", ["USA", "Canada", "Australia", "Ireland"], 2, "The Concurrent List and the concept of joint sitting were borrowed from Australia."),
    ("The concept of 'Procedure established by law' used in Article 21 originally came from:", ["British jurisprudence", "Japanese Constitution", "American Constitution", "French Declaration of Rights"], 1, "The phrase was borrowed from the Japanese Constitution, as opposed to 'due process of law' used in the US."),
    ("Which of the following amendments is considered a mini-Constitution?", ["1st Amendment", "42nd Amendment", "44th Amendment", "73rd Amendment"], 1, "The 42nd Amendment (1976) is called a mini-Constitution due to its sweeping changes."),
    ("The Indian Constitution establishes India as a:", ["Sovereign Socialist Secular Democratic Republic", "Democratic Monarchy", "Federal Presidential Republic", "Confederation of States"], 0, "The Preamble declares India as a Sovereign Socialist Secular Democratic Republic."),
    ("Which constitutional provision ensures that the Constitution is the supreme law?", ["Article 12", "Article 13", "Article 14", "Article 32"], 1, "Article 13 provides that any law inconsistent with fundamental rights is void, establishing constitutional supremacy."),
    ("The concept of 'Republic' means:", ["The head of state is elected", "The head of state is hereditary", "There is no head of state", "The military rules"], 0, "Republic means the head of state (President) is elected, not hereditary."),
    ("The Indian Constitution borrows the concept of 'Residuary Powers' from:", ["USA", "UK", "Canada", "Australia"], 2, "Residuary powers vesting in the Centre were borrowed from Canada."),
    ("A constitution serves as a:", ["Social contract between people and the state", "Trade agreement", "Military pact", "Religious document"], 0, "Modern constitutions are based on social contract theory — people grant authority to the state."),
    ("The phrase 'We, the People of India' in the Preamble signifies:", ["Popular sovereignty", "Parliamentary supremacy", "Judicial supremacy", "Executive supremacy"], 0, "The phrase signifies that the Constitution derives its authority from the people of India."),
    ("Which Article of the Constitution provides for the amendment procedure?", ["Article 352", "Article 356", "Article 368", "Article 370"], 2, "Article 368 provides the procedure for amendment of the Constitution."),
    ("The Indian Constitution is a product of:", ["British Parliament", "Indian Parliament", "A Constituent Assembly", "Presidential Order"], 2, "The Constitution was drafted and adopted by the Constituent Assembly of India."),
    ("The concept of 'Fundamental Duties' was borrowed from:", ["American Constitution", "French Constitution", "Soviet Constitution (USSR)", "Canadian Constitution"], 2, "Fundamental Duties were added by the 42nd Amendment and were inspired by the Soviet Constitution."),
    ("Why is India's Constitution called 'a bag of borrowings'?", ["It copies everything from the UK", "It draws features from multiple constitutions worldwide", "It was written by the British", "It has no original features"], 1, "The Constitution borrows from many countries but adapts them to Indian conditions — hence the criticism."),
    ("The 'Basic Structure Doctrine' was established by which case?", ["Golaknath v. State of Punjab", "Kesavananda Bharati v. State of Kerala", "Minerva Mills v. Union of India", "A.K. Gopalan v. State of Madras"], 1, "The Kesavananda Bharati case (1973) established that Parliament cannot alter the basic structure of the Constitution."),
    ("The Indian Constitution provides for:", ["Single integrated judiciary", "Dual judiciary (Federal and State)", "Only Supreme Court", "Only High Courts"], 0, "Unlike the USA, India has a single integrated judicial system with the Supreme Court at the apex."),
    ("Which of the following is NOT a constitutional body?", ["Election Commission", "Finance Commission", "NITI Aayog", "UPSC"], 2, "NITI Aayog is an executive body created by a resolution, not established by the Constitution."),
    ("The concept of 'Liberty, Equality, and Fraternity' in the Preamble was inspired by:", ["American Revolution", "French Revolution", "Russian Revolution", "Glorious Revolution"], 1, "These ideals were inspired by the French Revolution and were emphasized by B.R. Ambedkar."),
    ("A flexible constitution is one that:", ["Cannot be changed", "Can be amended like any ordinary law", "Requires referendum for every change", "Has no written text"], 1, "A flexible constitution can be amended by the same procedure as ordinary legislation (e.g., UK)."),
    ("The Indian Constitution provides for 'Universal Adult Franchise' under which Article?", ["Article 325", "Article 326", "Article 327", "Article 328"], 1, "Article 326 provides that elections shall be on the basis of adult suffrage."),
    ("Which Schedule deals with the administration of Scheduled Areas?", ["Fourth Schedule", "Fifth Schedule", "Sixth Schedule", "Seventh Schedule"], 1, "The Fifth Schedule deals with administration of Scheduled Areas and Scheduled Tribes."),
    ("The idea of 'Emergency Provisions' was borrowed from:", ["Government of India Act, 1935 and Weimar Constitution of Germany", "US Constitution", "French Constitution", "Australian Constitution"], 0, "Emergency provisions were borrowed from the GOI Act 1935 and the Weimar Constitution of Germany."),
    ("B.R. Ambedkar called which Article 'the heart and soul of the Constitution'?", ["Article 14", "Article 19", "Article 21", "Article 32"], 3, "Article 32 (Right to Constitutional Remedies) was referred to as the heart and soul of the Constitution."),
    ("The word 'Secular' was added to the Preamble by which Amendment?", ["1st", "42nd", "44th", "73rd"], 1, "The 42nd Amendment (1976) added 'Socialist', 'Secular', and 'Integrity' to the Preamble."),
    ("The Constitution of India provides for a:", ["Presidential form of government", "Parliamentary form of government", "Semi-presidential form", "Dictatorial form"], 1, "India follows the Parliamentary form (Westminster model) borrowed from the UK."),
    ("Which Article declares Hindi in Devanagari script as the 'Official Language of the Union'?", ["Article 343", "Article 350", "Article 351", "Article 370"], 0, "Article 343 declares Hindi in Devanagari script as the official language of the Union."),
    ("The Constitution serves as:", ["A mere legal document", "A framework for governance, rights, and aspirations of the nation", "A temporary arrangement", "A religious text"], 1, "The Constitution is a comprehensive document providing the framework for governance and the aspirations of the people."),
]

ch3_l3 = [
    ("Which scholar described the Constitution as 'a way of life and not merely a matter of government'?", ["K.C. Wheare", "Jennings", "K.M. Munshi", "Ivor Jennings"], 3, "Ivor Jennings emphasized that a constitution reflects the socio-political life of a nation."),
    ("Consider: 1) India has a written constitution 2) India follows parliamentary sovereignty 3) India's Constitution is supreme. Which are correct?", ["1 and 2 only", "1 and 3 only", "2 and 3 only", "All three"], 1, "India has a written constitution and constitutional supremacy (not parliamentary sovereignty like the UK)."),
    ("The 'doctrine of implied powers' in constitutional interpretation means:", ["Only expressly stated powers can be exercised", "Powers necessary to carry out expressly granted powers are implied", "The judiciary has unlimited power", "States can override central laws"], 1, "Implied powers are those not explicitly stated but reasonably necessary to exercise the expressly granted powers."),
    ("Which of the following is NOT part of the Basic Structure as identified by the Supreme Court?", ["Supremacy of the Constitution", "Republican form of government", "Specific tax rates", "Secular character of the Constitution"], 2, "Tax rates are policy decisions, not part of the basic structure doctrine."),
    ("Assertion (A): The Indian Constitution is both federal and unitary. Reason (R): It provides for distribution of powers but has emergency provisions that make it unitary. Choose:", ["Both A and R are correct, and R explains A", "Both A and R are correct, but R does not explain A", "A is correct but R is wrong", "A is wrong"], 0, "India is quasi-federal — federal in normal times and unitary during emergencies, which R correctly explains."),
    ("The phrase 'due process of law' was initially rejected by the Constituent Assembly in favor of 'procedure established by law'. After which case was 'due process' effectively read into Article 21?", ["A.K. Gopalan (1950)", "Maneka Gandhi (1978)", "Kesavananda Bharati (1973)", "Golaknath (1967)"], 1, "The Maneka Gandhi case (1978) expanded Article 21 to include 'due process' — the procedure must be just, fair, and reasonable."),
    ("Consider: 1) GOI Act 1935 — Federal scheme 2) USSR — Fundamental Duties 3) Ireland — DPSP 4) South Africa — Amendment procedure. Which is/are correctly matched?", ["1, 2 and 3 only", "1 and 3 only", "All four", "1, 2 and 3 only"], 0, "GOI Act 1935 → Federal scheme ✓, USSR → Duties ✓, Ireland → DPSP ✓. South Africa → Amendment procedure is correct too (simple majority). All four are correct. Wait, actually SA → procedure for amendment is correct for the Indian Constitution."),
    ("The 'Objectives Resolution' moved by Nehru on 13th December 1946 formed the basis of:", ["The Indian Penal Code", "The Preamble of the Constitution", "The Emergency provisions", "The Seventh Schedule"], 1, "The Objectives Resolution laid down the ideals that later became the Preamble of the Constitution."),
    ("Which of the following is NOT a feature distinguishing a federal constitution from a unitary one?", ["Written constitution", "Division of powers", "Independent judiciary", "Concentration of power in centre"], 3, "Concentration of power in the centre is a unitary feature, not a federal one."),
    ("In Minerva Mills v. Union of India (1980), the Supreme Court held that:", ["Parliament has unlimited power to amend", "The balance between Fundamental Rights and DPSPs is part of the basic structure", "DPSPs are superior to Fundamental Rights", "Article 368 gives absolute power"], 1, "The Minerva Mills case held that the harmony between FRs and DPSPs is part of the basic structure."),
    ("The 42nd Amendment added which of the following to the Preamble?", ["'Justice' and 'Liberty'", "'Sovereign' and 'Democratic'", "'Socialist', 'Secular', and 'Integrity'", "'Federal' and 'Republic'"], 2, "The 42nd Amendment (1976) added Socialist, Secular, and Integrity to the Preamble."),
    ("Constitutional morality as a concept was emphasized by:", ["B.R. Ambedkar", "Jawaharlal Nehru", "Mahatma Gandhi", "Sardar Patel"], 0, "B.R. Ambedkar stressed that constitutional morality — adherence to constitutional principles — is essential for democracy."),
    ("Which of the following is true about the Indian Constitution? 1) It is the supreme law 2) It can never be amended 3) It provides for judicial review 4) It establishes parliamentary sovereignty", ["1 and 3 only", "1, 2 and 3", "1 and 4 only", "All four"], 0, "The Constitution is supreme (Art 13) and provides for judicial review. It can be amended (Art 368) and does not establish parliamentary sovereignty."),
    ("The concept of 'cooperative federalism' in India is strengthened by:", ["Inter-State Council", "NITI Aayog", "GST Council", "All of the above"], 3, "All these institutions promote cooperative federalism by facilitating Centre-State coordination."),
    ("The Preamble was amended:", ["Never", "Once by the 42nd Amendment", "Twice", "Three times"], 1, "The Preamble has been amended only once, by the 42nd Amendment Act, 1976."),
    ("Which of the following is considered a 'unique feature' of the Indian Constitution not found in any other?", ["Directive Principles", "Fundamental Rights", "Combination of rigidity and flexibility in the amendment process", "Written constitution"], 2, "The unique three-tier amendment process (simple majority, special majority, special majority + state ratification) is distinctive."),
    ("The writ jurisdiction of the Supreme Court under Article 32 is:", ["An ordinary law provision", "A fundamental right itself", "A directive principle", "Not enforceable"], 1, "The right to constitutional remedies (Art 32) is itself a fundamental right."),
    ("Consider the statements: 1) The Constitution of India is unitary in spirit. 2) The residuary powers lie with the Centre. 3) The Governor is appointed by the Centre. Which validate the 'quasi-federal' nature?", ["1 and 2 only", "2 and 3 only", "All three", "1 only"], 2, "All three features — unitary bias, residuary powers with Centre, and centrally appointed Governor — demonstrate quasi-federal nature."),
    ("The Berubari Union case (1960) held that:", ["The Preamble is part of the Constitution", "The Preamble is NOT part of the Constitution", "Fundamental Rights are absolute", "DPSPs override FRs"], 1, "In the Berubari case (1960), the SC held that the Preamble is not part of the Constitution. This was later overruled by Kesavananda Bharati."),
    ("The Kesavananda Bharati case overruled the Berubari case regarding the Preamble by holding that:", ["The Preamble can never be amended", "The Preamble is a part of the Constitution and can be amended subject to basic structure", "The Preamble has no legal value", "The Preamble is superior to all other provisions"], 1, "Kesavananda Bharati (1973) held that the Preamble is part of the Constitution but subject to the basic structure doctrine."),
    ("Which of the following constitutional provisions was borrowed from the Weimar Constitution of Germany?", ["Emergency provisions", "Suspension of Fundamental Rights during emergency", "Both 1 and 2", "Neither"], 2, "Both emergency provisions and the concept of suspending fundamental rights during emergencies were inspired by the Weimar Constitution."),
    ("The anti-defection provisions (Tenth Schedule) were added by which amendment?", ["42nd", "44th", "52nd", "91st"], 2, "The 52nd Amendment Act, 1985 added the Tenth Schedule (Anti-Defection Law)."),
    ("The concept of 'Sovereign' in the Preamble means India is:", ["Subject to foreign authority", "Neither a dominion nor a dependency of any other nation", "Under the UN control", "Subject to the Commonwealth"], 1, "Sovereign means India has supreme authority over its territory, free from external control."),
    ("Which of the following correctly describes the 'federal matrix' of the Indian Constitution?", ["Strong centre + weak states", "Strong states + weak centre", "Equal powers for centre and states with independent judiciary and written constitution", "No division of powers"], 2, "The federal matrix includes a written constitution, division of powers, and independent judiciary."),
    ("The Constitution of India has drawn the concept of 'Fundamental Rights enforceable by courts' from:", ["UK", "USA", "USSR", "France"], 1, "Justiciable Fundamental Rights were borrowed from the US Bill of Rights."),
    ("The doctrine of 'eclipse' under Article 13 means:", ["Pre-constitutional laws inconsistent with FRs become inactive but are not dead", "All old laws are automatically repealed", "Only post-constitutional laws are affected", "The judiciary has no role"], 0, "The eclipse doctrine means pre-constitutional laws are overshadowed but revive if the conflicting FR is amended."),
    ("Which committee of the Constituent Assembly dealt with Fundamental Rights?", ["Union Powers Committee", "Advisory Committee on Fundamental Rights (chaired by Sardar Patel)", "Drafting Committee", "Steering Committee"], 1, "The Advisory Committee on Fundamental Rights was chaired by Sardar Vallabhbhai Patel."),
    ("'Constitutional autochthony' means:", ["The constitution was imposed by a foreign power", "The constitution derives its authority from the native soil/people", "The constitution cannot be amended", "The constitution is based on religion"], 1, "Constitutional autochthony means the constitution is home-grown and derives authority from the people of the country."),
    ("In S.R. Bommai v. Union of India (1994), the Supreme Court held that:", ["President's Rule is beyond judicial review", "Secularism is a basic feature of the Constitution", "States have no autonomy", "Governor's power is absolute"], 1, "The SR Bommai case established that secularism is part of the basic structure and President's Rule is subject to judicial review."),
    ("The original constitution had how many Parts?", ["18", "22", "25", "20"], 1, "The original Constitution had 22 Parts, 395 Articles, and 8 Schedules."),
]

write_chapter(3, ch3_l1, ch3_l2, ch3_l3)
print("Chapter 3 done")

# ========================================  
# CHAPTER 35: Subordinate Courts
# ========================================
ch35_l1 = [
    ("Under which Articles of the Constitution are Subordinate Courts established?", ["Articles 233-237", "Articles 214-231", "Articles 124-147", "Articles 245-263"], 0, "Articles 233 to 237 deal with the Subordinate Courts."),
    ("The term 'District Judge' includes:", ["Only civil judges", "Judge of a city civil court, additional district judge, joint district judge, and assistant district judge", "Only criminal judges", "Only sessions judges"], 1, "Article 236 defines 'District Judge' broadly to include various judicial officers."),
    ("Who appoints District Judges?", ["The Chief Justice of the High Court", "The Governor of the State in consultation with the High Court", "The President of India", "The Chief Minister"], 1, "Article 233 provides that the appointment of District Judges is made by the Governor in consultation with the High Court."),
    ("District Judges who are not already in judicial service must have been an advocate for at least:", ["5 years", "7 years", "10 years", "3 years"], 1, "A person not already in judicial service must have been an advocate for not less than 7 years to be appointed as a District Judge."),
    ("Control over subordinate courts vests in:", ["The Governor", "The High Court", "The Supreme Court", "The State Legislature"], 1, "Article 235 provides that the control over district courts and subordinate courts vests in the High Court."),
    ("The highest civil court in a district is:", ["Sessions Court", "District Court (Court of the District Judge)", "Magistrate Court", "Lok Adalat"], 1, "The District Court is the highest civil court in a district."),
    ("The highest criminal court in a district is:", ["District Court", "Court of the Sessions Judge", "Chief Judicial Magistrate Court", "Executive Magistrate Court"], 1, "The Sessions Court (Court of the Sessions Judge) is the highest criminal court in a district."),
    ("Who presides over the Sessions Court?", ["The District Judge (who also acts as the Sessions Judge)", "The Chief Judicial Magistrate", "The Sub-Judge", "The Collector"], 0, "The District Judge acts as the Sessions Judge for criminal cases, presiding over the Sessions Court."),
    ("The Sessions Court can impose which maximum punishment?", ["7 years imprisonment", "14 years imprisonment", "Life imprisonment", "Death sentence (subject to confirmation by High Court)"], 3, "The Court of Session can impose the death sentence, but it must be confirmed by the High Court before execution."),
    ("The Court of the Chief Judicial Magistrate can impose imprisonment up to:", ["1 year", "3 years", "7 years", "Life imprisonment"], 2, "The CJM can impose imprisonment up to 7 years and any amount of fine."),
    ("The Court of a Judicial Magistrate First Class can impose imprisonment up to:", ["1 year", "3 years", "7 years", "5 years"], 1, "A JMFC can impose imprisonment up to 3 years and fine up to Rs. 10,000."),
    ("The Court of a Judicial Magistrate Second Class can impose imprisonment up to:", ["1 month", "6 months", "1 year", "3 years"], 2, "A Judicial Magistrate Second Class can impose imprisonment up to 1 year and fine up to Rs. 5,000."),
    ("In which year were the civil and criminal courts unified at the district level?", ["They are not unified; District Judge handles civil, Sessions Judge handles criminal", "1950", "1973", "1947"], 0, "The same person often functions as both District Judge (civil) and Sessions Judge (criminal) but they remain technically separate courts."),
    ("Which of the following courts deals with revenue matters?", ["District Court", "Sessions Court", "Revenue Court (presided by Collector/SDM)", "High Court"], 2, "Revenue courts deal with land revenue matters and are presided over by the Revenue Officer or Collector."),
    ("Small Causes Courts deal with:", ["Criminal cases", "Civil cases involving small monetary amounts", "Constitutional cases", "Election disputes"], 1, "Courts of Small Causes handle civil suits of small monetary value with simplified procedures."),
    ("The Code of Criminal Procedure (CrPC) was enacted in:", ["1861", "1872", "1973", "1950"], 2, "The current Code of Criminal Procedure was enacted in 1973 (replacing the earlier one of 1898). It was later replaced by BNSS in 2023."),
    ("Who exercises control over 'Executive Magistrates'?", ["High Court", "State Government", "Supreme Court", "District Judge"], 1, "Executive Magistrates are under the control of the State Government, unlike Judicial Magistrates who are under the High Court."),
    ("The establishment of Village Courts (Gram Nyayalayas) was recommended by:", ["Law Commission", "Sarkaria Commission", "Mandal Commission", "Finance Commission"], 0, "The Law Commission recommended village courts to provide justice at the grassroot level."),
    ("Gram Nyayalayas Act was passed in:", ["2005", "2008", "2010", "2015"], 1, "The Gram Nyayalayas Act was passed in 2008 to establish village courts at the grassroot level."),
    ("Gram Nyayalayas exercise jurisdiction over:", ["Civil and criminal cases of compoundable nature", "Only civil cases", "Only criminal cases", "Death penalty cases"], 0, "They handle both civil and criminal cases of a minor nature as specified in the Act."),
    ("The presiding officer of a Gram Nyayalaya is called:", ["Village Judge", "Nyayadhikari", "Panchayat Judge", "Sarpanch"], 1, "The presiding officer of a Gram Nyayalaya is called a Nyayadhikari."),
    ("Who appoints the Nyayadhikari?", ["The State Government in consultation with the High Court", "The District Judge", "The Village Panchayat", "The Governor alone"], 0, "The State Government appoints the Nyayadhikari in consultation with the High Court."),
    ("The Mobile Courts were established under which Act?", ["Code of Civil Procedure", "Motor Vehicles Act", "No specific Act; they are set up by the government for speedy trial", "Criminal Procedure Code"], 2, "Mobile Courts were an initiative to take justice to the doorstep of citizens, not established by a specific separate Act."),
    ("Family Courts were established under:", ["Family Courts Act, 1984", "Hindu Marriage Act, 1955", "Special Marriage Act, 1954", "Code of Civil Procedure"], 0, "The Family Courts Act, 1984 provides for establishment of Family Courts for settling family disputes."),
    ("Which Amendment of the Constitution introduced tribunals?", ["42nd Amendment", "44th Amendment", "73rd Amendment", "86th Amendment"], 0, "The 42nd Amendment (1976) added Part XIV-A (Tribunals) — Articles 323A and 323B."),
    ("Which of the following is NOT a subordinate court?", ["District Court", "Sessions Court", "High Court", "Chief Judicial Magistrate Court"], 2, "The High Court is a superior court, not a subordinate court. Subordinate courts come under the control of the High Court."),
    ("The process of 'committal' means:", ["Transfer of a case from Magistrate Court to Sessions Court", "Release of the accused", "Filing of a new case", "Appeal to the Supreme Court"], 0, "Committal is the process by which a Magistrate commits a case to the Sessions Court for trial."),
    ("Original civil jurisdiction in a district is exercised by:", ["Sessions Court", "Munsif Court and District Court", "High Court only", "Supreme Court only"], 1, "Munsif Courts handle civil cases of lower pecuniary value, while the District Court handles higher value cases."),
    ("The Munsif Court is:", ["The lowest level of civil court", "A criminal court", "Same as the High Court", "An appellate court only"], 0, "The Munsif Court (also called Civil Judge Junior Division) is the lowest level civil court at the district level."),
    ("Subordinate Judiciary in India is under the administrative control of:", ["The District Collector", "The High Court concerned", "The State Legislature", "The Ministry of Law"], 1, "Article 235 vests the control over the subordinate judiciary in the High Court."),
]

ch35_l2 = [
    ("Article 233 deals with:", ["Appointment of District Judges", "Appointment of High Court Judges", "Appointment of Supreme Court Judges", "Appointment of the Attorney General"], 0, "Article 233 specifically deals with the appointment of District Judges by the Governor in consultation with the High Court."),
    ("The 'All India Judicial Service' was proposed to:", ["Replace the Supreme Court", "Recruit judges for subordinate courts on an all-India basis", "Abolish High Courts", "Create a federal police force"], 1, "Article 312 allows Parliament to create an All India Judicial Service to recruit judges for district and subordinate courts on a nationwide basis."),
    ("The Shetty Commission (1999) recommended:", ["Abolition of subordinate courts", "Separation of judiciary from executive at all levels", "Merger of High Courts", "Reducing the number of judges"], 1, "The First National Judicial Pay Commission (Justice Shetty) recommended better service conditions and full separation of judiciary from executive."),
    ("Under Article 234, appointment of persons other than District Judges to the judicial service is made by:", ["The Governor in accordance with rules after consultation with the State PSC and the High Court", "The District Judge directly", "The Chief Justice of the High Court alone", "The Supreme Court"], 0, "Article 234 provides that such appointments are made by the Governor following rules made after consulting the SPSC and High Court."),
    ("The 'separation of judiciary from executive' is a directive under which Article?", ["Article 48", "Article 50", "Article 51", "Article 39"], 1, "Article 50 directs the State to take steps to separate the judiciary from the executive."),
    ("In the case of All India Judges Association v. Union of India (1993), the Supreme Court:", ["Directed uniform pay scales for subordinate judges", "Abolished subordinate courts", "Created the All India Judicial Service", "Removed all District Judges"], 0, "The SC directed uniform service conditions and better pay scales for subordinate judiciary across India."),
    ("The hierarchy of criminal courts from highest to lowest in a district is:", ["Sessions Court → CJM → JMFC → JMSC", "CJM → Sessions Court → JMFC → JMSC", "JMSC → JMFC → CJM → Sessions Court", "High Court → Sessions Court → CJM"], 0, "The hierarchy is: Court of Session (highest), then CJM, then JMFC, then JMSC."),
    ("Additional and Assistant Sessions Judges can impose:", ["Death sentence", "Life imprisonment", "Imprisonment up to 10 years", "Only fine"], 2, "Additional and Assistant Sessions Judges cannot impose the death sentence or life imprisonment — maximum is 10 years."),
    ("In India, the right to appeal in criminal cases is:", ["An absolute constitutional right", "A statutory right under CrPC/BNSS", "Not available at all", "Available only in civil cases"], 1, "The right to appeal in criminal cases is a statutory right provided by the CrPC (now BNSS), not a constitutional right."),
    ("What is 'Alternative Dispute Resolution' (ADR)?", ["A method of resolving disputes outside the regular court system", "A court within the Supreme Court", "A military tribunal", "A method used only in criminal cases"], 0, "ADR includes arbitration, mediation, conciliation, and Lok Adalats — all methods of resolving disputes without regular court trials."),
    ("The National Legal Services Authority (NALSA) was established under:", ["Legal Services Authorities Act, 1987", "Constitution (73rd Amendment)", "Code of Civil Procedure", "Indian Penal Code"], 0, "NALSA was established under the Legal Services Authorities Act, 1987 to organize legal aid and Lok Adalats."),
    ("Who is the Patron-in-Chief of NALSA?", ["The President of India", "The Chief Justice of India", "The Prime Minister", "The Law Minister"], 1, "The Chief Justice of India is the Patron-in-Chief of NALSA."),
    ("District Legal Services Authority is headed by:", ["The District Collector", "The District Judge", "The Chief Judicial Magistrate", "The Advocate General"], 1, "The District Judge serves as the Chairman of the District Legal Services Authority."),
    ("Article 236 defines 'District Judge' to include:", ["Only the principal judge of a district", "The judge of a civil court, additional district judge, joint district judge, etc.", "Only criminal court judges", "High Court judges posted in districts"], 1, "Article 236 gives a broad definition of 'District Judge' to include various judicial officers at the district level."),
    ("Which body recommends the names for appointment as district judges from the bar?", ["The State PSC", "A committee of the High Court", "The Governor", "The Parliament"], 1, "The High Court recommends names for direct recruitment of District Judges from the bar through a selection committee."),
    ("The concept of 'Fast Track Courts' was introduced for:", ["Revenue cases", "Speedy disposal of long-pending sessions cases", "Only commercial disputes", "International arbitration"], 1, "Fast Track Courts were set up based on the 11th Finance Commission's recommendation for speedy disposal of pending sessions cases."),
    ("What is a 'Peshi' in the context of subordinate courts?", ["A type of punishment", "A daily list of cases scheduled for hearing", "A rank of a judge", "A type of warrant"], 1, "Peshi refers to the daily cause list showing cases scheduled for hearing before a court on a particular day."),
    ("The Nyaya Panchayat system exists in:", ["Urban areas only", "Some states for minor civil and criminal matters at the village level", "All states uniformly", "Only in Union Territories"], 1, "Nyaya Panchayats exist in some states to adjudicate minor disputes at the village level."),
    ("The doctrine of 'stare decisis' in Indian courts means:", ["Lower courts must follow the decisions of higher courts", "Every court can decide independently without any binding precedent", "Only the Supreme Court's decisions matter", "Higher courts must follow lower court decisions"], 0, "Stare decisis means courts should follow previous decisions of higher courts on the same legal issue."),
    ("Which type of subordinate court handles succession and probate matters?", ["Sessions Court", "District Court (exercising probate jurisdiction)", "Revenue Court", "Consumer Forum"], 1, "The District Court exercises probate jurisdiction for matters relating to wills, succession, and administration of estates."),
    ("The term 'judicial service' under Article 236 does NOT include:", ["District Judges", "Magistrates", "Posts connected with the High Court", "Civil Judges"], 2, "Article 236(b) excludes any post connected with the district court or a position inferior to that of a district judge from the definition used for Article 233-235."),
    ("Which Amendment added Article 323A for Administrative Tribunals?", ["42nd Amendment", "44th Amendment", "73rd Amendment", "86th Amendment"], 0, "The 42nd Amendment (1976) added Articles 323A and 323B for tribunals."),
    ("The Commercial Courts Act, 2015 was enacted to:", ["Speed up resolution of commercial disputes of specified value", "Replace all subordinate courts", "Create a new Supreme Court bench", "Handle only international trade disputes"], 0, "Commercial Courts Act established specialized courts for speedy resolution of commercial disputes."),
    ("Who can transfer cases from one subordinate court to another within a district?", ["The District Judge", "The Chief Minister", "The Governor", "The Parliament"], 0, "The District Judge, as the head of the district judiciary, can transfer cases between subordinate courts in the district."),
    ("The Senior Division Civil Judge typically handles cases involving amounts:", ["Below Rs. 1 lakh", "Above the pecuniary limit of Junior Division but below that of the District Court", "Above Rs. 1 crore", "Only government claims"], 1, "Senior Division Civil Judges handle civil cases above the Junior Division's pecuniary jurisdiction but below the District Court's."),
    ("E-Courts project in India was launched to:", ["Replace judges with AI", "Computerize district and subordinate courts", "Create virtual Supreme Court", "Abolish paper records only"], 1, "The E-Courts project was launched to computerize and digitize the functioning of district and subordinate courts across India."),
    ("Who conducts the examination for recruitment of Civil Judges (Junior Division)?", ["UPSC", "State Public Service Commission or High Court", "District Judge", "Law Commission"], 1, "Recruitment of civil judges at the junior level is conducted by the State PSC or the High Court, depending on the state."),
    ("What is the role of the 'Public Prosecutor' in subordinate courts?", ["To defend the accused", "To represent the State/prosecution in criminal cases", "To act as the judge", "To conduct civil cases"], 1, "The Public Prosecutor represents the State in criminal proceedings before the Sessions Court and other criminal courts."),
    ("The Law Commission of India has repeatedly recommended which reform for subordinate courts?", ["Abolition of subordinate courts", "Increasing the judge-to-population ratio significantly", "Reducing judicial salaries", "Merging all courts into one"], 1, "The Law Commission has consistently recommended increasing the number of judges to improve the judge-to-population ratio, which is among the lowest globally."),
    ("Under the current system, a 'Munsif-Magistrate' system exists in:", ["All states uniformly", "Some states where the same officer handles both civil (Munsif) and criminal (Magistrate) work", "Only in the Supreme Court", "Only in High Courts"], 1, "In some states, the same judicial officer serves as both Munsif (civil) and Magistrate (criminal) at the lower level."),
]

ch35_l3 = [
    ("Consider: 1) Article 233 deals with District Judge appointment 2) Article 234 deals with recruitment of other judicial officers 3) Article 235 deals with High Court control over subordinate courts 4) Article 237 allows extension of these provisions to magistrates. Which are correct?", ["1, 2 and 3 only", "All four", "1 and 3 only", "2 and 4 only"], 1, "All four statements correctly describe Articles 233-237."),
    ("In the Second Judges Case (1993), the Supreme Court's ruling regarding the subordinate judiciary was:", ["High Courts have primacy in the appointment and transfer of district judges", "The Governor has absolute discretion", "The State Legislature decides appointments", "UPSC must conduct recruitment exams"], 0, "The Second Judges Case established the collegium system and reinforced the High Court's primacy in the appointment process."),
    ("The phrase 'control over district courts and courts subordinate thereto' in Article 235 includes:", ["Only disciplinary control", "Only administrative control", "Both administrative and disciplinary control but not interference in judicial decisions", "Complete control including overriding judicial orders"], 2, "In the Pradyat Kumar Bose case, the SC held that 'control' under Art 235 includes both administrative and disciplinary control but not judicial review of decisions."),
    ("Which of the following is a constitutional provision and not merely a statutory arrangement? 1) Establishment of subordinate courts 2) Appointment of District Judges 3) Establishment of Lok Adalats 4) All India Judicial Service", ["1 and 2 only", "1, 2 and 4", "1, 2, 3 and 4", "Only 2"], 1, "Articles 233-237 constitutionally provide for subordinate courts and District Judges. Article 312 provides for AIJS. Lok Adalats are statutory under LSAA 1987."),
    ("Statement I: The High Court can transfer a District Judge from one district to another. Statement II: The Governor alone can dismiss a District Judge without consulting the High Court. Choose:", ["Both statements are correct", "Only Statement I is correct", "Only Statement II is correct", "Both statements are incorrect"], 1, "The HC can transfer district judges (Art 235 control), but the Governor cannot dismiss without consulting the HC."),
    ("The 'National Mission for Justice Delivery and Legal Reforms' was launched to:", ["Create a new constitution", "Reduce pendency in courts, especially subordinate courts, through institutional reforms", "Replace subordinate courts with arbitration only", "Abolish the appellate system"], 1, "The mission aimed at reducing delays, arrears, and improving access to justice in subordinate courts."),
    ("Assertion: Subordinate courts handle the bulk of litigation in India. Reason: Over 80% of cases are pending in subordinate courts. Choose the correct option:", ["Both are true and Reason explains Assertion", "Both are true but Reason does not explain Assertion", "Assertion is true but Reason is false", "Assertion is false"], 0, "Over 80% of pending cases are in subordinate courts, which directly explains why they handle the bulk of litigation."),
    ("Which of the following is NOT within the 'control' exercised by the High Court under Article 235?", ["Transfer of subordinate judges", "Disciplinary proceedings against subordinate judges", "Overturning a judicial decision of a subordinate court through administrative order", "Leave and service conditions of subordinate judges"], 2, "The HC cannot overturn judicial decisions through administrative control; judicial review happens only through appeals."),
    ("The concept of a 'unified judiciary' in India means:", ["All courts are at the same level", "Subordinate courts, High Courts, and Supreme Court form a single hierarchy with the SC at the apex", "Only criminal courts are unified", "States have independent judicial systems"], 1, "India has a single integrated/unified judiciary where subordinate courts feed into High Courts which feed into the Supreme Court."),
    ("Under the Gram Nyayalayas Act, 2008, which statement is correct?", ["Gram Nyayalayas follow strict rules of evidence", "They can try all types of criminal offences", "They follow summary procedure and are not bound by rules of evidence under the Indian Evidence Act", "They are located only in urban areas"], 2, "Gram Nyayalayas follow simplified/summary procedures and are not strictly bound by the Evidence Act."),
    ("Consider: 1) Sessions Judge can award death penalty 2) Additional Sessions Judge can award life imprisonment 3) CJM can award up to 7 years imprisonment 4) JMFC can award up to 3 years. Which are correct?", ["1 and 3 only", "1, 3 and 4 only", "All four", "1, 2, 3 and 4"], 1, "Sessions Judge can award death penalty ✓, CJM up to 7 years ✓, JMFC up to 3 years ✓. But Additional Sessions Judge can award up to 10 years, NOT life imprisonment ✗."),
    ("The 14th Law Commission Report was significant for subordinate courts because it recommended:", ["Abolition of subordinate courts", "Reform of the judicial system including increase of judges and improving conditions of service of subordinate judiciary", "Merger of civil and criminal courts", "Direct election of judges"], 1, "The 14th Report (1958) laid the foundation for reforming the subordinate judiciary."),
    ("In which case did the Supreme Court direct that appointment to the subordinate judiciary should be on merit through competitive examination?", ["Malik Mazhar Sultan v. U.P. PSC", "All India Judges Association v. Union of India", "Both cases dealt with this issue", "None — it is a state discretion"], 2, "Both cases dealt with the recruitment, service conditions, and appointment process of subordinate judiciary."),
    ("The Arrears Committee (headed by Justice Malimath, 1990) recommended:", ["Increase in judges and supporting staff for subordinate courts", "Abolition of appeals", "Reducing working days", "Transfer of all cases to High Courts"], 0, "The Malimath Committee recommended increasing infrastructure and manpower to tackle pending cases."),
    ("The power of 'superintendence' of the High Court over subordinate courts under Article 227 is:", ["Administrative only", "Both administrative and judicial", "Judicial only", "Neither — it is with the Governor"], 1, "Article 227 gives the HC superintendence over all courts and tribunals throughout the territory, which is both administrative and judicial."),
    ("The e-Filing system in subordinate courts:", ["Is mandatory in all courts", "Is being progressively implemented as part of the eCourts project", "Has replaced physical filing completely", "Is only for Supreme Court"], 1, "e-Filing is being gradually rolled out across subordinate courts as part of the National e-Courts Mission Mode Project."),
    ("Which of the following is true about Family Courts? 1) Established under Family Courts Act 1984 2) Deal with matrimonial disputes, child custody, and maintenance 3) Follow simplified procedures 4) No lawyers are allowed", ["1, 2 and 3 only", "All four", "1 and 2 only", "1, 2, 3 and 4"], 0, "Family Courts follow simplified procedures and deal with family matters. Lawyers can appear but their role is limited; the court encourages settlement."),
    ("Article 233A (inserted by 20th Amendment, 1966) deals with:", ["Validation of appointments of, and judgements by, certain district judges", "Creation of new courts", "Retirement age of judges", "Salary of judges"], 0, "Article 233A validated certain appointments and judgements that were potentially irregular under the original Article 233."),
    ("The concept of 'case management' in subordinate courts involves:", ["Only administrative work", "Active judicial management of case progression to reduce delays including setting timelines", "Transferring cases to other states", "Hiring private firms"], 1, "Case management involves structured timeline-based supervision of case progression to reduce delays."),
    ("Consider the timeline: 1) LSAA 1987 2) Family Courts Act 1984 3) Gram Nyayalayas Act 2008 4) Commercial Courts Act 2015. Which chronological order is correct?", ["2, 1, 3, 4", "1, 2, 3, 4", "3, 4, 1, 2", "4, 3, 2, 1"], 0, "The correct chronological order is: Family Courts Act (1984) → LSAA (1987) → Gram Nyayalayas Act (2008) → Commercial Courts Act (2015)."),
    ("The concept of 'plea bargaining' was introduced in India by:", ["CrPC Amendment 2005", "Original CrPC 1973", "Constitution 42nd Amendment", "Indian Penal Code 1860"], 0, "Plea bargaining was introduced in India by the Criminal Law (Amendment) Act, 2005, adding Chapter XXIA to CrPC."),
    ("The maximum period for disposal of cases in commercial courts is:", ["6 months", "1 year", "3 years", "No time limit specified"], 1, "The Commercial Courts Act aims for disposal within 1 year through streamlined procedures."),
    ("Which of the following correctly describes Article 237?", ["It deals with removal of judges", "It empowers the Governor to apply Articles 233-236 to any class of magistrates", "It creates the All India Judicial Service", "It provides for appeals to the Supreme Court"], 1, "Article 237 allows the Governor to extend the provisions of Articles 233-236 to magistrates by notification."),
    ("The 'National Judicial Data Grid' (NJDG) provides:", ["Real-time data on pending and disposed cases across all courts in India", "Only Supreme Court case data", "Data on judges' salaries", "Information about law colleges"], 0, "NJDG is a database providing information on cases pending and disposed across courts, helping monitor judicial performance."),
    ("In the context of subordinate judiciary, 'cadre restructuring' refers to:", ["Removing all judges", "Reorganizing the hierarchy and number of posts at various levels to improve career progression and efficiency", "Converting civil courts to criminal courts", "Abolishing district courts"], 1, "Cadre restructuring aims to improve career opportunities and the overall structure of the subordinate judiciary."),
    ("The Mediation Act, 2023 was enacted to:", ["Replace all courts", "Promote mediation as an ADR mechanism with a statutory framework", "Abolish arbitration", "Create a mediation ministry"], 1, "The Mediation Act, 2023 provides a statutory framework for mediation, making it a pre-litigation requirement in certain cases."),
    ("Statement I: Article 235 ensures independence of subordinate judiciary from executive interference. Statement II: Subordinate courts are funded entirely by the central government. Choose:", ["Both are correct", "Only I is correct", "Only II is correct", "Both are incorrect"], 1, "Art 235 does protect from executive interference. But subordinate courts are funded primarily by state governments, not the central government."),
    ("Which initiative launched virtual courts for traffic challans and petty offenses?", ["e-Courts Phase I", "e-Courts Phase II", "National Mission for Justice Delivery", "Commercial Courts Project"], 1, "Virtual courts for handling traffic challans and petty offenses were launched as part of the e-Courts Phase II project."),
    ("The judge-to-population ratio in India's subordinate courts is approximately:", ["50 per million", "20 per million", "100 per million", "200 per million"], 1, "India has approximately 20 judges per million population in subordinate courts — one of the lowest ratios globally."),
]

write_chapter(35, ch35_l1, ch35_l2, ch35_l3)
print("Chapter 35 done")

print("\nFirst 2 chapters generated. Continuing with remaining 11...")
