"""
EduEcosystem — Bulk MCQ Bank Seeder
=====================================
Seeds 30 PYQ-style MCQs per subject for all 11 subjects
(History, Geography, Environment, Economy, Sci-Tech,
Art & Culture, Society, Ethics, International Relations,
Current Affairs, CSAT)

Run: python backend/seed_mcq_bank.py
"""
import sys
import os
import json
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'backend'))

import logging
from app.db.session import SessionLocal
from app.models.user import User
from app.models.question_bank import BankQuestion

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

MASTER_EMAIL = "ktej255@gmail.com"

# ─────────────────────────────────────────────────────────────────
# 30 PYQ-style MCQs per subject
# Format: text, options (A-D), correct (A/B/C/D), explanation, topic_tag, difficulty
# ─────────────────────────────────────────────────────────────────

SUBJECT_MCQS = {

    "History": [
        {"text": "Who among the following gave the call 'Do or Die'?", "options": ["A) Nehru", "B) Gandhi", "C) Bose", "D) Patel"], "correct": "B", "explanation": "Mahatma Gandhi gave the Quit India call 'Do or Die' on August 9, 1942.", "topic_tag": "Quit India Movement", "difficulty": "easy"},
        {"text": "The Regulating Act of 1773 was significant because it:", "options": ["A) Gave Company trading monopoly", "B) Created a Governor-General of Bengal", "C) Abolished the Zamindari system", "D) Introduced the Ryotwari settlement"], "correct": "B", "explanation": "The Regulating Act 1773 created the post of Governor-General of Bengal for the first time.", "topic_tag": "British Administration", "difficulty": "medium"},
        {"text": "Dandi March was a protest against which of the following?", "options": ["A) Tax on cotton", "B) Salt tax", "C) Rubber tax", "D) Indigo plantation"], "correct": "B", "explanation": "Gandhi led a 240-mile march from Sabarmati to Dandi to protest the British salt tax (1930).", "topic_tag": "Civil Disobedience", "difficulty": "easy"},
        {"text": "The First Buddhist Council was held at:", "options": ["A) Rajgriha", "B) Vaishali", "C) Pataliputra", "D) Kashmir"], "correct": "A", "explanation": "The First Buddhist Council was held at Rajgriha (Rajgir) under the patronage of Ajatashatru after Buddha's mahaparinirvana.", "topic_tag": "Buddhism", "difficulty": "medium"},
        {"text": "Who founded the Satvahana dynasty?", "options": ["A) Simuka", "B) Shatakarni", "C) Hala", "D) Gautamiputra"], "correct": "A", "explanation": "Simuka was the founder of the Satavahana dynasty, who established it after ending Mauryan rule in the Deccan.", "topic_tag": "Ancient India", "difficulty": "hard"},
        {"text": "The Tebhaga Movement (1946) in Bengal was related to:", "options": ["A) Workers' wages", "B) Share of crops for tenants", "C) Land redistribution", "D) Salt production"], "correct": "B", "explanation": "The Tebhaga Movement demanded 2/3rd (tebhaga) share of the crop for sharecroppers instead of half.", "topic_tag": "Peasant Movements", "difficulty": "hard"},
        {"text": "'India Wins Freedom' is an autobiography of:", "options": ["A) Jawaharlal Nehru", "B) Abul Kalam Azad", "C) Subhas Bose", "D) Lal Bahadur Shastri"], "correct": "B", "explanation": "Maulana Abul Kalam Azad wrote 'India Wins Freedom', describing the events around Partition and Independence.", "topic_tag": "Freedom Struggle", "difficulty": "easy"},
        {"text": "Which of the following Mughal emperors abolished 'Jizya'?", "options": ["A) Babur", "B) Humayun", "C) Akbar", "D) Jahangir"], "correct": "C", "explanation": "Akbar abolished Jizya (tax on non-Muslims) in 1564 as part of his policy of religious tolerance.", "topic_tag": "Mughal Empire", "difficulty": "easy"},
        {"text": "The Poona Pact (1932) was between:", "options": ["A) Gandhi and Jinnah", "B) Gandhi and Ambedkar", "C) Nehru and Ambedkar", "D) Gandhi and Irwin"], "correct": "B", "explanation": "The Poona Pact was signed between Gandhi and B.R. Ambedkar, ending the separate electorate for depressed classes.", "topic_tag": "Constitutional History", "difficulty": "medium"},
        {"text": "The Revolt of 1857 started from:", "options": ["A) Delhi", "B) Meerut", "C) Kanpur", "D) Lucknow"], "correct": "B", "explanation": "The Revolt of 1857 began in Meerut on May 10, when Indian sepoys revolted against the use of greased cartridges.", "topic_tag": "1857 Revolt", "difficulty": "easy"},
        {"text": "Who is known as the 'Father of Indian Unrest'?", "options": ["A) Gopal Gokhale", "B) Bal Gangadhar Tilak", "C) Lala Lajpat Rai", "D) Bipin Chandra Pal"], "correct": "B", "explanation": "Bal Gangadhar Tilak is known as the 'Father of Indian Unrest' — a title given by British writer Valentine Chirol.", "topic_tag": "Nationalist Leaders", "difficulty": "medium"},
        {"text": "The Simon Commission visited India in:", "options": ["A) 1925", "B) 1927", "C) 1928", "D) 1930"], "correct": "C", "explanation": "The Simon Commission visited India in 1928 to review the Government of India Act 1919. It was boycotted as it had no Indian member.", "topic_tag": "Constitutional Reforms", "difficulty": "medium"},
        {"text": "The Battle of Plassey (1757) was fought between:", "options": ["A) British and Marathas", "B) British and Siraj-ud-Daulah", "C) British and Tipu Sultan", "D) British and the Nawab of Awadh"], "correct": "B", "explanation": "The Battle of Plassey was fought between Robert Clive and Siraj-ud-Daulah, leading to British dominance in Bengal.", "topic_tag": "British Expansion", "difficulty": "easy"},
        {"text": "The Indian National Army (INA) was organized by:", "options": ["A) Bhagat Singh", "B) Subhas Chandra Bose", "C) V.D. Savarkar", "D) Bal Gangadhar Tilak"], "correct": "B", "explanation": "Subhas Chandra Bose reorganized the INA (Azad Hind Fauj) in 1943 to fight against the British in World War II.", "topic_tag": "INA", "difficulty": "easy"},
        {"text": "The Vernacular Press Act (1878) was passed to:", "options": ["A) Promote Indian press", "B) Curb nationalist press in Indian languages", "C) Provide free press for all", "D) Restrict British press in India"], "correct": "B", "explanation": "The Vernacular Press Act 1878 was passed by Lytton to muzzle criticism of the government in Indian language newspapers.", "topic_tag": "Press and Media", "difficulty": "medium"},
        {"text": "Rangarajan Commission dealt with:", "options": ["A) Centre-State relations", "B) Poverty estimation methodology", "C) Electoral reforms", "D) Judicial appointments"], "correct": "B", "explanation": "The Rangarajan Committee (2014) revised the poverty line estimation methodology in India.", "topic_tag": "Modern History", "difficulty": "hard"},
        {"text": "Who among the following was the President of the Indian National Congress in 1905?", "options": ["A) Gopal Krishna Gokhale", "B) Dadabhai Naoroji", "C) Bal Gangadhar Tilak", "D) Surendranath Banerjee"], "correct": "A", "explanation": "Gopal Krishna Gokhale presided over the Banaras session of INC in 1905 when the Partition of Bengal was annulled.", "topic_tag": "INC History", "difficulty": "hard"},
        {"text": "The Gupta period is considered the Golden Age because:", "options": ["A) Military conquests", "B) Cultural, scientific and artistic developments", "C) Trade with China", "D) Establishment of democracy"], "correct": "B", "explanation": "The Gupta period (320-550 CE) saw major advances in science (Aryabhata), literature (Kalidasa), art and philosophy.", "topic_tag": "Gupta Empire", "difficulty": "easy"},
        {"text": "Mahmud Ghazni invaded India for the first time in:", "options": ["A) 998 CE", "B) 1000 CE", "C) 1008 CE", "D) 1025 CE"], "correct": "B", "explanation": "Mahmud Ghazni invaded India for the first time in 1000 CE and went on to conduct 17 raids, mainly for plunder.", "topic_tag": "Medieval India", "difficulty": "medium"},
        {"text": "The partition of India was based on which plan?", "options": ["A) Wavell Plan", "B) Cripps Mission", "C) Mountbatten Plan", "D) Cabinet Mission"], "correct": "C", "explanation": "The Mountbatten Plan (June 3, 1947) provided the framework for the partition of India and Pakistan.", "topic_tag": "Partition of India", "difficulty": "easy"},
        {"text": "The Maratha confederacy was finally destroyed in:", "options": ["A) First Anglo-Maratha War", "B) Second Anglo-Maratha War", "C) Third Anglo-Maratha War", "D) Battle of Panipat 1761"], "correct": "C", "explanation": "The Third Anglo-Maratha War (1817-1818) ended with British victory and the destruction of the Maratha confederacy.", "topic_tag": "Maratha Empire", "difficulty": "medium"},
        {"text": "The concept of 'drain of wealth' was first given by:", "options": ["A) Bal Gangadhar Tilak", "B) Dadabhai Naoroji", "C) M.G. Ranade", "D) Gopal Krishna Gokhale"], "correct": "B", "explanation": "'Drain of wealth' theory was propounded by Dadabhai Naoroji in his famous book 'Poverty and Un-British Rule in India'.", "topic_tag": "Economic History", "difficulty": "medium"},
        {"text": "Harappan civilization is also known as:", "options": ["A) Vedic civilization", "B) Dravidian civilization", "C) Indus Valley civilization", "D) Deccan civilization"], "correct": "C", "explanation": "The Harappan or Indus Valley Civilization (2600-1900 BCE) is one of the world's oldest urban civilizations.", "topic_tag": "Ancient India", "difficulty": "easy"},
        {"text": "Who wrote 'Discovery of India'?", "options": ["A) Rajendra Prasad", "B) Jawaharlal Nehru", "C) Mahatma Gandhi", "D) B.R. Ambedkar"], "correct": "B", "explanation": "Jawaharlal Nehru wrote 'Discovery of India' while imprisoned in Ahmednagar Fort (1942-1946).", "topic_tag": "Freedom Struggle", "difficulty": "easy"},
        {"text": "The Deccan Riots of 1875 were related to:", "options": ["A) Tax protests by zamindars", "B) Peasant uprisings against moneylenders", "C) Factory workers' strike", "D) Tribal resistance to British"], "correct": "B", "explanation": "The Deccan Riots (1875) were peasant uprisings in Maharashtra against exploitative moneylenders (mainly Marwari).", "topic_tag": "Peasant Movements", "difficulty": "hard"},
        {"text": "Cripps Mission came to India in:", "options": ["A) 1940", "B) 1942", "C) 1944", "D) 1946"], "correct": "B", "explanation": "The Cripps Mission came to India in 1942 to offer dominion status in exchange for Indian cooperation in World War II. It failed.", "topic_tag": "World War II", "difficulty": "medium"},
        {"text": "Subsidiary Alliance was introduced by:", "options": ["A) Lord Cornwallis", "B) Lord Wellesley", "C) Lord Dalhousie", "D) Lord Curzon"], "correct": "B", "explanation": "Lord Wellesley introduced the Subsidiary Alliance System (1798) forcing Indian rulers to maintain British troops.", "topic_tag": "British Policy", "difficulty": "easy"},
        {"text": "Where did Mahatma Gandhi first apply Satyagraha?", "options": ["A) India — Dandi", "B) South Africa — Natal", "C) India — Champaran", "D) South Africa — Transvaal"], "correct": "D", "explanation": "Gandhi first applied Satyagraha in the Transvaal of South Africa (1906) against the Black Act registration requirement.", "topic_tag": "Gandhi", "difficulty": "hard"},
        {"text": "'Swaraj is my birthright and I shall have it' was said by:", "options": ["A) Nehru", "B) Gandhi", "C) Tilak", "D) Bose"], "correct": "C", "explanation": "Bal Gangadhar Tilak said 'Swaraj is my birthright and I shall have it', galvanizing the Indian freedom movement.", "topic_tag": "Nationalist Slogans", "difficulty": "easy"},
        {"text": "The Servants of India Society was founded by:", "options": ["A) Gopal Krishna Gokhale", "B) Bal Gangadhar Tilak", "C) Dadabhai Naoroji", "D) Lala Lajpat Rai"], "correct": "A", "explanation": "Gopal Krishna Gokhale founded the Servants of India Society in 1905 to train public workers for national service.", "topic_tag": "Social Organizations", "difficulty": "medium"},
    ],

    "Geography": [
        {"text": "The Tropic of Cancer passes through how many Indian states?", "options": ["A) 6", "B) 7", "C) 8", "D) 9"], "correct": "C", "explanation": "The Tropic of Cancer passes through 8 Indian states: Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, West Bengal, Tripura, and Mizoram.", "topic_tag": "Physical Geography", "difficulty": "medium"},
        {"text": "Which of the following rivers flows into the Arabian Sea?", "options": ["A) Krishna", "B) Godavari", "C) Narmada", "D) Mahanadi"], "correct": "C", "explanation": "The Narmada and Tapti are the major rivers of peninsular India that flow westward into the Arabian Sea.", "topic_tag": "Rivers & Drainage", "difficulty": "easy"},
        {"text": "The Deccan Trap was formed due to:", "options": ["A) Volcanic eruptions", "B) Erosion by rivers", "C) Fold mountain formation", "D) Glacial deposits"], "correct": "A", "explanation": "The Deccan Traps were formed 65-68 million years ago by volcanic eruptions (lava flows), coinciding with the Cretaceous-Paleogene extinction event.", "topic_tag": "Geomorphology", "difficulty": "medium"},
        {"text": "Which soil is most suitable for cotton cultivation?", "options": ["A) Alluvial soil", "B) Red soil", "C) Black (Regur) soil", "D) Laterite soil"], "correct": "C", "explanation": "Black soil (Regur), found mainly in Deccan Trap areas, is most suitable for cotton cultivation due to its moisture-retaining capacity.", "topic_tag": "Soils", "difficulty": "easy"},
        {"text": "The Siachen Glacier is located in the:", "options": ["A) Himalayas", "B) Karakoram Range", "C) Hindu Kush", "D) Shivalik Hills"], "correct": "B", "explanation": "Siachen Glacier is located in the Karakoram Range and is the world's highest-altitude battle zone, claimed by both India and Pakistan.", "topic_tag": "Physical Geography", "difficulty": "medium"},
        {"text": "The Strait of Malacca separates:", "options": ["A) India and Sri Lanka", "B) Malaysia and Indonesia (Sumatra)", "C) Japan and Korea", "D) Philippines and Indonesia"], "correct": "B", "explanation": "The Strait of Malacca separates the Malay Peninsula (Malaysia) from the Indonesian island of Sumatra.", "topic_tag": "World Geography", "difficulty": "easy"},
        {"text": "Which of the following is the correct sequence of rivers from north to south on the western coast of India?", "options": ["A) Narmada, Tapti, Mahi", "B) Mahi, Narmada, Tapti", "C) Tapti, Narmada, Mahi", "D) Mahi, Tapti, Narmada"], "correct": "B", "explanation": "From north to south: Mahi (Gujarat) → Narmada (MP/Gujarat) → Tapti (MP/Maharashtra/Gujarat).", "topic_tag": "Rivers & Drainage", "difficulty": "hard"},
        {"text": "Monsoon in India is caused mainly by:", "options": ["A) Ocean currents", "B) Differential heating of land and sea", "C) Westerly jet streams", "D) Trade winds alone"], "correct": "B", "explanation": "The Indian Monsoon is primarily caused by differential heating of the Indian subcontinent and the Indian Ocean, creating a pressure gradient.", "topic_tag": "Climatology", "difficulty": "easy"},
        {"text": "The Andaman and Nicobar Islands are remnants of a submerged:", "options": ["A) Fold mountain chain", "B) Volcanic island arc", "C) Coastal plain", "D) Coral reef system"], "correct": "B", "explanation": "The Andaman and Nicobar Islands are remnants of a volcanic island arc, formed due to subduction of the Indo-Australian plate.", "topic_tag": "Physical Geography", "difficulty": "hard"},
        {"text": "Laterite soil is deficient in:", "options": ["A) Iron and Aluminium", "B) Nitrogen and Potash", "C) Calcium and Magnesium", "D) Silica and Potassium Oxide"], "correct": "B", "explanation": "Laterite soil is rich in iron and aluminium oxides but is deficient in N, P, K, and organic content, making it less fertile.", "topic_tag": "Soils", "difficulty": "medium"},
        {"text": "The 'rain shadow area' in India is:", "options": ["A) Western Ghat's windward side", "B) Eastern Ghat's western side", "C) Western Ghat's leeward (eastern) side", "D) Himalayan foothills"], "correct": "C", "explanation": "The eastern side of the Western Ghats forms a rain shadow area as the SW monsoon loses moisture while rising over the Ghats.", "topic_tag": "Climatology", "difficulty": "medium"},
        {"text": "Which of the following is a 'Hot Desert'?", "options": ["A) Gobi Desert", "B) Patagonian Desert", "C) Sahara Desert", "D) Antarctic Ice Sheet"], "correct": "C", "explanation": "The Sahara is the world's largest hot desert. Gobi and Patagonian are cold deserts. Antarctica is an ice desert.", "topic_tag": "World Geography", "difficulty": "easy"},
        {"text": "The Eastern Ghats are interrupted by which of the following rivers?", "options": ["A) Godavari, Krishna, Cauvery", "B) Narmada, Tapti, Mahanadi", "C) Mahanadi, Godavari, Krishna, Cauvery", "D) Chambal, Ken, Betwa"], "correct": "C", "explanation": "The Eastern Ghats are broken by rivers like Mahanadi, Godavari, Krishna, and Cauvery, making them discontinuous.", "topic_tag": "Physical Geography", "difficulty": "medium"},
        {"text": "The Chilika Lake is located in:", "options": ["A) Andhra Pradesh", "B) Odisha", "C) West Bengal", "D) Tamil Nadu"], "correct": "B", "explanation": "Chilika Lake in Odisha is Asia's largest brackish water lagoon and an important Ramsar Wetland site.", "topic_tag": "National Parks & Wildlife", "difficulty": "easy"},
        {"text": "Which type of vegetation grows in areas with rainfall between 70-200 cm?", "options": ["A) Tropical Evergreen", "B) Tropical Deciduous", "C) Tropical Thorn", "D) Mangrove"], "correct": "B", "explanation": "Tropical Deciduous (Monsoon) forests grow where rainfall is between 70-200 cm. Trees shed leaves in dry season.", "topic_tag": "Natural Vegetation", "difficulty": "medium"},
        {"text": "The Brahmaputra river in India originates from:", "options": ["A) Gangotri Glacier", "B) Amarkantak", "C) Chemayungdung Glacier (Tibet)", "D) Mansarovar Lake"], "correct": "C", "explanation": "The Brahmaputra originates from Chemayungdung Glacier in Tibet and enters India through Arunachal Pradesh.", "topic_tag": "Rivers & Drainage", "difficulty": "hard"},
        {"text": "Which of the following cities is NOT located on the banks of the Ganga?", "options": ["A) Varanasi", "B) Patna", "C) Kolkata", "D) Kanpur"], "correct": "C", "explanation": "Kolkata is located on the banks of the Hooghly River (a distributary of Ganga), not directly on the main Ganga.", "topic_tag": "Rivers & Drainage", "difficulty": "medium"},
        {"text": "The Nallamala Hills are part of:", "options": ["A) Western Ghats", "B) Eastern Ghats", "C) Aravalli Range", "D) Vindhya Range"], "correct": "B", "explanation": "Nallamala Hills are part of the Eastern Ghats, located in Andhra Pradesh. The Nagarjunasagar-Srisailam Tiger Reserve is here.", "topic_tag": "Physical Geography", "difficulty": "hard"},
        {"text": "The Himalayan river Ganga originates from:", "options": ["A) Yamunotri", "B) Gangotri Glacier", "C) Manasarovar Lake", "D) Kedarnath"], "correct": "B", "explanation": "The Ganga originates from Gangotri Glacier at Gomukh (Uttarakhand) at an altitude of 3,892 m.", "topic_tag": "Rivers & Drainage", "difficulty": "easy"},
        {"text": "Mango showers are associated with:", "options": ["A) Northwest India", "B) Kerala and Tamil Nadu", "C) Bengal", "D) Rajasthan"], "correct": "B", "explanation": "Mango showers are pre-monsoon showers in Kerala and Tamil Nadu that help in ripening of mango fruit.", "topic_tag": "Climatology", "difficulty": "medium"},
        {"text": "Which of the following states has the largest area under forests?", "options": ["A) Arunachal Pradesh", "B) Madhya Pradesh", "C) Chhattisgarh", "D) Uttarakhand"], "correct": "B", "explanation": "Madhya Pradesh has the largest area under forest cover in India (77,414 sq km) as per the State of Forest Report 2021.", "topic_tag": "Natural Vegetation & Forest", "difficulty": "hard"},
        {"text": "The Sunderban delta is formed by which rivers?", "options": ["A) Ganga and Brahmaputra", "B) Mahanadi and Godavari", "C) Indus and Chenab", "D) Narmada and Tapti"], "correct": "A", "explanation": "Sunderbans is the world's largest mangrove delta, formed by the Ganga-Brahmaputra river system in West Bengal and Bangladesh.", "topic_tag": "Geomorphology", "difficulty": "easy"},
        {"text": "The highest peak in the Eastern Ghats is:", "options": ["A) Mahendragiri", "B) Arma Konda", "C) Jindhagada Peak", "D) Shevaroy Hills"], "correct": "B", "explanation": "Arma Konda (1,680 m) in Andhra Pradesh is the highest peak of the Eastern Ghats.", "topic_tag": "Physical Geography", "difficulty": "hard"},
        {"text": "Which ocean current makes Western Europe warm?", "options": ["A) Labrador Current", "B) Gulf Stream", "C) Canary Current", "D) North Atlantic Current"], "correct": "D", "explanation": "The North Atlantic Current (extension of Gulf Stream) brings warm water to Western Europe, keeping it warmer than its latitude suggests.", "topic_tag": "World Geography", "difficulty": "medium"},
        {"text": "The laterite soils are most commonly found in:", "options": ["A) Indo-Gangetic plains", "B) High rainfall tropical regions", "C) Desert regions", "D) Mountainous regions"], "correct": "B", "explanation": "Laterite soils form in areas with high seasonal rainfall due to leaching of silica and accumulation of iron oxides.", "topic_tag": "Soils", "difficulty": "medium"},
        {"text": "The International Date Line passes through:", "options": ["A) Atlantic Ocean", "B) Pacific Ocean", "C) Indian Ocean", "D) Arctic Ocean"], "correct": "B", "explanation": "The International Date Line (180° meridian) passes through the Pacific Ocean, roughly following the 180° line of longitude.", "topic_tag": "Maps & Location", "difficulty": "easy"},
        {"text": "The continental shelf off India's coast is richest in:", "options": ["A) Fisheries", "B) Diamonds", "C) Coal deposits", "D) Thorium"], "correct": "A", "explanation": "India's continental shelf, especially off the northwest and southeast coasts, is rich in fisheries and some hydrocarbon deposits.", "topic_tag": "Economic Geography", "difficulty": "medium"},
        {"text": "Roaring Forties refers to:", "options": ["A) Tropical cyclones", "B) Ocean zones with heavy shipping traffic", "C) Strong westerly winds in 40°-50° S latitude", "D) Earthquake prone zones"], "correct": "C", "explanation": "Roaring Forties are strong westerly winds found between 40°-50° South latitude, famous for sailing routes.", "topic_tag": "Climatology", "difficulty": "hard"},
        {"text": "The Lonar Lake in Maharashtra was created by:", "options": ["A) Glacial activity", "B) Meteorite impact", "C) Volcanic eruption", "D) River erosion"], "correct": "B", "explanation": "Lonar Lake (Maharashtra) is one of the few hyper-velocity meteorite impact craters in the world, formed approximately 50,000 years ago.", "topic_tag": "Geomorphology", "difficulty": "hard"},
        {"text": "The term 'Doab' refers to the land between:", "options": ["A) Two mountains", "B) Two rivers", "C) A river and a lake", "D) The sea and a river"], "correct": "B", "explanation": "Doab literally means 'two waters' — it refers to the fertile land between two rivers, like the Ganga-Yamuna doab.", "topic_tag": "Rivers & Drainage", "difficulty": "easy"},
        {"text": "India's longest river (by length) is:", "options": ["A) Brahmaputra", "B) Yamuna", "C) Godavari", "D) Ganga"], "correct": "D", "explanation": "The Ganga (2,525 km) is India's longest river, flowing from Gangotri Glacier in Uttarakhand to the Bay of Bengal.", "topic_tag": "Rivers & Drainage", "difficulty": "easy"},
    ],

    "Environment": [
        {"text": "The CITES convention aims to protect:", "options": ["A) Marine pollution", "B) Flora and fauna in international trade", "C) Endangered habitats", "D) Freshwater bodies"], "correct": "B", "explanation": "CITES (Convention on International Trade in Endangered Species) regulates international trade in endangered wild species.", "topic_tag": "International Conventions", "difficulty": "easy"},
        {"text": "The ozone layer is found in which layer of the atmosphere?", "options": ["A) Troposphere", "B) Stratosphere", "C) Mesosphere", "D) Thermosphere"], "correct": "B", "explanation": "The ozone layer is found 15-35 km above the Earth's surface in the stratosphere, protecting us from UV-B and UV-C radiation.", "topic_tag": "Atmosphere", "difficulty": "easy"},
        {"text": "The Kyoto Protocol was related to:", "options": ["A) Ozone depletion", "B) Marine pollution", "C) Greenhouse gas emissions reduction", "D) Nuclear waste management"], "correct": "C", "explanation": "The Kyoto Protocol (1997) was the first international agreement binding developed nations to reduce greenhouse gas emissions.", "topic_tag": "Climate Agreements", "difficulty": "easy"},
        {"text": "Biosphere is defined as:", "options": ["A) All ecosystems within a defined area", "B) The sphere of water on Earth", "C) The zone of Earth supporting life", "D) The atmosphere above the tropics"], "correct": "C", "explanation": "Biosphere is the global sum of all ecosystems — the zone of Earth where life exists, from ocean floors to mountain tops.", "topic_tag": "Ecology", "difficulty": "easy"},
        {"text": "The 'Chipko Movement' was primarily related to:", "options": ["A) Water conservation", "B) Forest conservation", "C) Soil conservation", "D) Wildlife protection"], "correct": "B", "explanation": "Chipko Movement (1973), Uttarakhand — women hugged trees to prevent commercial logging, catalyzing India's environmental movement.", "topic_tag": "Environmental Movements", "difficulty": "easy"},
        {"text": "Which of the following is a greenhouse gas?", "options": ["A) Nitrogen", "B) Oxygen", "C) Methane", "D) Argon"], "correct": "C", "explanation": "Methane (CH₄) is a powerful greenhouse gas, about 30 times more potent than CO₂ on a 20-year timescale.", "topic_tag": "Climate Change", "difficulty": "easy"},
        {"text": "The National Action Plan on Climate Change (NAPCC) has how many missions?", "options": ["A) 6", "B) 8", "C) 10", "D) 12"], "correct": "B", "explanation": "NAPCC (2008) has 8 national missions including Solar, Enhanced Energy Efficiency, Sustainable Habitat, Water, Himalayan Ecosystem, Green India, Sustainable Agriculture, and Strategic Knowledge.", "topic_tag": "India's Climate Policy", "difficulty": "medium"},
        {"text": "The Ramsar Convention deals with:", "options": ["A) Marine Protected Areas", "B) Wetland conservation", "C) Trade in endangered species", "D) Ozone protection"], "correct": "B", "explanation": "The Ramsar Convention (1971) is an international treaty for the conservation and sustainable use of wetlands.", "topic_tag": "Wetlands", "difficulty": "easy"},
        {"text": "Eutrophication of water bodies is caused by excess of:", "options": ["A) Phosphorus and Nitrogen", "B) Carbon dioxide", "C) Heavy metals", "D) Chlorine"], "correct": "A", "explanation": "Eutrophication occurs due to excess nitrogen and phosphorus (from fertilizers) causing algal blooms and oxygen depletion.", "topic_tag": "Water Pollution", "difficulty": "medium"},
        {"text": "Primary succession occurs on:", "options": ["A) Previously forested areas", "B) Abandoned agricultural fields", "C) Bare rock or new volcanic island", "D) Logged forest areas"], "correct": "C", "explanation": "Primary succession starts on bare substrates (rocks, lava) where no organisms existed before. Pioneer organisms colonize first.", "topic_tag": "Ecology", "difficulty": "medium"},
        {"text": "The CBD (Convention on Biological Diversity) was signed at:", "options": ["A) Stockholm (1972)", "B) Rio de Janeiro (1992)", "C) Kyoto (1997)", "D) Paris (2015)"], "correct": "B", "explanation": "The CBD was signed at the UN Earth Summit in Rio de Janeiro in 1992. It covers biodiversity conservation, sustainable use, and benefit sharing.", "topic_tag": "International Conventions", "difficulty": "medium"},
        {"text": "Which of the following is NOT a characteristic of mangrove forests?", "options": ["A) Salt tolerance", "B) Prop roots", "C) Found in freshwater rivers", "D) Provide coastal protection"], "correct": "C", "explanation": "Mangroves grow in tropical and subtropical intertidal coastal areas, not freshwater. They are salt-tolerant halophytes.", "topic_tag": "Natural Vegetation", "difficulty": "easy"},
        {"text": "BRT Tiger Reserve is located in:", "options": ["A) Karnataka", "B) West Bengal", "C) Assam", "D) Rajasthan"], "correct": "A", "explanation": "Biligiri Rangana Hills (BRT) Tiger Reserve is located in Karnataka and is also an Elephant Reserve — unique status.", "topic_tag": "National Parks & Wildlife", "difficulty": "hard"},
        {"text": "The pollutant responsible for acid rain is:", "options": ["A) CO₂ and CH₄", "B) SO₂ and NOₓ", "C) CFC and HFC", "D) CO and VOC"], "correct": "B", "explanation": "Acid rain is caused by SO₂ and NOₓ emissions from burning fossil fuels, which react with water to form H₂SO₄ and HNO₃.", "topic_tag": "Air Pollution", "difficulty": "easy"},
        {"text": "In trophic levels, which of the following is a producer?", "options": ["A) Grasshopper", "B) Frog", "C) Grass", "D) Snake"], "correct": "C", "explanation": "Producers (autotrophs) like grass make their own food via photosynthesis. Grasshopper = primary consumer, Frog = secondary consumer.", "topic_tag": "Food Chains & Food Webs", "difficulty": "easy"},
        {"text": "Gond and Baiga tribes are associated with which national park?", "options": ["A) Kanha Tiger Reserve", "B) Sundarbans", "C) Ranthambore", "D) Periyar"], "correct": "A", "explanation": "Kanha National Park (MP) is associated with Gond and Baiga tribal communities and is famous for the Bengal tiger.", "topic_tag": "National Parks & Wildlife", "difficulty": "medium"},
        {"text": "The concept of 'Carrying Capacity' in ecology refers to:", "options": ["A) Weight a habitat can support", "B) Maximum population size an environment can support", "C) Minimum temperature for growth", "D) Biomass at a trophic level"], "correct": "B", "explanation": "Carrying capacity (K) is the maximum population size that an environment can sustain indefinitely given the available resources.", "topic_tag": "Ecology", "difficulty": "medium"},
        {"text": "The 'Kunming-Montreal Global Biodiversity Framework' target is to protect by 2030:", "options": ["A) 10% of land", "B) 20% of oceans", "C) 30% of land and 30% of oceans (30x30)", "D) 50% of tropical forests"], "correct": "C", "explanation": "The Kunming-Montreal GBF (2022) set a target to protect 30% of the world's land and 30% of oceans by 2030 (30x30 target).", "topic_tag": "Biodiversity", "difficulty": "hard"},
        {"text": "Project Tiger was launched in India in:", "options": ["A) 1965", "B) 1972", "C) 1973", "D) 1980"], "correct": "C", "explanation": "Project Tiger was launched in 1973 under PM Indira Gandhi to protect tigers from extinction. Corbett was the first reserve.", "topic_tag": "Conservation", "difficulty": "easy"},
        {"text": "Carbon sequestration refers to:", "options": ["A) Release of CO₂ into atmosphere", "B) Capturing and storing atmospheric carbon dioxide", "C) Burning of organic material", "D) Ocean acidification process"], "correct": "B", "explanation": "Carbon sequestration is the process of capturing CO₂ from the atmosphere and storing it in plants, soil, oceans, or geological formations.", "topic_tag": "Climate Change", "difficulty": "medium"},
        {"text": "UNFCCC stands for:", "options": ["A) UN Framework Convention on Climate Change", "B) United Fund for Climate Change Commitments", "C) UN Framework Conference on Carbon Credits", "D) UN Federation for Climate Conservation"], "correct": "A", "explanation": "UNFCCC is the United Nations Framework Convention on Climate Change, formed at Rio Earth Summit 1992, parent body for Paris Agreement and Kyoto Protocol.", "topic_tag": "International Conventions", "difficulty": "easy"},
        {"text": "The biological oxygen demand (BOD) measures:", "options": ["A) Oxygen produced by plants", "B) Oxygen consumed by microbes to decompose organic matter in water", "C) Carbon dioxide dissolved in water", "D) Toxic chemicals in water"], "correct": "B", "explanation": "BOD measures the amount of dissolved oxygen consumed by biological organisms when decomposing organic matter in water. Higher BOD = more polluted water.", "topic_tag": "Water Pollution", "difficulty": "medium"},
        {"text": "India's first National Park is:", "options": ["A) Bandipur", "B) Gir", "C) Corbett", "D) Kaziranga"], "correct": "C", "explanation": "Jim Corbett National Park (Uttarakhand), established in 1936 as Hailey National Park, is India's oldest national park.", "topic_tag": "National Parks & Wildlife", "difficulty": "easy"},
        {"text": "The 'Green Bonus' in India refers to:", "options": ["A) Subsidy for solar panels", "B) Additional funds to states with more forest cover", "C) Insurance for farmers", "D) Carbon credits for industry"], "correct": "B", "explanation": "Green Bonus/Green Budget proposals suggest compensating states like Northeastern states for maintaining large forest cover that provides ecological services.", "topic_tag": "India's Climate Policy", "difficulty": "hard"},
        {"text": "Pheromones in insects are used for:", "options": ["A) Defense against predators", "B) Chemical communication", "C) Photosynthesis", "D) Nitrogen fixation"], "correct": "B", "explanation": "Pheromones are chemical signals secreted by insects (and other animals) to communicate — for mating, alarm, trail marking etc.", "topic_tag": "Ecology", "difficulty": "medium"},
        {"text": "In situ conservation refers to:", "options": ["A) Conservation in zoos and botanical gardens", "B) Conservation of species in their natural habitat", "C) DNA banking of species", "D) Captive breeding programs"], "correct": "B", "explanation": "In situ conservation = conservation in natural habitats (national parks, biosphere reserves). Ex situ = outside habitats (zoos, seed banks).", "topic_tag": "Conservation", "difficulty": "easy"},
        {"text": "The Intergovernmental Panel on Climate Change (IPCC) was established in:", "options": ["A) 1972", "B) 1988", "C) 1992", "D) 1997"], "correct": "B", "explanation": "The IPCC was established in 1988 jointly by WMO and UNEP to assess climate change science and provide policy recommendations.", "topic_tag": "Climate Bodies", "difficulty": "medium"},
        {"text": "The 'missing carbon sink' paradox relates to:", "options": ["A) Unknown carbon emitters", "B) Carbon absorbed by terrestrial ecosystems not fully accounted for", "C) Carbon lost in the deep sea", "D) Carbon stored in urban trees"], "correct": "B", "explanation": "The missing carbon sink refers to the fact that measured emissions exceed measured atmospheric increase, suggesting large unknown terrestrial carbon sinks (likely forests).", "topic_tag": "Climate Change", "difficulty": "hard"},
        {"text": "National Green Tribunal (NGT) was established under:", "options": ["A) Environment Protection Act 1986", "B) Wildlife Protection Act 1972", "C) NGT Act 2010", "D) Forest Rights Act 2006"], "correct": "C", "explanation": "NGT was established under the National Green Tribunal Act 2010 to handle environmental disputes speedily.", "topic_tag": "Environmental Law", "difficulty": "medium"},
        {"text": "The concept of 'One Health' recognizes that:", "options": ["A) All diseases are caused by bacteria", "B) Human, animal and environmental health are interconnected", "C) Mental health is linked to physical health", "D) Healthcare needs to be universal"], "correct": "B", "explanation": "The 'One Health' concept recognizes that human health, animal health, and environmental health are interdependent — crucial for pandemic prevention.", "topic_tag": "Ecology", "difficulty": "hard"},
    ],

    "Economy": [
        {"text": "The RBI was established in:", "options": ["A) 1930", "B) 1935", "C) 1947", "D) 1955"], "correct": "B", "explanation": "Reserve Bank of India was established on April 1, 1935 under the RBI Act 1934 and was nationalized in 1949.", "topic_tag": "Banking System", "difficulty": "easy"},
        {"text": "Inflation is measured in India using:", "options": ["A) GDP Deflator only", "B) WPI, CPI, and GDP Deflator", "C) CPI only", "D) WPI only"], "correct": "B", "explanation": "India uses CPI (Consumer Price Index) for monetary policy (RBI's target), WPI (Wholesale Price Index) for industrial inflation, and GDP Deflator for national accounts.", "topic_tag": "Inflation", "difficulty": "medium"},
        {"text": "NITI Aayog replaced which institution?", "options": ["A) Ministry of Planning", "B) Planning Commission", "C) Finance Commission", "D) Economic Advisory Council"], "correct": "B", "explanation": "NITI Aayog replaced the Planning Commission on January 1, 2015. It is a policy think tank, not a resource allocation body.", "topic_tag": "Planning", "difficulty": "easy"},
        {"text": "The Goods and Services Tax (GST) in India is a:", "options": ["A) Single-rate tax", "B) Multi-rate, destination-based consumption tax", "C) Origin-based production tax", "D) Import tax"], "correct": "B", "explanation": "GST is a multi-rate consumption tax that is collected at the point of consumption (destination), replacing multiple indirect taxes.", "topic_tag": "Taxation", "difficulty": "medium"},
        {"text": "Which of the following is NOT a function of the RBI?", "options": ["A) Issue of currency", "B) Regulating commercial banks", "C) Determining fiscal policy", "D) Maintaining foreign exchange reserves"], "correct": "C", "explanation": "Fiscal policy (taxation, government spending) is determined by the government/Finance Ministry. RBI controls monetary policy.", "topic_tag": "Banking System", "difficulty": "easy"},
        {"text": "The Hawala transaction is related to:", "options": ["A) Legal banking transfers", "B) Informal parallel money transfer system", "C) International FDI", "D) Stock market speculation"], "correct": "B", "explanation": "Hawala is an informal value transfer system based on a network of brokers (hawaladars), often used to bypass official banking.", "topic_tag": "Black Economy", "difficulty": "medium"},
        {"text": "SEBI is the regulatory body for:", "options": ["A) Banking sector", "B) Insurance sector", "C) Securities and capital markets", "D) Foreign exchange"], "correct": "C", "explanation": "SEBI (Securities and Exchange Board of India) regulates the securities and capital markets, protecting investor interests.", "topic_tag": "Financial Markets", "difficulty": "easy"},
        {"text": "The current account of Balance of Payments includes:", "options": ["A) FDI flows", "B) Trade in goods and services, remittances", "C) External borrowings", "D) Foreign exchange reserves"], "correct": "B", "explanation": "India's current account includes trade balance (goods + services), income (remittances, dividends), and unilateral transfers.", "topic_tag": "Balance of Payments", "difficulty": "medium"},
        {"text": "The term 'Dutch Disease' refers to:", "options": ["A) A plant disease", "B) Economic harm from resource boom causing manufacturing decline", "C) Import substitution failure", "D) Petrodollar recycling"], "correct": "B", "explanation": "'Dutch Disease' refers to the decline in manufacturing due to currency appreciation caused by a natural resource boom (coined after Netherlands' gas discoveries).", "topic_tag": "Economic Concepts", "difficulty": "hard"},
        {"text": "India's fiscal year runs from:", "options": ["A) January to December", "B) April to March", "C) October to September", "D) July to June"], "correct": "B", "explanation": "India's fiscal year runs from April 1 to March 31. The Union Budget is typically presented on February 1.", "topic_tag": "Public Finance", "difficulty": "easy"},
        {"text": "The MGNREGA guarantees employment for how many days per year?", "options": ["A) 50 days", "B) 75 days", "C) 100 days", "D) 150 days"], "correct": "C", "explanation": "MGNREGA guarantees 100 days of unskilled wage employment per year to every rural household whose adult members opt for it.", "topic_tag": "Employment Schemes", "difficulty": "easy"},
        {"text": "Microfinance is primarily aimed at:", "options": ["A) Large corporations", "B) Government-owned enterprises", "C) Low-income individuals lacking access to formal banking", "D) Multinational companies"], "correct": "C", "explanation": "Microfinance provides small loans and financial services to low-income individuals, entrepreneurs without access to traditional banking.", "topic_tag": "Financial Inclusion", "difficulty": "easy"},
        {"text": "The Laffer Curve illustrates the relationship between:", "options": ["A) Tax rates and tax revenue", "B) Inflation and unemployment", "C) Savings and investment", "D) GDP and population growth"], "correct": "A", "explanation": "The Laffer Curve shows that beyond a certain tax rate, further rate increases reduce tax revenue as economic activity declines.", "topic_tag": "Taxation", "difficulty": "hard"},
        {"text": "Which of the following is a feature of 'Inclusive Growth'?", "options": ["A) Only GDP growth", "B) Growth that benefits marginalized sections", "C) Export-led growth", "D) Urban-centered development"], "correct": "B", "explanation": "Inclusive growth refers to economic growth that is equitably distributed across different segments of society, reducing poverty and inequality.", "topic_tag": "Development Economics", "difficulty": "easy"},
        {"text": "The MSME sector in India is defined by:", "options": ["A) Number of employees", "B) Investment in plant and machinery/equipment and turnover", "C) Annual export value", "D) Land area of enterprise"], "correct": "B", "explanation": "Post-2020 MSME definition is based on both investment limits AND turnover — Micro (≤1 Cr investment, ≤5 Cr turnover), Small, Medium.", "topic_tag": "MSME", "difficulty": "medium"},
        {"text": "The Phillips Curve represents the relationship between:", "options": ["A) Inflation and economic growth", "B) Unemployment and inflation", "C) Interest rates and investment", "D) Exchange rates and trade balance"], "correct": "B", "explanation": "The Phillips Curve shows an inverse relationship between unemployment and inflation — lower unemployment tends to cause higher inflation (short-run).", "topic_tag": "Economic Concepts", "difficulty": "medium"},
        {"text": "India's largest source of tax revenue is:", "options": ["A) Customs duty", "B) Corporation Tax", "C) Income Tax", "D) GST/Indirect taxes combined"], "correct": "D", "explanation": "GST (as indirect taxes) is India's largest tax revenue source, followed by income tax and corporate tax.", "topic_tag": "Taxation", "difficulty": "medium"},
        {"text": "FDI is preferred over FPI because:", "options": ["A) FDI is cheaper", "B) FDI is more stable and brings technology/jobs", "C) FDI avoids taxation", "D) FDI requires less regulatory approval"], "correct": "B", "explanation": "FDI (Foreign Direct Investment) is more stable than FPI (Foreign Portfolio Investment) and often comes with technology transfer, job creation, and long-term commitment.", "topic_tag": "Foreign Investment", "difficulty": "medium"},
        {"text": "The main objective of FRBM Act 2003 is:", "options": ["A) Regulate banks", "B) Control fiscal deficit and promote fiscal discipline", "C) Regulate stock markets", "D) Manage foreign exchange"], "correct": "B", "explanation": "The Fiscal Responsibility and Budget Management (FRBM) Act mandates deficit reduction targets for governments to ensure fiscal discipline.", "topic_tag": "Fiscal Policy", "difficulty": "medium"},
        {"text": "Base erosion and profit shifting (BEPS) is a concept related to:", "options": ["A) Soil erosion in agriculture", "B) Tax avoidance by multinational companies", "C) Capital flight from emerging markets", "D) Currency devaluation"], "correct": "B", "explanation": "BEPS refers to strategies used by multinationals to shift profits to low-tax jurisdictions, eroding national tax bases. OECD has developed anti-BEPS measures.", "topic_tag": "International Economics", "difficulty": "hard"},
        {"text": "Priority Sector Lending by banks in India includes:", "options": ["A) Only agriculture", "B) Agriculture, MSMEs, Export credit, Education, Housing, and social infrastructure", "C) Only government schemes", "D) Only export financing"], "correct": "B", "explanation": "Priority Sector Lending covers agriculture, MSME, export credit, education, housing, social infra, renewable energy, and others — mandated by RBI.", "topic_tag": "Banking System", "difficulty": "hard"},
        {"text": "Purchasing Power Parity (PPP) measures:", "options": ["A) A country's military strength", "B) Relative value of currencies based on goods basket", "C) Gold reserves of nations", "D) Trade volume between countries"], "correct": "B", "explanation": "PPP measures the relative value of currencies by comparing the cost of a basket of goods across countries, eliminating exchange rate distortions.", "topic_tag": "International Economics", "difficulty": "medium"},
        {"text": "The Gini Coefficient measures:", "options": ["A) GDP of a country", "B) Income inequality", "C) Inflation rate", "D) Employment rate"], "correct": "B", "explanation": "Gini coefficient ranges from 0 (perfect equality) to 1 (perfect inequality) — a standard measure of income or wealth inequality.", "topic_tag": "Development Economics", "difficulty": "easy"},
        {"text": "Which of the following is NOT a function of NABARD?", "options": ["A) Refinancing banks for agriculture credit", "B) Developing rural areas", "C) Regulating commercial banking sector", "D) Supporting microfinance institutions"], "correct": "C", "explanation": "NABARD (National Bank for Agriculture and Rural Development) is the apex development finance institution for India's rural sector, not a banking regulator.", "topic_tag": "Banking System", "difficulty": "medium"},
        {"text": "The Supply-side economics argues:", "options": ["A) Demand generates its own supply", "B) Tax cuts and deregulation stimulate growth by boosting production", "C) Government spending is key to growth", "D) Inflation is always a monetary phenomenon"], "correct": "B", "explanation": "Supply-side economics (Reaganomics/Thatcherism) argues tax cuts, deregulation and removing barriers to production stimulate economic growth.", "topic_tag": "Economic Theory", "difficulty": "hard"},
        {"text": "The term 'Bharat' bandwidth in India refers to:", "options": ["A) A satellite network", "B) The rural internet expansion initiative under Bharat Net", "C) Width of national highways", "D) Agricultural land measurement"], "correct": "B", "explanation": "BharatNet is India's flagship project to provide optical fiber internet connectivity to all gram panchayats.", "topic_tag": "Digital Economy", "difficulty": "medium"},
        {"text": "India's sovereign credit rating is given by:", "options": ["A) RBI and Finance Ministry", "B) International agencies like Moody's, S&P, Fitch", "C) World Bank", "D) IMF"], "correct": "B", "explanation": "India's sovereign credit rating is assigned by global agencies — Moody's, Standard & Poor's (S&P), and Fitch — affecting borrowing costs.", "topic_tag": "International Economics", "difficulty": "medium"},
        {"text": "Stagflation refers to:", "options": ["A) High growth with low inflation", "B) Simultaneous high inflation and high unemployment", "C) Deflation during economic boom", "D) Low growth with low inflation"], "correct": "B", "explanation": "Stagflation is an economic situation with high inflation + high unemployment + stagnant growth — a nightmare for policymakers.", "topic_tag": "Inflation", "difficulty": "medium"},
        {"text": "Which committee recommended the framework for Monetary Policy Committee (MPC) in India?", "options": ["A) Urjit Patel Committee", "B) Narasimham Committee", "C) Kelkar Committee", "D) Raghuram Rajan Committee"], "correct": "A", "explanation": "The Urjit Patel Committee (2014) recommended flexible inflation targeting and a structured MPC with RBI governor as chair.", "topic_tag": "Monetary Policy", "difficulty": "hard"},
        {"text": "The National Investment and Infrastructure Fund (NIIF) is:", "options": ["A) A private equity fund", "B) India's 'quasi-sovereign wealth fund' for infrastructure", "C) A government bank", "D) An international bond"], "correct": "B", "explanation": "NIIF, established in 2015, is India's quasi-sovereign wealth fund aimed at channeling investment into infrastructure projects.", "topic_tag": "Infrastructure Finance", "difficulty": "hard"},
    ],
}


def seed_mcq_bank():
    db = SessionLocal()
    try:
        admin_user = db.query(User).filter(User.email == MASTER_EMAIL).first()
        if not admin_user:
            logger.error(f"User {MASTER_EMAIL} not found.")
            return False

        logger.info(f"✅ Admin user found: {admin_user.email}")
        total_seeded = 0

        for subject, questions in SUBJECT_MCQS.items():
            # Check how many already exist
            existing = db.query(BankQuestion).filter(
                BankQuestion.subject == subject
            ).count()

            if existing >= len(questions):
                logger.info(f"  ℹ️  {subject}: Already has {existing} questions, skipping.")
                continue

            logger.info(f"\n  Seeding {subject}: {len(questions)} MCQs...")
            for q in questions:
                bank_q = BankQuestion(
                    instructor_id=admin_user.id,
                    text=q["text"],
                    type="multiple_choice",
                    points=1,
                    difficulty=q["difficulty"],
                    options=json.dumps(q["options"]),
                    correct_answer=q["correct"],
                    explanation=q["explanation"],
                    subject=subject,
                    topic_tag=q["topic_tag"],
                    tags=f"UPSC,{subject},{q['topic_tag']}",
                    usage_count=0
                )
                db.add(bank_q)

            db.commit()
            total_seeded += len(questions)
            logger.info(f"  ✅ {subject}: {len(questions)} MCQs seeded")

        logger.info(f"\n{'='*60}")
        logger.info(f"✅ MCQ BANK SEEDING COMPLETE! Total: {total_seeded} questions")
        logger.info(f"{'='*60}")
        return True

    except Exception as e:
        logger.error(f"❌ MCQ seeding failed: {e}")
        import traceback
        traceback.print_exc()
        db.rollback()
        return False
    finally:
        db.close()


if __name__ == "__main__":
    success = seed_mcq_bank()
    sys.exit(0 if success else 1)
