steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/eduecosystem-prod/eduecosystem-repo/backend:mcq-ingest', '-f', 'Dockerfile.production', '.']

images:
- 'us-central1-docker.pkg.dev/eduecosystem-prod/eduecosystem-repo/backend:mcq-ingest'
