// Auto-generated by Antigravity Script
import { Question } from '../../../../types';

export const MODERN_CHAPTER_35_MCQS: any[] = [
  {
    id: '34-81',
    question: "Ultimately, 'The Quit India Movement' (Chapter 34) was the \"Trial of Strength\" that proved:",
    options: ["The British were stronger.", "The \"Nationalist Consciousness\" had reached the point of no return\u2014where the people were willing to \"Die\" for the goal of \"Quit India.\"", "India was too poor for independence.", "The Congress should have waited longer."],
    correctAnswer: 1,
    explanation: "Irreversible nationalist consciousness.",
    chapterId: 34,
    difficulty: 'Hard'
  },
  {
    id: '35-2',
    question: "The end of the Second World War in 1945 saw a change of government in Britain. Which party came to power?",
    options: ["Conservative Party", "Labour Party", "Liberal Party", "Communist Party of Great Britain"],
    correctAnswer: 1,
    explanation: "Labour Party (led by Clement Attlee).",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-3',
    question: "Who was the Viceroy of India during the immediate post-war period (1945\u201347)?",
    options: ["Lord Linlithgow", "Lord Wavell", "Lord Mountbatten", "Lord Reading"],
    correctAnswer: 1,
    explanation: "Lord Wavell.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-4',
    question: "The 'Wavell Plan' was discussed at a conference held in which city in June 1945?",
    options: ["Delhi", "Simla", "Bombay", "London"],
    correctAnswer: 1,
    explanation: "Simla (The Simla Conference).",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-5',
    question: "The 'INA Trials' (Indian National Army) were held at which historic location in Delhi?",
    options: ["Qutub Minar", "Red Fort", "Purana Qila", "India Gate"],
    correctAnswer: 1,
    explanation: "Red Fort.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-6',
    question: "Who were the first three INA officers to be tried at the Red Fort?",
    options: ["Bose, Nehru, and Patel", "Prem Sahgal, Gurbaksh Singh Dhillon, and Shah Nawaz Khan", "Lakshmi Sahgal, Mohan Singh, and Rash Behari Bose", "Bhagat Singh, Rajguru, and Sukhdev"],
    correctAnswer: 1,
    explanation: "Sahgal, Dhillon, and Khan (representing Hindu, Sikh, and Muslim unity).",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-7',
    question: "Who led the legal defense team for the INA prisoners?",
    options: ["Mahatma Gandhi", "Bhulabhai Desai (supported by Nehru, Katju, and Sapru)", "Sardar Patel", "B.R. Ambedkar"],
    correctAnswer: 1,
    explanation: "Bhulabhai Desai.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-8',
    question: "The 'Royal Indian Navy' (RIN) Mutiny of February 1946 started on which ship?",
    options: ["HMIS Vikrant", "HMIS Talwar", "HMIS Viraat", "HMIS Hindustan"],
    correctAnswer: 1,
    explanation: "HMIS Talwar (in Bombay).",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-9',
    question: "The RIN ratings (sailors) went on strike primarily to protest against:",
    options: ["Low salaries and racial discrimination/bad food", "The arrest of Mahatma Gandhi", "The Partition of India", "The arrival of the Cabinet Mission"],
    correctAnswer: 0,
    explanation: "Racial discrimination and poor conditions.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-10',
    question: "Who acted as the mediator to persuade the RIN ratings to surrender, promising that the Congress and League would prevent victimization?",
    options: ["Jawaharlal Nehru", "Sardar Vallabhbhai Patel (and M.A. Jinnah)", "Subhas Chandra Bose", "C. Rajagopalachari"],
    correctAnswer: 1,
    explanation: "Sardar Patel.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-11',
    question: "The 'Cabinet Mission' was sent to India in 1946. Who were its three members?",
    options: ["Wavell, Mountbatten, and Attlee", "Pethick-Lawrence, Stafford Cripps, and A.V. Alexander", "Simon, Hunter, and Butler", "Morley, Minto, and Montagu"],
    correctAnswer: 1,
    explanation: "Pethick-Lawrence, Cripps, and Alexander.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-12',
    question: "The Cabinet Mission Plan rejected the demand for:",
    options: ["A Constituent Assembly", "A sovereign, independent Pakistan", "An Interim Government", "Provincial Autonomy"],
    correctAnswer: 1,
    explanation: "A sovereign Pakistan (It proposed a three-tier federation instead).",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-13',
    question: "Under the Cabinet Mission Plan, the provinces were divided into how many groups?",
    options: ["Two (Hindu and Muslim)", "Three (Group A, B, and C)", "Five", "Eleven"],
    correctAnswer: 1,
    explanation: "Three Groups (Group A: Hindu majority; B & C: Muslim majority).",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-14',
    question: "The Muslim League called for 'Direct Action Day' on which date?",
    options: ["August 15, 1947", "August 16, 1946", "January 26, 1946", "March 23, 1940"],
    correctAnswer: 1,
    explanation: "August 16, 1946.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-15',
    question: "The 'Great Calcutta Killings' occurred following the call for:",
    options: ["Quit India", "Direct Action Day", "Simla Conference", "INA Trials"],
    correctAnswer: 1,
    explanation: "Direct Action Day.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-16',
    question: "Who was the Vice-President of the 'Interim Government' formed in September 1946?",
    options: ["Sardar Patel", "Jawaharlal Nehru", "Rajendra Prasad", "Liaquat Ali Khan"],
    correctAnswer: 1,
    explanation: "Jawaharlal Nehru.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-17',
    question: "Which leader from the Muslim League held the Finance portfolio in the Interim Government?",
    options: ["M.A. Jinnah", "Liaquat Ali Khan", "Shaukat Ali", "H.S. Suhrawardy"],
    correctAnswer: 1,
    explanation: "Liaquat Ali Khan.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-18',
    question: "The 'Telegraph Strike' and 'Railway Strike' of 1946 were part of which broader phenomenon?",
    options: ["The Great Depression", "The Post-War Labor Upsurge", "The Non-Cooperation Movement", "The 1857 Revolt"],
    correctAnswer: 1,
    explanation: "Post-War Labor Upsurge.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-19',
    question: "The 'Azad Hind Fauj' (INA) slogan was:",
    options: ["Vande Mataram", "Jai Hind", "Inquilab Zindabad", "Satyamev Jayate"],
    correctAnswer: 1,
    explanation: "Jai Hind.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-20',
    question: "Clement Attlee made a historic statement on February 20, 1947, declaring that the British would leave India by:",
    options: ["August 15, 1947", "June 30, 1948", "January 1, 1950", "December 31, 1947"],
    correctAnswer: 1,
    explanation: "June 30, 1948.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-21',
    question: "Who was appointed as the last Viceroy of India to oversee the transfer of power?",
    options: ["Lord Wavell", "Lord Mountbatten", "Lord Curzon", "Lord Canning"],
    correctAnswer: 1,
    explanation: "Lord Mountbatten.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-22',
    question: "The 'Indian National Army' (INA) was first conceived by:",
    options: ["Subhas Chandra Bose", "Captain Mohan Singh", "Rash Behari Bose", "Niranjan Singh Gill"],
    correctAnswer: 1,
    explanation: "Captain Mohan Singh.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-23',
    question: "The 1945\u201346 elections in India saw a clear communal polarization. The Congress won most general seats, while the Muslim League won:",
    options: ["All the reserved seats for Muslims in the Central Legislative Assembly", "No seats at all", "Only seats in Bengal", "The seats in the Princely States"],
    correctAnswer: 0,
    explanation: "All Muslim reserved seats (30/30) in the Central Assembly.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-24',
    question: "The 'I.N.A. Week' was observed in November 1945 to:",
    options: ["Celebrate Bose's birthday", "Raise funds for the defense of INA prisoners and demonstrate public support", "Join the British army", "Promote non-violence"],
    correctAnswer: 1,
    explanation: "Defense of prisoners and public support.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-25',
    question: "In the RIN Mutiny, the sailors hoisted the flags of which three parties on their ships?",
    options: ["Congress, Muslim League, and Communist Party", "British, French, and American", "Congress, Akali Dal, and Justice Party", "Only the Congress flag"],
    correctAnswer: 0,
    explanation: "Congress, League, and Communist Party (Symbolizing total unity).",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-26',
    question: "Which province was the scene of the violent 'Tebhaga' movement in 1946?",
    options: ["Punjab", "Bengal", "Bihar", "Kerala"],
    correctAnswer: 1,
    explanation: "Bengal.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-27',
    question: "The 'Mountbatten Plan' is also known as the:",
    options: ["August Plan", "June 3rd Plan", "Delhi Plan", "Partition Plan"],
    correctAnswer: 1,
    explanation: "June 3rd Plan.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-28',
    question: "The 'Boundary Commission' for the partition of Punjab and Bengal was headed by:",
    options: ["Lord Mountbatten", "Sir Cyril Radcliffe", "Stafford Cripps", "Pethick-Lawrence"],
    correctAnswer: 1,
    explanation: "Sir Cyril Radcliffe.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-29',
    question: "Mahatma Gandhi spent the day of independence (August 15, 1947) in which city, working to stop communal violence?",
    options: ["Delhi", "Calcutta (Noakhali)", "Bombay", "Amritsar"],
    correctAnswer: 1,
    explanation: "Calcutta (specifically, he was in the riot-torn areas).",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-30',
    question: "The 'Indian Independence Act' was passed by the British Parliament in:",
    options: ["June 1947", "July 1947", "August 1947", "January 1947"],
    correctAnswer: 1,
    explanation: "July 1947.",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-31',
    question: "Who was the first Governor-General of independent India?",
    options: ["C. Rajagopalachari", "Lord Mountbatten", "Jawaharlal Nehru", "Rajendra Prasad"],
    correctAnswer: 1,
    explanation: "Lord Mountbatten (C. Rajagopalachari was the first Indian Governor-General).",
    chapterId: 35,
    difficulty: 'Easy'
  },
  {
    id: '35-32',
    question: "The INA Trials (1945) are considered a \"strategic blunder\" by the British. What was the most significant unintended consequence of these trials?",
    options: ["It led to a massive increase in the British defense budget.", "It created a pan-India wave of emotional unity that transcended religion, caste, and geography, as the soldiers being tried (Sahgal, Dhillon, Khan) represented India\u2019s diversity.", "It resulted in the immediate return of Subhas Chandra Bose.", "It forced the Congress to adopt a policy of violence."],
    correctAnswer: 1,
    explanation: "Pan-India emotional unity.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-33',
    question: "The 'Royal Indian Navy' (RIN) Mutiny of 1946 was more than just a protest over \"bad food.\" What was its deeper political significance?",
    options: ["It was a secret plan by the USA to remove the British.", "It signaled the \"Last Nail in the Coffin\" of British rule by showing that the ultimate instrument of colonial power\u2014the armed forces\u2014was no longer reliable or loyal to the Crown.", "It was an attempt to establish a Communist government in Bombay.", "It was a protest against the arrival of the Cabinet Mission."],
    correctAnswer: 1,
    explanation: "Collapse of military loyalty.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-34',
    question: "Consider the following statements regarding the 'Cabinet Mission Plan' (1946):\n1. It proposed a weak center with powers limited to Defense, Foreign Affairs, and Communications.\n2. It gave provinces the right to form 'Groups' (A, B, and C) with their own legislatures and executives.\n3. It officially accepted the Muslim League's demand for a sovereign Pakistan. Which of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2, and 3"],
    correctAnswer: 0,
    explanation: "1 and 2 only.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-35',
    question: "Why did the 'Congress' and the 'Muslim League' interpret the \"Grouping\" clause of the Cabinet Mission differently?",
    options: ["Congress believed grouping was optional, while the League believed it was compulsory.", "Congress wanted more groups, while the League wanted only one.", "Congress wanted Group A to be in London.", "The League wanted to include the Princely States in the groups."],
    correctAnswer: 0,
    explanation: "Optional vs. Compulsory grouping.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-36',
    question: "With reference to the 'Simla Conference' (1945), consider the following: Statement-I: The conference failed because Jinnah insisted that the Muslim League should have the sole right to nominate all Muslim members to the Executive Council. Statement-II: The Congress rejected this \"Veto\" as it would reduce the party to a purely \"Hindu\" body and ignore its nationalist Muslim members. Which one of the following is correct?",
    options: ["Both are correct and Statement-II explains the deadlock.", "Statement-I is correct but Statement-II is false.", "Both are false.", "Statement-II is correct but Statement-I is false."],
    correctAnswer: 0,
    explanation: "Both are correct.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-37',
    question: "The 'Post-War National Upsurge' (1945-46) was characterized by \"spontaneous edge-of-precipice\" strikes. Which of the following was a unique feature of the RIN Mutiny?",
    options: ["The sailors used British flags to show loyalty.", "It saw an unprecedented \"Communal Harmony\" where Hindu and Muslim sailors ate together and hoisted each other's party flags.", "It was led by the Indian Civil Service (ICS) officers.", "It lasted for only ten minutes."],
    correctAnswer: 1,
    explanation: "Communal harmony and joint action.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-38',
    question: "The 'Wavell Plan' (1945) proposed an Interim Government where all members except the __________ and the __________ would be Indians.",
    options: ["Finance Minister and Home Minister", "Viceroy and the Commander-in-Chief", "Education Minister and Health Minister", "Governor of Bengal and Governor of Bombay"],
    correctAnswer: 1,
    explanation: "Viceroy and Commander-in-Chief.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-39',
    question: "Why did the British 'Labour Party' government (Attlee) decide to leave India by June 1948?",
    options: ["Because they were bored of ruling.", "The exhaustion of the British economy after WWII, the breakdown of the administrative \"steel frame\" (ICS/Police), and the clear threat of a violent mass revolution.", "Because the USA threatened to invade Britain.", "Because the Muslim League asked them to leave."],
    correctAnswer: 1,
    explanation: "Economic exhaustion and administrative collapse.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-40',
    question: "Consider the following regarding the 'Direct Action Day' (1946):\n1. It was launched by Jinnah after the Muslim League withdrew its acceptance of the Cabinet Mission Plan.\n2. Its goal was to demonstrate the strength of the Muslim demand for Pakistan through \"Direct Action\" outside the constitutional process. 3. It was a non-violent protest similar to Gandhi\u2019s Satyagraha. How many of the above are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two (Statement 3 is incorrect; it led to horrific communal violence, starting with the Great Calcutta Killings).",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-41',
    question: "The 'Mountbatten Plan' (June 3, 1947) was essentially a plan for:",
    options: ["United India with a strong center.", "Partition of India and the grant of 'Dominion Status' to the two new nations.", "Granting independence to every single province separately.", "Moving the British capital to Singapore."],
    correctAnswer: 1,
    explanation: "Partition and Dominion Status.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-42',
    question: "Why did the 'Congress' finally accept the Partition of India?",
    options: ["Because they liked the idea of two countries.", "To stop the escalating communal carnage and to ensure a \"Strong Center\" for the remaining India, rather than a \"Balkanized\" nation of hundreds of independent units.", "Because Gandhi ordered them to do so.", "Because the British promised them money."],
    correctAnswer: 1,
    explanation: "To stop violence and ensure a strong center.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-43',
    question: "The 'Radcliffe Line' was the boundary between:",
    options: ["India and China", "India and Pakistan (both West and East)", "North and South India", "India and Afghanistan"],
    correctAnswer: 1,
    explanation: "India and Pakistan.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-44',
    question: "In the 1946 'Interim Government', the Finance portfolio was held by Liaquat Ali Khan. How did he use this position?",
    options: ["To help the Congress implement its budget.", "To create \"deadlocks\" in every department's functioning, thereby proving that a joint Hindu-Muslim government was impossible.", "To abolish all taxes.", "To build more schools in Delhi."],
    correctAnswer: 1,
    explanation: "Creating administrative deadlocks.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-45',
    question: "The 'Attlee Statement' of Feb 1947 was a \"Fixed Deadline.\" What was its psychological impact on the Indian parties?",
    options: ["It made them stop fighting.", "It created a \"Scramble for Power\" where both the Congress and the League tried to maximize their territorial claims before the British left.", "It made Jinnah join the Congress.", "It resulted in everyone going on holiday."],
    correctAnswer: 1,
    explanation: "Scramble for power and territorial claims.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-46',
    question: "Match the following 'Committees/Missions' with their 'Context':\n1. Whitley Commission \u2014",
    options: ["Labour conditions (1929) 2. Sapru Committee \u2014", "Constitutional proposals (1944-45) 3. Cabinet Mission \u2014", "Three-tier federal structure (1946) Select the correct matching code:", "1-A, 2-B, 3-C"],
    correctAnswer: 0,
    explanation: "1-A, 2-B, 3-C.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-47',
    question: "The 'Indian Independence Act' (1947) did NOT provide for:",
    options: ["The end of British suzerainty over the Princely States.", "The continuation of the post of Secretary of State for India.", "The designation of the Governor-General as a constitutional head.", "The right of each Dominion to frame its own constitution."],
    correctAnswer: 1,
    explanation: "Continuation of Secretary of State (This office was abolished).",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-48',
    question: "'V.P. Menon' and 'Sardar Patel' are associated with which monumental task during 1947?",
    options: ["Writing the Constitution.", "The integration of the Princely States into the Indian Union.", "The defense of the INA prisoners.", "Leading the RIN Mutiny."],
    correctAnswer: 1,
    explanation: "Integration of Princely States.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-49',
    question: "Why was the 'Dominion Status' accepted by India in 1947, even though the goal was 'Purna Swaraj'?",
    options: ["Because they wanted to stay with the King.", "It allowed for a \"Quick and Smooth\" transfer of power and maintained the existing administrative and military continuity during the chaotic period of partition.", "Because the British refused to give full independence.", "It was a mistake."],
    correctAnswer: 1,
    explanation: "Quick/Smooth transfer and continuity.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-50',
    question: "The 'C.R. Formula' (1944) and the 'Desai-Liaquat Pact' (1945) were:",
    options: ["Plans to join the war.", "Failed attempts at a Congress-League \"rapprochement\" (reconciliation) before the final partition.", "Agreements to trade tea for cotton.", "Military alliances."],
    correctAnswer: 1,
    explanation: "Failed reconciliation attempts.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-51',
    question: "Ultimately, the 'Post-War Upsurge' (Chapter 35) proved that the 'Quit India' movement of 1942 had:",
    options: ["Failed completely.", "Successfully \"prepared the ground\" so that by 1945, the British had no choice but to negotiate the terms of their departure.", "Made the British stronger.", "No impact on the 1946 elections."],
    correctAnswer: 1,
    explanation: "Prepared the ground for final negotiations.",
    chapterId: 35,
    difficulty: 'Moderate'
  },
  {
    id: '35-52',
    question: "Lord Wavell\u2019s \"Breakdown Plan\" (Operation Madhouse) was a secret contingency that proposed:",
    options: ["A total withdrawal of British troops and civilians to the coastal regions of India, leaving the interior to the Indian parties.", "The immediate arrest of all Congress and League leaders.", "A phased withdrawal from the South and Central provinces, while maintaining a British \"Middle East\" zone in the North-West and East.", "The total handing over of power to the Princely States only."],
    correctAnswer: 2,
    explanation: "Phased withdrawal focusing on holding strategic zones.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-53',
    question: "With reference to the 'Cabinet Mission Plan', what was the technical implication of the \"Grouping of Provinces\"?",
    options: ["It was meant to create three separate countries.", "It allowed the groups (A, B, and C) to frame their own constitutions and executives, essentially creating a \"sub-federal\" layer between the Provinces and the Center.", "It abolished the role of the Governor.", "It mandated that all provinces in a group must speak the same language."],
    correctAnswer: 1,
    explanation: "Sub-federal layer of governance.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-54',
    question: "The 'INA Trials' (1945) triggered a shift in the British intelligence assessment called the \"Loyalty of the Sword.\" This meant:",
    options: ["The British realized their own soldiers were tired.", "The realization that the Indian personnel in the British Army, Navy, and Air Force were no longer \"politically insulated\" and could no longer be trusted to fire upon their own countrymen.", "The INA had more advanced weapons.", "The Japanese were planning a second invasion."],
    correctAnswer: 1,
    explanation: "Political awakening of the Indian armed forces.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-55',
    question: "Consider the following regarding the 'Plan Balkan' (May 1947):\n1. It was the initial plan proposed by Mountbatten that suggested the transfer of power to individual provinces.\n2. It allowed each province to choose to join India, Pakistan, or remain independent.\n3. Jawaharlal Nehru rejected it vehemently, calling it a blueprint for the \"fragmentation of India.\" How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three. (This led to the revised 'June 3rd Plan').",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-56',
    question: "The 'Radcliffe Boundary Commission' was given only five weeks to demarcate the borders. What was the \"Contradictory Mandate\" given to Cyril Radcliffe?",
    options: ["To follow the river lines only.", "To demarcate based on \"contiguous majority areas of Muslims and non-Muslims\" while also considering \"other factors\" (like economic viability, irrigation systems, and sacred sites).", "To ensure everyone was happy.", "To follow the old Mughal provincial borders."],
    correctAnswer: 1,
    explanation: "Contiguity vs. \"Other Factors\" (The ambiguity of \"other factors\" led to intense territorial disputes).",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-57',
    question: "Why did the 'Muslim League' initially accept the Cabinet Mission Plan in June 1946?",
    options: ["Because they were promised the post of Viceroy.", "They viewed the \"Compulsory Grouping\" as the \"basis of Pakistan in embryo,\" seeing it as a stepping stone to eventual sovereignty.", "They were afraid of the British army.", "The Congress had already rejected it."],
    correctAnswer: 1,
    explanation: "Pakistan \"in embryo\" via grouping.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-58',
    question: "The 'Direct Action Day' (August 16, 1946) resulted in the \"Great Calcutta Killings.\" Historically, why was the Bengal Ministry (under H.S. Suhrawardy) criticized?",
    options: ["For not having a police force.", "For declaring a public holiday on that day, which facilitated the mobilization of mobs, and for the perceived failure of the state machinery to intervene in time.", "For trying to join the Congress.", "For stopping all trade with Britain."],
    correctAnswer: 1,
    explanation: "Administrative failure and holiday declaration.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-59',
    question: "The 'Indian Independence Act' (1947) stated that the 'Suzerainty' of the British Crown over the Princely States would lapse. This meant:",
    options: ["The States automatically became part of the UK.", "All treaties and obligations between the Crown and the States were terminated, leaving the States technically \"sovereign\" and free to join either dominion or remain independent.", "The States were given to the Congress.", "The States were turned into democratic republics immediately."],
    correctAnswer: 1,
    explanation: "Lapse of Paramountcy (Creating the massive challenge of integration for Sardar Patel).",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-60',
    question: "Consider the 'Liaquat Ali Khan' budget of 1947 in the Interim Government. It was called a \"Poor Man's Budget,\" but the Congress viewed it as:",
    options: ["A masterpiece of economics.", "A \"tactical strike\" against the Hindu business class (Congress supporters) through high taxes, aimed at paralyzing the administration and forcing the partition.", "A way to fund the Congress party.", "A plan to build hospitals in Pakistan only."],
    correctAnswer: 1,
    explanation: "Tactical economic strike to force partition.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-61',
    question: "The 'June 3rd Plan' (Mountbatten Plan) solved the 'Sikh Problem' in Punjab by:",
    options: ["Giving them a separate country.", "Partitioning the province of Punjab into two parts, even though it meant dividing the Sikh community and their holy sites.", "Forcing them to move to Delhi.", "Making the Golden Temple a separate dominion."],
    correctAnswer: 1,
    explanation: "Partitioning Punjab (The \"cruel necessity\").",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-62',
    question: "What was the \"Dickie Bird Plan\"?",
    options: ["A plan to build bird sanctuaries.", "Another name for the 'Plan Balkan' (named after Mountbatten's nickname 'Dickie').", "A plan to use pigeons for communication.", "A trade agreement between India and Burma."],
    correctAnswer: 1,
    explanation: "Alternative name for Plan Balkan.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-63',
    question: "The 'Referendum' in the North-West Frontier Province (NWFP) in 1947 was boycotted by which group?",
    options: ["The Muslim League.", "The 'Red Shirts' (Khudai Khidmatgars) led by Khan Abdul Ghaffar Khan, as the option for a \"Free Pathan State\" (Pashtunistan) was not included.", "The British Army.", "The Hindu Mahasabha."],
    correctAnswer: 1,
    explanation: "Red Shirts boycott over Pashtunistan issue.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-64',
    question: "In the 1945-46 elections, the 'Congress' won the majority in almost all provinces, but the 'Muslim League' won 87% of the total Muslim vote. This signaled:",
    options: ["The total failure of secularism.", "The \"Vanishment of the Middle Ground\"\u2014the virtual elimination of nationalist Muslim parties and the total polarization of the electorate.", "That Jinnah was more popular than Gandhi in the South.", "That everyone wanted to stay under the British."],
    correctAnswer: 1,
    explanation: "Disappearance of the middle ground/polarization.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-65',
    question: "The 'C.R. Formula' (1944) was rejected by Jinnah because it offered a \"moth-eaten\" Pakistan. What did he mean?",
    options: ["The food in Pakistan would be bad.", "He wanted the entirety of the six Muslim-majority provinces, whereas the CR formula suggested partitioning Punjab and Bengal to exclude non-Muslim areas.", "He didn't like the name.", "He wanted the British to stay as protectors."],
    correctAnswer: 1,
    explanation: "Demand for full provinces vs. partitioned ones.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-66',
    question: "Match the following 'Events' with their 'Date of Occurrence':\n1. Wavell Plan / Simla Conference \u2014",
    options: ["June 1945 2. RIN Mutiny Spark \u2014", "Feb 1946 3. Attlee\u2019s Deadline Statement \u2014", "Feb 1947 Select the correct code:", "1-A, 2-B, 3-C"],
    correctAnswer: 0,
    explanation: "1-A, 2-B, 3-C.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-67',
    question: "The 'RIN Mutiny' was officially ended after an appeal by Sardar Patel. What was his main argument to the ratings?",
    options: ["That they would be given medals.", "That the discipline of the armed forces was vital for the future of a \"Free India\" and that political grievances should be handled by political leaders.", "That the British were going to sink the ships.", "That Jinnah was coming to meet them."],
    correctAnswer: 1,
    explanation: "Importance of military discipline for a future nation.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-68',
    question: "The 'Cabinet Mission' rejected a \"Fully Sovereign Pakistan\" because it would:",
    options: ["Be too rich.", "Create insoluble problems regarding communication, defense, and the large minorities left behind in both nations, making it an \"unviable\" state.", "Make Jinnah too powerful.", "Annoy the USA."],
    correctAnswer: 1,
    explanation: "Unviability due to logistical and minority issues.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-69',
    question: "Consider the following regarding the 'Boundary Commission' (1947):\n1. It consisted of two Hindu and two Muslim judges, with Radcliffe as the Chairman.\n2. The judges were in perfect agreement on the borders.\n3. The maps were released after Independence Day (August 17) to avoid disrupting the celebrations. How many of the above are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two (Statement 2 is incorrect; the judges were totally deadlocked, forcing Radcliffe to make the final arbitrary decisions).",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-70',
    question: "The 'Bengal Famine' of 1943, though occurring earlier, had a \"delayed political impact\" in 1945 because:",
    options: ["It led to the 'Tebhaga' movement and the radicalization of the Bengal countryside against the feudal-colonial nexus.", "The British gave money to everyone.", "The Muslim League supported the famine.", "It resulted in the end of the Congress."],
    correctAnswer: 0,
    explanation: "Catalyst for Tebhaga and radicalization.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-71',
    question: "'Operation Madhouse' was eventually replaced by 'Plan Balkan' because Wavell was:",
    options: ["Promoted.", "Dismissed by Attlee for being too \"pessimistic\" and lacking a \"political imagination\" to handle the transfer of power.", "Arrested by Jinnah.", "Retired for health reasons."],
    correctAnswer: 1,
    explanation: "Dismissed for pessimism/lack of imagination.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-72',
    question: "The 'Simla Conference' (1945) is described as the \"last chance\" for a united India. What was the \"Parity\" issue?",
    options: ["Parity between men and women.", "Jinnah\u2019s demand for \"Caste Hindu-Muslim Parity\" in the Executive Council (giving 25% Muslims equal weightage to 75% Hindus), which the Congress saw as a communal trap.", "Parity between India and Britain.", "Parity between the Army and the Navy."],
    correctAnswer: 1,
    explanation: "Communal Parity in executive representation.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-73',
    question: "In the 'Interim Government', the Muslim League refused to attend the 'Constituent Assembly'. This effectively meant:",
    options: ["The Assembly was abolished.", "The Assembly became a \"one-party\" (Congress) body, which the British eventually used as a reason to concede the partition.", "Jinnah was arrested.", "The British took over the drafting."],
    correctAnswer: 1,
    explanation: "One-party character leading to partition justification.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-74',
    question: "The 'Direct Action' was specifically targeted against which 'Paper'?",
    options: ["The newspaper Dawn.", "The 'State Paper' of the Cabinet Mission (May 16 Plan).", "The British Pound note.", "The Congress Manifesto."],
    correctAnswer: 1,
    explanation: "The Cabinet Mission\u2019s State Paper.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-75',
    question: "'Cyril Radcliffe' had never been to India before 1947. Why was he chosen?",
    options: ["He was the best geographer.", "He was seen as \"impartial\" because he had no prior knowledge or bias regarding the Indian political landscape.", "He was a relative of Mountbatten.", "He volunteered for the job."],
    correctAnswer: 1,
    explanation: "Perceived impartiality due to lack of prior contact.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-76',
    question: "The 'Mountbatten Plan' moved the date of independence from June 1948 to August 1947. Why this \"Hurry\"?",
    options: ["He wanted to catch a flight.", "To \"outrun\" the growing communal fire and to ensure that the British were not held responsible for the administrative and humanitarian collapse that was imminent.", "Because the weather was better in August.", "Because the USA ordered it."],
    correctAnswer: 1,
    explanation: "Outrunning the communal collapse and avoiding responsibility.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-77',
    question: "Consider the following regarding 'V.P. Menon':",
    options: ["He was a British spy.", "He was the only Indian in Mountbatten's inner circle and was the real architect of the \"Dominion Status\" transfer plan.", "He was a leader of the Muslim League.", "He led the RIN Mutiny."],
    correctAnswer: 1,
    explanation: "Architect of the Dominion Status plan.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-78',
    question: "Why did the 'Congress' agree to 'Dominion Status' in the June 3rd Plan?",
    options: ["They wanted to stay with the British.", "It ensured an immediate transfer of power (in 2 months instead of 10) and prevented the \"Balkanization\" of the country.", "Jinnah asked them to.", "To please the King."],
    correctAnswer: 1,
    explanation: "Immediate transfer and preventing fragmentation.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-79',
    question: "The 'Standstill Agreement' of 1947 was a mechanism for:",
    options: ["Stopping all trains.", "Maintaining the status quo of administrative arrangements between the new dominions and the Princely States until final integration.", "Stopping the war.", "A pause in the partition."],
    correctAnswer: 1,
    explanation: "Administrative status quo for Princely States.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '35-80',
    question: "The 'Post-War National Upsurge' showed that the \"Shield of the Empire\" was broken. What was the \"Shield\"?",
    options: ["The British Navy.", "The \"Indifference\" of the Indian masses and the \"Loyalty\" of the Indian subordinates (Army/Police/ICS).", "The Great Wall of China.", "The Atlantic Charter."],
    correctAnswer: 1,
    explanation: "Mass indifference and subordinate loyalty.",
    chapterId: 35,
    difficulty: 'Hard'
  },
];
