// Auto-generated by Antigravity Script
import { Question } from '../../../../types';

export const MODERN_CHAPTER_38_MCQS: any[] = [
  {
    id: '37-71',
    question: "Ultimately, 'The Crisis at Tripuri and After' (Chapter 37) leads to the conclusion that:",
    options: ["Bose was a failure.", "Both Bose and Gandhi were \"complementary\" forces\u2014Bose provided the radical pressure, while Gandhi provided the organizational and moral stability for the final assault on the Raj.", "The British were the winners.", "Jinnah was the real leader."],
    correctAnswer: 1,
    explanation: "Complementary nature of the two leadership styles.",
    chapterId: 37,
    difficulty: 'Hard'
  },
  {
    id: '38-2',
    question: "The idea of the Indian National Army (INA) was first conceived in Malaya by:",
    options: ["Subhas Chandra Bose", "Captain Mohan Singh", "Rash Behari Bose", "Niranjan Singh Gill"],
    correctAnswer: 1,
    explanation: "Captain Mohan Singh",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-3',
    question: "The first phase of the INA was formed with the help of the Japanese after the fall of which British stronghold?",
    options: ["Hong Kong", "Singapore", "Rangoon", "Calcutta"],
    correctAnswer: 1,
    explanation: "Singapore (February 1942).",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-4',
    question: "Who was the veteran revolutionary who had been living in Japan since 1915 and played a key role in the formation of the Indian Independence League?",
    options: ["Lala Hardayal", "Rash Behari Bose", "Raja Mahendra Pratap", "Sachindra Sanyal"],
    correctAnswer: 1,
    explanation: "Rash Behari Bose.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-5',
    question: "Subhas Chandra Bose arrived in Singapore in July 1943 to take command of the INA. From which country did he travel by submarine?",
    options: ["Italy", "Germany", "USSR", "USA"],
    correctAnswer: 1,
    explanation: "Germany (U-180 to I-29).",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-6',
    question: "Upon taking command, Subhas Chandra Bose renamed the INA as:",
    options: ["Bharat Sena", "Azad Hind Fauj", "Mukti Bahini", "Hind Fauj"],
    correctAnswer: 1,
    explanation: "Azad Hind Fauj.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-7',
    question: "Where did Subhas Chandra Bose set up the 'Provisional Government of Free India' (Arzi Hukumat-e-Azad Hind) on October 21, 1943?",
    options: ["Tokyo", "Singapore (Cathay Cinema Hall)", "Rangoon", "Bangkok"],
    correctAnswer: 1,
    explanation: "Singapore.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-8',
    question: "The headquarters of the Provisional Government were later shifted in January 1944 to:",
    options: ["Bangkok", "Rangoon", "Port Blair", "Kohima"],
    correctAnswer: 1,
    explanation: "Rangoon.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-9',
    question: "Which of the following was the famous slogan given by Bose to the INA?",
    options: ["Vande Mataram", "Dilli Chalo", "Inquilab Zindabad", "Satyamev Jayate"],
    correctAnswer: 1,
    explanation: "Dilli Chalo.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-10',
    question: "The women\u2019s regiment of the INA was named after which historic Indian figure?",
    options: ["Ahilyabai Holkar", "Rani of Jhansi (Lakshmibai)", "Sarojini Naidu", "Kasturba Gandhi"],
    correctAnswer: 1,
    explanation: "Rani of Jhansi.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-11',
    question: "Who was the commander of the Rani Jhansi Regiment?",
    options: ["Aruna Asaf Ali", "Captain Lakshmi Swaminathan (Sahgal)", "Sucheta Kripalani", "Annie Mascarene"],
    correctAnswer: 1,
    explanation: "Captain Lakshmi Sahgal.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-12',
    question: "The Japanese handed over which two Indian islands to the Provisional Government of Azad Hind in November 1943?",
    options: ["Lakshadweep and Minicoy", "Andaman and Nicobar Islands", "Daman and Diu", "Majuli and Salsette"],
    correctAnswer: 1,
    explanation: "Andaman and Nicobar Islands.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-13',
    question: "Subhas Chandra Bose renamed the Andaman and Nicobar Islands respectively as:",
    options: ["Swaraj and Shaheed", "Shaheed and Swaraj", "Azad and Hind", "Bharat and Mukti"],
    correctAnswer: 1,
    explanation: "Shaheed (Andaman) and Swaraj (Nicobar).",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-14',
    question: "In March 1944, the INA began its offensive into Indian territory. Which was the first Indian town where the INA hoisted the tricolour?",
    options: ["Kohima", "Moirang (Manipur)", "Imphal", "Silchar"],
    correctAnswer: 1,
    explanation: "Moirang.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-15',
    question: "The INA\u2019s military campaign in 1944 was focused on the capture of which two key strategic towns in Northeast India?",
    options: ["Guwahati and Shillong", "Imphal and Kohima", "Agartala and Aizawl", "Dibrugarh and Tinsukia"],
    correctAnswer: 1,
    explanation: "Imphal and Kohima.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-16',
    question: "The INA failed to capture Imphal and Kohima primarily due to:",
    options: ["Lack of bravery.", "Monsoon rains, supply line failures, and Japanese withdrawal of air support.", "A peace treaty with the British.", "The death of Subhas Chandra Bose."],
    correctAnswer: 1,
    explanation: "Logistics, weather, and lack of air support.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-17',
    question: "Who was the senior officer of the INA who led the 'Subhash Brigade' during the 1944 offensive?",
    options: ["Prem Sahgal", "Shah Nawaz Khan", "Gurbaksh Singh Dhillon", "Lakshmi Sahgal"],
    correctAnswer: 1,
    explanation: "Shah Nawaz Khan.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-18',
    question: "What was the name of the intelligence and sabotage unit of the INA?",
    options: ["Toofan Sena", "Bahadur Group", "Azad Dasta", "Mukti Group"],
    correctAnswer: 1,
    explanation: "Bahadur Group.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-19',
    question: "Subhas Chandra Bose was given the title 'Netaji' by:",
    options: ["Mahatma Gandhi", "The Indian soldiers in Germany (Free India Legion)", "The Japanese Emperor", "The people of Calcutta"],
    correctAnswer: 1,
    explanation: "Indian soldiers in Germany.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-20',
    question: "The 'Azad Hind Radio' was first started by Bose in which country?",
    options: ["Singapore", "Germany", "Japan", "Thailand"],
    correctAnswer: 1,
    explanation: "Germany (1942).",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-21',
    question: "On July 6, 1944, in a broadcast from Singapore, Bose addressed Mahatma Gandhi for the first time as:",
    options: ["The Great Soul", "Father of the Nation", "Saint of Sabarmati", "Dictator of Congress"],
    correctAnswer: 1,
    explanation: "Father of the Nation.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-22',
    question: "The INA was officially dissolved following the surrender of:",
    options: ["Germany", "Japan (August 1945)", "Italy", "The USSR"],
    correctAnswer: 1,
    explanation: "Japan.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-23',
    question: "According to official reports, Subhas Chandra Bose died in a plane crash in August 1945 at:",
    options: ["Tokyo", "Taihoku (Taipei), Taiwan", "Singapore", "Bangkok"],
    correctAnswer: 1,
    explanation: "Taihoku, Taiwan.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-24',
    question: "The 'INA Trials' of 1945-46 are also known as the:",
    options: ["Calcutta Trials", "Red Fort Trials", "Tihar Trials", "Simla Trials"],
    correctAnswer: 1,
    explanation: "Red Fort Trials.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-25',
    question: "Which political party in India organized the 'INA Week' and 'INA Day' to mobilize public support for the prisoners?",
    options: ["Muslim League", "Indian National Congress", "Communist Party", "Hindu Mahasabha"],
    correctAnswer: 1,
    explanation: "Indian National Congress.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-26',
    question: "\"Give me blood, and I shall give you freedom!\" This famous speech was delivered by Bose in:",
    options: ["Calcutta", "Burma (Myanmar)", "Tokyo", "Berlin"],
    correctAnswer: 1,
    explanation: "Burma.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-27',
    question: "The INA soldiers who were captured by the British were categorized based on their \"level of guilt\" as:",
    options: ["Red, Blue, and Green", "White, Grey, and Black", "Loyal, Rebel, and Traitor", "High, Medium, and Low"],
    correctAnswer: 1,
    explanation: "White (Loyal), Grey (Suspect), and Black (Dedicated INA).",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-28',
    question: "Who was the Japanese Prime Minister who supported Bose and the INA?",
    options: ["Hirohito", "Hideki Tojo", "Shinzo Abe", "Mutsuhito"],
    correctAnswer: 1,
    explanation: "Hideki Tojo.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-29',
    question: "The 'Indian Independence League' conference that invited Bose to East Asia was held in 1942 at:",
    options: ["Tokyo and Bangkok", "Singapore and Manila", "Rangoon and Jakarta", "Delhi and Kabul"],
    correctAnswer: 0,
    explanation: "Tokyo and Bangkok.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-30',
    question: "Before reaching Japan, Bose had formed the 'Free India Legion' in Germany. The soldiers for this legion were recruited from:",
    options: ["German schools.", "Indian Prisoners of War (POWs) captured by Germany in North Africa.", "The German Navy.", "Indian students in London."],
    correctAnswer: 1,
    explanation: "Indian POWs in North Africa.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-31',
    question: "Ultimately, the INA movement succeeded in:",
    options: ["Defeating the British army in open battle.", "Inspiring a massive wave of nationalism and accelerating the end of British rule by breaking the loyalty of the Indian army.", "Capturing Delhi in 1944.", "Making Bose the first PM in 1945."],
    correctAnswer: 1,
    explanation: "Inspiring nationalism and breaking military loyalty.",
    chapterId: 38,
    difficulty: 'Easy'
  },
  {
    id: '38-32',
    question: "The INA is historically divided into two phases. What was the primary cause for the collapse of \"Phase I\" under Captain Mohan Singh?",
    options: ["Lack of funding from Indian merchants in Malaya.", "Disagreements between Mohan Singh and the Japanese military command over the autonomy of the INA and the number of POWs to be recruited.", "A successful British counter-offensive in 1942.", "Mohan Singh's decision to join the Indian National Congress."],
    correctAnswer: 1,
    explanation: "Autonomy and recruitment disputes.",
    chapterId: 38,
    difficulty: 'Moderate'
  },
  {
    id: '38-33',
    question: "The 'Provisional Government of Free India' (Arzi Hukumat-e-Azad Hind) was not just a symbolic body. Which of the following confirms its \"International Status\"?",
    options: ["It had a seat in the United Nations.", "It was formally recognized by nine world powers, including Japan, Germany, Italy, and Thailand, and it declared war on Britain and the USA.", "It issued its own currency and passports to all Indians.", "It was recognized by the British Parliament as a legitimate government."],
    correctAnswer: 1,
    explanation: "Formal recognition and declaration of war.",
    chapterId: 38,
    difficulty: 'Moderate'
  },
  {
    id: '38-34',
    question: "Consider the following statements regarding the 'Rani Jhansi Regiment': 1. it was the first all-female combat unit in the history of modern Asian warfare. 2. Its members were exclusively recruited from the women of the Indian mainland who escaped to Singapore. 3. It was trained for active combat, including nursing and guerrilla warfare. Which of the statements given above are correct?",
    options: ["1 and 2 only", "1 and 3 only", "2 and 3 only", "1, 2, and 3"],
    correctAnswer: 1,
    explanation: "1 and 3 only. Statement 2 is incorrect; the majority of the recruits were from the Indian diaspora in Southeast Asia (Malaya, Singapore, and Burma), mostly daughters of plantation workers and traders.",
    chapterId: 38,
    difficulty: 'Moderate'
  },
  {
    id: '38-35',
    question: "The 'Imphal-Kohima' Campaign (1944) is often called the \"Stalingrad of the East.\" Why did it become a turning point for the INA?",
    options: ["Because the INA successfully captured the whole of Northeast India.", "The failure of this campaign, caused by the early onset of monsoons and Japanese logistical collapse, forced the INA into a long, brutal retreat that broke its military momentum.", "It was where Bose and Gandhi met for the last time.", "It resulted in the immediate independence of Burma."],
    correctAnswer: 1,
    explanation: "Military failure leading to a strategic retreat.",
    chapterId: 38,
    difficulty: 'Moderate'
  },
  {
    id: '38-36',
    question: "With reference to the 'INA-Japanese' relationship, consider the following: Statement-I: Subhas Chandra Bose maintained a policy of \"Independence within Alliance,\" often clashing with Japanese officials to ensure the INA was not treated as a puppet force. Statement-II: The Japanese handed over the Andaman and Nicobar Islands to the INA to give the Provisional Government a territorial base on Indian soil. Which one of the following is correct?",
    options: ["Both are correct and Statement-II is an example of the success of Statement-I.", "Statement-I is correct but Statement-II is false.", "Both are false.", "Statement-II is correct but Statement-I is false."],
    correctAnswer: 0,
    explanation: "Both are correct.",
    chapterId: 38,
    difficulty: 'Moderate'
  },
  {
    id: '38-37',
    question: "Why did Bose choose the slogan \"Jai Hind\" as the common greeting for the INA?",
    options: ["Because it was the only Hindi word he knew.", "To replace religious or communal greetings (like Salam or Ram Ram) with a secular, nationalist salute that promoted unity among Hindu, Muslim, and Sikh soldiers.", "Because the Japanese ordered him to.", "It was the name of his favorite book."],
    correctAnswer: 1,
    explanation: "Secular/Nationalist unity.",
    chapterId: 38,
    difficulty: 'Moderate'
  },
  {
    id: '38-38',
    question: "The 'Bahadur Group' of the INA was specialized in \"Special Operations.\" What was their primary tactical role during the advance?",
    options: ["Building bridges.", "Infiltrating British Indian Army lines to encourage desertion among Indian soldiers and gathering local intelligence.", "Managing the kitchens.", "Translating Japanese orders."],
    correctAnswer: 1,
    explanation: "Infiltration and inciting desertion.",
    chapterId: 38,
    difficulty: 'Moderate'
  },
  {
    id: '38-39',
    question: "Consider the following regarding the 'INA Trials' (1945-46) and their impact: 1. The British choice of a Hindu, a Muslim, and a Sikh for the first trial (Sahgal, Dhillon, Khan) backfired by creating a unified national outcry. 2. The trials were the first time the Congress and the Muslim League stood on the same legal platform for a common cause. 3. The trials resulted in the immediate execution of all three officers. How many of the above are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two (Statement 3 is incorrect; due to massive public pressure, their sentences were eventually remitted by the Commander-in-Chief).",
    chapterId: 38,
    difficulty: 'Moderate'
  },
  {
    id: '38-40',
    question: "What was the \"Psychological Effect\" of the INA on the British Indian Army after the war?",
    options: ["It made the Indian soldiers want to move to Japan.", "It shattered the myth of \"unquestioning loyalty\" to the Crown, as the British realized they could no longer rely on Indian troops to suppress their own people during a mass uprising.", "It made the British soldiers join the Congress.", "It had no effect at all."],
    correctAnswer: 1,
    explanation: "Breakdown of the \"Loyalty of the Sword.\"",
    chapterId: 38,
    difficulty: 'Moderate'
  },
  {
    id: '38-41',
    question: "Ultimately, 'The Azad Hind Fauj' (Chapter 38) provided the \"Military Pressure\" that complemented the \"Moral Pressure\" of Gandhi. This synergy meant:",
    options: ["That Bose was more important than Gandhi.", "That the British were now fighting a war on two fronts\u2014a non-violent mass movement internally and a potential military rebellion within their own armed forces.", "That India would only be free through violence.", "That Japan would rule India."],
    correctAnswer: 1,
    explanation: "Two-front pressure (Internal Mass and External Military).",
    chapterId: 38,
    difficulty: 'Moderate'
  },
  {
    id: '38-42',
    question: "From a legal standpoint, why was the establishment of the 'Provisional Government of Free India' (Arzi Hukumat-e-Azad Hind) vital for the INA?",
    options: ["To allow Bose to collect taxes from Japan.", "To transform the INA from a \"rebel group\" into the organized army of a \"sovereign state,\" thereby claiming protection under the International Laws of War and the Geneva Convention.", "To make Bose the official King of Singapore.", "To allow Indian soldiers to use Japanese passports."],
    correctAnswer: 1,
    explanation: "Legitimization under International Law.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-43',
    question: "During the 'Greater East Asia Conference' (Tokyo, 1943), Bose attended as an \"Observer\" rather than a \"Member.\" What was the strategic reasoning behind this?",
    options: ["The Japanese refused to let him join.", "Bose wanted to maintain the \"Independent\" character of the Indian struggle and avoid the perception of India being just another \"puppet state\" within the Japanese Co-Prosperity Sphere.", "He didn't speak Japanese.", "He was waiting for a signal from the Congress in India."],
    correctAnswer: 1,
    explanation: "Maintaining an independent nationalist identity.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-44',
    question: "Consider the following regarding the 'Azad Hind Bank' established in Rangoon (1944): 1. It issued its own currency and postage stamps recognized by the Axis powers. 2. It was primarily funded by the voluntary contributions of the Indian diaspora in Southeast Asia. 3. It was a branch of the Imperial Bank of India. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two (Statement 3 is incorrect; it was an independent central bank for the Provisional Government).",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-45',
    question: "The 'U-Go Offensive' was the code name for the Japanese-INA attack on:",
    options: ["Calcutta and Dhaka", "Imphal and Kohima", "Singapore and Malaya", "Delhi and Lahore"],
    correctAnswer: 1,
    explanation: "Imphal and Kohima.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-46',
    question: "With reference to the 'Andaman and Nicobar Islands' under the Provisional Government, which of the following is true?",
    options: ["The Japanese completely withdrew their troops and gave full administrative control to Bose.", "The transfer was largely symbolic; while Bose appointed a Governor (A.C. Chatterjee), the Japanese military retained effective control for \"defense purposes.\"", "The islands were used as a base to launch nuclear weapons.", "The British recaptured them within two days."],
    correctAnswer: 1,
    explanation: "Symbolic transfer with Japanese military override.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-47',
    question: "The 'Hikari Kikan' was a Japanese organization that acted as:",
    options: ["A combat unit fighting alongside the INA.", "The liaison body between the Japanese Imperial Army and the INA, often criticized by Bose for interfering in INA's internal affairs.", "A secret society of Indian monks.", "A trade union for Indian workers in Tokyo."],
    correctAnswer: 1,
    explanation: "Liaison body between Japan and the INA.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-48',
    question: "Why did the INA's 'Imphal Campaign' ultimately fail to trigger a \"Mass Uprising\" inside India as Bose had expected?",
    options: ["The Indian people didn't like Bose.", "The inability of the INA to penetrate deep into the Indian heartland and the effective British \"news blackout\" prevented the masses from knowing how close the \"Liberation Army\" was.", "The Congress told the people to fight against Bose.", "The Japanese surrendered before the campaign started."],
    correctAnswer: 1,
    explanation: "Lack of deep penetration and British news censorship.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-49',
    question: "Consider the following regarding the 'Rani Jhansi Regiment' recruitment: 1. It included women from diverse backgrounds, including rubber plantation laborers and medical students. 2. It was the only unit of the INA that was not allowed to carry weapons. 3. The training included advanced tactical maneuvers and night-marching. How many of the above are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two (Statement 2 is incorrect; they were fully armed combatants).",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-50',
    question: "The \"Black\" category in the British classification of INA prisoners referred to:",
    options: ["Those who were forced to join.", "The \"hardcore\" ideologically driven volunteers who were considered the most dangerous to the British Raj and were intended for severe punishment.", "Soldiers who were of African descent.", "Those who were sick or wounded."],
    correctAnswer: 1,
    explanation: "Ideologically committed \"hardcore\" volunteers.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-51',
    question: "Match the following 'INA Brigades' with their 'Context': 1. Gandhi Brigade \u2014",
    options: ["One of the main guerrilla regiments. 2. Nehru Brigade \u2014", "Named to show respect to the leaders in India. 3. Subhash Brigade \u2014", "The first to reach the Indian soil (Arakan/Manipur). Select the correct matching code:", "1-A, 2-B, 3-C"],
    correctAnswer: 0,
    explanation: "1-A, 2-B, 3-C.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-52',
    question: "The 'Indian Independence League' (IIL) acted as the \"Political Parent\" of the INA. Where was its headquarters established after the 1942 Bangkok Conference?",
    options: ["Tokyo", "Bangkok (later shifted to Singapore/Rangoon)", "Berlin", "Kabul"],
    correctAnswer: 1,
    explanation: "Bangkok.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-53',
    question: "What was the \"Propaganda of the British\" regarding the INA during the war?",
    options: ["That the INA was a huge and successful army.", "That the INA were \"Jiffs\" (Japanese Inspired Forces)\u2014mere puppets and traitors who were helping a Fascist power enslave India.", "That Bose had never left India.", "That the INA was a secret branch of the British Army."],
    correctAnswer: 1,
    explanation: "The \"Jiffs\" / Puppet-force narrative.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-54',
    question: "In his 1944 broadcast, Bose called Gandhi the \"Father of the Nation.\" Why was this a significant tactical move?",
    options: ["He wanted to return to the Congress.", "To seek the \"Blessings\" of the supreme leader of the Indian masses and to show the world that his \"Armed Struggle\" and Gandhi's \"Satyagraha\" were two paths to the same goal.", "Because the Japanese told him to do so.", "To confuse the British Intelligence."],
    correctAnswer: 1,
    explanation: "Seeking legitimacy and establishing tactical synergy with Gandhi.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-55',
    question: "The 'Free India Legion' in Germany (1941) was known as 'Infanterie-Regiment 950'. What was its primary 'Badge' or emblem?",
    options: ["A Swastika.", "A Leaping Tiger with the words \"Azad Hind.\"", "A Spinning Wheel (Charkha).", "A Lotus flower."],
    correctAnswer: 1,
    explanation: "The Leaping Tiger.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-56',
    question: "Consider the following regarding 'Captain Lakshmi Sahgal': 1. She was a medical doctor before joining the INA. 2. She held a cabinet rank in the Provisional Government as the Minister in charge of Women's Organization. 3. She was the only person to escape the Red Fort Trials. Which of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2, and 3"],
    correctAnswer: 0,
    explanation: "1 and 2 only. (She was tried but her case was handled separately from the 'Big Three').",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-57',
    question: "Why did the INA soldiers feel that they had \"not surrendered, but been overwhelmed\"?",
    options: ["Because they ran out of ammunition.", "Because their collapse was a result of the global surrender of Japan and the loss of supply lines, rather than a defeat on the battlefield by the British Indian Army.", "Because they wanted to continue fighting alone.", "Because Bose told them not to surrender."],
    correctAnswer: 1,
    explanation: "Overwhelmed by external geopolitical collapse.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-58',
    question: "The 'Bahadur Group' was essentially an \"Elite Unit.\" Its training was heavily influenced by:",
    options: ["British Commando tactics.", "Japanese 'Special Intelligence' training, focusing on psychological warfare and frontline subversion.", "Traditional Indian wrestling.", "German tank warfare."],
    correctAnswer: 1,
    explanation: "Japanese-influenced psychological warfare.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-59',
    question: "Consider the 'Netaji Fund' collected in Southeast Asia:",
    options: ["It was mostly stolen by the British.", "It was so massive that it allowed the INA to be financially self-sufficient for a long period, primarily through the contributions of the 'Chettiar' and other Indian business communities.", "It was only used for Bose's personal travel.", "It was all in gold coins from the Mughal era."],
    correctAnswer: 1,
    explanation: "Diaspora-funded financial self-sufficiency.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-60',
    question: "The 'Simla Conference' (1945) happened just before the INA Trials. How did the \"INA Factor\" affect the conference?",
    options: ["It had no effect.", "The \"Heroism\" of the INA (which was becoming public news) put the Congress under pressure to take a more militant stand and refuse to compromise on the issue of independence.", "The INA leaders were invited to the conference.", "Jinnah used the INA to demand more seats."],
    correctAnswer: 1,
    explanation: "Public pressure for a militant nationalist stand.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-61',
    question: "Why did the 'Red Fort' trials backfire on the British legally?",
    options: ["The lawyers were better.", "The defense (Bhulabhai Desai) argued that according to International Law, the INA were soldiers of a \"Sovereign State\" (Provisional Government) and therefore could not be tried for \"Treason\" against a foreign king.", "The British forgot to bring evidence.", "The King of England pardoned them."],
    correctAnswer: 1,
    explanation: "The \"Sovereign State\" legal defense.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-62',
    question: "The 'INA's' biggest contribution to the \"Communal\" situation in India was:",
    options: ["Dividing the army further.", "Providing a working model of \"Total Communal Integration,\" where soldiers of all religions lived, ate, and fought together under a common flag and language.", "Making everyone become Hindu.", "Supporting the Muslim League."],
    correctAnswer: 1,
    explanation: "Model of total communal integration.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-63',
    question: "In 1945, the 'AICC' resolution on the INA described them as:",
    options: ["Traitors.", "\"Misguided but patriotic\" sons of India, whose courage and devotion to the cause of freedom was beyond doubt.", "British spies.", "The only true leaders of India."],
    correctAnswer: 1,
    explanation: "\"Misguided but patriotic\" (A careful balance to support them without endorsing Bose's alliance with the Axis).",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-64',
    question: "The 'Battle of Kohima' is often described as the \"Turning Point.\" What happened there?",
    options: ["The INA won a major victory.", "It was a brutal hand-to-hand fight where the British forces finally stopped the advance of the Japanese and INA, marking the beginning of the Allied counter-offensive.", "The INA surrendered at Kohima.", "Bose was captured at Kohima."],
    correctAnswer: 1,
    explanation: "Allied halt of the Axis-INA advance.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-65',
    question: "'Subhas Chandra Bose's' death remains a subject of controversy. What was the finding of the 'Shah Nawaz Committee' (1956)?",
    options: ["That he was still alive.", "That he died in the plane crash at Taihoku.", "That he was in a Russian prison.", "That he had become a monk."],
    correctAnswer: 1,
    explanation: "Confirmation of death in the plane crash.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-66',
    question: "Why did the 'Royal Indian Navy' (RIN) ratings in 1946 look up to the INA?",
    options: ["Because they wanted to wear the same uniform.", "The \"Anti-Imperialist\" spirit of the INA and the public trials made the sailors realize that they, too, could challenge the British authority from within the military.", "They were trained by Bose.", "The INA gave them money."],
    correctAnswer: 1,
    explanation: "Inspiration to challenge authority from within.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-67',
    question: "The 'Azad Hind Fauj' was the first to implement 'Hindustani' (a mix of Hindi and Urdu) in:",
    options: ["Schools only.", "All military commands and official correspondence, aimed at creating a unified lingual identity for the army.", "The British Parliament.", "Only the religious prayers."],
    correctAnswer: 1,
    explanation: "Unified military language (Hindustani).",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-68',
    question: "'Rash Behari Bose' handed over the leadership to Netaji because:",
    options: ["He was tired.", "He recognized that Netaji\u2019s charismatic leadership and his recent presence in the Indian mainland made him the most suitable person to lead the final assault.", "The Japanese forced him to.", "They had a fight."],
    correctAnswer: 1,
    explanation: "Recognition of Netaji's charismatic/mainland appeal.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-69',
    question: "The 'INA Relief Committee' was set up by the Congress to:",
    options: ["Give the INA soldiers a vacation.", "Provide financial aid and legal support to the thousands of INA POWs returning to India, ensuring they were treated as heroes by the public.", "Send them back to Japan.", "Build a new parliament."],
    correctAnswer: 1,
    explanation: "Financial and legal support for returning heroes.",
    chapterId: 38,
    difficulty: 'Hard'
  },
  {
    id: '38-70',
    question: "Ultimately, the 'Azad Hind Fauj' (Chapter 38) proved that the 'British Raj' was:",
    options: ["Stronger than Japan.", "A \"Paper Tiger\" that could not stand if its Indian military base collapsed\u2014a collapse that the INA had successfully initiated.", "A friend of India.", "Not interested in the war."],
    correctAnswer: 1,
    explanation: "Vulnerability of the Raj without military loyalty.",
    chapterId: 38,
    difficulty: 'Hard'
  },
];
