// Auto-generated by Antigravity Script
import { Question } from '../../../../types';

export const MODERN_CHAPTER_7_MCQS: any[] = [
  {
    id: '8-31',
    question: "In 1920, Dr. B.R. Ambedkar started a fortnightly newspaper named:",
    options: ["Bahishkrit Bharat", "Mooknayak", "Vital Vidhvasak", "Harijan"],
    correctAnswer: 1,
    explanation: "Mooknayak",
    chapterId: 8,
    difficulty: 'Easy'
  },
  {
    id: '7-2',
    question: "The 19th-century reform movements are often categorized into 'Reformist' and 'Revivalist'. Which of the following best describes the fundamental difference between these two approaches?",
    options: ["Reformists wanted to adopt Christianity, while Revivalists wanted to maintain indigenous traditions.", "Reformists aimed at a synthesis of Indian and Western liberal values, while Revivalists sought to restore the purity of ancient traditions by appealing to the authority of original scriptures.", "Reformists supported British political rule, while Revivalists were strictly anti-British revolutionaries.", "Reformists focused only on women's issues, while Revivalists focused only on the caste system."],
    correctAnswer: 1,
    explanation: "Reformists aimed at a synthesis of Indian and Western liberal values, while Revivalists sought to restore the purity of ancient traditions by appealing to original scriptures.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-3',
    question: "Raja Rammohan Roy is famously known as the 'Father of the Indian Renaissance'. Which of the following was a core ideological pillar of his reformist agenda?",
    options: ["Monotheism and the rejection of idol worship based on a rationalist interpretation of the Vedas and Upanishads.", "The complete rejection of all ancient Indian scriptures in favor of the Bible.", "The promotion of the Sanskrit language as the sole medium of modern education.", "The establishment of a new religion that excluded all non-Hindus."],
    correctAnswer: 0,
    explanation: "Monotheism and the rejection of idol worship based on a rationalist interpretation of the Vedas and Upanishads.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-4',
    question: "Consider the following statements regarding the 'Age of Consent Act' (1891):\n1. It was enacted due to the relentless efforts of the Parsi reformer Behramji Malabari.\n2. It prohibited the marriage of girls below the age of 12.\n3. It was widely supported by conservative nationalist leaders like Bal Gangadhar Tilak. Which of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2, and 3"],
    correctAnswer: 0,
    explanation: "1 and 2 only Statement 3 is incorrect. Tilak and other orthodox nationalists opposed the Act, arguing that the British government had no right to interfere in Hindu social and religious customs.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-5',
    question: "Pandit Ishwar Chandra Vidyasagar's contribution to the cause of women was monumental. What was the primary evidence he provided to argue in favor of widow remarriage?",
    options: ["He quoted Western liberal philosophers like John Stuart Mill.", "He cited specific verses from ancient Hindu scriptures (shastras) to prove that widow remarriage was not forbidden by religion.", "He argued that widow remarriage was necessary to increase the population of India.", "He translated the Quran to show parallels in social reform."],
    correctAnswer: 1,
    explanation: "He cited specific verses from ancient Hindu scriptures to prove that widow remarriage was not forbidden.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-6',
    question: "The 'Native Marriage Act' (1872) was a significant step toward social reform, but it had a specific limitation. What was it?",
    options: ["It applied only to Christians and Parsis.", "It did not apply to Hindus, Muslims, and other recognized religions unless they declared they did not belong to any of these religions.", "It was immediately repealed by the British due to mass protests.", "It legalized polygamy for all communities."],
    correctAnswer: 1,
    explanation: "It did not apply to Hindus, Muslims, and other recognized religions unless they declared they did not belong to any of these religions.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-7',
    question: "Jyotirao Phule's Satyashodhak Samaj (1873) was unique among 19th-century reform movements because it:",
    options: ["Focused exclusively on the religious education of upper-caste Brahmins.", "Aimed at the social and economic liberation of the 'Bahujan' (low castes, Dalits, and women) from the oppression of Brahminical hegemony.", "Advocated for a return to the Vedic age.", "Supported the British government's policy of annexing princely states."],
    correctAnswer: 1,
    explanation: "Aimed at the social and economic liberation of the 'Bahujan' from the oppression of Brahminical hegemony.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-8',
    question: "Which of the following statements best describes the attitude of 19th-century social reformers toward British rule?",
    options: ["They viewed it as a divine curse that needed to be overthrown by armed rebellion.", "They generally viewed British rule as a providential opportunity for India to modernize and reform its decayed social and religious structures.", "They ignored the British entirely and focused only on internal village administration.", "They believed the British were a tool for the Marathas to regain power."],
    correctAnswer: 1,
    explanation: "They generally viewed British rule as a providential opportunity for India to modernize.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-9',
    question: "The 'Sarda Act' of 1929 (Child Marriage Restraint Act) was named after Harbilas Sarda. What was the minimum age for marriage fixed for boys and girls under this Act?",
    options: ["15 for boys and 12 for girls", "18 for boys and 14 for girls", "21 for boys and 18 for girls", "16 for boys and 13 for girls"],
    correctAnswer: 1,
    explanation: "18 for boys and 14 for girls",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-10',
    question: "Consider the following regarding the 'Aligarh Movement' led by Sir Syed Ahmed Khan:\n1. It aimed at reconciling Western scientific education with the teachings of the Quran.\n2. It was strictly revivalist, calling for a return to the primitive Islam of the 7th century.\n3. It advocated for the active participation of Muslims in the Indian National Congress. Which of the statements given above is/are correct?",
    options: ["1 only", "1 and 2 only", "2 and 3 only", "1, 2, and 3"],
    correctAnswer: 0,
    explanation: "1 only Sir Syed Ahmed Khan was a reformist (not revivalist) and he advised Muslims to stay away from the Congress in its early years.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-11',
    question: "The 19th-century reformers used the concept of 'Religious Universalism' to:",
    options: ["Argue that all religions are fundamentally different and incompatible.", "Claim that Hinduism was the only true religion in the world.", "Assert that all religions share a common core of ethical and humanistic values, thus promoting communal harmony.", "Convert the entire world to a single new faith."],
    correctAnswer: 2,
    explanation: "Assert that all religions share a common core of ethical and humanistic values.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-12',
    question: "Pandit Ishwar Chandra Vidyasagar's name is associated with the founding of which institution in 1849 to promote women's education?",
    options: ["Lady Irwin College", "Bethune School", "Miranda House", "SNDT University"],
    correctAnswer: 1,
    explanation: "Bethune School",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-13',
    question: "The reform movements were largely restricted to the urban educated middle class. What was a primary reason for their failure to reach the rural masses?",
    options: ["The reformers used highly technical Sanskrit and Persian, which the masses did not understand.", "The movements remained largely intellectual and did not adequately address the pressing economic grievances of the peasantry.", "The British government legally banned reformers from entering villages.", "The rural masses were already fully reformed."],
    correctAnswer: 1,
    explanation: "The movements remained largely intellectual and did not adequately address the pressing economic grievances of the peasantry.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-14',
    question: "D.K. Karve is a legendary figure in the field of women's empowerment. Which of the following was his most significant achievement in 1916?",
    options: ["Passing the Widow Remarriage Act.", "Setting up the Indian Women's University in Bombay.", "Leading the Satyagraha for temple entry.", "Abolishing the Purdah system in Maharashtra."],
    correctAnswer: 1,
    explanation: "Setting up the Indian Women's University in Bombay.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-15',
    question: "The 19th-century reformers often appealed to the 'Golden Age' of India. Why?",
    options: ["To support British claims that India was always a colony.", "To create a sense of self-respect and pride among Indians, arguing that current social evils were later distortions and not part of 'original' Indian culture.", "To demand the restoration of the Mughal Empire.", "To promote the study of ancient Greek history."],
    correctAnswer: 1,
    explanation: "To create a sense of self-respect and pride among Indians.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-16',
    question: "Who was the first Dalit leader to launch a newspaper, the Vital Vidhvasak, to raise the issues of the untouchables?",
    options: ["B.R. Ambedkar", "Jyotiba Phule", "Gopal Baba Walangkar", "E.V. Ramaswamy Naicker"],
    correctAnswer: 2,
    explanation: "Gopal Baba Walangkar",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-17',
    question: "The socio-religious reform movements led to the growth of 'Modern Indian Languages'. How?",
    options: ["The British forced reformers to write only in English.", "Reformers used vernacular languages to reach a wider audience, leading to the development of modern prose and journalism.", "All religious texts were rewritten in Latin.", "The reformers banned the use of local dialects."],
    correctAnswer: 1,
    explanation: "Reformers used vernacular languages to reach a wider audience.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-18',
    question: "Consider the following pairs of reformers and their primary focus area:\n1. B.M. Malabari \u2014 Age of Consent\n2. D.K. Karve \u2014 Women's University\n3. Vishnu Shastri Pandit \u2014 Widow Remarriage How many of the above pairs are correctly matched?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-19',
    question: "The 'All India Women's Conference' (1927) was a milestone in the women's movement. Who was its primary founder?",
    options: ["Sarojini Naidu", "Pandita Ramabai", "Margaret Cousins", "Annie Besant"],
    correctAnswer: 2,
    explanation: "Margaret Cousins",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-20',
    question: "What was the 'Shuddhi' movement initiated by the Arya Samaj?",
    options: ["A movement to clean the holy rivers of India.", "A movement to bring back those who had converted to other religions into the Hindu fold.", "A movement to abolish the caste system through inter-dining.", "A movement to promote Western clothing."],
    correctAnswer: 1,
    explanation: "A movement to bring back those who had converted to other religions into the Hindu fold.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-21',
    question: "In the context of 19th-century India, the term 'Humanism' meant:",
    options: ["The belief that humans are superior to all gods.", "A focus on the social well-being and dignity of the individual in the 'here and now' rather than just religious salvation.", "The complete rejection of all religious organizations.", "The study of human anatomy in medical colleges."],
    correctAnswer: 1,
    explanation: "A focus on the social well-being and dignity of the individual in the 'here and now'.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-22',
    question: "The 'Self-Respect Movement' in South India was launched by E.V. Ramaswamy Naicker (Periyar) primarily to:",
    options: ["Support the Brahmins against British taxation.", "Overthrow the British Raj through armed struggle.", "Challenge Brahminical dominance and the caste system.", "Promote the Hindi language in Tamil Nadu."],
    correctAnswer: 2,
    explanation: "Challenge Brahminical dominance and the caste system.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-23',
    question: "Which reformer argued that \"so long as the child-wife should graduate at the primary school in the art of training children, there is no hope for the country\"?",
    options: ["Raja Rammohan Roy", "B.M. Malabari", "Swami Vivekananda", "Dayanand Saraswati"],
    correctAnswer: 1,
    explanation: "B.M. Malabari",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-24',
    question: "The 19th-century reform movements provided an ideological base for the later nationalist movement by:",
    options: ["Teaching Indians how to manufacture weapons.", "Creating a sense of national unity, self-respect, and a critique of traditional social structures.", "Translating British law books into Sanskrit.", "Encouraging Indians to migrate to London."],
    correctAnswer: 1,
    explanation: "Creating a sense of national unity, self-respect, and a critique of traditional social structures.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-25',
    question: "Consider the following regarding the 'Brahmo Samaj' and the 'Prarthana Samaj': Statement-I: Both movements were primarily focused on the religious and social reform of Hindu society. Statement-II: Both movements completely rejected the authority of the Vedas and Upanishads. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 1,
    explanation: "Statement-I is correct but Statement-II is incorrect Statement-II is incorrect because the Brahmo Samaj (under Rammohan Roy) and the Prarthana Samaj actually based many of their arguments on a rationalist re-interpretation of the Upanishads and other scriptures.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-26',
    question: "Who was the founder of the 'Seva Sadan' in 1908, an organization dedicated to the service of the poor and distressed women?",
    options: ["G.K. Gokhale", "B.M. Malabari", "D.K. Karve", "M.G. Ranade"],
    correctAnswer: 1,
    explanation: "B.M. Malabari",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-27',
    question: "In the 19th century, the 'Prarthana Samaj' was most active in which region?",
    options: ["Bengal", "Maharashtra", "Punjab", "Madras"],
    correctAnswer: 1,
    explanation: "Maharashtra",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-28',
    question: "The concept of 'Religious Reformation' in 19th-century India was often a prerequisite for social reform because:",
    options: ["Social evils like Sati and child marriage were often given a religious justification.", "Only religious leaders were allowed to talk to the British.", "The British government would only change laws if the Pope agreed.", "The reformers were all atheists."],
    correctAnswer: 0,
    explanation: "Social evils like Sati and child marriage were often given a religious justification.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-29',
    question: "The 19th-century reformers' emphasis on 'Individualism' meant:",
    options: ["That every person should live in isolation in the forest.", "The right of an individual to interpret scriptures and moral codes based on reason rather than blind faith in the clergy.", "That the state has no right to tax any individual.", "The abolition of the family unit."],
    correctAnswer: 1,
    explanation: "The right of an individual to interpret scriptures and moral codes based on reason.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-30',
    question: "The Arya Samaj's slogan \"Back to the Vedas\" was an example of:",
    options: ["A reformist approach aiming at Westernization.", "A revivalist approach aiming at restoring the perceived purity of the Vedic age.", "A political approach to restore the Gupta Empire.", "A secular approach that ignored all religions."],
    correctAnswer: 1,
    explanation: "A revivalist approach aiming at restoring the perceived purity of the Vedic age.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-31',
    question: "Which of the following was a common feature of almost all 19th-century socio-religious reform movements?",
    options: ["Armed struggle against the British.", "Demand for a separate religious state.", "Opposition to idolatry and polytheism, and a push for social equality.", "Promotion of child marriage to protect tradition."],
    correctAnswer: 2,
    explanation: "Opposition to idolatry and polytheism, and a push for social equality.",
    chapterId: 7,
    difficulty: 'Moderate'
  },
  {
    id: '7-32',
    question: "Consider the following statements regarding the ideological base of 19th-century reform movements:\n1. The reformers aimed at a total rejection of Indian tradition in favor of a complete adoption of Western colonial culture.\n2. 'Religious Universalism' was used as a tool to argue that all religions were fundamentally same and that social evils were distortions of original faith.\n3. Rationalism was emphasized as the only preceptor, with leaders like Akshay Kumar Dutt arguing that even religious principles must be judged by the laws of nature. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statement 1 is incorrect; the reformers sought a synthesis of the best of the East and the West, not a total rejection of Indian tradition. Statements 2 and 3 are correct.",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-33',
    question: "With reference to the legislative measures for women's reform, consider the following: Statement-I: The Bengal Regulations of 1795 and 1804 were the first to declare female infanticide illegal and equivalent to murder. Statement-II: These regulations were immediately and successfully implemented across the entire Indian subcontinent by the end of the 18th century. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 2,
    explanation: "Statement-I is correct but Statement-II is incorrect While the regulations were passed (Statement-I), their implementation was slow and difficult, especially in the princely states and remote areas (Statement-II is false).",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-34',
    question: "Arrange the following social reform legislations in the correct chronological order of their enactment:\n1. Hindu Widows' Remarriage Act\n2. Sarda Act (Child Marriage Restraint Act)\n3. Age of Consent Act\n4. Native Marriage Act (Civil Marriage Act) Select the correct answer using the code given below:",
    options: ["1 \u2014 4 \u2014 3 \u2014 2", "4 \u2014 1 \u2014 2 \u2014 3", "1 \u2014 3 \u2014 4 \u2014 2", "4 \u2014 2 \u2014 1 \u2014 3"],
    correctAnswer: 0,
    explanation: "1 \u2014 4 \u2014 3 \u2014 2 Hindu Widows' Remarriage Act (1856) -> Native Marriage Act (1872) -> Age of Consent Act (1891) -> Sarda Act (1929).",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-35',
    question: "Consider the following pairs of Women's Organizations and their Founders:\n1. Bharat Stree Mahamandal \u2014 Sarla Devi Chaudhurani\n2. Ladies Social Conference (Bharat Mahila Parishad) \u2014 Ramabai Ranade\n3. All India Women's Conference (AIWC) \u2014 Margaret Cousins\n4. Arya Mahila Samaj \u2014 Pandita Ramabai How many of the above pairs are correctly matched?",
    options: ["Only one pair", "Only two pairs", "Only three pairs", "All four pairs"],
    correctAnswer: 3,
    explanation: "All four pairs",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-36',
    question: "Regarding the 'Satyashodhak Samaj' founded by Jyotirao Phule, consider the following statements:\n1. It sought to provide leadership to the oppressed classes by bypassing the intermediary role of the Brahmin priests.\n2. It was primarily funded by the orthodox Brahmin aristocracy of Pune.\n3. Phule\u2019s works, such as Gulamgiri, served as the ideological foundation for the movement. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 3 are correct. Statement 2 is incorrect; the movement was aimed against Brahminical hegemony and was supported by the non-Brahmin masses.",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-37',
    question: "\"He started a widows\u2019 home in Poona, married a widow himself, and eventually founded the first Indian Women's University in 1916. He was also a professor at Fergusson College.\" The above description refers to:",
    options: ["Jyotirao Phule", "M.G. Ranade", "D.K. Karve", "B.M. Malabari"],
    correctAnswer: 2,
    explanation: "D.K. Karve",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-38',
    question: "With reference to the Aligarh Movement and the Deoband Movement, consider the following: Statement-I: Both movements aimed at a liberal and modern re-interpretation of Islamic scriptures to suit the needs of the 19th century. Statement-II: The Deoband Movement was an orthodox revivalist movement aimed at preaching the original teachings of the Quran and Hadis, whereas the Aligarh Movement was reformist. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 2,
    explanation: "Statement-I is incorrect but Statement-II is correct Statement-I is false because Deoband was revivalist and orthodox, opposing the liberal Aligarh movement.",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-39',
    question: "Consider the following statements regarding the 'Age of Consent Act' (1891):\n1. It was heavily opposed by Bal Gangadhar Tilak on the grounds of foreign interference in Hindu traditions.\n2. It prohibited the marriage of girls below the age of 14.\n3. The Act was a direct result of the Phulmani Das case in Bengal. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 3 are correct. Statement 2 is incorrect; the Act raised the age from 10 to 12, not 14.",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-40',
    question: "Consider the following pairs of Reformers and their associated Journals/Newspapers:\n1. Gopal Baba Walangkar \u2014 Vital Vidhvasak\n2. B.R. Ambedkar \u2014 Mooknayak\n3. Karsandas Mulji \u2014 Satya Prakash How many of the above pairs are correctly matched?",
    options: ["Only one pair", "Only two pairs", "All three pairs", "None"],
    correctAnswer: 2,
    explanation: "All three pairs",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-41',
    question: "The 'Aravippuram Movement' (1888) in Kerala, which challenged the Brahminical monopoly over religious rites, was led by:",
    options: ["E.V. Ramaswamy Naicker", "Sri Narayana Guru", "Sahodaran Ayyappan", "Dr. Palpu"],
    correctAnswer: 1,
    explanation: "Sri Narayana Guru",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-42',
    question: "With reference to the 'Self-Respect Movement', consider the following: Statement-I: It was launched by E.V. Ramaswamy Naicker to encourage non-Brahmins to conduct weddings without the help of Brahmin priests. Statement-II: The movement advocated for the strict implementation of the Varna system to maintain social order. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 1,
    explanation: "Statement-I is correct but Statement-II is incorrect The movement was vehemently anti-Varna and anti-caste.",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-43',
    question: "The 'Temple Entry Movement' reached its peak in the 1920s and 30s. Arrange the following events in chronological order:\n1. Vaikom Satyagraha\n2. Guruvayur Satyagraha\n3. Temple Entry Proclamation by the Maharaja of Travancore Select the correct answer using the code given below:",
    options: ["1 \u2014 2 \u2014 3", "2 \u2014 1 \u2014 3", "3 \u2014 1 \u2014 2", "1 \u2014 3 \u2014 2"],
    correctAnswer: 0,
    explanation: "1 \u2014 2 \u2014 3 Vaikom (1924) -> Guruvayur (1931) -> Proclamation (1936).",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-44',
    question: "Consider the following statements regarding the Arya Samaj:\n1. It supported the 'Shuddhi' movement to convert non-Hindus to Hinduism.\n2. It emphasized the absolute authority of the Puranas over the Vedas.\n3. It promoted the D.A.V. (Dayanand Anglo-Vedic) schools to provide a blend of Western and Vedic education. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 3 are correct. Statement 2 is incorrect; Arya Samaj rejected the Puranas and held \"Back to the Vedas\" as its primary slogan.",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-45',
    question: "The 'Native Marriage Act' (1872) is significant because it was the first legislative attempt to:",
    options: ["Legalize inter-caste and inter-religious marriages.", "Abolish the practice of polygamy among Muslims.", "Fix the marriage age for all Indians regardless of religion.", "Mandate that all marriages be conducted by Christian priests."],
    correctAnswer: 0,
    explanation: "Legalize inter-caste and inter-religious marriages",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-46',
    question: "Consider the following regarding the 'Seva Sadan' founded by B.M. Malabari and Dayaram Gidumal: Statement-I: It was an organization specifically designed to train Hindu women for political leadership in the Indian National Congress. Statement-II: It specialized in taking care of those women who were exploited and then discarded by society, providing them with medical and educational services. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 2,
    explanation: "Statement-I is incorrect but Statement-II is correct",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-47',
    question: "The concept of 'Renaissance' in 19th-century India was structurally different from the European Renaissance because:",
    options: ["It completely ignored the study of the past.", "It was heavily influenced by the colonial presence and was restricted largely to the urban middle class.", "It occurred before the invention of the printing press in India.", "It was led entirely by the rural peasantry."],
    correctAnswer: 1,
    explanation: "It was heavily influenced by the colonial presence and was restricted largely to the urban middle class",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-48',
    question: "Which of the following pairs of Women's Journals/Magazines and their associated communities is incorrectly matched?\n1. Stri Darpan \u2014 General/Nationalist women\n2. Tahzib-e-Niswan \u2014 Muslim women\n3. Khatoon \u2014 Sikh women Select the correct answer using the code given below:",
    options: ["1 only", "3 only", "1 and 2 only", "2 and 3 only"],
    correctAnswer: 1,
    explanation: "3 only Khatoon was also a journal for Muslim women (published from Aligarh), not Sikh women.",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-49',
    question: "Consider the following statements regarding the 'Bahishkrit Hitakarini Sabha' (1924):\n1. It was founded by Jyotirao Phule to promote primary education in rural Maharashtra.\n2. Its primary goal was to improve the conditions of the Depressed Classes (Dalits) and represent their grievances to the government.\n3. It organized the Mahad Satyagraha to assert the right of untouchables to use water from public tanks. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 2 and 3 are correct. Statement 1 is incorrect; it was founded by Dr. B.R. Ambedkar, not Jyotirao Phule.",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-50',
    question: "With reference to 19th-century reform, what was 'Prarthana Samaj's' stance on the Vedas?",
    options: ["It held them as the infallible word of God.", "It did not regard them as infallible or as the sole repository of truth, focusing instead on theistic devotion.", "It demanded that the Vedas be translated into English by the British government.", "It rejected the Vedas entirely as being 'foreign' to the Indian soil."],
    correctAnswer: 1,
    explanation: "It did not regard them as infallible",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-51',
    question: "\"He was a Parsi reformer who spent his whole life fighting against child marriage and for widow remarriage. He was the editor of 'Indian Spectator' and his notes led to the Age of Consent Act.\" The above description refers to:",
    options: ["Dadabhai Naoroji", "Behramji M. Malabari", "Pherozeshah Mehta", "Dinshaw Wacha"],
    correctAnswer: 1,
    explanation: "Behramji M. Malabari",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-52',
    question: "The 'Self-Respect' weddings (Swayam-Mariyathai) initiated by Periyar were notable because:\n1. They were conducted without the presence of a Brahmin priest.\n2. They were valid only if conducted in a Hindu temple.\n3. They were recognized by the Madras government only after a long legal struggle. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 3 are correct. Statement 2 is incorrect; they were designed to be secular and could be held anywhere.",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-53',
    question: "In the context of 19th-century India, 'Reformist' movements (like Brahmo Samaj) and 'Revivalist' movements (like Arya Samaj) shared which common goal?",
    options: ["The conversion of India to Christianity.", "The removal of social evils and the modernization of Indian society, albeit through different ideological justifications.", "The restoration of the Mughal administrative system.", "The complete isolation of India from global trade."],
    correctAnswer: 1,
    explanation: "The removal of social evils",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-54',
    question: "Consider the following statements regarding the 'All India Depressed Classes Federation' (1942): Statement-I: It was the first organization to demand separate electorates for the untouchables. Statement-II: It was founded by Dr. B.R. Ambedkar to consolidate Dalit political power at a national level. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 0,
    explanation: "Both Statement-I and Statement-II are correct",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-55',
    question: "Which reformer argued that \"so long as the child-wife should graduate at the primary school in the art of training children, there is no hope for the country\"?",
    options: ["Raja Rammohan Roy", "B.M. Malabari", "Swami Vivekananda", "Dayanand Saraswati"],
    correctAnswer: 1,
    explanation: "B.M. Malabari",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-56',
    question: "\"A Muslim reformist movement that arose in response to the Western influence. It advocated for a modern interpretation of the Quran and aimed at improving the social and educational status of Muslims by reconciling Islam with Western science.\" This refers to the:",
    options: ["Wahabi Movement", "Deoband Movement", "Aligarh Movement", "Faraizi Movement"],
    correctAnswer: 2,
    explanation: "Aligarh Movement",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-57',
    question: "Consider the impact of the socio-religious reform movements on the Indian National Movement:\n1. They created a sense of self-respect and pride in the Indian heritage.\n2. They provided a critique of the decaying traditional social structure that hindered national unity.\n3. they led to a complete and permanent end to all communal tensions in India. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 2 are correct. Statement 3 is false; unfortunately, some movements (especially revivalist and shuddhi/tabligh) contributed to communal polarization later on.",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-58',
    question: "The 'Tattvabodhini Sabha', which carried forward the message of Raja Rammohan Roy, was founded by:",
    options: ["Keshab Chandra Sen", "Debendranath Tagore", "Ishwar Chandra Vidyasagar", "Akshay Kumar Dutt"],
    correctAnswer: 1,
    explanation: "Debendranath Tagore",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-59',
    question: "With reference to 'Pandita Ramabai', consider the following statements:\n1. She was the first woman to be awarded the title of 'Pandita' and 'Saraswati' by the University of Calcutta.\n2. She founded the Sharada Sadan to provide education to child widows.\n3. She remained a lifelong orthodox Hindu and fiercely opposed the work of Christian missionaries. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 2 are correct. Statement 3 is incorrect; she converted to Christianity, which led to controversy in her later life.",
    chapterId: 7,
    difficulty: 'Hard'
  },
  {
    id: '7-60',
    question: "The 'Sarda Act' of 1929 was significant because it was the first time that:",
    options: ["The British government fixed a minimum age for marriage for all Indians across all religions.", "The marriage of widows was made legal.", "inter-caste marriages were promoted by the government.", "the Dowry system was officially abolished."],
    correctAnswer: 0,
    explanation: "The British government fixed a minimum age for marriage",
    chapterId: 7,
    difficulty: 'Hard'
  },
];