// Auto-generated by Antigravity Script
import { Question } from '../../../../types';

export const MODERN_CHAPTER_16_MCQS: any[] = [
  {
    id: '15-56',
    question: "The Non-Cooperation Movement is often cited as the 'Greatest Success' of Gandhi despite its withdrawal. Why?",
    options: ["It achieved the repeal of the Salt Tax.", "It created a 'National Political Consciousness' on an unprecedented scale and made the British Raj realize it was ruling on borrowed time.", "It forced the British to merge the Muslim League and Congress.", "It resulted in the first Indian being appointed as the Viceroy."],
    correctAnswer: 1,
    explanation: "It created unprecedented national consciousness.",
    chapterId: 15,
    difficulty: 'Hard'
  },
  {
    id: '16-2',
    question: "After the withdrawal of NCM, the Congress split into two groups over the question of entering legislative councils. These groups were known as:",
    options: ["Moderates and Extremists", "Pro-Changers and No-Changers", "Liberals and Radicals", "Swarajists and Socialists"],
    correctAnswer: 1,
    explanation: "Pro-Changers and No-Changers",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-3',
    question: "Who were the two primary leaders of the 'Pro-Changers' who advocated for \"ending or mending\" the councils from within?",
    options: ["C.R. Das and Motilal Nehru", "Vallabhbhai Patel and", "Rajagopalachari", "Jawaharlal Nehru and Subhash Bose"],
    correctAnswer: 0,
    explanation: "C.R. Das and Motilal Nehru",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-4',
    question: "Which group of leaders, known as 'No-Changers', opposed council entry and wanted to focus on Gandhi's constructive program?",
    options: ["C.R. Das and Motilal Nehru", "C. Rajagopalachari, Vallabhbhai Patel, and Rajendra Prasad", "Hakim Ajmal Khan and Vithalbhai Patel", "Satyamurti and Srinivas Iyengar"],
    correctAnswer: 1,
    explanation: "C. Rajagopalachari, Vallabhbhai Patel, and Rajendra Prasad",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-5',
    question: "The 'Congress-Khilafat Swaraj Party' was formed in January 1923 following the deadlock at which Congress session?",
    options: ["Nagpur Session (1920)", "Gaya Session (1922)", "Belgaum Session (1924)", "Kanpur Session (1925)"],
    correctAnswer: 1,
    explanation: "Gaya Session (1922)",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-6',
    question: "Who was the first President of the Swaraj Party?",
    options: ["Motilal Nehru", "C.R. Das", "Vithalbhai Patel", "Lala Lajpat Rai"],
    correctAnswer: 1,
    explanation: "C.R. Das",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-7',
    question: "In the 1923 elections, the Swarajists won a clear majority in which provincial council?",
    options: ["Madras", "Central Provinces", "United Provinces", "Punjab"],
    correctAnswer: 1,
    explanation: "Central Provinces",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-8',
    question: "Who was elected as the Speaker (President) of the Central Legislative Assembly in 1925, marking a major victory for the Swarajists?",
    options: ["Motilal Nehru", "Vithalbhai Patel", "Madan Mohan Malaviya", "C.R. Das"],
    correctAnswer: 1,
    explanation: "Vithalbhai Patel",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-9',
    question: "The death of which leader in June 1925 led to a decline in the strength of the Swarajists?",
    options: ["Motilal Nehru", "C.R. Das", "Lala Lajpat Rai", "Hakim Ajmal Khan"],
    correctAnswer: 1,
    explanation: "C.R. Das",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-10',
    question: "Which group within the Swarajists, led by Madan Mohan Malaviya and Lala Lajpat Rai, advocated for cooperation with the government to protect Hindu interests?",
    options: ["Responsivists", "Non-Responsivists", "Socialist Wing", "Revolutionary Wing"],
    correctAnswer: 0,
    explanation: "Responsivists",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-11',
    question: "The 'Hindustan Republican Association' (HRA) was founded in 1924 at:",
    options: ["Calcutta", "Kanpur", "Delhi", "Lahore"],
    correctAnswer: 1,
    explanation: "Kanpur",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-12',
    question: "Who were the main founders of the HRA?",
    options: ["Bhagat Singh and Sukhdev", "Ram Prasad Bismil, Jogesh Chandra Chatterjee, and Sachin Sanyal", "Surya Sen and Kalpana Datta", "Chandrashekhar Azad and Batukeshwar Dutt"],
    correctAnswer: 1,
    explanation: "Ram Prasad Bismil, Jogesh Chandra Chatterjee, and Sachin Sanyal",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-13',
    question: "The famous 'Kakori Train Robbery' took place in which year?",
    options: ["1924", "1925", "1926", "1928"],
    correctAnswer: 1,
    explanation: "1925",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-14',
    question: "The HRA was reorganized as the 'Hindustan Socialist Republican Association' (HSRA) in 1928 at:",
    options: ["Jallianwala Bagh, Amritsar", "Feroz Shah Kotla, Delhi", "Alfred Park, Allahabad", "Kakori, UP"],
    correctAnswer: 1,
    explanation: "Feroz Shah Kotla, Delhi",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-15',
    question: "Who added the word 'Socialist' to the HRA and gave it a new ideological direction?",
    options: ["Bhagat Singh", "Chandrashekhar Azad", "Subhash Chandra Bose", "Jawaharlal Nehru"],
    correctAnswer: 0,
    explanation: "Bhagat Singh",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-16',
    question: "To avenge the death of Lala Lajpat Rai, Bhagat Singh, Rajguru, and Azad assassinated which British officer in 1928?",
    options: ["General Dyer", "John Saunders", "Michael O'Dwyer", "Lord Irwin"],
    correctAnswer: 1,
    explanation: "John Saunders (Assistant Superintendent of Police)",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-17',
    question: "Bhagat Singh and Batukeshwar Dutt threw bombs in the Central Legislative Assembly in April 1929 to protest against:",
    options: ["The Partition of Bengal", "The Public Safety Bill and Trade Dispute Bill", "The Simon Commission", "The Rowlatt Act"],
    correctAnswer: 1,
    explanation: "The Public Safety Bill and Trade Dispute Bill",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-18',
    question: "Which revolutionary died in 1929 after a 64-day hunger strike in jail demanding better conditions for political prisoners?",
    options: ["Bhagat Singh", "Jatin Das", "Sukhdev", "Surya Sen"],
    correctAnswer: 1,
    explanation: "Jatin Das",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-19',
    question: "Bhagat Singh, Rajguru, and Sukhdev were executed on March 23, 1931, in the:",
    options: ["Alipore Conspiracy Case", "Lahore Conspiracy Case", "Meerut Conspiracy Case", "Kakori Case"],
    correctAnswer: 1,
    explanation: "Lahore Conspiracy Case",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-20',
    question: "Who led the famous 'Chittagong Armoury Raid' in April 1930?",
    options: ["Bhagat Singh", "Surya Sen ('Master Da')", "Chandrashekhar Azad", "Sachin Sanyal"],
    correctAnswer: 1,
    explanation: "Surya Sen",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-21',
    question: "Chandrashekhar Azad died in a shootout with the police in February 1931 at:",
    options: ["Victoria Park, Calcutta", "Alfred Park, Allahabad", "Chandni Chowk, Delhi", "Lawrence Garden, Lahore"],
    correctAnswer: 1,
    explanation: "Alfred Park, Allahabad",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-22',
    question: "The 'Communist Party of India' (CPI) was first formed in Tashkent in 1920 by:",
    options: ["M.N. Roy, Abani Mukherji, and others", "S.A. Dange", "Muzaffar Ahmed", "P.C. Joshi"],
    correctAnswer: 0,
    explanation: "M.N. Roy, Abani Mukherji, and others",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-23',
    question: "The 'Kanpur Bolshevik Conspiracy Case' (1924) was directed against:",
    options: ["Swarajists", "Early Communists like S.A. Dange and Muzaffar Ahmed", "Revolutionary Terrorists", "Akalis"],
    correctAnswer: 1,
    explanation: "Early Communists",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-24',
    question: "Which leader was the main advocate of socialist ideas within the Congress during the late 1920s?",
    options: ["Sardar Patel", "Jawaharlal Nehru", "Rajendra Prasad", "C. Rajagopalachari"],
    correctAnswer: 1,
    explanation: "Jawaharlal Nehru (along with Subhash Bose)",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-25',
    question: "The 'Meerut Conspiracy Case' (1929) involved the arrest of 31 labor leaders, including three British communists. Who were the British communists?",
    options: ["Philip Spratt, Ben Bradley, and Lester Hutchinson", "A.O. Hume, George Yule, and William Wedderburn", "Annie Besant and Charles Bradlaugh", "Lord Morley and Lord Minto"],
    correctAnswer: 0,
    explanation: "Philip Spratt, Ben Bradley, and Lester Hutchinson",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-26',
    question: "The 'Workers and Peasants Parties' (WPPs) were formed to:",
    options: ["Support the British war effort", "Provide a legal platform for communist activities and organize labor/peasantry", "Oppose the formation of trade unions", "Promote the interests of the Zamindars"],
    correctAnswer: 1,
    explanation: "Provide a legal platform for communist activities",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-27',
    question: "Bhagat Singh founded which youth organization in Punjab in 1926?",
    options: ["Naujawan Bharat Sabha", "Punjab Youth Congress", "Bharat Mata Society", "Ghadr Party (Punjab Wing)"],
    correctAnswer: 0,
    explanation: "Naujawan Bharat Sabha",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-28',
    question: "The book The Philosophy of the Bomb was written by which HSRA member?",
    options: ["Bhagat Singh", "Bhagwati Charan Vohra", "Chandrashekhar Azad", "Yashpal"],
    correctAnswer: 1,
    explanation: "Bhagwati Charan Vohra",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-29',
    question: "In 1928, a major peasant movement against revenue hike was led by Vallabhbhai Patel in:",
    options: ["Kheda", "Bardoli", "Champaran", "Borsad"],
    correctAnswer: 1,
    explanation: "Bardoli (Where he earned the title 'Sardar')",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-30',
    question: "The Self-Respect Movement in South India was started by:",
    options: ["Jyotiba Phule", "E.V. Ramaswamy Naicker (Periyar)", "Dr. B.R. Ambedkar", "Sri Narayana Guru"],
    correctAnswer: 1,
    explanation: "E.V. Ramaswamy Naicker",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-31',
    question: "Which revolutionary woman fired at the Governor while receiving her degree at the Convocation of Calcutta University in 1932?",
    options: ["Kalpana Datta", "Bina Das", "Pritilata Waddedar", "Shanti Ghosh"],
    correctAnswer: 1,
    explanation: "Bina Das",
    chapterId: 16,
    difficulty: 'Easy'
  },
  {
    id: '16-32',
    question: "The debate between 'Pro-Changers' and 'No-Changers' after 1922 was essentially a debate over the strategy of the national movement. Which of the following best describes the 'Pro-Changer' argument?",
    options: ["They wanted to permanently abandon the path of non-violence.", "They believed that by entering the councils, they could \"wreck the reforms from within,\" expose the hollow nature of the 1919 Act, and keep up the political morale during a period of \"passive\" struggle.", "They advocated for a total merger with the British Liberal Party.", "They believed that only the peasantry could lead the next phase of the struggle."],
    correctAnswer: 1,
    explanation: "Wreck the reforms from within. C.R. Das and Motilal Nehru argued that council entry would prevent the government from filling seats with \"yes-men\" and would provide a platform for nationalist propaganda.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-33',
    question: "Consider the following statements regarding the 'Swaraj Party' and its relationship with the Congress: 1. The Swaraj Party was formed as a separate political party outside the organizational umbrella of the Indian National Congress. 2. Mahatma Gandhi, after his release in 1924, initially opposed council entry but eventually reached a compromise (the Belgaum Session) to maintain Congress unity. 3. The Swarajists agreed to work as an integral part of the Congress, following its basic principles of non-violence. Which of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2, and 3"],
    correctAnswer: 1,
    explanation: "2 and 3 only Statement 1 is incorrect. The Swaraj Party was established as a group within the Congress to avoid another disastrous split like the one in 1907.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-34',
    question: "The election of Vithalbhai Patel as the Speaker of the Central Legislative Assembly in 1925 was a landmark for the Swarajists because:",
    options: ["It gave them the power to declare India's independence immediately.", "It showed that Indians could master the parliamentary procedures of the colonizers and use their own institutions to challenge them.", "It resulted in the abolition of all taxes on salt.", "He was the first Indian to be appointed as the Viceroy's secretary."],
    correctAnswer: 1,
    explanation: "Mastered parliamentary procedures to challenge the British.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-35',
    question: "The 'Hindustan Socialist Republican Association' (HSRA) marked a significant ideological shift in revolutionary terrorism. What was the most notable change under Bhagat Singh's leadership?",
    options: ["A shift from purely 'individual heroic action' toward an understanding of the need for a mass-based revolution and the adoption of Socialist/Marxist ideas.", "The total rejection of the 1857 Revolt as an inspiration.", "The decision to support the British in World War II.", "The demand for the restoration of the Caliphate in Turkey."],
    correctAnswer: 0,
    explanation: "Shift toward mass-based revolution and Socialist ideas.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-36',
    question: "With reference to the 'Kakori Train Action' (1925), consider the following: Statement-I: It was organized by the HRA to fund their revolutionary activities by looting a government railway cash office. Statement-II: The incident led to the arrest and eventual execution of top leaders like Ram Prasad Bismil and Ashfaqullah Khan. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 0,
    explanation: "Both are correct.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-37',
    question: "Why did Bhagat Singh and Batukeshwar Dutt throw a bomb in the Central Legislative Assembly in 1929, making sure not to hurt anyone?",
    options: ["Because they ran out of high-quality explosives.", "To \"make the deaf hear\"\u2014protesting against the repressive Public Safety Bill and Trade Dispute Bill, and using the court trial as a platform to spread their revolutionary message.", "It was a practice run for a larger attack on the Viceroy.", "They were trying to help the Swarajists win the local elections."],
    correctAnswer: 1,
    explanation: "To \"make the deaf hear\" and use the trial for propaganda.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-38',
    question: "The 'Meerut Conspiracy Case' (1929) was a significant attempt by the British to:",
    options: ["Suppress the growing influence of Socialist and Communist ideas in the Indian labor movement.", "Arrest the leaders of the Swaraj Party.", "End the influence of the Theosophical Society.", "Punish the soldiers who participated in the 1857 revolt."],
    correctAnswer: 0,
    explanation: "Suppress Socialist and Communist influence.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-39',
    question: "Consider the following regarding the 'Bardoli Satyagraha' (1928): 1. It was a protest against the 22% increase in land revenue by the Bombay government. 2. Vallabhbhai Patel led the movement and successfully organized a total boycott of revenue payment. 3. The movement resulted in the government reducing the revenue hike to approximately 6%. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-40',
    question: "The 'Chittagong Armoury Raid' (1930) was unique because:",
    options: ["It was led by a school teacher, Surya Sen, and involved a well-planned, large-scale paramilitary action rather than a small assassination attempt.", "It was the first time the British army joined the revolutionaries.", "It was funded by the League of Nations.", "It took place in London."],
    correctAnswer: 0,
    explanation: "Led by Surya Sen; large-scale paramilitary action.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-41',
    question: "The 'Swarajists' were eventually criticized by the 'No-Changers' because they began to:",
    options: ["Adopt the violent methods of the HSRA.", "Get \"absorbed\" into the colonial system, with some members (Responsivists) seeking government offices and moving away from the policy of \"constant obstruction.\"", "Demand the return of the British to London.", "Ban the use of Khadi in the councils."],
    correctAnswer: 1,
    explanation: "Moving away from constant obstruction (Absorption).",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-42',
    question: "Who wrote the influential book Pather Dabi, which glorified the revolutionary struggle and was banned by the British?",
    options: ["Rabindranath Tagore", "Sarat Chandra Chattopadhyay", "Bankim Chandra Chatterjee", "Premchand"],
    correctAnswer: 1,
    explanation: "Sarat Chandra Chattopadhyay.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-43',
    question: "What was the 'Philosophy of the Bomb' (1930) a response to?",
    options: ["A direct order from the Soviet Union.", "Gandhi's article 'The Cult of the Bomb', where he criticized revolutionary violence.", "The discovery of gunpowder in China.", "The failure of the 1929 elections."],
    correctAnswer: 1,
    explanation: "Response to Gandhi's 'The Cult of the Bomb'.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-44',
    question: "Consider the following pairs of 'New Forces' in the 1920s and their leaders: 1. Communist Party of India \u2014 M.N. Roy 2. Self-Respect Movement \u2014 E.V. Ramaswamy 'Periyar' 3. Bahishkrit Hitakarini Sabha \u2014 B.R. Ambedkar How many of the above pairs are correctly matched?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-45',
    question: "The 'Responsivists' group within the Swarajists was led by:",
    options: ["Motilal Nehru and C.R. Das", "Madan Mohan Malaviya, Lala Lajpat Rai, and N.C. Kelkar", "Jawaharlal Nehru and Subhash Bose", "Vallabhbhai Patel and Rajendra Prasad"],
    correctAnswer: 1,
    explanation: "Malaviya, Lajpat Rai, and Kelkar.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-46',
    question: "Ultimately, the period of the 1920s (Chapter 16) is significant because it:",
    options: ["Saw the total decline of the national movement.", "Was an era of \"intellectual fermentation\" and organizational diversification that prepared different sections of society for the final mass struggle for independence.", "Led to the immediate grant of Purna Swaraj.", "Was the only period where the British were not in power."],
    correctAnswer: 1,
    explanation: "Era of intellectual fermentation and diversification.",
    chapterId: 16,
    difficulty: 'Moderate'
  },
  {
    id: '16-47',
    question: "Consider the following statements regarding the 'Swarajist' strategy within the Central Legislative Assembly: 1. Their primary tactic was 'Uniform, Continuous, and Consistent Obstruction' to make the governance under the 1919 Act impossible. 2. They successfully defeated the government on several proposals, including the 'Public Safety Bill' in 1928. 3. The Swarajists remained a monolithic block until 1930, strictly adhering to the policy of non-participation in any government committees. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 2 are correct. The Swarajists, with the help of independents, famously defeated the Public Safety Bill (which was aimed at curbing communists). Statement 3 is incorrect; the party suffered internal dissension, leading to the rise of Responsivists who wanted to accept offices, and some members did join committees like the Skeen Committee.",
    chapterId: 16,
    difficulty: 'Hard'
  },
  {
    id: '16-48',
    question: "With reference to the 'Hindustan Socialist Republican Association' (HSRA), consider the following: Statement-I: The transition from HRA to HSRA in 1928 signified a shift from a focus on political independence to a broader vision of ending the exploitation of man by man. Statement-II: Bhagat Singh and his comrades were influenced by the October Revolution in Russia and sought to organize a revolution of the \"masses for the masses.\" Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 0,
    explanation: "Both are correct and the Marxist influence (Statement-II) was the driving force behind the ideological renaming (Statement-I).",
    chapterId: 16,
    difficulty: 'Hard'
  },
  {
    id: '16-49',
    question: "Arrange the following revolutionary legal cases in the correct chronological order: 1. Meerut Conspiracy Case 2. Kakori Train Robbery Case 3. Kanpur Bolshevik Conspiracy Case 4. Lahore Conspiracy Case (Trial of Bhagat Singh, Rajguru, and Sukhdev) Select the correct answer using the code given below:",
    options: ["3 \u2014 2 \u2014 1 \u2014 4", "3 \u2014 1 \u2014 2 \u2014 4", "2 \u2014 3 \u2014 4 \u2014 1", "3 \u2014 2 \u2014 4 \u2014 1"],
    correctAnswer: 0,
    explanation: "3 \u2014 2 \u2014 1 \u2014 4 Kanpur (1924) -> Kakori (1925) -> Meerut (1929) -> Lahore (1929-1931).",
    chapterId: 16,
    difficulty: 'Hard'
  },
  {
    id: '16-50',
    question: "Consider the following pairs of 'New Organizations' and their Founders/Leaders in the 1920s: 1. Workers and Peasants Party (WPP) \u2014 S.S. Mirajkar and K.N. Joglekar 2. Bahishkrit Hitakarini Sabha \u2014 B.R. Ambedkar 3. Naujawan Bharat Sabha \u2014 Bhagat Singh 4. All India Trade Union Congress (AITUC) \u2014 N.M. Joshi (General Secretary) How many of the above pairs are correctly matched?",
    options: ["Only one pair", "Only two pairs", "Only three pairs", "All four pairs"],
    correctAnswer: 3,
    explanation: "All four pairs",
    chapterId: 16,
    difficulty: 'Hard'
  },
  {
    id: '16-51',
    question: "The 'Public Safety Bill' of 1928 was a major point of contention in the Assembly. Why did the Nationalists (Swarajists and others) oppose it so vehemently?",
    options: ["It proposed to ban the Indian National Congress.", "It gave the government the power to deport \"undesirable\" British and foreign communists who were helping the Indian labor movement.", "It aimed at increasing the salt tax by 200%.", "It made the use of Khadi illegal in public offices."],
    correctAnswer: 1,
    explanation: "Power to deport foreign communists assisting Indian labor.",
    chapterId: 16,
    difficulty: 'Hard'
  },
  {
    id: '16-52',
    question: "Regarding the 'Chittagong Armoury Raid' (1930) led by Surya Sen, consider the following statements: 1. The revolutionaries succeeded in capturing two armories and cutting off communication with the rest of India for a few days. 2. Surya Sen famously declared a Provisional Revolutionary Government of India and hoisted the National Flag. 3. The group included a significant number of women revolutionaries like Pritilata Waddedar and Kalpana Datta. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three",
    chapterId: 16,
    difficulty: 'Hard'
  },
  {
    id: '16-53',
    question: "With reference to the 'Meerut Conspiracy Case' (1929), consider the following: Statement-I: It was an attempt by the British to decapitate the growing Communist and Trade Union movement in India. Statement-II: The trial gained international attention, with figures like Albert Einstein and Romain Rolland speaking out in defense of the accused. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 0,
    explanation: "Both are correct. (The defense was organized by the Central Defense Committee, including Nehru and Katju).",
    chapterId: 16,
    difficulty: 'Hard'
  },
  {
    id: '16-54',
    question: "Match the following HSRA members with their specific contributions/events: 1. Jatin Das \u2014",
    options: ["Author of The Philosophy of the Bomb 2. Bhagwati Charan Vohra \u2014", "Martyrdom after a 64-day hunger strike 3. Chandrashekhar Azad \u2014", "Reorganized HRA into HSRA 4. Batukeshwar Dutt \u2014", "Accompanied Bhagat Singh to the Assembly bombing Select the correct matching code:"],
    correctAnswer: 0,
    explanation: "1-B, 2-A, 3-C, 4-D",
    chapterId: 16,
    difficulty: 'Hard'
  },
  {
    id: '16-55',
    question: "Consider the following regarding 'Socialist' ideas within the Congress in the late 1920s: 1. Jawaharlal Nehru and Subhash Chandra Bose were the primary advocates of a socialist future for independent India. 2. They founded the 'Independence for India League' in 1928 to pressure the Congress to adopt 'Purna Swaraj' and socialist principles. 3. Mahatma Gandhi was the first to propose a socialist economic model in the 1924 Belgaum session. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 2 are correct. Statement 3 is incorrect; while Gandhi had his own \"Trusteeship\" model, he was wary of Western socialism/Marxism and prioritized the \"Constructive Program.\"",
    chapterId: 16,
    difficulty: 'Hard'
  },
];