// Auto-generated by Antigravity Script
import { Question } from '../../../../types';

export const MODERN_CHAPTER_36_MCQS: any[] = [
  {
    id: '35-81',
    question: "Ultimately, 'Chapter 35' concludes that 'Independence with Partition' was:",
    options: ["A total success.", "A \"Tragic Necessity\"\u2014the cost paid for a stable, unified, and strong central government for the rest of India.", "A British trick.", "A result of Gandhi\u2019s failure."],
    correctAnswer: 1,
    explanation: "Tragic necessity for a strong center.",
    chapterId: 35,
    difficulty: 'Hard'
  },
  {
    id: '36-2',
    question: "Who is considered the principal architect of the 'Two-Nation Theory' in its final political form?",
    options: ["Sir Syed Ahmed Khan", "Muhammad Ali Jinnah", "Muhammad Iqbal", "Liaquat Ali Khan"],
    correctAnswer: 1,
    explanation: "Muhammad Ali Jinnah",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-3',
    question: "In which year was the All-India Muslim League founded?",
    options: ["1905", "1906", "1909", "1916"],
    correctAnswer: 1,
    explanation: "1906 (in Dhaka).",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-4',
    question: "Who was the first presiding President of the Muslim League?",
    options: ["Aga Khan III", "Nawab Viqar-ul-Mulk", "Nawab Salimullah", "Muhammad Ali Jinnah"],
    correctAnswer: 1,
    explanation: "Nawab Viqar-ul-Mulk (Aga Khan III was the first permanent president).",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-5',
    question: "The 'Shimla Deputation' (1906), led by Aga Khan, met which Viceroy to demand separate electorates?",
    options: ["Lord Curzon", "Lord Minto", "Lord Hardinge", "Lord Morley"],
    correctAnswer: 1,
    explanation: "Lord Minto.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-6',
    question: "The 'Separate Electorates' for Muslims were formally introduced by which Act?",
    options: ["Indian Councils Act 1892", "Morley-Minto Reforms (1909)", "Montagu-Chelmsford Reforms (1919)", "Government of India Act 1935"],
    correctAnswer: 1,
    explanation: "Morley-Minto Reforms (1909).",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-7',
    question: "The 'Hindu Mahasabha' was founded in 1915 at Haridwar. Who was its primary founder?",
    options: ["V.D. Savarkar", "Madan Mohan Malaviya", "Lala Lajpat Rai", "K.B. Hedgewar"],
    correctAnswer: 1,
    explanation: "Madan Mohan Malaviya.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-8',
    question: "The 'Lucknow Pact' (1916) saw an agreement between the Congress and the Muslim League. What was the major concession by the Congress?",
    options: ["Acceptance of the demand for Pakistan", "Acceptance of Separate Electorates for Muslims", "Giving up the demand for Purna Swaraj", "Allowing Jinnah to be the Congress President"],
    correctAnswer: 1,
    explanation: "Acceptance of Separate Electorates.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-9',
    question: "The 'Shuddhi' and 'Sangathan' movements were associated with which group?",
    options: ["Brahmo Samaj", "Arya Samaj (and later Hindu Mahasabha)", "Theosophical Society", "Ramakrishna Mission"],
    correctAnswer: 1,
    explanation: "Arya Samaj.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-10',
    question: "Corresponding to 'Shuddhi', the Muslim movements for religious propagation and organization were:",
    options: ["Khilafat and Hijrat", "Tabligh and Tanzim", "Aligarh and Deoband", "Wahabi and Ahmadiyya"],
    correctAnswer: 1,
    explanation: "Tabligh and Tanzim.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-11',
    question: "Who was the first to give the idea of a separate Muslim state in the North-West during his 1930 presidential address at Allahabad? A. Rahmat Ali B. Muhammad Iqbal C. Muhammad Ali Jinnah",
    options: ["Option A", "Option B", "Option C", "Option D"],
    correctAnswer: 1,
    explanation: "Muhammad Iqbal.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-12',
    question: "The name 'Pakistan' (Punjab, Afghania, Kashmir, Sindh, Baluchistan) was coined by:",
    options: ["Muhammad Iqbal", "Choudhry Rahmat Ali", "Muhammad Ali Jinnah", "Liaquat Ali Khan"],
    correctAnswer: 1,
    explanation: "Choudhry Rahmat Ali (a student at Cambridge).",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-13',
    question: "The 'Communal Award' (1932) was announced by which British Prime Minister?",
    options: ["Winston Churchill", "Ramsay MacDonald", "Clement Attlee", "Neville Chamberlain"],
    correctAnswer: 1,
    explanation: "Ramsay MacDonald.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-14',
    question: "In which year did Jinnah return to India from London to reorganize the Muslim League as a mass party?",
    options: ["1930 /", "1934", "1937", "1940"],
    correctAnswer: 1,
    explanation: "1934.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-15',
    question: "The 'Fourteen Points' were put forward by Jinnah in 1929 as a reaction to:",
    options: ["The Simon Commission", "The Nehru Report", "The 1919 Act", "The Civil Disobedience Movement"],
    correctAnswer: 1,
    explanation: "The Nehru Report.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-16',
    question: "The 'Rashtriya Swayamsevak Sangh' (RSS) was founded in 1925 by:",
    options: ["V.D. Savarkar", "K.B. Hedgewar", "M.S. Golwalkar", "B.S. Moonje"],
    correctAnswer: 1,
    explanation: "K.B. Hedgewar.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-17',
    question: "The 'United Indian Patriotic Association' (1888) was formed to oppose the Congress by:",
    options: ["Lord Dufferin", "Sir Syed Ahmed Khan", "Raja Shiv Prasad of Benares", "Both B and C"],
    correctAnswer: 3,
    explanation: "Both B and C.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-18',
    question: "Which British official's book The Indian Musalmans (1871) influenced the shift in British policy toward favoring Muslims to counter \"Hindu\" nationalism?",
    options: ["W.W. Hunter", "James Stephen", "Alfred Lyall", "Thomas Raleigh"],
    correctAnswer: 0,
    explanation: "W.W. Hunter.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-19',
    question: "The 'Agha Khan' led a deputation to Minto in 1906. This event is often called the 'Communal Command Performance' because:",
    options: ["It was a secret plan of the Congress.", "It was allegedly encouraged and engineered by the British officials (like Minto\u2019s secretary Dunlop Smith).", "It was a dance performance.", "It was held in a theatre."],
    correctAnswer: 1,
    explanation: "Alleged British engineering.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-20',
    question: "The 'Delhi Proposals' (1927) were a set of four demands by the Muslim League in exchange for giving up:",
    options: ["The demand for Pakistan", "Separate Electorates (in favor of Joint Electorates)", "Their membership in the Congress", "The Khilafat movement"],
    correctAnswer: 1,
    explanation: "Separate Electorates.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-21',
    question: "In the 1937 elections, the Muslim League performed poorly. Out of the 482 Muslim reserved seats, it won only:",
    options: ["10", "109", "400", "250"],
    correctAnswer: 1,
    explanation: "109.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-22',
    question: "The 'Pirpur Report' (1938) was titled:",
    options: ["The History of Muslim League", "Report of the Inquiry Committee into Muslim Grievances in Congress Provinces", "The Pakistan Manifesto", "British Atrocities in India"],
    correctAnswer: 1,
    explanation: "Report on Muslim Grievances.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-23',
    question: "Who authored the book Hindutva: Who is a Hindu? (1923), which defined the ideology of the Hindu Right?",
    options: ["K.B. Hedgewar", "V.D. Savarkar", "M.S. Golwalkar", "Madan Mohan Malaviya"],
    correctAnswer: 1,
    explanation: "V.D. Savarkar.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-24',
    question: "The 'Lahore Resolution' (1940) was moved by which leader from Bengal?",
    options: ["H.S. Suhrawardy", "Fazlul Huq (Sher-e-Bangla)", "Nazimuddin", "Khwaja Salimullah"],
    correctAnswer: 1,
    explanation: "Fazlul Huq.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-25',
    question: "The 'Two-Nation Theory' was based on the premise that Hindus and Muslims were:",
    options: ["Two different political parties", "Two distinct nations with incompatible cultures and religions", "Two groups of friends", "Two types of farmers"],
    correctAnswer: 1,
    explanation: "Two distinct nations.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-26',
    question: "'B.R. Ambedkar' analyzed the communal problem in his famous 1940 book titled:",
    options: ["The Annihilation of Caste", "Thoughts on Pakistan (or Pakistan or the Partition of India)", "The Untouchables", "Who Were the Shudras?"],
    correctAnswer: 1,
    explanation: "Thoughts on Pakistan.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-27',
    question: "Which year is associated with the 'Kohat Riots', which led to a breakdown of the Hindu-Muslim unity of the Non-Cooperation era?",
    options: ["1919", "1924", "1930", "1942"],
    correctAnswer: 1,
    explanation: "1924.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-28',
    question: "The 'Direct Action Day' (1946) was a call for:",
    options: ["Peaceful protests", "Establishing the strength of the Muslim demand for Pakistan through extra-constitutional means", "Joining the Interim Government", "Supporting the British war effort"],
    correctAnswer: 1,
    explanation: "Extra-constitutional pressure for Pakistan.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-29',
    question: "The slogan 'Divide and Quit' was given by:",
    options: ["Mahatma Gandhi", "Muhammad Ali Jinnah (to the British)", "Lord Mountbatten", "Winston Churchill"],
    correctAnswer: 1,
    explanation: "Muhammad Ali Jinnah.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-30',
    question: "'Liaquat Ali Khan' held which important post in the Muslim League and later became the first PM of Pakistan?",
    options: ["President", "Honorary Secretary", "Treasurer", "Youth Leader"],
    correctAnswer: 1,
    explanation: "Honorary Secretary.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-31',
    question: "Ultimately, the British 'Divide and Rule' policy turned into 'Divide and _____' by 1947.",
    options: ["Stay", "Quit", "Rule Forever", "Prosper"],
    correctAnswer: 1,
    explanation: "Quit.",
    chapterId: 36,
    difficulty: 'Easy'
  },
  {
    id: '36-32',
    question: "Historians often discuss the \"Lag Theory\" regarding the Muslim middle class in the 19th century. What does this signify?",
    options: ["Muslims were physically slower than Hindus.", "Due to the late adoption of Western education and the loss of administrative positions after 1857, the Muslim middle class developed later than the Hindu middle class, creating a sense of insecurity and competition for limited government jobs.", "Muslims refused to use the railway system.", "The Muslim League was founded 100 years after the Congress."],
    correctAnswer: 1,
    explanation: "Late development of the middle class and competition for jobs. This economic competition was the \"material base\" upon which political communalism was built.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-33',
    question: "The British policy shift from favoring Hindus (pre-1870s) to favoring Muslims (post-1870s) was a strategic response to:",
    options: ["The British falling in love with Islamic culture.", "The rise of a \"seditious\" Hindu middle class led by the Congress, which prompted the British to use the Muslim elite as a \"counterpoise\" to nationalist demands.", "A massive Muslim migration to London.", "The discovery of oil in the Middle East."],
    correctAnswer: 1,
    explanation: "Creating a \"counterpoise\" to the Congress.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-34',
    question: "Consider the following statements regarding 'Sir Syed Ahmed Khan':\n1. He was a lifelong opponent of Western education and science.\n2. Initially, he spoke of Hindus and Muslims as the \"two eyes of a beautiful bride\" (India). 3. Later in life, he argued that the interests of the two communities were divergent and that Hindus would dominate Muslims in a democratic setup. Which of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2, and 3"],
    correctAnswer: 1,
    explanation: "2 and 3 only. Sir Syed was actually a pioneer of Western education (Aligarh Movement), but his political views shifted toward separatism as the Congress grew.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-35',
    question: "The 'Morley-Minto Reforms' (1909) are seen as the \"Legal Birth\" of communalism because they:",
    options: ["Banned the Hindu Mahasabha.", "Introduced 'Separate Electorates', which forced candidates to appeal only to their own religious community, thereby institutionalizing religious identity in politics.", "Abolished the post of Secretary of State.", "Made Urdu the official language of Britain."],
    correctAnswer: 1,
    explanation: "Institutionalization of religious identity via Separate Electorates.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-36',
    question: "With reference to the 'Lucknow Pact' (1916), consider the following: Statement-I: It was a high point of Hindu-Muslim unity where both parties presented a joint constitutional scheme to the British. Statement-II: However, by accepting 'Separate Electorates', the Congress made a \"tactical error\" that gave a permanent legitimacy to the idea that Hindus and Muslims were two separate political entities. Which one of the following is correct?",
    options: ["Both are correct and Statement-II highlights the long-term cost of Statement-I.", "Statement-I is correct but Statement-II is false.", "Both are false.", "Statement-II is correct but Statement-I is false."],
    correctAnswer: 0,
    explanation: "Both are correct.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-37',
    question: "Why did the 'Khilafat Movement' (1919-24) represent a \"double-edged sword\" for Indian nationalism?",
    options: ["It brought the Muslim masses into the freedom struggle but also introduced \"Religious Idioms\" and \"Pan-Islamic\" issues into secular politics, which could later be used by communalists.", "it resulted in the end of the British Empire in 1924.", "It forced Gandhi to leave the Congress.", "It only concerned the people of Turkey."],
    correctAnswer: 0,
    explanation: "Mass mobilization vs. religious idioms in politics.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-38',
    question: "The 'Nehru Report' (1928) was rejected by the Muslim League primarily because it:",
    options: ["Demanded Purna Swaraj.", "Proposed 'Joint Electorates' with reservation of seats instead of the 'Separate Electorates' that the League considered vital for its survival.", "Was written in Hindi.", "Abolished the post of Viceroy."],
    correctAnswer: 1,
    explanation: "Proposed Joint Electorates.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-39',
    question: "Consider the following regarding the 'Three Stages of Communalism' as defined by historians like Bipan Chandra:\n1. Liberal Communalism: Belief that communal interests are different but can be accommodated.\n2. Extremist Communalism: Belief that communal interests are inherently antagonistic.\n3. Fascist Communalism: Belief that the other community is an enemy and cannot coexist. How many of the above are correctly defined?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three. (Jinnah's career moved through all three stages).",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-40',
    question: "The 'Communal Award' (1932) further fragmented Indian society by extending separate electorates to:",
    options: ["Women and Students.", "The 'Depressed Classes' (Dalits), which Gandhi opposed through the 'Poona Pact'.", "The British residents in India only.", "Farmers and Laborers."],
    correctAnswer: 1,
    explanation: "Depressed Classes.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-41',
    question: "Match the following 'Ideological Shifts' with the 'Period':\n1. 1906\u20131915 \u2014",
    options: ["Elite communalism (Demanding jobs/electorates) 2. 1920\u20131937 \u2014", "Liberal communalism (Bargaining for safeguards) 3. 1937\u20131947 \u2014", "Mass communalism (Demanding a separate nation) Select the correct matching code:", "1-A, 2-B, 3-C"],
    correctAnswer: 0,
    explanation: "1-A, 2-B, 3-C.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-42',
    question: "Why did the '1937 Election' failure of the Muslim League lead to its \"Radicalization\"?",
    options: ["Jinnah decided to quit politics.", "The League realized that it could not win power through constitutional bargaining alone and needed to appeal to religious \"emotions\" (Cry of 'Islam in Danger') to win the Muslim masses.", "The British told Jinnah to become more radical.", "The Congress offered Jinnah the post of Prime Minister."],
    correctAnswer: 1,
    explanation: "Shift from elite bargaining to emotional mass-appeal.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-43',
    question: "The 'Wardha Scheme' and 'Vidya Mandir' education programs were used by communalists to argue that the Congress was:",
    options: ["Promoting science too much.", "Attempting to \"culturally colonize\" Muslims and impose Hindu symbols and rituals on Muslim children.", "Refusing to build schools.", "Secretly working for the British."],
    correctAnswer: 1,
    explanation: "Allegation of \"Cultural Colonization.\"",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-44',
    question: "What was the \"Veto\" given to the Muslim League by the 'August Offer' (1940)?",
    options: ["A veto over the British budget.", "An assurance that no future constitution would be imposed on India without the consent of the \"powerful elements\" (the League).", "The right to stop the war.", "The right to arrest Gandhi."],
    correctAnswer: 1,
    explanation: "Minority Veto over the future Constitution.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-45',
    question: "The 'RSS' (1925) and 'Hindu Mahasabha' (1915) were 'Mirror Images' of Muslim communalism because they:",
    options: ["Both wanted to join the British army.", "Both believed that the two communities were separate nations and that the Congress's secularism was a \"betrayal\" of their respective identities.", "Both supported Gandhi.", "Both were founded in London."],
    correctAnswer: 1,
    explanation: "Essentialist belief in \"Two Nations\" and rejection of secularism.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-46',
    question: "Consider the following regarding 'V.D. Savarkar\u2019s' view on the \"Two-Nation Theory\":",
    options: ["He was its greatest opponent.", "In his 1937 presidential address at the Hindu Mahasabha, he explicitly stated that \"India cannot be assumed today to be a unitarian and homogeneous nation, but on the contrary, there are two nations in the main: the Hindus and the Muslims.\"", "He wanted to merge India with Japan.", "He believed everyone in India was a Hindu by religion."],
    correctAnswer: 1,
    explanation: "Savarkar\u2019s early articulation of the two-nation reality.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-47',
    question: "Why did the 'Communist Party of India' (CPI) support the demand for Pakistan in 1942\u201344?",
    options: ["They were secret members of the League.", "They interpreted the demand as a \"Nationalist struggle of oppressed Muslim nationalities\" for self-determination, applying the Stalinist theory of nationalities to India.", "The British paid them to do so.", "They wanted to divide the Congress."],
    correctAnswer: 1,
    explanation: "Application of the Stalinist \"Theory of Nationalities.\"",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-48',
    question: "The 'Direct Action Day' (1946) represented the transition of communalism into which phase?",
    options: ["The Liberal phase.", "The \"Total War\" or \"Civil War\" phase, where political goals were to be achieved through street violence and communal terror.", "The Non-violence phase.", "The Administrative phase."],
    correctAnswer: 1,
    explanation: "The transition to communal civil war.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-49',
    question: "Consider the following regarding 'M.A. Jinnah\u2019s' 14 Points (1929):\n1. One-third representation for Muslims in the Central Legislature.\n2. Residuary powers to be vested in the Provinces.\n3. Separation of Sindh from Bombay. How many of the above were included in his demands?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-50',
    question: "The 'Crisis of 1947' is often analyzed as a \"Triangular\" conflict. Who were the three parties?",
    options: ["USA, USSR, and UK.", "British Imperialism, Indian Nationalism (Congress), and Communalism (League).", "Farmers, Workers, and Landlords.", "Hindus, Muslims, and Sikhs only."],
    correctAnswer: 1,
    explanation: "Imperialism, Nationalism, and Communalism.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-51',
    question: "Ultimately, 'Chapter 36' concludes that Communalism was NOT a \"legacy of the past,\" but a:",
    options: ["Modern phenomenon.", "Modern political ideology that utilized traditional religious identities to mobilize the masses for modern political power and resources.", "Natural outcome of religion.", "Result of the Mughal Empire."],
    correctAnswer: 1,
    explanation: "Modern ideology using traditional identity for modern power.",
    chapterId: 36,
    difficulty: 'Moderate'
  },
  {
    id: '36-52',
    question: "In the analytical history of Indian communalism, the \"Hunter Commission\" (1882) on education is significant because it:",
    options: ["Recommended the closure of madrasas.", "Formally acknowledged the \"backwardness\" of Muslims in modern education and recommended special scholarships and preference in government jobs to bridge the \"lag.\"", "Banned the study of Sanskrit.", "Suggested that only English-speakers could own land."],
    correctAnswer: 1,
    explanation: "Institutionalizing the \"Lag\" theory.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-53',
    question: "With reference to the 'United Indian Patriotic Association' (1888), which of the following best describes its structural purpose?",
    options: ["To demand the immediate withdrawal of the British.", "To create a \"loyalist\" front of the landed aristocracy (Hindu and Muslim) to convince the British that the Congress did not represent the \"true\" interests of the Indian people.", "To promote the Urdu language.", "To support the 1857 rebels."],
    correctAnswer: 1,
    explanation: "Loyalist-Aristocratic front against the Congress.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-54',
    question: "The 'Morley-Minto Reforms' (1909) are criticized for creating \"Constitutional Watertight Compartments.\" What does this signify?",
    options: ["It stopped the mixing of river waters.", "By creating separate electorates, it ensured that Hindu and Muslim leaders never had to seek the votes of the other community, thus preventing the growth of a \"composite\" political culture.", "It abolished the provincial legislatures.", "It restricted voting to the British only."],
    correctAnswer: 1,
    explanation: "Prevention of composite political culture.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-55',
    question: "Consider the following regarding the 'Lucknow Pact' (1916):\n1. It was the only time the Congress and the League officially agreed on a common constitutional scheme.\n2. The Congress conceded 'Weightage' to Muslims in provinces where they were a minority (like UP).\n3. The Pact successfully ended communalism in India for the next 30 years. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two (Statement 3 is incorrect; the pact was a temporary \"marriage of convenience\" that fell apart within a decade).",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-56',
    question: "The 'Delhi Proposals' (1927) are seen as a \"Lost Opportunity.\" What was the core trade-off Jinnah offered?",
    options: ["Giving up the demand for Sindh in exchange for Delhi.", "Giving up 'Separate Electorates' in favor of 'Joint Electorates' if the Congress accepted four demands (including 1/3rd representation at the center and the separation of Sindh).", "Moving the Muslim League headquarters to Calcutta.", "Joining the British Cabinet."],
    correctAnswer: 1,
    explanation: "Joint Electorates offer in exchange for specific safeguards.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-57',
    question: "Why did the 'Nehru Report' (1928) fail to satisfy the \"Liberal Communalists\" like Jinnah and Malaviya?",
    options: ["It was too radical on socialism.", "It tried to strike a balance that satisfied neither: it rejected separate electorates (annoying the League) and proposed the separation of Sindh (annoying the Hindu Mahasabha).", "It didn't mention 'Purna Swaraj'.", "It was written in a language they didn't understand."],
    correctAnswer: 1,
    explanation: "Failed balancing act between communal demands.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-58',
    question: "The 'Communal Award' (1932) is described as the \"Final Logical Extension\" of the Minto-MacDonald policy. Why?",
    options: ["Because it gave everyone a prize.", "It extended the principle of \"Separate Representation\" to almost every segment of Indian society\u2014Muslims, Sikhs, Christians, Anglo-Indians, and even the Depressed Classes.", "It abolished all elections.", "It made Jinnah the permanent President of India."],
    correctAnswer: 1,
    explanation: "Universalizing fragmentation via representation.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-59',
    question: "Regarding the 'Two-Nation Theory', consider the following: Statement-I: In 1930, Muhammad Iqbal proposed a \"consolidated North-West Indian Muslim State\" but viewed it as a \"Final Settlement\" within a larger Indian federation. Statement-II: By 1940, Jinnah transformed this into a demand for \"Complete Sovereignty,\" rejecting any federal link with a Hindu-majority center. Which one is correct?",
    options: ["Both are correct and show the transition from \"Autonomy\" to \"Sovereignty.\"", "Statement-I is false.", "Statement-II is false.", "Both are incorrect."],
    correctAnswer: 0,
    explanation: "Both are correct.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-60',
    question: "The 'Pirpur Report' (1938) utilized a \"New Narrative\" of victimization. What was its main sociological claim?",
    options: ["That Muslims were getting richer.", "That under \"Congress Raj,\" a \"Hindu-Fascist\" culture was being imposed through schools, symbols (Wardha scheme), and the suppression of the Urdu language.", "That the British were leaving India to Jinnah.", "That all Muslims should become farmers."],
    correctAnswer: 1,
    explanation: "Cultural suppression and \"Hindu-Fascist\" allegations.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-61',
    question: "Why did the 'Muslim League's' demand for Pakistan find support among the 'Muslim Professional Middle Class' (Salariat)?",
    options: ["Because they wanted to travel.", "They feared that in a \"United India\" with merit-based competition, they would be \"swamped\" by the numerically stronger and more educationally advanced Hindu middle class.", "Because Jinnah promised them free land.", "Because the British gave them more money in 1940."],
    correctAnswer: 1,
    explanation: "Fear of professional displacement in a meritocratic united India.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-62',
    question: "The 'August Offer' (1940) is called the \"Great Charter of Communalism.\" Why?",
    options: ["Because it gave Pakistan immediately.", "It gave the Muslim League a \"Veto\" over any future constitution by stating that no power would be transferred to a system whose authority was denied by large sections of India.", "It banned the Congress party.", "It made Urdu the only official language."],
    correctAnswer: 1,
    explanation: "Granting the \"Minority Veto.\"",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-63',
    question: "What was the \"Hostage Theory\" used by some communalists in the 1940s?",
    options: ["Taking British officers as prisoners.", "The idea that the presence of a \"Hindu Minority\" in Pakistan would act as a \"Hostage\" to ensure the fair treatment of the \"Muslim Minority\" in India, and vice versa.", "A theory about banking.", "A plan to kidnap the Viceroy."],
    correctAnswer: 1,
    explanation: "Minority-Hostage exchange logic.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-64',
    question: "In 1944, 'Gandhi-Jinnah' talks were held based on the 'C.R. Formula'. Why did Jinnah reject it?",
    options: ["Because Gandhi was late.", "He called it a \"maimed, mutilated, and moth-eaten\" Pakistan because it proposed partitioning Punjab and Bengal based on non-Muslim majority areas.", "He wanted the British to stay as the third party.", "He wanted to include the whole of South India in Pakistan."],
    correctAnswer: 1,
    explanation: "Rejection of partitioned provinces.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-65',
    question: "The 'Desai-Liaquat Pact' (1945) proposed an Interim Government with \"Parity.\" What did parity mean here?",
    options: ["Equal number of men and women.", "Equal number of nominees from the Congress and the Muslim League in the Central Executive, effectively treating the League as an equal to the Congress.", "Parity between India and Britain.", "Parity between the Army and the Navy."],
    correctAnswer: 1,
    explanation: "Parity between the Congress and the League.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-66',
    question: "Match the following 'Communal Organizations' with their 'Core Ideology':\n1. Muslim League (Post-1940) \u2014",
    options: ["Separate sovereign state (Pakistan) 2. Hindu Mahasabha (Savarkar) \u2014", "Hindu Rashtra (India as a Hindu Nation) 3. Akali Dal (Tara Singh) \u2014", "Azad Punjab / Sikh Rights Select the correct matching code:", "1-A, 2-B, 3-C"],
    correctAnswer: 0,
    explanation: "1-A, 2-B, 3-C.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-67',
    question: "The 'Wavell Plan' (1945) failed at the Simla Conference because of the \"Exclusive Representation\" claim. Who made this claim?",
    options: ["The British.", "Jinnah, who insisted that the League must nominate all Muslim members, thus denying the Congress the right to nominate even its own President (Maulana Azad).", "Mahatma Gandhi.", "The Communist Party."],
    correctAnswer: 1,
    explanation: "Jinnah's claim to be the \"Sole Spokesman\" of Muslims.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-68',
    question: "The 'Cabinet Mission' (1946) rejected Pakistan on which \"Technical\" ground?",
    options: ["They didn't like Jinnah.", "The creation of two separate Pakistans (East and West) would leave massive minorities in both India and Pakistan, solving nothing while destroying communications and defense.", "The USA was against it.", "The British wanted to stay for another 100 years."],
    correctAnswer: 1,
    explanation: "Geographical/Logistical unviability and minority problem.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-69',
    question: "Consider the following regarding the '1945\u201346 Elections':\n1. The Congress won the \"General\" seats but the League won 30/30 Muslim seats in the Central Assembly. 2. The elections proved that there was no \"Middle Ground\" left in Indian politics. 3. The elections were fought on the single issue of 'Pakistan' by the League. How many of the above are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-70',
    question: "The 'Direct Action' (1946) resulted in the \"Great Calcutta Killings.\" How did this change the \"Psychology of the British\"?",
    options: ["They decided to stay longer to keep peace.", "They realized that a \"Civil War\" was imminent and that their only options were \"Repression\" (which they couldn't afford) or \"Immediate Exit\" (Transfer of Power).", "They blamed the USA.", "They abolished the Muslim League."],
    correctAnswer: 1,
    explanation: "Imminent civil war forcing immediate exit.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-71',
    question: "Why did 'Jawaharlal Nehru's' statement in July 1946 about the \"Sovereignty of the Constituent Assembly\" lead to the League's withdrawal from the Cabinet Mission Plan?",
    options: ["Nehru said Jinnah was not allowed.", "Jinnah feared that the Congress, using its majority in the Assembly, would scrap the \"Compulsory Grouping\" (the basis of 'Pakistan in embryo').", "Nehru said the British must stay.", "It was a secret plan to join the USSR."],
    correctAnswer: 1,
    explanation: "Fear of Congress scrapping \"Grouping.\"",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-72',
    question: "The 'Mountbatten Plan' (1947) conceded Pakistan but with the \"Radcliffe Partition.\" This was Jinnah's \"Moth-eaten\" nightmare becoming reality because:",
    options: ["He got no land.", "He got Pakistan, but with a \"Cripple\" Punjab and Bengal, partitioned right through their cultural and economic hearts.", "He had to pay the British.", "The British took all the oil."],
    correctAnswer: 1,
    explanation: "Partitioned provinces.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-73',
    question: "In the context of 1947, what was the \"Plan Balkan\"?",
    options: ["A plan to build more railways.", "A British proposal to transfer power to individual provinces, allowing each to choose its own fate (leading to a fragmented India).", "A plan to join the UN.", "A trade deal with Russia."],
    correctAnswer: 1,
    explanation: "Fragmented transfer of power (thwarted by Nehru).",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-74',
    question: "The 'Boundary Commission' was criticized for being \"Map-based, not Ground-based.\" Why?",
    options: ["They used only satellite images.", "The demarcation was done in a room in Delhi by a man (Radcliffe) who had never seen the terrain, leading to villages being split and families separated.", "They didn't have a map.", "They used only the stars to guide them."],
    correctAnswer: 1,
    explanation: "Demarcation without field knowledge.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-75',
    question: "'V.P. Menon' is significant because he convinced the Congress to accept 'Dominion Status' in 1947. What was the \"Strategic Benefit\"?",
    options: ["They liked the British King.", "It ensured an \"Immediate and Orderly\" transfer of power, preventing a total administrative collapse during the partition riots.", "Jinnah agreed to join India.", "The British promised to give back all the gold."],
    correctAnswer: 1,
    explanation: "Immediate/Orderly transfer and administrative continuity.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-76',
    question: "'Sardar Patel' is called the \"Iron Man of India\" for his role in the 1947\u201348 period. His main success was:",
    options: ["Winning the 1942 movement.", "The \"Integration of Princely States,\" preventing the \"Balkanization\" of India by integrating over 560 states.", "Leading the RIN Mutiny.", "Writing the Constitution."],
    correctAnswer: 1,
    explanation: "Integration of Princely States.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-77',
    question: "Why did the 'Muslim League' refuse to join the Constituent Assembly even after joining the Interim Government in 1946?",
    options: ["They were not given seats.", "They joined the government only to \"Sabotage\" it from within and prove that Hindus and Muslims could not work together.", "They were afraid of Nehru.", "The British told them not to join."],
    correctAnswer: 1,
    explanation: "Strategic sabotage of joint governance.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-78',
    question: "The 'Independence Act of 1947' was a \"Surrender\" of British Imperialism. Which clause signaled the finality of this surrender?",
    options: ["The King would remain the head.", "The \"Lapse of Paramountcy\" over Princely States and the total withdrawal of British control over the two new dominions.", "The British army would stay as advisors.", "The British would keep the Indian treasury."],
    correctAnswer: 1,
    explanation: "Lapse of Paramountcy and withdrawal of control.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-79',
    question: "Ultimately, 'Chapter 36' analyzes 'Communalism' not as a religious issue, but as a 'Modern Politics' issue. What was its ultimate \"Success\"?",
    options: ["The establishment of a religious empire.", "The successful mobilization of the masses based on identity to secure political sovereignty and a separate state.", "The end of all religions.", "The return of the British."],
    correctAnswer: 1,
    explanation: "Identity-based mass mobilization for sovereignty.",
    chapterId: 36,
    difficulty: 'Hard'
  },
  {
    id: '36-80',
    question: "'Mahatma Gandhi's' final fast in January 1948 was for:",
    options: ["His own health.", "To restore communal harmony in Delhi and to pressure the Indian government to pay Pakistan its fair share of assets (\u20b955 crore).", "To stop the British from leaving.", "To become the President."],
    correctAnswer: 1,
    explanation: "Harmony and asset payment to Pakistan.",
    chapterId: 36,
    difficulty: 'Hard'
  },
];
