# Import all the models, so that Base has them before being
# imported by Alembic
from app.db.session import Base  # noqa
from app.models.student_progress import QuizResult
from app.models.batch1 import Batch1Segment  # noqa
from app.models.ai_coaching import CoachingSession  # noqa
print("DEBUG: Importing models in base.py")
from app.models import (
    achievement,
    activity_log,
    admin_log,
    affiliate,
    ai_avatar,
    ai_conversation,
    ai_features,
    flashcard,
    analytics,
    announcement,
    asset,
    assignment,
    blockchain,
    bundle,
    cart,
    category,
    certificate,
    certificate_template,
    challenge,
    chat,
    chatbot,
    coin_transaction,
    collaborative_project,
    coupon,
    course,
    course_payment,
    course_review,
    digital_product,
    direct_message,
    discussion,
    email_notification,
    enquiry,
    enrollment,
    exam,
    friendship,
    graphotherapy,
    group,
    invoice,
    learning_group,
    learning_path,
    lesson,
    lesson_drip,
    lesson_progress,
    live_class,
    live_class_interactive,
    marketplace,
    meditation,
    module,
    mood,
    notification,
    order,
    payment_method,
    peer_review,
    permissions,
    question_bank,
    quiz,
    recommendations,
    reward,
    shadow_mode,
    # print("DEBUG: Importing sso"),
    sso,
    student_notes,
    study_group,
    study_room,
    submission,
    subscription,
    task,
    tax,
    translation,
    two_factor,
    upsc,
    user,
    daily_action,
    drill,
    ai_debug_logs,
    lead,
    user_management,
    marketing_automation,
    retention,
    field_activity,
    voice_note,
    call_log,
    ras_planner,
    study_session,
)
print("DEBUG: Models imported in base.py")
