"""add_adaptive_models

Revision ID: 575d9bd6123e
Revises: 9b18277e8f32
Create Date: 2026-01-18 18:13:30.406462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575d9bd6123e'
down_revision: Union[str, Sequence[str], None] = '9b18277e8f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('granularity_type', sa.Enum('SUBJECT', 'TOPIC', 'NANO_POINT', name='granularitytype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_dependencies',
    sa.Column('parent_concept_id', sa.String(36), nullable=False),
    sa.Column('child_concept_id', sa.String(36), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['child_concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['parent_concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('parent_concept_id', 'child_concept_id')
    )
    op.create_table('interaction_logs',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('associated_concept_id', sa.String(36), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_taken_ms', sa.Integer(), nullable=True),
    sa.Column('hesitation_detected', sa.Boolean(), nullable=True),
    sa.Column('backspaces_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['associated_concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_logs_user_id'), 'interaction_logs', ['user_id'], unique=False)
    op.create_table('student_mastery',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(36), nullable=False),
    sa.Column('mastery_probability', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('RED', 'YELLOW', 'GREEN', name='masterystatus'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('last_assessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'concept_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_mastery')
    op.drop_index(op.f('ix_interaction_logs_user_id'), table_name='interaction_logs')
    op.drop_table('interaction_logs')
    op.drop_table('concept_dependencies')
    op.drop_table('concepts')
    # ### end Alembic commands ###
