// Auto-generated by Antigravity Script
import { Question } from '../../../../types';

export const MODERN_CHAPTER_13_MCQS: any[] = [
  {
    id: '12-56',
    question: "The 'Ghadarites' failed to achieve their objective of a 1915 uprising primarily because: 1. Their plan was leaked by a traitor (Kripal Singh) within their ranks. 2. They had no support from any international powers like Germany or Turkey. 3. The British government effectively used the 'Defence of India Act' to arrest the key leaders before the date of the revolt. Select the correct answer using the code given below:",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "All of the above"],
    correctAnswer: 2,
    explanation: "1 and 3 only Statement 2 is incorrect; they did have support from Germany (the Zimmermann Plan) and parts of the Ottoman Empire.",
    chapterId: 12,
    difficulty: 'Hard'
  },
  {
    id: '13-2',
    question: "When the First World War broke out in 1914, what was the initial reaction of the Moderates in the Congress?",
    options: ["To launch an immediate revolt against the British.", "To support the British war effort as a matter of duty.", "To seek help from Germany for independence.", "To go on a permanent strike."],
    correctAnswer: 1,
    explanation: "To support the British war effort as a matter of duty.",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-3',
    question: "Which leader was released from Mandalay Jail in June 1914, just before the start of the Home Rule movement?",
    options: ["Lala Lajpat Rai", "Bal Gangadhar Tilak", "Aurobindo Ghosh", "Bipin Chandra Pal"],
    correctAnswer: 1,
    explanation: "Bal Gangadhar Tilak",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-4',
    question: "The Home Rule League movement in India was inspired by a similar movement in:",
    options: ["South Africa", "Ireland", "United States", "Russia"],
    correctAnswer: 1,
    explanation: "Ireland",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-5',
    question: "Who were the two main leaders who started the Home Rule Leagues in India?",
    options: ["Mahatma Gandhi and Jawaharlal Nehru", "Bal Gangadhar Tilak and Annie Besant", "Motilal Nehru and C.R. Das", "Dadabhai Naoroji and G.K. Gokhale"],
    correctAnswer: 1,
    explanation: "Bal Gangadhar Tilak and Annie Besant",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-6',
    question: "Tilak set up his Home Rule League in April 1916 at:",
    options: ["Bombay", "Belgaum", "Poona", "Madras"],
    correctAnswer: 1,
    explanation: "Belgaum",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-7',
    question: "Annie Besant\u2019s Home Rule League was formally started in September 1916 at:",
    options: ["Calcutta", "Adyar (Madras)", "Bombay", "Allahabad"],
    correctAnswer: 1,
    explanation: "Adyar (Madras)",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-8',
    question: "Tilak\u2019s League was restricted to which of the following regions?",
    options: ["All of India except Maharashtra", "Maharashtra (excluding Bombay city), Karnataka, Central Provinces, and Berar", "Only the Madras Presidency", "Only the United Provinces"],
    correctAnswer: 1,
    explanation: "Maharashtra (excluding Bombay), Karnataka, Central Provinces, and Berar",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-9',
    question: "Which of the following journals was started by Annie Besant to propagate her ideas?",
    options: ["Kesari and Mahratta", "New India and Commonweal", "Young India", "Harijan"],
    correctAnswer: 1,
    explanation: "New India and Commonweal",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-10',
    question: "Which journals were used by Tilak to support the Home Rule cause?",
    options: ["New India and Commonweal", "Kesari and Mahratta", "Al-Hilal", "Comrade"],
    correctAnswer: 1,
    explanation: "Kesari and Mahratta",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-11',
    question: "Who was the General Secretary of Annie Besant\u2019s Home Rule League?",
    options: ["George Arundale", "B.P. Wadia", "C.P. Ramaswami Aiyar", "All of the above (as key organizers)"],
    correctAnswer: 0,
    explanation: "George Arundale",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-12',
    question: "The Lucknow Session of the Congress (1916) is famous for the 'Lucknow Pact' between the Congress and:",
    options: ["The British Government", "The Muslim League", "The Ghadar Party", "The Justice Party"],
    correctAnswer: 1,
    explanation: "The Muslim League",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-13',
    question: "Who presided over the historic Lucknow Session of 1816?",
    options: ["Annie Besant", "Ambica Charan Mazumdar", "Motilal Nehru", "Rashbehari Ghosh"],
    correctAnswer: 1,
    explanation: "Ambica Charan Mazumdar",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-14',
    question: "In which session did the Moderates and Extremists formally reunite after the 1907 split?",
    options: ["1915 Bombay Session", "1916 Lucknow Session", "1917 Calcutta Session", "1918 Delhi Session"],
    correctAnswer: 1,
    explanation: "1916 Lucknow Session",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-15',
    question: "The \"August Declaration\" of 1917, which promised the gradual development of self-governing institutions, was made by:",
    options: ["Lord Curzon", "Edwin Montagu", "Lord Chelmsford", "Lord Morley"],
    correctAnswer: 1,
    explanation: "Edwin Montagu (Secretary of State for India)",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-16',
    question: "Who renounced his knighthood in protest against the arrest of Annie Besant in 1917?",
    options: ["Rabindranath Tagore", "S. Subramania Aiyar", "Mahatma Gandhi", "Jawaharlal Nehru"],
    correctAnswer: 1,
    explanation: "S. Subramania Aiyar",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-17',
    question: "Which prominent leader joined Annie Besant\u2019s League in Allahabad?",
    options: ["Sardar Patel", "Jawaharlal Nehru", "Muhammad Ali Jinnah", "Both B and C"],
    correctAnswer: 3,
    explanation: "Both B and C",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-18',
    question: "The Home Rule movement primarily demanded:",
    options: ["Purna Swaraj (Complete Independence)", "Home Rule (Self-government) for India within the British Empire", "The restoration of the Mughal Caliphate", "The complete withdrawal of British troops"],
    correctAnswer: 1,
    explanation: "Home Rule (Self-government) within the British Empire",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-19',
    question: "Tilak was defended in a sedition case in 1916 by a legal team led by:",
    options: ["Motilal Nehru", "Muhammad Ali Jinnah", "Bhulabhai Desai", "Tej Bahadur Sapru"],
    correctAnswer: 1,
    explanation: "Muhammad Ali Jinnah",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-20',
    question: "Annie Besant was the President of the Theosophical Society. Where was its headquarters?",
    options: ["Banaras", "Adyar", "Bombay", "London"],
    correctAnswer: 1,
    explanation: "Adyar",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-21',
    question: "Why did the Home Rule movement decline by 1919?",
    options: ["Lack of an effective organization", "Annie Besant\u2019s wavering attitude after her release", "Tilak\u2019s departure to England for a libel case", "All of the above"],
    correctAnswer: 3,
    explanation: "All of the above",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-22',
    question: "The Lucknow Pact (1916) saw the Congress accept which controversial demand of the Muslim League?",
    options: ["Separate Electorates", "Partition of Bengal", "Complete Independence", "Withdrawal of Urdu as an official language"],
    correctAnswer: 0,
    explanation: "Separate Electorates",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-23',
    question: "Who were the main architects of the Lucknow Pact?",
    options: ["Gandhi and Nehru", "Tilak and Jinnah", "Gokhale and Pherozeshah Mehta", "Annie Besant and Curzon"],
    correctAnswer: 1,
    explanation: "Tilak and Jinnah",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-24',
    question: "Which event in 1914 acted as a catalyst for Indian nationalism by highlighting racial discrimination against Indians abroad?",
    options: ["The Boer War", "The Komagata Maru Incident", "The Jallianwala Bagh Massacre", "The Rowlatt Act"],
    correctAnswer: 1,
    explanation: "The Komagata Maru Incident",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-25',
    question: "In the August Declaration of 1917, the British government for the first time used which term to define the goal of British rule in India?",
    options: ["Independence", "Responsible Government", "Purna Swaraj", "Dominion Status"],
    correctAnswer: 1,
    explanation: "Responsible Government",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-26',
    question: "Who was the Viceroy of India during the peak of the Home Rule movement (1916)?",
    options: ["Lord Hardinge", "Lord Chelmsford", "Lord Reading", "Lord Irwin"],
    correctAnswer: 1,
    explanation: "Lord Chelmsford",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-27',
    question: "Annie Besant became the first woman President of the Indian National Congress in which session?",
    options: ["1916 Lucknow", "1917 Calcutta", "1918 Delhi", "1925 Kanpur"],
    correctAnswer: 1,
    explanation: "1917 Calcutta",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-28',
    question: "The Montagu-Chelmsford Reforms (1919) were a direct result of which declaration?",
    options: ["Queen\u2019s Proclamation 1858", "August Declaration 1917", "Delhi Declaration 1911", "Nehru Report 1928"],
    correctAnswer: 1,
    explanation: "August Declaration 1917",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-29',
    question: "Which Moderate leader died in 1915, easing the way for the Extremists to rejoin the Congress?",
    options: ["Dadabhai Naoroji", "Gopal Krishna Gokhale", "Pherozeshah Mehta", "Both B and C"],
    correctAnswer: 3,
    explanation: "Both B and C",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-30',
    question: "Tilak's Home Rule League had how many branches?",
    options: ["6", "200", "50", "100"],
    correctAnswer: 0,
    explanation: "6 (It was more compact and organized than Besant's)",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-31',
    question: "The \"Commonweal\" was a:",
    options: ["Secret revolutionary society", "Weekly journal started by Annie Besant", "Pro-British political party", "Treaty signed between Tilak and Jinnah"],
    correctAnswer: 1,
    explanation: "Weekly journal started by Annie Besant",
    chapterId: 13,
    difficulty: 'Easy'
  },
  {
    id: '13-32',
    question: "The Home Rule League movement represented a new phase in the Indian national struggle. How did it differ fundamentally from the earlier Swadeshi Movement?",
    options: ["It relied exclusively on the support of the Indian peasantry.", "It focused on the demand for 'Self-Government' as a permanent political goal rather than just a reaction to a specific administrative measure like the Partition of Bengal.", "It completely rejected the use of the English language.", "It was the first movement to demand the total expulsion of all Europeans from India."],
    correctAnswer: 1,
    explanation: "It focused on 'Self-Government' as a permanent goal.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-33',
    question: "Consider the following statements regarding the organizational structure of the Home Rule Leagues: 1. Tilak\u2019s League was organized on a linguistic basis and was more compact compared to Annie Besant\u2019s League. 2. Annie Besant\u2019s League was loosely organized and covered the parts of India not covered by Tilak\u2019s League. 3. Both leaders merged their leagues into a single unified organization in 1917 to ensure better coordination. Which of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2, and 3"],
    correctAnswer: 0,
    explanation: "1 and 2 only Statement 3 is incorrect. Tilak and Besant chose not to merge their leagues because, as Tilak noted, some of his followers did not like Besant and vice versa; however, they worked in close cooperation.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-34',
    question: "The 'Lucknow Pact' (1916) is often described as a double-edged sword in Indian history. Why is it criticized by many modern historians?",
    options: ["Because it led to the permanent dissolution of the Muslim League.", "Because, by accepting 'Separate Electorates', the Congress provided official recognition to the principle of communal politics, which eventually contributed to the partition of India.", "Because it demanded the continuation of British rule for another 100 years.", "Because it excluded the Extremists from the Congress."],
    correctAnswer: 1,
    explanation: "It provided official recognition to communal politics.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-35',
    question: "With reference to the 'August Declaration' of 1917, consider the following: Statement-I: It was a response to the growing strength of the Home Rule movement and the revolutionary activities during the war. Statement-II: The declaration for the first time made 'Responsible Government' the official goal of British policy in India, although it did not specify a timeframe. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 1,
    explanation: "Both Statement-I and Statement-II are correct.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-36',
    question: "Annie Besant\u2019s arrest in June 1917 proved to be a turning point for the movement. How did the 'Moderates' react to her arrest?",
    options: ["They celebrated it as a victory for British law.", "They were pushed into active protest, with many moderate leaders like Jawaharlal Nehru and B.P. Wadia joining the Home Rule League in solidarity.", "They immediately called for an armed revolution.", "They resigned from the Congress in protest against Besant."],
    correctAnswer: 1,
    explanation: "They were pushed into active protest and joined the League.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-37',
    question: "What was the primary reason for the 'reunion' of the Moderates and Extremists at the 1916 Lucknow session?",
    options: ["The death of moderate giants like Gokhale and Pherozeshah Mehta, who had earlier blocked the return of the Extremists.", "A direct order from the British Queen.", "The Extremists agreed to give up their demand for Swaraj.", "The Moderates agreed to use the method of bomb-making."],
    correctAnswer: 0,
    explanation: "The death of Gokhale and Pherozeshah Mehta.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-38',
    question: "Consider the following regarding the social base of the Home Rule Movement: 1. It saw significant participation from the urban educated middle class and professional groups. 2. It gained substantial traction among the students who acted as messengers for the league. 3. The Anglo-Indians, most Muslims, and non-Brahmins from South India largely stayed away, fearing it would lead to 'Brahmin Raj'. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-39',
    question: "The 'Ghadar' revolutionaries and the 'Home Rule' leagues represented two different responses to the First World War. What was the common ground between them?",
    options: ["Both believed in non-violent constitutional methods.", "Both shared the objective of achieving Indian independence/self-rule by exploiting the 'opportunity' provided by Britain's involvement in the war.", "Both were led by Annie Besant.", "Both were founded in San Francisco."],
    correctAnswer: 1,
    explanation: "Both aimed to exploit the war for Indian interests.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-40',
    question: "Which of the following describes Tilak\u2019s attitude toward the British during the First World War?",
    options: ["He called for a total boycott of the British army.", "He advocated for 'Responsive Cooperation', meaning India would help the British in the war effort if the British promised self-government in return.", "He became a secret advisor to the German Kaiser.", "He retired to the Himalayas to avoid the war."],
    correctAnswer: 1,
    explanation: "He advocated for 'Responsive Cooperation'.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-41',
    question: "The 'Montagu-Chelmsford Reforms' (1919) disappointed many Home Rule supporters because:",
    options: ["They abolished the Indian National Congress.", "They introduced 'Diarchy' at the center instead of the provinces.", "They failed to grant the 'Responsible Government' promised in the 1817 Declaration and kept most powers in the hands of the British bureaucracy.", "They made Annie Besant the Empress of India."],
    correctAnswer: 2,
    explanation: "They failed to grant real 'Responsible Government'.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-42',
    question: "Why did the Home Rule Movement fail to maintain its momentum after 1918?",
    options: ["The Moderates were pacified by the 1917 Declaration and the 1919 Reforms.", "There was no single unified leader, as Besant wavered and Tilak went to London to fight a court case against Valentine Chirol.", "The rise of Mahatma Gandhi provided a new, more effective method of mass struggle (Satyagraha).", "All of the above."],
    correctAnswer: 3,
    explanation: "All of the above.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-43',
    question: "Consider the following pairs of leaders and their roles in the Home Rule era: 1. George Arundale \u2014 Organizing secretary of Besant\u2019s League. 2. S. Subramania Aiyar \u2014 Renounced knighthood after Besant's arrest. 3. Joseph Baptista \u2014 First President of Tilak\u2019s League. How many of the above pairs are correctly matched?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-44',
    question: "The Lucknow Pact (1916) included a proposal for 'Weighted Representation'. What did this mean?",
    options: ["Every Indian would be given a weight based on their education.", "Muslims were given more seats in the legislative councils than their population percentage in provinces where they were in a minority (like UP).", "Only the heavy-weight wrestlers could vote.", "The British government\u2019s vote carried more weight than the Indian vote."],
    correctAnswer: 1,
    explanation: "Muslims were given more seats in minority provinces.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-45',
    question: "Annie Besant\u2019s entry into Indian politics was significant because she brought which of the following to the national movement?",
    options: ["An international perspective and a highly organized propaganda machine based on the Irish model.", "A secret supply of Irish weapons.", "The support of the Pope.", "A plan to convert all Indians to Theosophy."],
    correctAnswer: 0,
    explanation: "International perspective and organized propaganda machine.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-46',
    question: "Ultimately, the Home Rule Movement was a landmark because it:",
    options: ["Won complete independence for India in 1919.", "Created a generation of political workers and a nationwide network that prepared the ground for the mass movements of the Gandhian era.", "Abolished the separate electorates.", "Led to the victory of Germany in WWI."],
    correctAnswer: 1,
    explanation: "Prepared the ground for the Gandhian era.",
    chapterId: 13,
    difficulty: 'Moderate'
  },
  {
    id: '13-47',
    question: "Consider the following statements regarding the Home Rule League Movement (1916-1918): 1. Tilak\u2019s League was first to be established and its headquarters were located at Poona. 2. The movement aimed at the overthrow of the British Crown and the establishment of an independent Indian Republic. 3. While the Moderates initially stayed away, the arrest of Annie Besant in 1917 forced many of them to join the League. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 3 are correct. Statement 2 is incorrect; the Home Rule movement did not aim for an independent Republic. It demanded 'Self-Government' or 'Home Rule' within the British Empire, similar to the status enjoyed by Canada and Australia.",
    chapterId: 13,
    difficulty: 'Hard'
  },
  {
    id: '13-48',
    question: "With reference to the 'Lucknow Pact' (1916), consider the following: Statement-I: The Congress agreed to the Muslim League's demand for Separate Electorates in the provincial legislative elections. Statement-II: The Congress and the Muslim League presented a joint demand to the British government for a 'Responsible Government' and a fixed timeframe for self-rule. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 1,
    explanation: "Both Statement-I and Statement-II are correct Both are factually true. However, agreeing to Separate Electorates (Statement-I) was a concession to achieve the political unity required to present the joint demands (Statement-II), not the other way around.",
    chapterId: 13,
    difficulty: 'Hard'
  },
  {
    id: '13-49',
    question: "Arrange the following events of the First World War era in the correct chronological order: 1. Death of Pherozeshah Mehta. 2. The August Declaration (Montagu\u2019s Statement). 3. The Lucknow Session of the INC. 4. Formation of Tilak\u2019s Home Rule League. Select the correct answer using the code given below:",
    options: ["1 \u2014 4 \u2014 3 \u2014 2", "1 \u2014 3 \u2014 4 \u2014 2", "4 \u2014 1 \u2014 2 \u2014 3", "1 \u2014 4 \u2014 2 \u2014 3"],
    correctAnswer: 0,
    explanation: "1 \u2014 4 \u2014 3 \u2014 2 Death of Mehta (Nov 1915) -> Tilak\u2019s League (April 1916) -> Lucknow Session (Dec 1916) -> August Declaration (Aug 1917).",
    chapterId: 13,
    difficulty: 'Hard'
  },
  {
    id: '13-50',
    question: "Consider the following pairs of Leaders and the Journals they used for the Home Rule campaign: 1. Annie Besant \u2014 Commonweal 2. Bal Gangadhar Tilak \u2014 The Mahratta 3. S. Subramania Aiyar \u2014 New India How many of the above pairs are correctly matched?",
    options: ["Only one pair", "Only two pairs", "All three pairs", "None"],
    correctAnswer: 1,
    explanation: "Only two pairs Pairs 1 and 2 are correct. Pair 3 is incorrect; New India was also started and edited by Annie Besant. S. Subramania Aiyar was a prominent supporter and former judge who renounced his knighthood.",
    chapterId: 13,
    difficulty: 'Hard'
  },
  {
    id: '13-51',
    question: "The 'August Declaration' (1917) by Edwin Montagu is significant because: 1. It for the first time officially defined 'Responsible Government' as the goal of British rule in India. 2. It was a direct response to the pressure created by the Home Rule Leagues. 3. It granted universal adult franchise to all Indian citizens. Select the correct answer using the code given below:",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "All of the above"],
    correctAnswer: 0,
    explanation: "1 and 2 only Statement 3 is incorrect; the declaration and the subsequent 1919 Act provided a very limited franchise based on property and education.",
    chapterId: 13,
    difficulty: 'Hard'
  },
  {
    id: '13-52',
    question: "\"He was a former president of the Congress who was nominated as a member of the British Parliament's House of Commons. He was also the first Indian to provide a statistical proof of the economic drain of India.\" The above description refers to:",
    options: ["Gopal Krishna Gokhale", "Dadabhai Naoroji", "Pherozeshah Mehta", "Dinshaw Wacha"],
    correctAnswer: 1,
    explanation: "Dadabhai Naoroji",
    chapterId: 13,
    difficulty: 'Hard'
  },
  {
    id: '13-53',
    question: "Regarding the decline of the Home Rule Movement by 1919, consider the following: Statement-I: The movement lost its momentum because the British government effectively used the 'policy of the carrot and the stick'. Statement-II: The 'carrot' was the August Declaration of 1917, while the 'stick' was the Rowlatt Act. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 0,
    explanation: "Both Statement-I and Statement-II are correct",
    chapterId: 13,
    difficulty: 'Hard'
  },
  {
    id: '13-54',
    question: "Match the following regions with the respective Home Rule League influence: 1. Karnataka \u2014",
    options: ["Annie Besant\u2019s League 2. United Provinces \u2014", "Tilak\u2019s League 3. Bihar \u2014", "No League activity 4. Central Provinces \u2014", "Both Leagues active (shared) Select the correct matching code (Note: Tilak had specific jurisdictions):"],
    correctAnswer: 0,
    explanation: "1-B, 2-A, 3-A, 4-B Tilak\u2019s League was restricted to Maharashtra (excluding Bombay), Karnataka, Central Provinces, and Berar. The rest of India was under Besant\u2019s League.",
    chapterId: 13,
    difficulty: 'Hard'
  },
  {
    id: '13-55',
    question: "Consider the following regarding the 'Lucknow Session' (1916): 1. It saw the return of the Extremists to the Congress after nine years. 2. It was the first session where the Congress and the Muslim League met simultaneously and approved the 'Lucknow Pact'. 3. It was presided over by Annie Besant. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 2 are correct. Statement 3 is incorrect; the session was presided over by Ambica Charan Mazumdar. Annie Besant presided over the 1917 Calcutta session.",
    chapterId: 13,
    difficulty: 'Hard'
  },
];