// Auto-generated by Antigravity Script
import { Question } from '../../../../types';

export const MODERN_CHAPTER_29_MCQS: any[] = [
  {
    id: '28-91',
    question: "Ultimately, 'Social Reform' (Chapter 28) was the 'Moral Laboratory' of the Indian National Movement because:",
    options: ["It tested new medicines.", "It was here that the ideals of 'Equality', 'Liberty', and 'Fraternity' were first applied to the internal structures of Indian society before they were demanded from the colonial state.", "It was where the Congress flag was designed.", "It was funded by the US."],
    correctAnswer: 1,
    explanation: "Ideals of Liberty/Equality first applied internally.",
    chapterId: 28,
    difficulty: 'Hard'
  },
  {
    id: '29-2',
    question: "Who was the first to organize a movement specifically for the \"untouchables\" in Maharashtra and founded the 'Anarya Dosh-Parihar Samaj' (1888)?",
    options: ["Jyotiba Phule", "Gopal Baba Walangkar", "B.R. Ambedkar", "Jagjivan Ram"],
    correctAnswer: 1,
    explanation: "Gopal Baba Walangkar",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-3',
    question: "The 'Satyashodhak Samaj' (1873) was primarily dedicated to the social and educational upliftment of:",
    options: ["Brahmins", "Shudras and Ati-Shudras", "British Officers", "Merchants"],
    correctAnswer: 1,
    explanation: "Shudras and Ati-Shudras",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-4',
    question: "Which leader led the 'Mahad Satyagraha' in 1927 to assert the right of untouchables to use water from the Chawdar Tank?",
    options: ["Mahatma Gandhi", "Dr. B.R. Ambedkar", "Jyotiba Phule", "Periyar"],
    correctAnswer: 1,
    explanation: "Dr. B.R. Ambedkar",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-5',
    question: "The 'Self-Respect Movement' (Suyamariyathai Iyakkam) was founded in 1925 by:",
    options: ["C.N. Annadurai", "E.V. Ramaswamy 'Periyar'", "T.M. Nair", "K. Kamaraj"],
    correctAnswer: 1,
    explanation: "E.V. Ramaswamy 'Periyar'",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-6',
    question: "The 'Sri Narayana Dharma Paripalana (SNDP) Yogam' was founded in 1903 in:",
    options: ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh"],
    correctAnswer: 1,
    explanation: "Kerala",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-7',
    question: "Who was the first General Secretary of the SNDP Yogam and a famous Malayalam poet?",
    options: ["Sri Narayana Guru", "Kumaran Asan", "Dr. Palpu", "Sahodaran Ayyappan"],
    correctAnswer: 1,
    explanation: "Kumaran Asan",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-8',
    question: "The 'Justice Party' (South Indian Liberal Federation) was formed in 1916 to represent the interests of:",
    options: ["Non-Brahmins in Madras Presidency", "The British Army", "The Congress party", "Only the landless laborers"],
    correctAnswer: 0,
    explanation: "Non-Brahmins in Madras.",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-9',
    question: "The 'Vaikom Satyagraha' (1924\u201325) was a landmark struggle in Kerala for:",
    options: ["Freedom from taxes", "Temple entry and the right of untouchables to use roads leading to the Vaikom Temple", "The promotion of the English language", "The partition of India"],
    correctAnswer: 1,
    explanation: "Temple entry and road access.",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-10',
    question: "Who founded the 'All India Depressed Classes Association' in 1930?",
    options: ["Dr. B.R. Ambedkar", "M.C. Rajah", "Mahatma Gandhi", "Babu Jagjivan Ram"],
    correctAnswer: 1,
    explanation: "M.C. Rajah (Ambedkar founded the 'All India Depressed Classes Federation').",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-11',
    question: "The 'Poona Pact' (1932) was signed between which two leaders?",
    options: ["Nehru and Jinnah", "Gandhi and Ambedkar", "Patel and Bose", "Ambedkar and Jinnah"],
    correctAnswer: 1,
    explanation: "Gandhi and Ambedkar",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-12',
    question: "Following the Poona Pact, Mahatma Gandhi founded which organization for the welfare of the 'Harijans'?",
    options: ["Bahishkrit Hitakarini Sabha", "Harijan Sevak Sangh", "Satyashodhak Samaj", "Self-Respect Movement"],
    correctAnswer: 1,
    explanation: "Harijan Sevak Sangh (1932).",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-13',
    question: "The term 'Harijan' (Children of God) was popularized by:",
    options: ["Dr. B.R. Ambedkar", "Mahatma Gandhi", "Jyotiba Phule", "Periyar"],
    correctAnswer: 1,
    explanation: "Mahatma Gandhi",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-14',
    question: "Who was the leader of the 'Ezhava' community in Kerala who famously said, \"One Caste, One Religion, One God for Man\"?",
    options: ["Sahodaran Ayyappan", "Sri Narayana Guru", "T.K. Madhavan", "K. Kelappan"],
    correctAnswer: 1,
    explanation: "Sri Narayana Guru",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-15',
    question: "The 'Bahishkrit Hitakarini Sabha' (1924) had the motto:",
    options: ["\"Jai Bhim\"", "\"Educate, Agitate, and Organize\"", "\"Do or Die\"", "\"Satyamev Jayate\""],
    correctAnswer: 1,
    explanation: "\"Educate, Agitate, and Organize\"",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-16',
    question: "Which magazine was started by Dr. B.R. Ambedkar in 1920 with the help of the Maharaja of Kolhapur?",
    options: ["Bahishkrit Bharat", "Mooknayak (Leader of the Silent)", "Janata", "Prabuddha Bharat"],
    correctAnswer: 1,
    explanation: "Mooknayak",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-17',
    question: "The 'Kalaram Temple Satyagraha' (1930) took place in which city?",
    options: ["Pune", "Nashik", "Nagpur", "Mumbai"],
    correctAnswer: 1,
    explanation: "Nashik (Led by Ambedkar).",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-18',
    question: "The 'Guruvayur Satyagraha' (1931\u201332) for temple entry was led by which Congress leader in Kerala?",
    options: ["K. Kelappan", "A.K. Gopalan", "T.K. Madhavan", "Both A and B"],
    correctAnswer: 3,
    explanation: "Both A and B (Kelappan went on a fast).",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-19',
    question: "Who founded the 'Sadhujana Paripalana Yogam' (1907) for the upliftment of the Pulaya community in Kerala?",
    options: ["Sri Narayana Guru", "Ayyankali", "Dr. Palpu", "Sahodaran Ayyappan"],
    correctAnswer: 1,
    explanation: "Ayyankali",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-20',
    question: "The journal Kudi Arasu (Republic) was the mouthpiece of which movement?",
    options: ["Satyashodhak Samaj", "Self-Respect Movement", "SNDP Yogam", "Justice Party"],
    correctAnswer: 1,
    explanation: "Self-Respect Movement",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-21',
    question: "In his famous book Gulamgiri (1873), Jyotiba Phule dedicated his work to:",
    options: ["The British Government", "The American movement to abolish slavery", "The Indian National Congress", "The Brahmin community"],
    correctAnswer: 1,
    explanation: "The American anti-slavery movement.",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-22',
    question: "The 'Temple Entry Proclamation' of 1936, which opened temples to all Hindus, was issued by the Maharaja of which state?",
    options: ["Mysore", "Travancore", "Baroda", "Hyderabad"],
    correctAnswer: 1,
    explanation: "Travancore",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-23',
    question: "Who started the 'Cheramar Mahajana Sabha' in 1921?",
    options: ["Ayyankali", "Pambadi John Joseph", "Sri Narayana Guru", "Dr. Palpu"],
    correctAnswer: 1,
    explanation: "Pambadi John Joseph",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-24',
    question: "The 'Depressed Classes Mission Society of India' (1906) was founded by:",
    options: ["Dr. B.R. Ambedkar", "V.R. Shinde (Vitthal Ramji Shinde)", "Jyotiba Phule", "Mahatma Gandhi"],
    correctAnswer: 1,
    explanation: "V.R. Shinde",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-25',
    question: "Who was the President of the first session of the All India Depressed Classes Federation in 1942?",
    options: ["Dr. B.R. Ambedkar", "N. Sivaraj", "Babu Jagjivan Ram", "M.C. Rajah"],
    correctAnswer: 1,
    explanation: "N. Sivaraj",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-26',
    question: "The movement led by E.V. Ramaswamy 'Periyar' strongly advocated for:",
    options: ["The use of Hindi in schools", "The eradication of Brahminical supremacy and the promotion of a Dravidian identity", "The return to the Vedas", "The maintenance of the Varna system"],
    correctAnswer: 1,
    explanation: "Eradication of Brahminical supremacy.",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-27',
    question: "Who wrote the influential book Annihilation of Caste?",
    options: ["Mahatma Gandhi", "Dr. B.R. Ambedkar", "Periyar", "Kanshi Ram"],
    correctAnswer: 1,
    explanation: "Dr. B.R. Ambedkar (Originally written as a speech).",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-28',
    question: "The 'Ezhava Memorial' (1896) was a petition submitted to the Maharaja of Travancore demanding:",
    options: ["Tax relief", "Government jobs for the Ezhava community", "A separate country", "Freedom of the press"],
    correctAnswer: 1,
    explanation: "Government jobs for Ezhavas.",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-29',
    question: "'Sahodaran Ayyappan' started the 'Sahodara Sangham' (1917) and popularized:",
    options: ["Single-caste dining", "'Misra-Bhojan' (Inter-dining) across caste lines", "Only Vedic education", "The use of Sanskrit"],
    correctAnswer: 1,
    explanation: "Misra-Bhojan.",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-30',
    question: "Mahatma Gandhi\u2019s 'Harijan' tour (1933\u201334) was aimed at:",
    options: ["Raising money for the Quit India movement", "Campaigning against untouchability and raising funds for the Harijan Sevak Sangh", "Promoting the Salt Satyagraha", "Opposing the Muslim League"],
    correctAnswer: 1,
    explanation: "Campaigning against untouchability.",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-31',
    question: "The 'Communal Award' (1932) by Ramsay MacDonald provided for:",
    options: ["Separate electorates for Muslims only", "Separate electorates for the Depressed Classes (Dalits) among others", "The partition of Bengal", "The independence of Princely States"],
    correctAnswer: 1,
    explanation: "Separate electorates for Dalits.",
    chapterId: 29,
    difficulty: 'Easy'
  },
  {
    id: '29-32',
    question: "The 'Satyashodhak Samaj' founded by Jyotiba Phule was revolutionary because it was the first to:",
    options: ["Use only English for its manifestos.", "Propose a non-Brahminical social identity by claiming that the \"lower\" castes were the original inhabitants (sons of the soil) and the \"upper\" castes were alien 'Aryan' invaders.", "Demand a separate country for Shudras.", "Support the British during the 1857 revolt."],
    correctAnswer: 1,
    explanation: "Non-Brahminical identity and the 'Aryan' invasion theory. Phule used this theory to deconstruct the religious authority of the Brahmins and create a sense of historical pride among the masses.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-33',
    question: "Consider the following statements regarding 'Dr. B.R. Ambedkar\u2019s' stance at the Round Table Conferences: 1. He argued that the 'Depressed Classes' were a distinct element in Indian society, separate from the Hindus. 2. He demanded separate electorates for the Dalits to ensure their true political representation. 3. He initially supported Gandhi\u2019s 'Harijan' terminology as a respectful alternative. Which of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2, and 3"],
    correctAnswer: 0,
    explanation: "1 and 2 only. Statement 3 is incorrect; Ambedkar strongly rejected the term 'Harijan', viewing it as patronizing and a way to keep Dalits within the fold of the very religion that oppressed them.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-34',
    question: "The 'Poona Pact' (1932) is often seen as a political compromise. What was the core trade-off?",
    options: ["Ambedkar gave up the demand for a separate country in exchange for reservation.", "Ambedkar gave up 'Separate Electorates' for the Depressed Classes in exchange for an increased number of 'Reserved Seats' within the general electorate.", "Gandhi agreed to join the Depressed Classes Federation.", "The British agreed to leave India immediately."],
    correctAnswer: 1,
    explanation: "Reservation within General Electorate vs Separate Electorates.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-35',
    question: "With reference to 'E.V. Ramaswamy Periyar', consider the following: Statement-I: He believed that true liberation for the backward castes required a total rejection of Hinduism and the 'Brahmin-dominated' North Indian culture. Statement-II: He started the 'Self-Respect Movement' to instill a sense of pride in Dravidian identity and promote rationalism over superstition. Which one of the following is correct?",
    options: ["Both are correct and Statement-II is the method to achieve Statement-I.", "Both are correct but unrelated.", "Statement-I is false.", "Statement-II is false."],
    correctAnswer: 0,
    explanation: "Both are correct.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-36',
    question: "Why did 'Sri Narayana Guru' install a mirror instead of an idol in one of his temples later in life?",
    options: ["Because he ran out of stone.", "To symbolize that the \"Divine\" is within one's self and to emphasize the message of \"One God\" for all mankind beyond sectarian images.", "To help people fix their clothes before worship.", "Because the British banned the use of idols."],
    correctAnswer: 1,
    explanation: "Symbolizing the Divine within and universalism.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-37',
    question: "The 'Justice Party' (1916) in Madras is significant because it:",
    options: ["Led the armed struggle in the South.", "Was the first successful non-Brahmin political party that utilized the colonial administrative structure to secure reservations in government jobs and education.", "Merged with the Muslim League.", "Abolished the salt tax in Madras."],
    correctAnswer: 1,
    explanation: "First successful non-Brahmin political mobilization for reservations.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-38',
    question: "Consider the following regarding the 'Mahad Satyagraha' (1927): 1. It was an assertion of 'Civil Rights' rather than just a religious demand. 2. During this movement, Ambedkar and his followers publicly burned the 'Manusmriti'. 3. The Satyagraha was immediately successful in ending untouchability in Mahad. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two (Statement 3 is incorrect; while it was a massive psychological victory, the legal and social battle for the tank continued for years).",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-39',
    question: "The 'Temple Entry Proclamation' of Travancore (1936) was a response to:",
    options: ["A direct order from the British King.", "The persistent and massive 'Temple Entry' movements (like Vaikom and Guruvayur) and the threat of large-scale conversion of lower castes to other religions.", "The discovery of gold inside the temple.", "A request from the Mughal Emperor."],
    correctAnswer: 1,
    explanation: "Pressure from grassroots movements and fear of conversion.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-40',
    question: "Match the following 'Social Movements' with their 'Region': 1. Satyashodhak Samaj \u2014",
    options: ["Maharashtra 2. Self-Respect Movement \u2014", "Tamil Nadu 3. SNDP Yogam \u2014", "Kerala 4. Namasudra Movement \u2014", "Bengal Select the correct matching code:"],
    correctAnswer: 0,
    explanation: "All are correctly matched.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-41',
    question: "'Vitthal Ramji Shinde' is often called the \"bridge\" between the Moderate Congress and the Dalit movement. Why?",
    options: ["He built an actual bridge.", "He worked within the Brahmo Samaj and the Congress while founding the 'Depressed Classes Mission' to sensitize the upper castes about untouchability.", "He was Ambedkar's teacher.", "He led the Quit India movement in the South."],
    correctAnswer: 1,
    explanation: "Sensitizing upper castes while working for Dalits.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-42',
    question: "The 'Self-Respect Movement' emphasized 'Rationalism'. In this context, it advocated for:",
    options: ["The return to Vedic rituals.", "Abandoning Sanskritized rituals and priestly control in favor of simple, logic-based social ceremonies.", "Joining the British civil service.", "Scientific farming only."],
    correctAnswer: 1,
    explanation: "Logic-based ceremonies vs priestly control.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-43',
    question: "What was the 'Vaikom Satyagraha' (1924) uniquely known for in the context of the National Movement?",
    options: ["It was the first time an all-India leader like Gandhi got involved in a local 'caste' issue, linking social reform with the broader national struggle.", "It was a violent revolt.", "It was purely an economic strike by laborers.", "It resulted in the independence of Kerala."],
    correctAnswer: 0,
    explanation: "Gandhi's involvement linking social reform to nationalism.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-44',
    question: "'Ayyankali's' struggle for the Pulayas in Kerala was characterized by:",
    options: ["Only writing letters to the King.", "Direct action, such as the 'Villuvandi' (bullock cart) journey to assert the right to use public roads reserved for upper castes.", "Moving his community to America.", "Supporting the British salt tax."],
    correctAnswer: 1,
    explanation: "Direct action via the 'Villuvandi' journey.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-45',
    question: "The 'All India Scheduled Castes Federation' (1942) was Ambedkar\u2019s attempt to:",
    options: ["Join the Congress.", "Create an independent political party to safeguard Dalit interests during the negotiations for the transfer of power.", "Start a new religion immediately.", "Support the Quit India movement."],
    correctAnswer: 1,
    explanation: "Independent political party for post-war power negotiations.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-46',
    question: "Consider the following regarding 'Mahatma Gandhi\u2019s' approach to Caste: 1. He believed that 'Untouchability' was a sin and a blot on Hinduism that must be removed. 2. He initially defended the 'Varna' system as a healthy social order while attacking its current \"degenerate\" form. 3. He advocated for the total destruction of the Hindu religion to end caste. How many of the above are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two (Statement 3 is incorrect; Gandhi wanted to purify Hinduism, whereas Ambedkar wanted to transcend it).",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-47',
    question: "The 'Justice Party's' failure to survive in the 1930s was largely due to:",
    options: ["Its pro-British stance and its inability to compete with the growing mass appeal and nationalist fervor of the Congress under Gandhi.", "It had no money.", "All its leaders died.", "It was banned by the British."],
    correctAnswer: 0,
    explanation: "Pro-British stance vs Nationalist mass appeal.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-48',
    question: "The 'Ezhava' community in Kerala was unique because it utilized which 'strategy' to climb the social ladder?",
    options: ["Only through religious conversion.", "A combination of 'Sanskritization' (adopting upper-caste habits) and 'Modernization' (securing Western education and government jobs).", "Armed rebellion.", "Supporting the French."],
    correctAnswer: 1,
    explanation: "Sanskritization and Modernization.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-49',
    question: "Consider the following regarding 'Periyar\u2019s' view on Women:",
    options: ["He believed they should stay at home.", "He was a radical feminist who argued that women\u2019s liberation was central to the self-respect of the Dravidian race, advocating for the right to divorce and property.", "He thought women shouldn't be educated.", "He supported the practice of Sati."],
    correctAnswer: 1,
    explanation: "Radical feminism as part of self-respect.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-50',
    question: "The 'Poona Pact' resulted in the creation of 'Reserved Seats'. How does this differ from 'Separate Electorates'?",
    options: ["In reserved seats, only Dalits vote.", "In reserved seats, the candidate must be a Dalit, but the entire population of the constituency (all castes) votes for them.", "There is no difference.", "Reserved seats are only for the British."],
    correctAnswer: 1,
    explanation: "Joint electorate with a reserved candidate.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-51',
    question: "Why did 'Ambedkar' eventually convert to Buddhism in 1956?",
    options: ["Because he liked the architecture.", "He viewed it as an indigenous Indian religion that was egalitarian, rational, and free from the inherent hierarchy of the caste system.", "To escape the British.", "Because the Congress asked him to."],
    correctAnswer: 1,
    explanation: "Egalitarian, rational, and indigenous alternative.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-52',
    question: "The 'Namasudra Movement' in Bengal was primarily a struggle for:",
    options: ["Separate country.", "Dignity, education, and social rights by the 'Chandala' community against the dominance of the 'Bhadralok' (upper castes).", "Joining the British Navy.", "Building more temples in Delhi."],
    correctAnswer: 1,
    explanation: "Dignity/Rights of Namasudras vs Bhadralok.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-53',
    question: "'Sahodaran Ayyappan's' slogan \"No Caste, No Religion, No God for Man\" was a radical departure from whose teachings?",
    options: ["Dr. B.R. Ambedkar.", "Sri Narayana Guru (who had said \"One Caste, One Religion, One God\").", "Mahatma Gandhi.", "The British King."],
    correctAnswer: 1,
    explanation: "Sri Narayana Guru (Ayyappan took a more secular/atheist turn).",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-54',
    question: "The 'Communal Award' (1932) was seen by Gandhi as a 'Divide and Rule' tactic because:",
    options: ["It gave too much money to Dalits.", "It threatened to separate the Dalit community from the Hindu fold permanently, creating a constitutional fracture in the Indian society.", "It abolished the Congress.", "it promoted the Russian language."],
    correctAnswer: 1,
    explanation: "Permanent constitutional fracture of Hindu society.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-55',
    question: "'B.R. Ambedkar's' role in the drafting of the Constitution ensured that:",
    options: ["The caste system was made legal.", "Provisions for the abolition of untouchability (Article 17) and reservation for SC/STs were firmly embedded in the legal framework of modern India.", "Everyone was forced to become Buddhist.", "The British stayed as advisors."],
    correctAnswer: 1,
    explanation: "Legal abolition of untouchability and reservation.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-56',
    question: "'Ayyankali' was called \"Pulayaraja\" (King of Pulayas) by whom?",
    options: ["The British Queen.", "Mahatma Gandhi (in recognition of his leadership).", "Dr. B.R. Ambedkar.", "The King of Travancore."],
    correctAnswer: 1,
    explanation: "Mahatma Gandhi.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-57',
    question: "Why did the 'Self-Respect Movement' burn the 'Ramayana'?",
    options: ["Because they ran out of firewood.", "They interpreted it as a tale of 'Aryan' (North Indian) victory over 'Dravidian' (South Indian) people, used to culturally subjugate the South.", "To protest against the price of books.", "By mistake."],
    correctAnswer: 1,
    explanation: "Interpretation as Aryan cultural subjugation of Dravidians.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-58',
    question: "The 'SNDP Yogam' was instrumental in creating which type of institutions?",
    options: ["Only temples.", "A vast network of schools, colleges, and hospitals to empower the community through education and professional efficiency.", "Military academies.", "Banks in London."],
    correctAnswer: 1,
    explanation: "Education and Health empowerment network.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-59',
    question: "'M.C. Rajah' and the 'Justice Party' eventually had a falling out because:",
    options: ["They didn't like the food.", "Rajah felt that the Justice Party was becoming dominated by 'Non-Brahmin' upper castes who were as oppressive toward Dalits as the Brahmins.", "Rajah wanted to join the British army.", "The British ordered them to fight."],
    correctAnswer: 1,
    explanation: "Exclusion of Dalits by Non-Brahmin upper castes.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
  {
    id: '29-60',
    question: "'Bahishkrit Hitakarini Sabha' (1924) focused on which three pillars?",
    options: ["Eat, Sleep, and Pray.", "Educate, Agitate, and Organize.", "Fight, Win, and Rule.", "Study, Work, and Earn."],
    correctAnswer: 1,
    explanation: "Educate, Agitate, and Organize.",
    chapterId: 29,
    difficulty: 'Moderate'
  },
];