from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import func, desc
from typing import Any, List, Dict
from datetime import datetime, timedelta
from app.api import deps
from app.models.user import User
from app.models.course import Course
from app.models.course_payment import CoursePayment
from app.models.lesson_progress import LessonProgress
from app.models.drill import DrillSession
from app.models.announcement import CourseAnnouncement as Announcement
from app.models.marketing_automation import MarketingWorkflow

router = APIRouter()

@router.get("/{teacher_id}/performance", response_model=Dict[str, Any])
def get_teacher_performance(
    teacher_id: int,
    db: Session = Depends(deps.get_db),
    current_admin: User = Depends(deps.get_current_active_admin),
) -> Any:
    """
    TASK 1.4 — TEACHER PERFORMANCE SCORING ENGINE
    Formula: 
    Score = (completion*0.3 + mcq_imp*0.25 + retention*0.2 + content*0.15 + response*0.1) * 100
    """
    teacher = db.query(User).filter(User.id == teacher_id, User.role.in_(["teacher", "admin"])).first()
    if not teacher:
        raise HTTPException(status_code=404, detail="Teacher not found")

    # 1. student_completion_rate (0.0 - 1.0)
    # Average completion rate of students in this teacher's courses
    courses = db.query(Course).filter(Course.instructor_id == teacher_id).all()
    c_ids = [c.id for c in courses]
    
    completion_rate = 0.0
    if c_ids:
        avg_progress = db.query(func.avg(LessonProgress.progress_percentage)).join(CoursePayment, CoursePayment.user_id == LessonProgress.user_id).filter(
            CoursePayment.course_id.in_(c_ids)
        ).scalar() or 0.0
        completion_rate = float(avg_progress) / 100.0

    # 2. student_mcq_improvement (0.0 - 1.0)
    # Comparison of first 10 drills vs last 10 drills
    mcq_improvement = 0.75 # Placeholder heuristic

    # 3. student_retention_rate (0.0 - 1.0)
    # % of students who were active in last 7 days
    retention_rate = 0.85 # Placeholder

    # 4. content_creation_score (0.0 - 1.0)
    # Based on number of courses and chapters
    content_score = min(1.0, len(courses) / 5.0)

    # 5. response_time_score (0.0 - 1.0)
    # Based on announcement frequency
    announcements = db.query(func.count(Announcement.id)).filter(Announcement.instructor_id == teacher_id).scalar() or 0
    response_score = min(1.0, announcements / 10.0)

    # Composite Score
    composite_score = (
        (completion_rate * 0.30) +
        (mcq_improvement * 0.25) +
        (retention_rate * 0.20) +
        (content_score * 0.15) +
        (response_score * 0.10)
    ) * 100

    grade = "B"
    if composite_score >= 90: grade = "A+"
    elif composite_score >= 80: grade = "A"
    elif composite_score >= 70: grade = "B"
    elif composite_score >= 60: grade = "C"
    else: grade = "D"

    # Revenue generated by this teacher's courses
    total_rev = db.query(func.sum(CoursePayment.amount)).filter(
        CoursePayment.course_id.in_(c_ids),
        CoursePayment.status == "succeeded"
    ).scalar() or 0.0

    return {
        "id": teacher.id,
        "teacher_id": teacher.id,
        "teacher_name": teacher.full_name,
        "email": teacher.email,
        "composite_score": round(composite_score, 2),
        "grade": grade,
        "breakdown": {
            "student_completion_rate": round(completion_rate, 2),
            "student_mcq_improvement": mcq_improvement,
            "student_retention_rate": retention_rate,
            "content_creation_score": content_score,
            "response_time_score": response_score
        },
        "student_count": db.query(func.count(func.distinct(CoursePayment.user_id))).filter(CoursePayment.course_id.in_(c_ids)).scalar() or 0,
        "course_count": len(courses),
        "active_marketing_count": db.query(func.count(MarketingWorkflow.id)).filter(
            MarketingWorkflow.created_by == teacher_id,
            MarketingWorkflow.status == "ACTIVE"
        ).scalar() or 0,
        "students_active_7d": 12, # Placeholder
        "avg_student_streak": 8.5, # Placeholder
        "revenue_generated": float(total_rev),
        "trend": "IMPROVING"
    }

@router.get("/leaderboard", response_model=List[Dict[str, Any]])
def get_teacher_leaderboard(
    db: Session = Depends(deps.get_db),
    current_admin: User = Depends(deps.get_current_active_admin),
) -> Any:
    """Ranked list of teachers by composite score."""
    teachers = db.query(User).filter(User.role.in_(["teacher", "admin"])).all()
    leaderboard = []
    for t in teachers:
        perf = get_teacher_performance(t.id, db, current_admin)
        leaderboard.append(perf)
    
    leaderboard.sort(key=lambda x: x["composite_score"], reverse=True)
    return leaderboard
