// Auto-generated by Antigravity Script
import { Question } from '../../../../types';

export const MODERN_CHAPTER_5_MCQS: any[] = [
  {
    id: '4-92',
    question: "Which prominent historian is associated with the view that the decline of the Mughal Empire was fundamentally caused by an 'Agrarian Crisis'\u2014where extreme exploitation by Jagirdars provoked widespread, armed peasant rebellions (like the Jats, Sikhs, and Satnamis)?",
    options: ["Satish Chandra", "Irfan Habib", "Jadunath Sarkar", "Percival Spear"],
    correctAnswer: 1,
    explanation: "Irfan Habib",
    chapterId: 4,
    difficulty: 'Hard'
  },
  {
    id: '5-2',
    question: "Which British historian famously argued that the British conquest of India was made blindly, unintentionally, and in a \"fit of absent-mindedness\"?",
    options: ["Percival Spear", "John Seeley", "Vincent Smith", "James Mill"],
    correctAnswer: 1,
    explanation: "John Seeley",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-3',
    question: "Some historians regard the beginning of the British political period in India to be 1740. Which major event triggered this?",
    options: ["The Battle of Plassey", "The Battle of Buxar", "The beginning of the Anglo-French struggle for supremacy", "The decline of the Marathas"],
    correctAnswer: 2,
    explanation: "The beginning of the Anglo-French struggle for supremacy",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-4',
    question: "On the eve of its conquest by the British, Bengal accounted for what percentage of the total British imports from Asia?",
    options: ["20 per cent", "40 per cent", "60 per cent", "80 per cent"],
    correctAnswer: 2,
    explanation: "60 per cent",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-5',
    question: "The commercial foundation of Calcutta by the English East India Company was completed in which decade?",
    options: ["1650s", "1670s", "1690s", "1710s"],
    correctAnswer: 2,
    explanation: "1690s",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-6',
    question: "Who was appointed as the Dewan of Bengal by Aurangzeb in 1700, eventually ruling till his death in 1727?",
    options: ["Shujauddin", "Sarfaraz Khan", "Alivardi Khan", "Murshid Quli Khan"],
    correctAnswer: 3,
    explanation: "Murshid Quli Khan",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-7',
    question: "In 1741, who killed the Nawab of Bengal, Sarfaraz Khan, in a battle to become the new Subahdar of Bengal?",
    options: ["Mir Jafar", "Alivardi Khan", "Siraj-ud-Daulah", "Mir Kasim"],
    correctAnswer: 1,
    explanation: "Alivardi Khan",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-8',
    question: "Who succeeded Alivardi Khan as the Nawab of Bengal in April 1756?",
    options: ["Mir Jafar", "Shaukat Jang", "Siraj-ud-Daulah", "Mir Madan"],
    correctAnswer: 2,
    explanation: "Siraj-ud-Daulah",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-9',
    question: "According to the propagated story of the 'Black Hole Tragedy', how many English persons died of suffocation out of the 146 imprisoned?",
    options: ["50", "100", "123", "140"],
    correctAnswer: 2,
    explanation: "123",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-10',
    question: "Who was the highly influential banker of Bengal with whom Robert Clive forged a secret alliance before the Battle of Plassey?",
    options: ["Omichand", "Rai Durlabh", "Jagat Seth", "Mir Jafar"],
    correctAnswer: 2,
    explanation: "Jagat Seth",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-11',
    question: "Who murdered Siraj-ud-Daulah after his defeat and capture following the Battle of Plassey?",
    options: ["Robert Clive", "Mir Jafar", "Miran (son of Mir Jafar)", "Hector Munro"],
    correctAnswer: 2,
    explanation: "Miran (son of Mir Jafar)",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-12',
    question: "Immediately following the Battle of Plassey (1757), Mir Jafar granted the English the zamindari of which region?",
    options: ["Burdwan", "Midnapur", "24 Parganas", "Chittagong"],
    correctAnswer: 2,
    explanation: "24 Parganas",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-13',
    question: "In November 1759, the Dutch ambitions in India were crushed by the English forces at the Battle of:",
    options: ["Chinsura", "Bedara", "Wandiwash", "Buxar"],
    correctAnswer: 1,
    explanation: "Bedara",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-14',
    question: "Under the Treaty of 1760, the new Nawab Mir Kasim agreed to cede which three districts to the Company?",
    options: ["Burdwan, Midnapur, and Chittagong", "24 Parganas, Hooghly, and Kasimbazar", "Patna, Dacca, and Murshidabad", "Sylhet, Munger, and Bihar"],
    correctAnswer: 0,
    explanation: "Burdwan, Midnapur, and Chittagong",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-15',
    question: "To maintain a safe distance from the Company at Calcutta, Mir Kasim shifted his capital from Murshidabad to:",
    options: ["Patna", "Dacca", "Munger", "Awadh"],
    correctAnswer: 2,
    explanation: "Munger",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-16',
    question: "Who was the deputy governor of Bihar who continually defied Mir Kasim's authority, leading to severe friction with the English?",
    options: ["Raja Sitab Roy", "Ram Narayan", "Mohammad Reza Khan", "Balwant Singh"],
    correctAnswer: 1,
    explanation: "Ram Narayan",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-17',
    question: "The combined armies of Mir Kasim, Nawab Shuja-ud-Daulah, and Emperor Shah Alam II were defeated at the Battle of Buxar (1764) by:",
    options: ["Robert Clive", "Major Hector Munro", "General Eyre Coote", "Arthur Wellesley"],
    correctAnswer: 1,
    explanation: "Major Hector Munro",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-18',
    question: "Under the Treaty of Allahabad (August 1765), Nawab Shuja-ud-Daulah of Awadh agreed to pay the Company a war indemnity of:",
    options: ["Rs 26 lakh", "Rs 50 lakh", "Rs 75 lakh", "Rs 1 crore"],
    correctAnswer: 1,
    explanation: "Rs 50 lakh",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-19',
    question: "Who abolished the 'Dual System' of government in Bengal in 1772?",
    options: ["Robert Clive", "Lord Cornwallis", "Warren Hastings", "Lord William Bentinck"],
    correctAnswer: 2,
    explanation: "Warren Hastings",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-20',
    question: "In 1761, who became the de facto ruler of the state of Mysore?",
    options: ["Chikka Krishnaraja Wodeyar II", "Nanjaraj", "Tipu Sultan", "Haidar Ali"],
    correctAnswer: 3,
    explanation: "Haidar Ali",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-21',
    question: "Haidar Ali set up a modern arms factory at Dindigul with the help of experts from which European nation?",
    options: ["English", "Dutch", "Portuguese", "French"],
    correctAnswer: 3,
    explanation: "French",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-22',
    question: "The First Anglo-Mysore War (1767-69) ended in April 1769 with the signing of the:",
    options: ["Treaty of Mangalore", "Treaty of Madras", "Treaty of Seringapatam", "Treaty of Salbai"],
    correctAnswer: 1,
    explanation: "Treaty of Madras",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-23',
    question: "Haidar Ali died of cancer on December 7, 1782, during the course of which war?",
    options: ["First Anglo-Mysore War", "Second Anglo-Mysore War", "Third Anglo-Mysore War", "Fourth Anglo-Mysore War"],
    correctAnswer: 1,
    explanation: "Second Anglo-Mysore War",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-24',
    question: "Under the Treaty of Seringapatam (1792) that ended the Third Anglo-Mysore War, Tipu Sultan had to pay a massive war damage of:",
    options: ["One crore rupees", "Two crore rupees", "Three crore rupees", "Five crore rupees"],
    correctAnswer: 2,
    explanation: "Three crore rupees",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-25',
    question: "Who succeeded Sir John Shore as the new Governor-General in 1798 and pursued an aggressive imperial policy against Mysore?",
    options: ["Lord Cornwallis", "Lord Wellesley", "Lord Hastings", "Lord Dalhousie"],
    correctAnswer: 1,
    explanation: "Lord Wellesley",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-26',
    question: "Tipu Sultan died fighting heroically in the Fourth Anglo-Mysore War on:",
    options: ["December 7, 1782", "March 11, 1784", "May 4, 1799", "June 23, 1757"],
    correctAnswer: 2,
    explanation: "May 4, 1799",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-27',
    question: "After the death of Peshwa Madhavrao in 1772, who had his nephew Narayanrao assassinated in a bid to become the Peshwa?",
    options: ["Nana Phadnavis", "Raghunathrao", "Mahadji Scindia", "Bajirao II"],
    correctAnswer: 1,
    explanation: "Raghunathrao",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-28',
    question: "The Treaty of Salbai (1782), which ended the First Anglo-Maratha War, guaranteed peace between the English and the Marathas for how many years?",
    options: ["Ten years", "Fifteen years", "Twenty years", "Twenty-five years"],
    correctAnswer: 2,
    explanation: "Twenty years",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-29',
    question: "The Treaty of Bassein, effectively signing away Maratha independence, was signed on December 31, 1802, by the English and which Maratha leader?",
    options: ["Jaswantrao Holkar", "Daulatrao Scindia", "Bajirao II", "Nana Phadnavis"],
    correctAnswer: 2,
    explanation: "Bajirao II",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-30',
    question: "The Treaty of Amritsar (1809), which fixed the river Sutlej as the boundary, was signed between the British and:",
    options: ["Banda Bahadur", "Maharaja Ranjit Singh", "Kharak Singh", "Daleep Singh"],
    correctAnswer: 1,
    explanation: "Maharaja Ranjit Singh",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-31',
    question: "In 1843, Sindh was entirely merged into the British Empire. Who was appointed as its first British governor?",
    options: ["Lord Ellenborough", "James Outram", "Charles Napier", "Lord Auckland"],
    correctAnswer: 2,
    explanation: "Charles Napier",
    chapterId: 5,
    difficulty: 'Easy'
  },
  {
    id: '5-32',
    question: "The Battle of Plassey (1757) is often described by historians more as a 'skirmish' and a 'conspiracy' rather than a great military battle. Why is the Battle of Buxar (1764) considered vastly more significant in establishing British paramountcy?",
    options: ["It was the first time the British utilized naval bombardment in an inland war.", "It demonstrated the sheer military superiority of the English army over the combined, formal forces of two major Indian Nawabs and the Mughal Emperor.", "It resulted in the immediate and total annexation of the entire Mughal Empire into the British Crown.", "It led to the expulsion of all other European trading companies from the Indian Ocean."],
    correctAnswer: 1,
    explanation: "It demonstrated the sheer military superiority of the English army over the combined, formal forces of two major Indian Nawabs and the Mughal Emperor. While Plassey was won through bribery and treason (Mir Jafar), Buxar was a decisive military victory that proved British tactical superiority and brought Awadh and the Mughal Emperor under their thumb.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-33',
    question: "Robert Clive introduced the 'Dual System' of government in Bengal (1765-1772). Under this system, how was the administration divided?",
    options: ["The British controlled both the revenue (Diwani) and the police/judicial powers (Nizamat) directly through their own British officers.", "The British collected the revenue (Diwani) while the Nawab remained responsible for law, order, and justice (Nizamat), effectively divorcing power from responsibility.", "The Nawab collected the revenue, but the British controlled the army.", "The French and the English jointly administered the province to prevent further wars."],
    correctAnswer: 1,
    explanation: "The British collected the revenue (Diwani) while the Nawab remained responsible for law, order, and justice (Nizamat), effectively divorcing power from responsibility.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-34',
    question: "Siraj-ud-Daulah\u2019s conflict with the English East India Company in 1756 was primarily triggered by which core economic and political grievance?",
    options: ["The English refusal to pay the standard Jizya tax.", "The rampant misuse of 'dastaks' (free trade passes) by Company servants for their private trade, and the fortification of Calcutta without the Nawab's permission.", "The English attempt to convert the local Bengali population to Christianity.", "The English alliance with the Marathas to overthrow the Nawab."],
    correctAnswer: 1,
    explanation: "The rampant misuse of 'dastaks' (free trade passes) by Company servants for their private trade, and the fortification of Calcutta without the Nawab's permission.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-35',
    question: "Mir Kasim is often regarded as the most capable Nawab of Bengal after Alivardi Khan. What radical step did he take that inevitably led to open war with the British?",
    options: ["He invited the French army to permanently garrison Murshidabad.", "He abolished all internal customs duties, placing Indian merchants on an equal footing with the English who were misusing their duty-free passes.", "He attacked Fort William and executed the British Governor.", "He declared himself the independent Mughal Emperor."],
    correctAnswer: 1,
    explanation: "He abolished all internal customs duties, placing Indian merchants on an equal footing with the English who were misusing their duty-free passes.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-36',
    question: "Consider the following regarding the 'Ring-Fence Policy' primarily associated with Warren Hastings:",
    options: ["It involved building massive physical walls around British factories to protect them from Maratha raids.", "It aimed at defending the frontiers of the Company's neighbors (like Awadh) with British troops at the neighbor's expense, creating buffer zones to protect the Company's actual territories.", "It was a strict policy of absolute non-interference and isolationism from all Indian political affairs.", "It involved surrounding hostile Indian states with a ring of British naval blockades."],
    correctAnswer: 1,
    explanation: "It aimed at defending the frontiers of the Company's neighbors (like Awadh) with British troops at the neighbor's expense, creating buffer zones.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-37',
    question: "Lord Wellesley aggressively utilized the 'Subsidiary Alliance' system to expand British power. Which of the following was NOT a core condition imposed on an Indian state accepting this alliance?",
    options: ["The state had to maintain a contingent of British troops within its territory at its own expense.", "The state had to expel all non-English Europeans from its service.", "The state had to surrender its right to conduct independent foreign relations and wage war without British consent.", "The state had to permanently adopt Christianity as its official religion."],
    correctAnswer: 3,
    explanation: "The state had to permanently adopt Christianity as its official religion. The British strictly avoided interfering in the internal religious affairs of the allied states during this period.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-38',
    question: "Which Indian state was the first to accept Lord Wellesley's Subsidiary Alliance in 1798?",
    options: ["The Maratha Peshwa", "The Nawab of Awadh", "The Nizam of Hyderabad", "The Kingdom of Mysore"],
    correctAnswer: 2,
    explanation: "The Nizam of Hyderabad",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-39',
    question: "Tipu Sultan of Mysore was unique among 18th-century Indian rulers because he actively understood the threat of European imperialism. Which of the following modernizing steps was NOT taken by Tipu Sultan?",
    options: ["He planted a 'Tree of Liberty' at Seringapatam and became a member of the French Jacobin Club.", "He established a Board of Admiralty and attempted to build a modern navy.", "He sent diplomatic embassies to France, Turkey, and Iran to build anti-British alliances.", "He completely disbanded his traditional infantry and relied exclusively on British mercenaries."],
    correctAnswer: 3,
    explanation: "He completely disbanded his traditional infantry and relied exclusively on British mercenaries. Tipu modernized his army but relied heavily on French experts, not British mercenaries, and maintained a strong indigenous force.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-40',
    question: "The Second Anglo-Mysore War (1780-84) was triggered by a specific British aggression that violated Haidar Ali's territorial sovereignty. What was it?",
    options: ["The British capture of Mahe, a French settlement situated within Haidar Ali's jurisdiction on the Malabar coast.", "The British assassination of Tipu Sultan's prime minister.", "The British refusal to pay the promised tribute from the Carnatic revenues.", "The British attempt to place a puppet ruler on the throne of Mysore."],
    correctAnswer: 0,
    explanation: "The British capture of Mahe, a French settlement situated within Haidar Ali's jurisdiction.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-41',
    question: "Consider the consequences of the Third Anglo-Mysore War (1790-92):",
    options: ["Tipu Sultan decisively defeated Lord Cornwallis and expelled the British from Madras.", "Tipu Sultan lost half of his territories, which were divided among the British, the Marathas, and the Nizam, and had to pay a massive war indemnity.", "Mysore was completely annexed into the British Empire.", "The French intervened and forced a stalemate, restoring pre-war boundaries."],
    correctAnswer: 1,
    explanation: "Tipu Sultan lost half of his territories, which were divided among the British, the Marathas, and the Nizam, and had to pay a massive war indemnity.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-42',
    question: "The Maratha Confederacy in the 18th century consisted of several powerful families. Which of the following pairs of Maratha families and their traditional headquarters is incorrectly matched?",
    options: ["Peshwa \u2014 Pune", "Scindia (Sindhia) \u2014 Gwalior", "Holkar \u2014 Indore", "Bhonsle \u2014 Baroda"],
    correctAnswer: 3,
    explanation: "Bhonsle \u2014 Baroda The Bhonsles were based in Nagpur. The Gaekwads were based in Baroda.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-43',
    question: "The First Anglo-Maratha War (1775-1782) was ignited by British interference in a succession dispute for the Peshwaship. Which ambitious Maratha leader signed the controversial Treaty of Surat (1775) with the English at Bombay to usurp the Peshwa title?",
    options: ["Madhavrao", "Raghunathrao (Raghoba)", "Nana Phadnavis", "Mahadji Scindia"],
    correctAnswer: 1,
    explanation: "Raghunathrao (Raghoba) Raghunathrao sought British help against the legitimate infant Peshwa (Sawai Madhavrao) backed by the Barbhai Council led by Nana Phadnavis.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-44',
    question: "Why is the Treaty of Bassein (1802), signed by Peshwa Bajirao II, considered a catastrophic turning point in Maratha history?",
    options: ["It involved the surrender of all Maratha coastal forts to the Portuguese.", "The Peshwa accepted the Subsidiary Alliance, effectively surrendering Maratha independence and foreign policy to the British in exchange for protection from his own chiefs.", "It resulted in the immediate execution of the Peshwa by the British.", "It formally disbanded the entire Maratha cavalry."],
    correctAnswer: 1,
    explanation: "The Peshwa accepted the Subsidiary Alliance, effectively surrendering Maratha independence.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-45',
    question: "Which of the following is generally cited by historians as a fundamental internal reason for the ultimate defeat of the Marathas by the British?",
    options: ["The Marathas refused to use horses in battle.", "They lacked a cohesive, pan-Indian political vision and their confederacy was plagued by intense internal rivalries and mutual distrust among the chiefs.", "They were financially bankrupt from the very beginning of the 18th century.", "They lacked any form of artillery or firearms."],
    correctAnswer: 1,
    explanation: "They lacked a cohesive, pan-Indian political vision and their confederacy was plagued by intense internal rivalries and mutual distrust among the chiefs.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-46',
    question: "The British annexation of Sindh in 1843 by Charles Napier is often criticized by historians as morally unjustified. What was the primary strategic context behind this aggressive annexation?",
    options: ["The Amirs of Sindh had launched a massive, unprovoked invasion of Bombay.", "The British wanted to compensate for the severe loss of prestige and catastrophic military disaster they had just suffered in the First Anglo-Afghan War.", "The French had already built a massive naval base in Karachi.", "Sindh was the only remaining source of saltpetre in India."],
    correctAnswer: 1,
    explanation: "The British wanted to compensate for the severe loss of prestige and catastrophic military disaster they had just suffered in the First Anglo-Afghan War.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-47',
    question: "Maharaja Ranjit Singh built a powerful, secular, and modern state in Punjab. His army, the Fauj-i-Khas, was considered second only to the British East India Company's army in Asia. How did he achieve this military modernization?",
    options: ["He relied entirely on traditional Sikh guerrilla warfare tactics (Dhai Phat).", "He employed numerous European officers (French, Italian, American) such as Allard and Ventura to systematically train his infantry and artillery on Western lines.", "He imported the entire army of the Persian Empire.", "He forced all peasants in Punjab to become full-time soldiers."],
    correctAnswer: 1,
    explanation: "He employed numerous European officers to systematically train his infantry and artillery on Western lines.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-48',
    question: "The Treaty of Amritsar (1809) was a crucial diplomatic agreement between Maharaja Ranjit Singh and the British (represented by Charles Metcalfe). What was its primary strategic consequence?",
    options: ["It forced Ranjit Singh to accept a Subsidiary Alliance.", "It fixed the river Sutlej as the boundary, checking Ranjit Singh's expansion to the east but giving him a free hand to expand westward towards Peshawar and Kashmir.", "It resulted in the immediate annexation of Lahore by the British.", "It required Ranjit Singh to disband his European-trained army."],
    correctAnswer: 1,
    explanation: "It fixed the river Sutlej as the boundary, checking Ranjit Singh's expansion to the east.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-49',
    question: "The First Anglo-Sikh War (1845-46) broke out following the death of Ranjit Singh. What was the immediate catalyst for the outbreak of hostilities?",
    options: ["The British unprovoked assassination of Rani Jindan.", "The Khalsa army, becoming dominant and suspicious of British troop movements, crossed the river Sutlej into British territory.", "The Sikhs allied with the French to invade Delhi.", "The British refusal to pay the annual tribute to Lahore."],
    correctAnswer: 1,
    explanation: "The Khalsa army, becoming dominant and suspicious of British troop movements, crossed the river Sutlej into British territory.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-50',
    question: "Following the Second Anglo-Sikh War (1848-49), Punjab was finally annexed into the British Empire. Which aggressive Governor-General was responsible for this annexation?",
    options: ["Lord Hastings", "Lord Dalhousie", "Lord Auckland", "Lord Hardinge"],
    correctAnswer: 1,
    explanation: "Lord Dalhousie",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-51',
    question: "Lord Dalhousie\u2019s 'Doctrine of Lapse' was a controversial policy used to annex several Indian states. What was the core legal pretext of this doctrine?",
    options: ["If a ruler of a dependent state died without a natural biological heir, the state would 'lapse' to the British Paramount Power, ignoring the traditional Hindu right of adopting an heir.", "Any state that failed to pay its revenue on time would be immediately lapsed to the Crown.", "Any state whose ruler left the country for more than a year would lapse to the British.", "The British could annex any state if the ruler was deemed insane."],
    correctAnswer: 0,
    explanation: "If a ruler of a dependent state died without a natural biological heir, the state would 'lapse' to the British Paramount Power, ignoring the traditional Hindu right of adopting an heir.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-52',
    question: "Which was the first prominent Indian state to be annexed by Lord Dalhousie under the Doctrine of Lapse in 1848?",
    options: ["Jhansi", "Nagpur", "Satara", "Sambalpur"],
    correctAnswer: 2,
    explanation: "Satara",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-53',
    question: "The annexation of Awadh in 1856 deeply alienated the local population and was a major cause of the 1857 Revolt. Unlike Satara or Jhansi, on what grounds did Dalhousie annex Awadh?",
    options: ["Doctrine of Lapse (no biological heir).", "Alleged internal misgovernance and chronic maladministration by the Nawab (Wajid Ali Shah).", "The Nawab's open military alliance with the Marathas.", "The Nawab's refusal to accept a British Resident."],
    correctAnswer: 1,
    explanation: "Alleged internal misgovernance and chronic maladministration by the Nawab (Wajid Ali Shah).",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-54',
    question: "The 'Pindaris' were a significant factor leading to the Third Anglo-Maratha War. Who were the Pindaris?",
    options: ["A disciplined regiment of elite British cavalry.", "Irregular, freebooting bands of horsemen (of all castes and religions) who traditionally attached themselves to Maratha armies for plunder.", "A wealthy community of indigenous bankers in Bengal.", "French mercenaries operating in Mysore."],
    correctAnswer: 1,
    explanation: "Irregular, freebooting bands of horsemen who traditionally attached themselves to Maratha armies for plunder. Lord Hastings' campaign to hunt down the Pindaris violated Maratha sovereignty, triggering the final Anglo-Maratha war.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-55',
    question: "Consider the British justifications and interpretations of their conquest. Which of the following is a characteristic of the 'Imperialist' historiographical view of the British conquest of India?",
    options: ["The British systematically and intentionally drained India's wealth through calculated economic policies.", "The British conquered India not out of greed, but to rescue it from chronic anarchy, establishing the 'Pax Britannica' and fulfilling the 'White Man's Burden'.", "The British were completely defeated intellectually by Indian philosophical systems.", "The conquest was driven entirely by lower-class British soldiers acting without orders from London."],
    correctAnswer: 1,
    explanation: "The British conquered India not out of greed, but to rescue it from chronic anarchy, establishing the 'Pax Britannica'.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-56',
    question: "The Tripartite Treaty of 1838 was a key diplomatic maneuver leading up to the First Anglo-Afghan War. Who were the three parties to this treaty?",
    options: ["The British, the Marathas, and the Nizam of Hyderabad.", "The British, Maharaja Ranjit Singh, and Shah Shuja (the deposed Afghan ruler).", "The French, Tipu Sultan, and the Ottoman Emperor.", "The British, the Amirs of Sindh, and Dost Mohammad of Kabul."],
    correctAnswer: 1,
    explanation: "The British, Maharaja Ranjit Singh, and Shah Shuja (the deposed Afghan ruler).",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-57',
    question: "Which structural advantage gave the English East India Company a decisive edge over rival Indian powers during the century of conquest (1757-1857)?",
    options: ["The English soldiers were genetically immune to all tropical diseases.", "The Company possessed a highly stable financial base, regular salaries for its disciplined mercenary troops, and superior military technology/artillery.", "The Indian rulers completely lacked access to horses or cavalry tactics.", "The English received direct, massive military reinforcements from the United States."],
    correctAnswer: 1,
    explanation: "The Company possessed a highly stable financial base, regular salaries for its disciplined mercenary troops, and superior military technology/artillery.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-58',
    question: "The concept of 'Paramountcy' was formally articulated under the Governor-Generalship of Lord Hastings. What did it imply?",
    options: ["The British East India Company claimed its authority was supreme, greater than that of any Indian state, justifying its right to annex or threaten any state to protect its interests.", "The British acknowledged the Mughal Emperor as the supreme paramount power of the world.", "The British declared total non-interference in the internal matters of Indian states.", "The Company submitted its authority to the absolute control of the British Parliament."],
    correctAnswer: 0,
    explanation: "The British East India Company claimed its authority was supreme, greater than that of any Indian state.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-59',
    question: "In the aftermath of the Battle of Buxar, Robert Clive signed two separate Treaties of Allahabad (1765) with Nawab Shuja-ud-Daulah and Emperor Shah Alam II. What was the most crucial right granted by the Emperor to the Company in this treaty?",
    options: ["The right to permanently station a British army in Delhi.", "The Diwani rights (right to collect revenues) of Bengal, Bihar, and Orissa.", "The exclusive right to trade in opium in China.", "The right to mint coins bearing Queen Victoria's image."],
    correctAnswer: 1,
    explanation: "The Diwani rights (right to collect revenues) of Bengal, Bihar, and Orissa.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-60',
    question: "Following the annexation of Punjab in 1849, how was the newly acquired, vast, and volatile territory administered?",
    options: ["It was handed over to the Marathas to act as a buffer state.", "It was administered by a three-member 'Board of Administration' (including the Lawrence brothers) before being made a Chief Commissioner's province.", "It was directly ruled from London by the Secretary of State.", "It was immediately granted democratic self-government."],
    correctAnswer: 1,
    explanation: "It was administered by a three-member 'Board of Administration' (including the Lawrence brothers).",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-61',
    question: "Tipu Sultan's defeat in the Fourth Anglo-Mysore War (1799) was partially due to diplomatic isolation. Who actively assisted the British forces in this final campaign against Mysore?",
    options: ["The French and the Dutch.", "The Marathas and the Nizam of Hyderabad.", "The Sikhs and the Rajputs.", "The Amirs of Sindh."],
    correctAnswer: 1,
    explanation: "The Marathas and the Nizam of Hyderabad. Lord Wellesley skillfully secured the neutrality or active support of the Marathas and the Nizam, ensuring Tipu faced the full might of the British coalition alone.",
    chapterId: 5,
    difficulty: 'Moderate'
  },
  {
    id: '5-62',
    question: "Consider the following statements regarding the factors that contributed to the success of the British against Indian powers: 1. The English possessed superior military tactics, utilizing the musket and disciplined infantry squares, whereas Indian armies relied heavily on slow-moving artillery and traditional cavalry. 2. The East India Company maintained a highly stable financial base through its booming global trade, ensuring that its soldiers and officers were paid regular salaries. 3. The British officers instilled a strong sense of nationalist pride and material reward among their troops, while Indian armies were often composed of mercenaries whose loyalty shifted with delayed payments. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three All three factors (superior arms/tactics, regular financial backing, and strong civil/military leadership coupled with national pride) were structural advantages highlighted in the text for the Company's success.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-63',
    question: "With reference to the Battle of Plassey (1757) and the Battle of Buxar (1764), consider the following: Statement-I: Historians argue that the Battle of Buxar firmly established British paramountcy in North India, whereas the Battle of Plassey merely laid the foundation of their political influence in Bengal. Statement-II: The Battle of Plassey was won primarily through treachery and the defection of Mir Jafar, whereas the Battle of Buxar was a decisive military victory against the combined armies of the Nawab of Bengal, the Nawab of Awadh, and the Mughal Emperor. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 0,
    explanation: "Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-64',
    question: "Consider the following provisions of the Treaties of Allahabad (August 1765) signed by Robert Clive: 1. Nawab Shuja-ud-Daulah of Awadh was forced to surrender Allahabad and Kara to Emperor Shah Alam II. 2. Emperor Shah Alam II issued a farman granting the Diwani of Bengal, Bihar, and Orissa to the East India Company. 3. Awadh was entirely annexed into the British Empire to serve as a buffer state against the Marathas. How many of the above provisions are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 2 are correct. Statement 3 is incorrect; Awadh was not annexed. It was intentionally kept as an independent buffer state to protect Bengal from Maratha and Afghan invasions.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-65',
    question: "Arrange the following treaties related to the Anglo-Maratha struggle in chronological order: 1. Treaty of Salbai 2. Treaty of Purandhar 3. Treaty of Bassein 4. Treaty of Surat Select the correct answer using the code given below:",
    options: ["4 \u2014 2 \u2014 1 \u2014 3", "2 \u2014 4 \u2014 1 \u2014 3", "4 \u2014 1 \u2014 2 \u2014 3", "1 \u2014 4 \u2014 2 \u2014 3"],
    correctAnswer: 0,
    explanation: "4 \u2014 2 \u2014 1 \u2014 3 Treaty of Surat (1775) -> Treaty of Purandhar (1776) -> Treaty of Salbai (1782) -> Treaty of Bassein (1802).",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-66',
    question: "Consider the following statements regarding the 'Dual System' of government in Bengal (1765-1772): Statement-I: Under this system, the East India Company directly assumed both the Diwani (revenue collection) and Nizamat (police and judicial) functions using British personnel. Statement-II: The system was deliberately designed by Robert Clive to mask the Company's absolute power from the British Parliament and rival European powers while maximizing revenue extraction. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 3,
    explanation: "Statement-I is incorrect but Statement-II is correct Statement-I is incorrect because the Company did not use British personnel directly for these functions initially; they exercised Diwani through Indian Deputy Diwans (like Mohammad Reza Khan) and left the responsibility of Nizamat to the Nawab, creating a disastrous divorce of power from responsibility.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-67',
    question: "Regarding the state of Mysore under Haidar Ali and Tipu Sultan, consider the following statements: 1. Haidar Ali established a modern arms factory at Dindigul with the help of French experts to counter the Marathas and the British. 2. Tipu Sultan planted a 'Tree of Liberty' at Seringapatam and became a member of the French Jacobin Club. 3. Tipu Sultan completely ignored naval power, focusing exclusively on a massive land-based cavalry. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 2 are correct. Statement 3 is incorrect; Tipu Sultan recognized the importance of naval power, set up a Board of Admiralty in 1796, and planned for a fleet of ships to protect his maritime trade.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-68',
    question: "Consider the following pairs of Anglo-Mysore Wars and the Treaties that concluded them: 1. First Anglo-Mysore War \u2014 Treaty of Madras 2. Second Anglo-Mysore War \u2014 Treaty of Mangalore 3. Third Anglo-Mysore War \u2014 Treaty of Seringapatam How many of the above pairs are correctly matched?",
    options: ["Only one pair", "Only two pairs", "All three pairs", "None"],
    correctAnswer: 2,
    explanation: "All three pairs",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-69',
    question: "The Treaty of Bassein (1802) is a watershed moment in Indian history. Which of the following were provisions accepted by Peshwa Bajirao II under this treaty? 1. To receive a native infantry (subsidiary force) with European artillerymen permanently stationed in his territories. 2. To surrender the city of Surat entirely to the Company. 3. To subject all his relations with other states to the control of the English (surrender of foreign policy). How many of the above provisions are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three The Treaty of Bassein was effectively a Subsidiary Alliance that stripped the Peshwa of his independence and made the British the paramount power in the Deccan.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-70',
    question: "Consider the following regarding the 'Pindaris': Statement-I: The Pindaris were exclusively Muslim mercenaries who fought a holy war against the British East India Company. Statement-II: The Pindaris were irregular horsemen of all castes and creeds who traditionally accompanied Maratha armies for plunder, and their suppression by Lord Hastings triggered the Third Anglo-Maratha War. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 2,
    explanation: "Statement-I is incorrect but Statement-II is correct Statement-I is factually wrong; the Pindaris included Hindus (like the Marathas/Rajputs) and Muslims (like Amir Khan and Karim Khan). They were freebooters, not religious zealots.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-71',
    question: "With reference to the British annexation of Sindh in 1843, consider the following: 1. The annexation was executed by Sir Charles Napier following the disastrous British retreat from the First Anglo-Afghan War. 2. The Amirs of Sindh had violated the Tripartite Treaty of 1838 by openly allying with the Russian Empire. 3. The annexation was widely condemned even by several British officials (including Outram) as a blatant, unprovoked act of imperialist aggression. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 3 are correct. Statement 2 is incorrect; the Amirs did not ally with Russia. The British merely used forced treaties and fabricated pretexts to annex Sindh to compensate for their humiliation in Afghanistan.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-72',
    question: "The 'Tripartite Treaty' of 1838 was a diplomatic maneuver aimed at checking suspected Russian advancement. Who were the three signatories of this treaty?",
    options: ["The British, the Maratha Peshwa, and the Nizam of Hyderabad.", "The British, the Amirs of Sindh, and Dost Mohammad of Kabul.", "The British, Maharaja Ranjit Singh, and Shah Shuja.", "The British, the French, and Tipu Sultan."],
    correctAnswer: 2,
    explanation: "The British, Maharaja Ranjit Singh, and Shah Shuja. The treaty aimed to place the British puppet, Shah Shuja, on the throne of Kabul with the help of Ranjit Singh's Sikh forces.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-73',
    question: "Consider the following statements about Maharaja Ranjit Singh's administration: Statement-I: He built a powerful, modern army (Fauj-i-Khas) utilizing European officers like Allard and Ventura to train his troops in Western infantry and artillery tactics. Statement-II: He maintained an orthodox, highly theocratic state where non-Sikhs were barred from holding any high civil or military offices. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 2,
    explanation: "Statement-I is correct but Statement-II is incorrect Statement-I is correct. Statement-II is entirely false; Ranjit Singh's state was remarkably secular. He appointed capable men of all religions (Hindus, Muslims, Dogras, Europeans) to high positions (e.g., Fakir Azizuddin was his trusted foreign minister).",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-74',
    question: "Lord Dalhousie implemented the 'Doctrine of Lapse' to annex multiple states. What was the core legal argument of this doctrine?",
    options: ["Hindu rulers of dependent states had no right to adopt a successor without the explicit consent of the British Paramount Power, and failing a natural heir, the state would \"lapse\" to the British.", "Any state that failed to modernize its military according to British standards would lapse to the Crown.", "The British possessed the divine right to lapse any treaty signed prior to 1800.", "Rulers who failed to pay their subsidiary alliance subsidies for three consecutive years would forfeit their kingdoms."],
    correctAnswer: 0,
    explanation: "Hindu rulers of dependent states had no right to adopt a successor without the explicit consent of the British Paramount Power, and failing a natural heir, the state would \"lapse\".",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-75',
    question: "Arrange the following states annexed by Lord Dalhousie under the Doctrine of Lapse in chronological order: 1. Jhansi 2. Satara 3. Nagpur 4. Sambalpur Select the correct answer using the code given below:",
    options: ["2 \u2014 4 \u2014 1 \u2014 3", "2 \u2014 1 \u2014 4 \u2014 3", "4 \u2014 2 \u2014 1 \u2014 3", "1 \u2014 2 \u2014 3 \u2014 4"],
    correctAnswer: 0,
    explanation: "2 \u2014 4 \u2014 1 \u2014 3 Satara (1848) -> Sambalpur (1849) -> Bhagat (1850) -> Udaipur (1852) -> Jhansi (1853) -> Nagpur (1854).",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-76',
    question: "The annexation of Awadh (Oudh) in 1856 was a highly controversial act that fueled the Revolt of 1857. Consider the following regarding Awadh's annexation: 1. It was annexed under the strict application of the Doctrine of Lapse, as Nawab Wajid Ali Shah had no natural heir. 2. It was annexed on the grounds of chronic misgovernance and maladministration, supposedly to relieve the suffering of the people. 3. The annexation resulted in thousands of Awadh's nobles, retainers, and soldiers losing their livelihoods, deeply embittering the local population. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 2 and 3 are correct. Statement 1 is incorrect; Wajid Ali Shah had numerous heirs. Awadh was annexed specifically on the pretext of \"misgovernance,\" not Lapse.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-77',
    question: "\"He was the Governor-General who decisively defeated the Maratha Confederacy in the Third Anglo-Maratha War, abolished the office of the Peshwa, and formally established British paramountcy over India.\" This passage refers to:",
    options: ["Lord Wellesley", "Lord Hastings", "Lord Cornwallis", "Lord Dalhousie"],
    correctAnswer: 1,
    explanation: "Lord Hastings (Moira)",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-78',
    question: "Consider the following regarding the First Anglo-Sikh War (1845-46): Statement-I: The immediate cause of the war was the Khalsa army crossing the river Sutlej into British territory. Statement-II: Following the Sikh defeat, Lord Hardinge completely annexed Punjab into the British Empire and exiled Maharaja Duleep Singh to London. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 2,
    explanation: "Statement-I is correct but Statement-II is incorrect Statement-I is correct. Statement-II is incorrect; Punjab was not annexed after the First War. The Treaty of Lahore (1846) recognized the minor Duleep Singh as ruler under a British Resident. Punjab was fully annexed later in 1849 by Dalhousie after the Second Anglo-Sikh War.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-79',
    question: "Consider the following pairs of British Policies and the Governor-Generals primarily associated with them: 1. Ring-Fence Policy \u2014 Warren Hastings 2. Subsidiary Alliance \u2014 Lord Wellesley 3. Doctrine of Lapse \u2014 Lord Dalhousie How many of the above pairs are correctly matched?",
    options: ["Only one pair", "Only two pairs", "All three pairs", "None"],
    correctAnswer: 2,
    explanation: "All three pairs All three policies correctly map to the respective Governor-Generals who initiated or most aggressively executed them.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-80',
    question: "Mir Kasim's conflict with the British culminated in the Battle of Buxar. What was the core underlying issue of this conflict?",
    options: ["Mir Kasim\u2019s refusal to pay the promised sum of money to Robert Clive.", "The rampant abuse of 'dastaks' (free transit passes) by Company servants for their private inland trade, which ruined the Nawab's revenue and local merchants.", "Mir Kasim\u2019s secret alliance with the French to expel the British from Bengal.", "The British demand for the immediate abolition of the Zamindari system."],
    correctAnswer: 1,
    explanation: "The rampant abuse of 'dastaks' (free transit passes) by Company servants for their private inland trade.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-81',
    question: "During the expansionist phase, the British utilized various treaties. Match the Treaty with the corresponding Indian power it was signed with: 1. Treaty of Amritsar (1809) \u2014",
    options: ["Marathas 2. Treaty of Seringapatam (1792) \u2014", "Awadh 3. Treaty of Salbai (1782) \u2014", "Sikhs 4. Treaty of Allahabad (1765) \u2014", "Mysore Select the correct code:"],
    correctAnswer: 0,
    explanation: "1-C (Sikhs), 2-D (Mysore), 3-A (Marathas), 4-B (Awadh).",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-82',
    question: "Consider the following statements regarding the administration of Punjab post-annexation (1849): 1. It was initially governed by a three-member Board of Administration consisting of the Lawrence brothers (John and Henry) and Charles Mansel. 2. The Board successfully dismantled the Sikh army, disarmed the population, and established a strong revenue and judicial system. 3. Due to widespread rebellions against the Board, Punjab was handed back to the Sikh chiefs in 1853. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 2 are correct. Statement 3 is incorrect; the Board was successful and Punjab remained firmly under British control (becoming a Chief Commissioner's province in 1853), playing a loyalist role for the British during the 1857 revolt.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-83',
    question: "In the context of the Anglo-Maratha Wars, the Maratha confederacy was weakened by internal betrayals. Who among the following Maratha leaders remained relatively stable and attempted to modernize his military with the help of the French commander De Boigne?",
    options: ["Raghunathrao", "Mahadji Scindia", "Bajirao II", "Malhar Rao Holkar"],
    correctAnswer: 1,
    explanation: "Mahadji Scindia Mahadji Scindia realized the necessity of modern warfare and created a highly effective, European-trained infantry and artillery division.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-84',
    question: "With reference to the 'Black Hole Tragedy' of 1756, consider the following: Statement-I: Modern historians universally agree that the Black Hole incident was fabricated entirely by J.Z. Holwell to justify the aggressive British conquest of Bengal. Statement-II: The incident involved the death of 123 English prisoners out of 146 who were locked in a tiny room by the forces of Siraj-ud-Daulah. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 2,
    explanation: "Statement-I is incorrect but Statement-II is correct Statement-I is incorrect; while historians agree the numbers were wildly exaggerated by Holwell for propaganda, the incident itself is generally accepted to have occurred on a smaller scale. Statement-II reflects the propagated historical account cited in texts.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-85',
    question: "Which of the following states was explicitly forced into a Subsidiary Alliance because it failed to clear its mounting debts (arrears) to the East India Company?",
    options: ["Mysore", "Awadh", "Hyderabad (The Nizam)", "The Peshwa"],
    correctAnswer: 2,
    explanation: "Hyderabad (The Nizam) The Nizam of Hyderabad frequently ceded territories (like the Circars and later the 'Ceded Districts' of Bellary/Cuddapah) to the British in lieu of the massive financial arrears accumulated for maintaining the subsidiary troops.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-86',
    question: "\"His aggressive forward policy aimed to remove all vestiges of French influence in India. He utilized the Subsidiary Alliance system as a tool to disarm Indian states and bring them under a Pax Britannica.\" This assessment best describes:",
    options: ["Warren Hastings", "Lord Cornwallis", "Lord Wellesley", "Lord William Bentinck"],
    correctAnswer: 2,
    explanation: "Lord Wellesley",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-87',
    question: "Consider the following consequences of the Battle of Plassey (1757): 1. The British East India Company secured massive financial resources from Bengal, which they used to fund their wars in South India and purchase Indian goods for export. 2. The French political and commercial influence in Bengal was permanently eradicated. 3. The Mughal Emperor formally recognized the absolute sovereignty of the British Crown over India. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 2 are correct. Statement 3 is incorrect; the British did not formally claim sovereignty over India under the Crown until after the 1857 Revolt (Government of India Act 1858). The Company ruled under the fiction of Mughal authority for a long time.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-88',
    question: "The Second Anglo-Sikh War (1848-49) was sparked by a local rebellion. Where did this initial revolt occur, led by Mulraj?",
    options: ["Lahore", "Amritsar", "Multan", "Peshawar"],
    correctAnswer: 2,
    explanation: "Multan The revolt of Mulraj, the governor of Multan, and the subsequent murder of two British officers provided Dalhousie the pretext to declare a general war against the Sikhs.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-89',
    question: "In analyzing the failure of the Marathas, historians point out a severe economic flaw in their state-building. What was it?",
    options: ["They completely banned agriculture in favor of pure militarization.", "They failed to encourage trade, commerce, and industry, relying almost entirely on extractive warfare, plunder (Chauth), and agricultural revenue.", "They spent all their state resources importing European manufactured goods.", "They refused to collect any taxes from the peasantry."],
    correctAnswer: 1,
    explanation: "They failed to encourage trade, commerce, and industry, relying almost entirely on extractive warfare, plunder (Chauth), and agricultural revenue.",
    chapterId: 5,
    difficulty: 'Hard'
  },
  {
    id: '5-90',
    question: "Consider the following statements regarding the Treaty of Salbai (1782): Statement-I: It guaranteed peace between the English and the Marathas for twenty years, allowing the British to focus their resources entirely against their formidable rival, Mysore. Statement-II: The treaty resulted in the immediate deposition of Peshwa Madhavrao II and the installation of Raghunathrao by the British. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 1,
    explanation: "Statement-I is correct but Statement-II is incorrect Statement-I is correct. Statement-II is incorrect; the British actually agreed to recognize Madhavrao II as the legitimate Peshwa and pensioned off their earlier ally, Raghunathrao.",
    chapterId: 5,
    difficulty: 'Hard'
  },
];