// Auto-generated by Antigravity Script
import { Question } from '../../../../types';

export const MODERN_CHAPTER_18_MCQS: any[] = [
  {
    id: '17-91',
    question: "Ultimately, the Nehru Report is considered a \"failed\" but \"great\" document because:",
    options: ["It led to an immediate British retreat.", "It showed that Indians could design a modern, secular, and democratic constitution despite communal hurdles.", "It unified the Muslim League and Hindu Mahasabha forever.", "It was the only report ever written by Motilal Nehru."],
    correctAnswer: 1,
    explanation: "Showed Indians could design a modern constitution.",
    chapterId: 17,
    difficulty: 'Hard'
  },
  {
    id: '18-2',
    question: "The 1929 Lahore Session of the Indian National Congress is historic because it passed the resolution for:",
    options: ["Non-Cooperation", "Purna Swaraj (Complete Independence)", "Dominion Status", "Quit India"],
    correctAnswer: 1,
    explanation: "Purna Swaraj",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-3',
    question: "Who presided over the 1929 Lahore Session of the Congress?",
    options: ["Motilal Nehru", "Jawaharlal Nehru", "Mahatma Gandhi", "Subhash Chandra Bose"],
    correctAnswer: 1,
    explanation: "Jawaharlal Nehru",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-4',
    question: "On which date was the first 'Independence Day' celebrated across India during the colonial era?",
    options: ["August 15, 1930", "January 26, 1930", "April 6, 1930", "December 31, 1929"],
    correctAnswer: 1,
    explanation: "January 26, 1930",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-5',
    question: "Mahatma Gandhi started the historic Dandi March from Sabarmati Ashram on:",
    options: ["March 12, 1930", "April 6, 1930", "January 26, 1930", "October 2, 1930"],
    correctAnswer: 0,
    explanation: "March 12, 1930",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-6',
    question: "How many followers accompanied Gandhi on the start of the Dandi March?",
    options: ["11", "72", "78", "100"],
    correctAnswer: 2,
    explanation: "78",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-7',
    question: "On which date did Gandhi reach Dandi and formally break the salt law?",
    options: ["March 12, 1930", "April 6, 1930", "April 13, 1930", "May 1, 1930"],
    correctAnswer: 1,
    explanation: "April 6, 1930",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-8',
    question: "The distance from Sabarmati Ashram to Dandi was approximately:",
    options: ["100 miles", "240 miles", "300 miles", "500 miles"],
    correctAnswer: 1,
    explanation: "240 miles",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-9',
    question: "Who led the salt satyagraha at Vedaranyam in Tamil Nadu?",
    options: ["K. Kelappan", "C. Rajagopalachari", "P. Krishna Pillai", "Sarojini Naidu"],
    correctAnswer: 1,
    explanation: "C. Rajagopalachari",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-10',
    question: "Who led the salt march from Calicut to Payyanur in Malabar (Kerala)?",
    options: ["C. Rajagopalachari", "K. Kelappan", "T. Prakasam", "V.O. Chidambaram Pillai"],
    correctAnswer: 1,
    explanation: "K. Kelappan",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-11',
    question: "The 'Dharasana Salt Works' raid (after Gandhi's arrest) was led by:",
    options: ["Jawaharlal Nehru", "Sarojini Naidu, Imam Sahib, and Manilal Gandhi", "Khan Abdul Ghaffar Khan", "Sardar Patel"],
    correctAnswer: 1,
    explanation: "Sarojini Naidu, Imam Sahib, and Manilal Gandhi",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-12',
    question: "Khan Abdul Ghaffar Khan, also known as 'Frontier Gandhi', organized a volunteer corps called:",
    options: ["Red Shirts (Khuda-i-Khidmatgar)", "Blue Shirts", "Satyagraha Army", "Azad Hind Fauj"],
    correctAnswer: 0,
    explanation: "Red Shirts (Khuda-i-Khidmatgar)",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-13',
    question: "The 'Peshawar Uprising' (1930) was notable because which regiment refused to fire on the unarmed crowds?",
    options: ["Jat Regiment", "Garhwal Rifles", "Sikh Regiment", "Gorkha Rifles"],
    correctAnswer: 1,
    explanation: "Garhwal Rifles",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-14',
    question: "In which state did Rani Gaidinliu lead a rebellion against the British during the Civil Disobedience Movement?",
    options: ["Manipur", "Nagaland", "Assam", "Tripura"],
    correctAnswer: 1,
    explanation: "Nagaland (and Manipur area)",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-15',
    question: "The 'Chaukidari Tax' boycott was a prominent feature of the movement in:",
    options: ["Gujarat", "Bihar and Bengal", "Maharashtra", "Madras"],
    correctAnswer: 1,
    explanation: "Bihar and Bengal",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-16',
    question: "The first Round Table Conference (1930) was held in:",
    options: ["Delhi", "London", "Bombay", "Calcutta"],
    correctAnswer: 1,
    explanation: "London",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-17',
    question: "Which of the following parties did NOT participate in the First Round Table Conference?",
    options: ["Muslim League", "Hindu Mahasabha", "Indian National Congress", "Princely States"],
    correctAnswer: 2,
    explanation: "Indian National Congress",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-18',
    question: "The 'Gandhi-Irwin Pact' was signed in which year?",
    options: ["1930", "1931", "1932", "1933"],
    correctAnswer: 1,
    explanation: "1931 (March 5)",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-19',
    question: "As per the Gandhi-Irwin Pact, the Congress agreed to:",
    options: ["Accept the Rowlatt Act", "Suspend the Civil Disobedience Movement and participate in the Second RTC", "Give up the demand for Purna Swaraj", "Disband the Seva Dal"],
    correctAnswer: 1,
    explanation: "Suspend the movement and participate in the Second RTC",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-20',
    question: "At which Congress session was the Gandhi-Irwin Pact endorsed?",
    options: ["Lahore Session (1929)", "Karachi Session (1931)", "Lucknow Session (1936)", "Faizpur Session (1937)"],
    correctAnswer: 1,
    explanation: "Karachi Session (Presided by Sardar Patel)",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-21',
    question: "In which Round Table Conference did Mahatma Gandhi participate as the sole representative of the Congress?",
    options: ["First RTC", "Second RTC", "Third RTC", "None"],
    correctAnswer: 1,
    explanation: "Second RTC",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-22',
    question: "The 'Communal Award' (1932) was announced by which British Prime Minister?",
    options: ["Winston Churchill", "Ramsay MacDonald", "Clement Attlee", "Neville Chamberlain"],
    correctAnswer: 1,
    explanation: "Ramsay MacDonald",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-23',
    question: "Against which provision of the Communal Award did Gandhi start a fast unto death in Yerwada Jail?",
    options: ["Separate electorates for Muslims", "Separate electorates for the Depressed Classes (Dalits)", "Reservation for Sikhs in Punjab", "Special status for Anglo-Indians"],
    correctAnswer: 1,
    explanation: "Separate electorates for the Depressed Classes",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-24',
    question: "The 'Poona Pact' (1932) was signed between:",
    options: ["Gandhi and Lord Irwin", "Gandhi and B.R. Ambedkar", "Motilal Nehru and Jinnah", "Subhash Bose and Jawaharlal Nehru"],
    correctAnswer: 1,
    explanation: "Gandhi and B.R. Ambedkar",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-25',
    question: "As a result of the Poona Pact, the seats reserved for the Depressed Classes in provincial legislatures were:",
    options: ["Reduced", "Increased from 71 to 147", "Abolished", "Given only in Maharashtra"],
    correctAnswer: 1,
    explanation: "Increased from 71 to 147",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-26',
    question: "Gandhi started the 'All India Anti-Untouchability League' (later Harijan Sevak Sangh) in:",
    options: ["1930", "1932", "1934", "1942"],
    correctAnswer: 1,
    explanation: "1932",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-27',
    question: "The journal started by Gandhi for the upliftment of the depressed classes was named:",
    options: ["Young India", "Harijan", "Navjivan", "Indian Opinion"],
    correctAnswer: 1,
    explanation: "Harijan",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-28',
    question: "The Civil Disobedience Movement was finally withdrawn by Gandhi in:",
    options: ["1931", "1932", "1934", "1947"],
    correctAnswer: 2,
    explanation: "1934",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-29',
    question: "Who was the British Viceroy during the start of the Civil Disobedience Movement and the Dandi March?",
    options: ["Lord Reading", "Lord Irwin", "Lord Willingdon", "Lord Linlithgow"],
    correctAnswer: 1,
    explanation: "Lord Irwin",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-30',
    question: "Which movement in the North West Frontier Province was led by the 'Khuda-i-Khidmatgars'?",
    options: ["Red Shirt Movement", "Blue Shirt Movement", "Quit India Movement", "Home Rule Movement"],
    correctAnswer: 0,
    explanation: "Red Shirt Movement",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-31',
    question: "The 'Karachi Session' of 1931 is also famous for passing a resolution on:",
    options: ["The National Economic Programme and Fundamental Rights", "Immediate Partition", "Abolition of Zamindari", "Formation of the Planning Commission"],
    correctAnswer: 0,
    explanation: "National Economic Programme and Fundamental Rights",
    chapterId: 18,
    difficulty: 'Easy'
  },
  {
    id: '18-32',
    question: "The 'Purna Swaraj' declaration at Lahore (1929) marked a major shift in Congress's goal. Which of the following was a direct consequence of this shift?",
    options: ["The Congress leaders resigned from all provincial and central legislatures to prepare for a mass movement.", "The Congress formally merged with the Muslim League.", "The British government immediately offered Dominion Status.", "The Congress decided to participate in the First Round Table Conference."],
    correctAnswer: 0,
    explanation: "Resignation from legislatures. To give meaning to 'Complete Independence', the Congress called for the boycott of legislatures and fixed January 26 as Independence Day.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-33',
    question: "Why did Gandhi choose 'Salt' as the central formula for the Civil Disobedience Movement?",
    options: ["Salt was the most expensive commodity in the British Empire.", "It was a commodity used by every Indian, from the poorest to the richest, making it a powerful symbol of common suffering under an unjust law.", "The British had requested Gandhi to help them regulate salt production.", "Only the Brahmins were allowed to produce salt under British law."],
    correctAnswer: 1,
    explanation: "Symbol of common suffering.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-34',
    question: "Consider the following statements regarding the 'Dandi March': 1. Gandhi gave the 'Eleven Demands' to Lord Irwin before starting the march. 2. The march was extensively covered by the international press, significantly damaging British moral prestige. 3. The movement remained strictly restricted to the coastline of Gujarat. Which of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2, and 3"],
    correctAnswer: 0,
    explanation: "1 and 2 only Statement 3 is incorrect. While the march was in Gujarat, it triggered illegal salt making and law-breaking across the entire country.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-35',
    question: "The 'Civil Disobedience Movement' (CDM) differed from the 'Non-Cooperation Movement' (NCM) because:",
    options: ["NCM involved the boycott of foreign goods, while CDM involved the deliberate breaking of laws (Civil Disobedience).", "CDM was strictly non-violent, while NCM was a violent movement.", "CDM was led by the Extremists, while NCM was led by the Moderates.", "NCM was only for Hindus, while CDM was only for Muslims."],
    correctAnswer: 0,
    explanation: "CDM involved the deliberate breaking of laws.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-36',
    question: "With reference to the 'Red Shirts' (Khuda-i-Khidmatgar), consider the following: Statement-I: They were a non-violent group in the North-West Frontier Province that strongly supported the Congress and the CDM. Statement-II: Their leader, Khan Abdul Ghaffar Khan, advocated for the creation of a separate independent state for Pathans outside of India. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 1,
    explanation: "Statement-I is correct. Statement-II is incorrect; the Khuda-i-Khidmatgars were committed to Indian unity and the national movement, not a separate state.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-37',
    question: "The 'Chaukidari Tax' boycott in Bihar and Bengal was a response to:",
    options: ["The lack of police protection in rural areas.", "The inability of peasants to pay salt tax in inland areas, leading them to target other visible symbols of British local administration.", "The order of the British King to double the tax.", "The demand for the return of the Mughals."],
    correctAnswer: 1,
    explanation: "Targeted other symbols of local administration.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-38',
    question: "During the CDM, the 'Forest Laws' were defied in which of the following regions?",
    options: ["Punjab and Sindh", "Central Provinces, Maharashtra, and Karnataka", "Bengal and Assam", "Manipur and Nagaland"],
    correctAnswer: 1,
    explanation: "Central Provinces, Maharashtra, and Karnataka.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-39',
    question: "The 'Gandhi-Irwin Pact' (1931) was criticized by younger Congress leaders like Nehru and Bose because:",
    options: ["It gave too much power to the Muslim League.", "It did not secure the commutation of the death sentences of Bhagat Singh, Rajguru, and Sukhdev.", "It abolished the Congress Working Committee.", "It forced Gandhi to leave India permanently."],
    correctAnswer: 1,
    explanation: "Did not secure commutation for Bhagat Singh and comrades.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-40',
    question: "The 'Karachi Session' (1931) is significant for passing a resolution on 'Fundamental Rights'. Which of the following was a feature of that resolution?",
    options: ["Freedom of speech and press.", "Right to form associations and equality before the law.", "Protection of minority rights and neutral state regarding religion.", "All of the above."],
    correctAnswer: 3,
    explanation: "All of the above.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-41',
    question: "Why did the 'Second Round Table Conference' fail to achieve a constitutional breakthrough?",
    options: ["Because Gandhi was arrested in London.", "Because of the deadlock over the issue of 'Separate Electorates' for minorities, with various groups demanding their own quotas.", "Because the British King refused to meet the Indian delegates.", "Because the Congress refused to attend the conference."],
    correctAnswer: 1,
    explanation: "Deadlock over Separate Electorates.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-42',
    question: "The 'Communal Award' (1932) by Ramsay MacDonald treated which of the following as a 'minority' for the first time in terms of electorates?",
    options: ["The Depressed Classes (Dalits)", "The Jains", "The Marathas", "The Parsees"],
    correctAnswer: 0,
    explanation: "The Depressed Classes.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-43',
    question: "The 'Poona Pact' (1932) replaced 'Separate Electorates' for Depressed Classes with:",
    options: ["No representation at all.", "'Reserved Seats' within the general electorates, with an increased number of seats compared to the Communal Award.", "A separate country in South India.", "Direct appointment by the British Governor."],
    correctAnswer: 1,
    explanation: "Reserved Seats within general electorates.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-44',
    question: "How did the participation of women in CDM compare to NCM?",
    options: ["It was significantly higher, with women picketing liquor shops and foreign cloth stores on a massive scale.", "It was lower because Gandhi banned women from joining the Dandi March.", "It was the same.", "Women only participated in the revolutionary phase, not CDM."],
    correctAnswer: 0,
    explanation: "Significantly higher participation.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-45',
    question: "The 'No-Rent' and 'No-Revenue' campaigns in the United Provinces (UP) were unique because:",
    options: ["They were led by British officers.", "They combined the grievances of the tenants (against Zamindars) and the landlords (against the Government).", "They were strictly restricted to the cities.", "They were based on the American model of taxation."],
    correctAnswer: 1,
    explanation: "Combined grievances of tenants and landlords.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-46',
    question: "The 'Third Round Table Conference' (1932) was attended by:",
    options: ["All major Indian parties including the Congress.", "Only the loyalists, some princely states, and a few minority representatives; the Congress boycotted it.", "Only Mahatma Gandhi and Ambedkar.", "Only the British Labour Party."],
    correctAnswer: 1,
    explanation: "Congress boycotted it.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-47',
    question: "The 'August Offer' of the CDM era was actually the 'Irwin Declaration' (1929). What did it vaugely promise?",
    options: ["Immediate independence.", "That \"Dominion Status\" was the natural issue of India's constitutional progress.", "The partition of India.", "The return of the Koh-i-noor."],
    correctAnswer: 1,
    explanation: "Dominion Status as the natural issue.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-48',
    question: "In the 'North-West Frontier Province' (NWFP), the government's repression was so severe that it declared:",
    options: ["Martial Law in Peshawar.", "Total independence for Pathans.", "The NWFP as part of Afghanistan.", "Gandhi as the King of Peshawar."],
    correctAnswer: 0,
    explanation: "Martial Law in Peshawar.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-49',
    question: "Consider the following regarding the 'Vaikom Satyagraha' (1924-25) and its relation to Gandhi: 1. It was a struggle for the right of untouchables to use the roads near the Vaikom temple. 2. Gandhi visited Vaikom and supported the movement, which set the stage for his later Harijan work. 3. The movement resulted in the total abolition of the caste system in Kerala. Which of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2, and 3"],
    correctAnswer: 0,
    explanation: "1 and 2 only.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-50',
    question: "The 'Hindustan Socialist Republican Association' (HSRA) members' activities during the early CDM period were intended to:",
    options: ["Support the non-violent CDM directly.", "Take revenge for the death of Lala Lajpat Rai and utilize the atmosphere of mass unrest to trigger a revolution.", "Join the British police force.", "Arrest Mahatma Gandhi."],
    correctAnswer: 1,
    explanation: "Take revenge and trigger revolution.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-51',
    question: "Why did Gandhi resume the Civil Disobedience Movement in 1932 after returning from the Second RTC?",
    options: ["Because he missed the jail life.", "Because the new Viceroy, Lord Willingdon, had unleashed a policy of \"Civil Martial Law\" and repression against Congress workers.", "Because the British government gave him too much money.", "Because Jinnah requested him to do so."],
    correctAnswer: 1,
    explanation: "Repression under Lord Willingdon.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-52',
    question: "The 'Garhwal Rifles' episode in Peshawar demonstrated:",
    options: ["The military superiority of the British.", "The growing nationalism among Indian soldiers who refused to fire on their own countrymen.", "The failure of the Red Shirt movement.", "The start of the First World War."],
    correctAnswer: 1,
    explanation: "Growing nationalism among Indian soldiers.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-53',
    question: "The 'Communal Award' was seen by Gandhi as a tool for:",
    options: ["Empowering the Dalits.", "Dividing the Hindu community permanently and creating a rift within the national movement.", "Helping the Congress win elections.", "Abolishing the separate electorates for Muslims."],
    correctAnswer: 1,
    explanation: "Dividing the Hindu community.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-54',
    question: "In the 'Karachi Session' (1931), the Congress for the first time defined what?",
    options: ["The flag of Pakistan.", "The meaning of 'Swaraj' for the masses, including economic and civil liberties.", "The method of bomb-making.", "The role of the British King in India."],
    correctAnswer: 1,
    explanation: "Meaning of Swaraj for the masses.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-55',
    question: "The 'Dharasana Salt Satyagraha' was described by the American journalist Webb Miller as:",
    options: ["A peaceful picnic.", "One of the most horrifying scenes of police brutality against non-violent protesters he had ever witnessed.", "A victory for the British police.", "A religious festival."],
    correctAnswer: 1,
    explanation: "Horrifying police brutality against non-violent protesters.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-56',
    question: "Who was the President of the Congress during the second phase of the CDM (1932)?",
    options: ["Mahatma Gandhi", "Vallabhbhai Patel (In jail, others acted as substitutes)", "Madan Mohan Malaviya", "Jawaharlal Nehru"],
    correctAnswer: 1,
    explanation: "Vallabhbhai Patel (Technically, though the Congress was declared illegal).",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-57',
    question: "The 'White Paper' published in 1933 after the RTCs became the basis for:",
    options: ["The Nehru Report.", "The Government of India Act, 1935.", "The Indian Independence Act.", "The Quit India Resolution."],
    correctAnswer: 1,
    explanation: "Government of India Act, 1935.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-58',
    question: "The 'Harijan' movement launched by Gandhi in 1932 aimed at:",
    options: ["Converting Dalits to Christianity.", "Internal reform of Hindu society to abolish untouchability and improve the living conditions of the depressed classes.", "Fighting for separate electorates for Dalits.", "Promoting the use of foreign cloth among Dalits."],
    correctAnswer: 1,
    explanation: "Internal reform to abolish untouchability.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-59',
    question: "Which of the following describes the attitude of the Muslim League during the CDM?",
    options: ["They joined the movement in large numbers.", "They generally stayed away, influenced by the communal propaganda that CDM was a 'Hindu' movement for 'Hindu Raj'.", "they were the main leaders of the Dandi March.", "They demanded the immediate release of Gandhi."],
    correctAnswer: 1,
    explanation: "Generally stayed away.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-60',
    question: "The 'Nagpur Pact' (later in history, but related to provincial politics) vs the 'Poona Pact'\u2014which one was signed in 1932?",
    options: ["Nagpur Pact", "Poona Pact", "Lucknow Pact", "Gandhi-Irwin Pact"],
    correctAnswer: 1,
    explanation: "Poona Pact.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-61',
    question: "Ultimately, the CDM (1930-34) was successful in:",
    options: ["Achieving Purna Swaraj immediately.", "Mobilizing the masses on an even larger scale than NCM and making the British realize that they could no longer rule India without the consent of the Indians.", "Convincing Ambedkar to join the Congress permanently.", "Ending the First World War."],
    correctAnswer: 1,
    explanation: "Large scale mass mobilization.",
    chapterId: 18,
    difficulty: 'Moderate'
  },
  {
    id: '18-62',
    question: "Consider the following statements regarding the 'Purna Swaraj' resolution of 1929: 1. It authorized the Congress Working Committee to launch a program of Civil Disobedience including non-payment of taxes. 2. It declared that the \"Emperor of India\" was no longer recognized as the sovereign. 3. It called upon all members of legislatures to resign their seats immediately. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two (Statements 1 and 3 are correct. The resolution didn't technically address the legal person of the Emperor but rejected British sovereignty over India as a whole.)",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-63',
    question: "With reference to Gandhi\u2019s 'Eleven Demands' (1930), which of the following were included? 1. 50% reduction in land revenue. 2. Abolition of the Salt Tax and government salt monopoly. 3. Protection of the indigenous textile industry through tariffs. 4. Total prohibition of intoxicants. Select the correct answer using the code given below:",
    options: ["1, 2, and 4 only", "2 and 3 only", "1, 3, and 4 only", "All of the above"],
    correctAnswer: 3,
    explanation: "All of the above.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-64',
    question: "Regarding the 'Dandi March', consider the following: Statement-I: The march was strategic in timing, coinciding with the \"National Week\" commemorating the Jallianwala Bagh massacre. Statement-II: Gandhi chose the salt law because it was the most significant source of revenue for the British Indian government. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 1,
    explanation: "Statement-I is correct. (Statement-II is incorrect; salt revenue was a small fraction of total revenue, but its psychological impact was immense.)",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-65',
    question: "Arrange the following regional Civil Disobedience activities in correct chronological order: 1. Raid on the Dharasana Salt Works. 2. Chittagong Armoury Raid. 3. Vedaranyam Salt Satyagraha. 4. Peshawar Uprising (Garhwal Rifles episode). Select the correct answer using the code given below:",
    options: ["4 \u2014 2 \u2014 3 \u2014 1", "2 \u2014 4 \u2014 3 \u2014 1", "4 \u2014 3 \u2014 2 \u2014 1", "2 \u2014 3 \u2014 4 \u2014 1"],
    correctAnswer: 0,
    explanation: "4 \u2014 2 \u2014 3 \u2014 1 (Peshawar: April 23; Chittagong: April 18; Vedaranyam: April 30; Dharasana: May 21).",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-66',
    question: "The 'Chaukidari Tax' agitation in Bihar during CDM was unique because:",
    options: ["It led to the mass resignation of village officials (Chaukidars and Dafadars).", "It was the first time the British used air strikes against peasants.", "It was led exclusively by the Muslim League.", "The tax was replaced by a voluntary \"Gandhi Tax.\""],
    correctAnswer: 0,
    explanation: "Mass resignation of village officials.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-67',
    question: "Consider the following pairs of leaders and their respective CDM activities: 1. Surya Sen \u2014 Indian Republican Army (Chittagong) 2. K. Kelappan \u2014 Vaikom Satyagraha (1924) & Payyanur March (1930) 3. P. Krishna Pillai \u2014 Defending the National Flag in Calicut 4. Sarojini Naidu \u2014 Dharasana Raid How many of the above pairs are correctly matched?",
    options: ["Only one pair", "Only two pairs", "Only three pairs", "All four pairs"],
    correctAnswer: 3,
    explanation: "All four pairs.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-68',
    question: "With reference to the 'First Round Table Conference', consider the following statements: 1. It was the first conference where Indians and Britishers met as \"equals\" in status. 2. The Congress boycotted it, but the Princely States, Muslim League, and Hindu Mahasabha attended. 3. It reached a definitive agreement on the federation and the communal question. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two (Statement 3 is incorrect; it failed to resolve the communal deadlock).",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-69',
    question: "The 'Gandhi-Irwin Pact' allowed for: 1. The immediate release of all political prisoners, including those convicted of violence. 2. The right to make salt for personal consumption in coastal villages. 3. Peaceful picketing of liquor and foreign cloth shops. Select the correct answer using the code given below:",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "All of the above"],
    correctAnswer: 1,
    explanation: "2 and 3 only (Prisoners convicted of violence were not released).",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-70',
    question: "Why did the 'Second Round Table Conference' lead to Gandhi\u2019s disillusionment?",
    options: ["The British government refused to discuss the Gandhi-Irwin Pact.", "The minorities (Muslims, Depressed Classes, Christians) formed a \"Minorities Pact\" demanding separate electorates, which Gandhi viewed as an attempt to fragment India.", "Gandhi was denied permission to speak in Hindi.", "The conference was moved from London to Paris."],
    correctAnswer: 1,
    explanation: "The Minorities Pact and the separate electorates deadlock.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-71',
    question: "The 'Karachi Session' (1931) resolution on Fundamental Rights included which of the following? 1. Neutrality of the state in regard to all religions. 2. Protection of women workers and adequate wage for laborers. 3. Total control of key industries by the state. 4. Universal adult franchise. Select the correct answer using the code given below:",
    options: ["1, 2, and 4 only", "2, 3, and 4 only", "1 and 3 only", "All of the above"],
    correctAnswer: 3,
    explanation: "All of the above.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-72',
    question: "Regarding the 'Communal Award' (1932), which of the following statements is/are correct? 1. It treated the Depressed Classes as a minority community entitled to separate electorates. 2. It was based on the findings of the Lothian Committee on Franchise. 3. It was rejected by the Muslim League. Select the correct answer using the code given below:",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "All of the above"],
    correctAnswer: 0,
    explanation: "1 and 2 only (The League generally accepted the Award as it protected their interests).",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-73',
    question: "The 'Poona Pact' modified the Communal Award by:",
    options: ["Abolishing seats for Dalits.", "Giving Dalits 147 seats in provincial legislatures under joint electorates instead of 71 under separate electorates.", "Making Ambedkar the President of the Congress.", "Allowing Dalits to vote only in local elections."],
    correctAnswer: 1,
    explanation: "147 seats under joint electorates.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-74',
    question: "Consider the following regarding the 'Harijan' tour of Gandhi (1933-34): 1. He traveled over 20,000 km across India. 2. He faced opposition from orthodox Hindus (Sanatanists). 3. He argued that Shastras did not support untouchability. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-75',
    question: "The 'Civil Disobedience Movement' in the NWFP saw the 'Red Shirts' adopting which unique tactic?",
    options: ["Use of guerrilla warfare in the mountains.", "Strict adherence to non-violence despite extreme martial law and humiliation by the British.", "Use of local radio to broadcast secret messages.", "Alliance with the Soviet Union."],
    correctAnswer: 1,
    explanation: "Strict non-violence under extreme provocation.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-76',
    question: "In the United Provinces (UP), the 'No-Rent' campaign was particularly effective because:",
    options: ["The Congress managed to bridge the gap between small landlords and tenants against the high revenue demands of the state.", "The British government voluntarily halved the rent.", "The Russian Bolsheviks provided financial aid.", "The movement was led by the British Governor."],
    correctAnswer: 0,
    explanation: "Bridged the gap between landlords and tenants.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-77',
    question: "Match the following 'Round Table' features: 1. First RTC \u2014",
    options: ["Gandhi as sole Congress representative 2. Second RTC \u2014", "Discussed the Communal Award 3. Third RTC \u2014", "Total Congress Boycott Select the correct matching code:", "1-B, 2-A, 3-C"],
    correctAnswer: 0,
    explanation: "1-B, 2-A, 3-C.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-78',
    question: "The 'Independence Day Pledge' (January 26, 1930) stated that the most \"unpardonable sin\" of the British was:",
    options: ["The introduction of English education.", "The economic, political, cultural, and spiritual ruin of India.", "The partition of Bengal.", "The arrest of the Ali brothers."],
    correctAnswer: 1,
    explanation: "Economic, political, cultural, and spiritual ruin.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-79',
    question: "Consider the following statements about 'Rani Gaidinliu': 1. She led the Heraka religious movement which turned into a political rebellion against the British. 2. Jawaharlal Nehru gave her the title of 'Rani'. 3. She was released from jail immediately after the Gandhi-Irwin Pact. Which of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2, and 3"],
    correctAnswer: 0,
    explanation: "1 and 2 only (She was released only in 1947 after independence).",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-80',
    question: "During the CDM, the 'National Flag' became a major symbol of defiance. In which city did T. Prakasam lead a \"defiance of the flag\" protest?",
    options: ["Bombay", "Madras", "Calcutta", "Delhi"],
    correctAnswer: 1,
    explanation: "Madras.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-81',
    question: "The 'Salt Satyagraha' was more successful than the NCM in terms of:",
    options: ["Immediate independence.", "Bringing in the participation of the merchant class and women on an unprecedented scale.", "Abolishing the Muslim League.", "Preventing the Second World War."],
    correctAnswer: 1,
    explanation: "Participation of merchants and women.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-82',
    question: "The 'White Paper' of 1933 was criticized by the Congress because:",
    options: ["It was written on cheap paper.", "It outlined a constitutional scheme that ignored the demand for 'Responsible Government' at the center.", "It proposed the partition of India.", "It banned the Khadi industry."],
    correctAnswer: 1,
    explanation: "Ignored responsible government at the center.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-83',
    question: "In the Second RTC, Gandhi\u2019s insistence on being the \"sole representative\" of India was challenged by:",
    options: ["B.R. Ambedkar (for Depressed Classes).", "Muhammad Ali Jinnah (for Muslims).", "The Princely States.", "All of the above."],
    correctAnswer: 3,
    explanation: "All of the above.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-84',
    question: "The 'Dharasana Raid' was significant because it proved to the world that:",
    options: ["Indians were capable of extreme violence.", "The British claim of \"civilizing\" India was a sham in the face of their brutal treatment of non-violent Satyagrahis.", "The Salt tax was profitable.", "Gandhi was not in control of the movement."],
    correctAnswer: 1,
    explanation: "Exposed the brutality of British rule.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-85',
    question: "Consider the following regarding the 'August Offer' (not the 1940 one, but the 1932 Communal Award context): Statement-I: Gandhi viewed the separation of Depressed Classes from the Hindu fold as a \"perpetual bar\" to their upliftment. Statement-II: Ambedkar viewed separate electorates as the only way to ensure political safeguards for the untouchables. Which one is correct?",
    options: ["Both are correct and reflect the core of the Poona Pact conflict.", "Statement-I is false.", "Statement-II is false.", "Both are false."],
    correctAnswer: 0,
    explanation: "Both are correct.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-86',
    question: "Which of the following groups participated in the CDM but in smaller numbers compared to the NCM?",
    options: ["Women", "Students", "Muslims (due to communal tension and League propaganda)", "Urban laborers"],
    correctAnswer: 2,
    explanation: "Muslims.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-87',
    question: "The 'Forest Satyagraha' in the Central Provinces involved:",
    options: ["Burning down all forests.", "Deliberately violating the restrictive forest laws that prevented grazing and wood-cutting.", "Planting only Neem trees.", "Hunting tigers in British zones."],
    correctAnswer: 1,
    explanation: "Violating restrictive forest laws.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-88',
    question: "The 'Poona Pact' is often cited as a compromise where:",
    options: ["Gandhi won legally, but Ambedkar won morally.", "Both sides gave up something to prevent the fragmentation of Hindu society while ensuring Dalit representation.", "The British government was the mediator.", "It led to the immediate end of the CDM."],
    correctAnswer: 1,
    explanation: "Balanced Dalit representation with Hindu unity.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-89',
    question: "The 'Third Round Table Conference' ended with:",
    options: ["A treaty of independence.", "No major Indian leader present and a final report that led to the 1935 Act.", "A dinner with the King.", "The arrest of Ambedkar."],
    correctAnswer: 1,
    explanation: "Led to the 1935 Act without major nationalist input.",
    chapterId: 18,
    difficulty: 'Hard'
  },
  {
    id: '18-90',
    question: "What was the 'Yervada Pact' another name for?",
    options: ["Gandhi-Irwin Pact", "Poona Pact", "Lucknow Pact", "Shimla Agreement"],
    correctAnswer: 1,
    explanation: "Poona Pact (Signed in Yervada Jail).",
    chapterId: 18,
    difficulty: 'Hard'
  },
];