import { MCQ } from '../RevisionRegistry';

export const CHAPTER_89_MCQS: MCQ[] = [
    {
        id: 1,

        question: "UIDAI was originally created in 2009 as an attached office of which body?",
        options: ["Home Ministry", "Finance Ministry", "Planning Commission", "Election Commission"],
        correctAnswer: 2,
        explanation: "It was under the Planning Commission (now NITI Aayog).",
        difficulty: "easy"
    },
    {
        id: 2,

        question: "The Aadhaar Act was passed in which year to give UIDAI statutory status?",
        options: ["2009", "2012", "2014", "2016"],
        correctAnswer: 3,
        explanation: "The Aadhaar Act, 2016 provides the legal framework.",
        difficulty: "easy"
    },
    {
        id: 3,

        question: "Aadhaar is a proof of:",
        options: ["Citizenship", "Domicile", "Identity", "Both A and C"],
        correctAnswer: 2,
        explanation: "It is strictly a proof of identity and residence, not citizenship.",
        difficulty: "medium"
    },
    {
        id: 4,

        question: "The 12-digit Aadhaar number is:",
        options: ["Chronological", "Random", "Sequential", "Area-based"],
        correctAnswer: 1,
        explanation: "It is a unique random number generated by the system.",
        difficulty: "medium"
    },
    {
        id: 5,

        question: "Under the SC 2018 judgement, Aadhaar is mandatory for:",
        options: ["Bank Accounts", "Mobile SIM", "PAN and IT Returns", "School Admissions"],
        correctAnswer: 2,
        explanation: "Mandatory for PAN linking and tax filing.",
        difficulty: "easy"
    },
    {
        id: 6,

        question: "Which of the following is NOT demographic data for Aadhaar?",
        options: ["Name", "Gender", "Caste", "Address"],
        correctAnswer: 2,
        explanation: "Aadhaar does not collect caste or religion data.",
        difficulty: "medium"
    },
    {
        id: 7,

        question: "To get an Aadhaar, a resident must have lived in India for at least:",
        options: ["90 days", "120 days", "182 days", "365 days"],
        correctAnswer: 2,
        explanation: "182 days or more in the 12 months immediately preceding the application.",
        difficulty: "hard"
    },
    {
        id: 8,

        question: "The Authority (UIDAI) is currently under which Ministry?",
        options: ["Home Affairs", "Finance", "Social Justice", "Electronics and IT"],
        correctAnswer: 3,
        explanation: "MeitY is the parent ministry.",
        difficulty: "easy"
    },
    {
        id: 9,

        question: "The Central Identities Data Repository (CIDR) is managed by:",
        options: ["RBI", "Google", "UIDAI", "NIC"],
        correctAnswer: 2,
        explanation: "UIDAI manages the CIDR database.",
        difficulty: "medium"
    },
    {
        id: 10,

        question: "Virtual ID (VID) is a ________ digit temporary number to protect privacy.",
        options: ["10", "12", "16", "20"],
        correctAnswer: 2,
        explanation: "Virtual ID is a 16-digit random number to be used instead of actual Aadhaar.",
        difficulty: "hard"
    }
];

export default CHAPTER_89_MCQS;
