// Auto-generated by Antigravity Script
import { Question } from '../../../../types';

export const MODERN_CHAPTER_11_MCQS: any[] = [
  {
    id: '10-91',
    question: "Ultimately, the 'Beginning of Modern Nationalism' in India (Chapter 10) teaches us that:",
    options: ["Nationalism was a gift from the British.", "Nationalism was a reaction to the exploitative and discriminatory nature of colonial rule, organized by the emerging modern Indian intelligentsia.", "The Indian National Congress was founded to help the British rule longer.", "There was no nationalism in India before 1947."],
    correctAnswer: 1,
    explanation: "Nationalism was a reaction to colonial rule organized by the intelligentsia.",
    chapterId: 10,
    difficulty: 'Hard'
  },
  {
    id: '11-2',
    question: "The formal proclamation of the Swadeshi Movement was made on August 7, 1905, at:",
    options: ["Gokuldas Tejpal Sanskrit College, Bombay", "Town Hall, Calcutta", "Federation Hall, Calcutta", "Barisal Conference"],
    correctAnswer: 1,
    explanation: "Town Hall, Calcutta",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-3',
    question: "Who was the Viceroy of India when the Partition of Bengal was announced in 1905?",
    options: ["Lord Minto", "Lord Curzon", "Lord Hardinge", "Lord Chelmsford"],
    correctAnswer: 1,
    explanation: "Lord Curzon",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-4',
    question: "According to the government, what was the official reason for the partition of Bengal?",
    options: ["To curb the rising tide of nationalism", "Administrative convenience due to the large size of the province", "To create a Muslim-majority province", "To promote industrialization in East Bengal"],
    correctAnswer: 1,
    explanation: "Administrative convenience",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-5',
    question: "The day the partition of Bengal took effect was declared as a day of mourning throughout Bengal. What was that date?",
    options: ["July 4, 1905", "August 7, 1905", "October 16, 1905", "December 12, 1905"],
    correctAnswer: 2,
    explanation: "October 16, 1905",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-6',
    question: "During the Swadeshi Movement, who suggested that the day of partition be observed as Raksha Bandhan to symbolize unity?",
    options: ["Surendranath Banerjea", "Rabindranath Tagore", "Aurobindo Ghosh", "Anandamohan Bose"],
    correctAnswer: 1,
    explanation: "Rabindranath Tagore",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-7',
    question: "Which famous song composed by Rabindranath Tagore during this period later became the national anthem of Bangladesh?",
    options: ["Vande Mataram", "Jana Gana Mana", "Amar Sonar Bangla", "Saare Jahan Se Achha"],
    correctAnswer: 2,
    explanation: "Amar Sonar Bangla",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-8',
    question: "Who was the President of the Banaras session of the Indian National Congress in 1905?",
    options: ["Dadabhai Naoroji", "Gopal Krishna Gokhale", "Bal Gangadhar Tilak", "Pherozeshah Mehta"],
    correctAnswer: 1,
    explanation: "Gopal Krishna Gokhale",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-9',
    question: "In the 1906 Calcutta session, the goal of the Indian National Congress was defined as 'Swaraj'. Who was the President of this session?",
    options: ["Gopal Krishna Gokhale", "Dadabhai Naoroji", "Rashbehari Ghosh", "Bipin Chandra Pal"],
    correctAnswer: 1,
    explanation: "Dadabhai Naoroji",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-10',
    question: "The famous slogan \"Swaraj is my birthright and I shall have it\" was given by:",
    options: ["Lala Lajpat Rai", "Bal Gangadhar Tilak", "Aurobindo Ghosh", "Bhagat Singh"],
    correctAnswer: 1,
    explanation: "Bal Gangadhar Tilak",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-11',
    question: "Who was the founder of the 'Swadesh Bandhab Samiti' in Barisal, which became a powerful medium for mass mobilization?",
    options: ["Ashwini Kumar Datta", "Pulin Das", "Satish Chandra Mukherjee", "Barindra Kumar Ghosh"],
    correctAnswer: 0,
    explanation: "Ashwini Kumar Datta",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-12',
    question: "The National Council of Education was set up in August 1906 to organize a system of education on national lines. Who was its first principal?",
    options: ["Satish Chandra Mukherjee", "Aurobindo Ghosh", "Rabindranath Tagore", "Rashbehari Ghosh"],
    correctAnswer: 1,
    explanation: "Aurobindo Ghosh",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-13',
    question: "In the field of Indian art, who founded the Indian Society of Oriental Art in 1907 to break the hegemony of Victorian naturalism?",
    options: ["Nandalal Bose", "Abanindranath Tagore", "Raja Ravi Varma", "Amrita Sher-Gil"],
    correctAnswer: 1,
    explanation: "Abanindranath Tagore",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-14',
    question: "Who was the leader of the Swadeshi Movement in Delhi?",
    options: ["Lala Lajpat Rai", "Syed Haider Raza", "Chidambaram Pillai", "Ajit Singh"],
    correctAnswer: 1,
    explanation: "Syed Haider Raza",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-15',
    question: "The 'Swadeshi Steam Navigation Company' was established in Tuticorin by:",
    options: ["V.O. Chidambaram Pillai", "Subramania Bharati", "Tirumalachari", "Rajagopalachari"],
    correctAnswer: 0,
    explanation: "V.O. Chidambaram Pillai",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-16',
    question: "The 'Anti-Circular Society' was formed to protest against which government circular that banned students from participating in politics?",
    options: ["Lytton Circular", "Carlyle Circular", "Risley Circular", "Curzon Circular"],
    correctAnswer: 1,
    explanation: "Carlyle Circular",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-17',
    question: "The Surat Split of the Indian National Congress took place in which year?",
    options: ["1905", "1906", "1907", "1909"],
    correctAnswer: 2,
    explanation: "1907",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-18',
    question: "Who was the President of the 1907 Surat session where the Congress split into Moderates and Extremists?",
    options: ["Bal Gangadhar Tilak", "Pherozeshah Mehta", "Rashbehari Ghosh", "Dadabhai Naoroji"],
    correctAnswer: 2,
    explanation: "Rashbehari Ghosh",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-19',
    question: "The 'All India Muslim League' was founded in 1906 under the leadership of:",
    options: ["Muhammad Ali Jinnah", "Nawab Salimullah of Dacca", "Syed Ahmed Khan", "Aga Khan III"],
    correctAnswer: 1,
    explanation: "Nawab Salimullah of Dacca",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-20',
    question: "The Morley-Minto Reforms were enacted in which year?",
    options: ["1905", "1907", "1909", "1911"],
    correctAnswer: 2,
    explanation: "1909",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-21',
    question: "Which feature of the Morley-Minto Reforms was most criticized by nationalists for sowing the seeds of communalism?",
    options: ["Increase in the number of elected members", "Introduction of Separate Electorates for Muslims", "Right to ask supplementary questions", "Inclusion of an Indian in the Viceroy's Executive Council"],
    correctAnswer: 1,
    explanation: "Introduction of Separate Electorates for Muslims",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-22',
    question: "Who was the first Indian to be appointed to the Viceroy\u2019s Executive Council?",
    options: ["Satyendra Prasad Sinha", "Badruddin Tyabji", "Dadabhai Naoroji", "Rashbehari Ghosh"],
    correctAnswer: 0,
    explanation: "Satyendra Prasad Sinha",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-23',
    question: "The 'Seditious Meetings Act' and the 'Indian Newspapers (Incitement to Offences) Act' were passed in 1907-1908 to:",
    options: ["Promote social reform", "Curb the militant nationalist activities", "Increase the land revenue", "Protect the British factories"],
    correctAnswer: 1,
    explanation: "Curb the militant nationalist activities",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-24',
    question: "In 1908, Bal Gangadhar Tilak was sentenced to six years of imprisonment and sent to:",
    options: ["Cellular Jail, Andaman", "Mandalay Jail, Burma", "Yerwada Jail, Pune", "Alipore Jail, Calcutta"],
    correctAnswer: 1,
    explanation: "Mandalay Jail, Burma",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-25',
    question: "Who wrote the famous series of articles titled 'New Lamps for Old' criticizing the Moderate politics of the Congress?",
    options: ["Bal Gangadhar Tilak", "Bipin Chandra Pal", "Aurobindo Ghosh", "Lala Lajpat Rai"],
    correctAnswer: 2,
    explanation: "Aurobindo Ghosh",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-26',
    question: "The Ganapati and Shivaji festivals were used for national propaganda in Maharashtra by:",
    options: ["Gopal Ganesh Agarkar", "M.G. Ranade", "Bal Gangadhar Tilak", "V.D. Savarkar"],
    correctAnswer: 2,
    explanation: "Bal Gangadhar Tilak",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-27',
    question: "Which revolutionary group was founded by Barindra Kumar Ghosh and Bhupendranath Datta in Bengal?",
    options: ["Anushilan Samiti", "Jugantar", "Abhinav Bharat", "Ghadar Party"],
    correctAnswer: 1,
    explanation: "Jugantar",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-28',
    question: "The partition of Bengal was eventually annulled in which year?",
    options: ["1909", "1911", "1914", "1919"],
    correctAnswer: 1,
    explanation: "1911",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-29',
    question: "In 1911, the capital of British India was shifted from Calcutta to:",
    options: ["Bombay", "Madras", "Delhi", "Simla"],
    correctAnswer: 2,
    explanation: "Delhi",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-30',
    question: "Which Moderate leader was referred to as the 'Lion of Bombay'?",
    options: ["Dadabhai Naoroji", "Pherozeshah Mehta", "K.T. Telang", "Badruddin Tyabji"],
    correctAnswer: 1,
    explanation: "Pherozeshah Mehta",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-31',
    question: "Who criticized the Swadeshi Movement for its \"excessive focus on symbols\" and called for a more constructive work in villages (Atmashakti)?",
    options: ["Surendranath Banerjea", "Rabindranath Tagore", "Aurobindo Ghosh", "Bipin Chandra Pal"],
    correctAnswer: 1,
    explanation: "Rabindranath Tagore",
    chapterId: 11,
    difficulty: 'Easy'
  },
  {
    id: '11-32',
    question: "The Partition of Bengal was not merely an administrative measure as claimed by the British. Which of the following best describes the real political motive of Lord Curzon?",
    options: ["To provide better healthcare to the residents of East Bengal.", "To create a rift between Hindus and Muslims and to crush the nerve center of Indian nationalism\u2014Bengal\u2014by dividing it on communal and linguistic lines.", "To prepare Bengal for a direct invasion from the Russian Empire.", "To abolish the Zamindari system in the eastern districts."],
    correctAnswer: 1,
    explanation: "To create a rift between Hindus and Muslims and to crush the nerve center of Indian nationalism.",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-33',
    question: "Consider the following statements regarding the 'Moderate' vs 'Extremist' stance on the Swadeshi Movement: 1. The Moderates wanted to restrict the boycott movement to Bengal only. 2. The Extremists, led by Tilak, wanted to take the movement to other parts of India and transform it into a full-fledged political mass struggle for Swaraj. 3. Both groups agreed to include the boycott of government schools and courts from the very beginning. Which of the statements given above are correct?",
    options: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2, and 3"],
    correctAnswer: 0,
    explanation: "1 and 2 only Statement 3 is incorrect. The Moderates were highly reluctant to include the boycott of schools and courts, which was a major point of contention leading to the Surat Split.",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-34',
    question: "The concept of 'Atmashakti' (Self-reliance) was a significant ideological component of the Swadeshi Movement. Who among the following was the most prominent advocate of this constructive program?",
    options: ["Aurobindo Ghosh", "Rabindranath Tagore", "Lala Lajpat Rai", "Bipin Chandra Pal"],
    correctAnswer: 1,
    explanation: "Rabindranath Tagore Tagore emphasized social and economic regeneration of villages and education in vernacular languages as the true path to freedom.",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-35',
    question: "During the Swadeshi Movement, several national educational institutions were established. Match the following institutions with their associated personalities: 1. National Council of Education \u2014",
    options: ["Satish Chandra Mukherjee 2. Dawn Society \u2014", "Aurobindo Ghosh (First Principal) 3. Bengal National College \u2014", "Rashbehari Ghosh (President) Select the correct matching code:", "1-C, 2-A, 3-B"],
    correctAnswer: 0,
    explanation: "1-C, 2-A, 3-B",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-36',
    question: "The 'Surat Split' of 1907 was a major setback for the nationalist movement. What was the immediate cause of the split during the session?",
    options: ["A dispute over the venue of the next session.", "The disagreement over the candidacy for the President (Rashbehari Ghosh vs. Lala Lajpat Rai) and the inclusion of resolutions on Swadeshi, Boycott, and National Education.", "Tilak\u2019s arrest by the British police inside the pandal.", "The Muslim League's interference in Congress proceedings."],
    correctAnswer: 1,
    explanation: "Disagreement over the Presidency and the core Swadeshi resolutions.",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-37',
    question: "With reference to the 'Morley-Minto Reforms' of 1909, consider the following: Statement-I: The reforms introduced the system of Separate Electorates for Muslims, where only Muslims could vote for Muslim candidates. Statement-II: The primary objective of these reforms was to grant Indians a substantial share in the decision-making process of the government. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 1,
    explanation: "Statement-I is correct but Statement-II is incorrect The real intent (Statement-II) was to divide the nationalist ranks and rally the Moderates and Muslims to the side of the government, not to share power.",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-38',
    question: "The Swadeshi Movement saw the first major participation of women and students in the national struggle. How did the government react to student participation?",
    options: ["By granting them scholarships for higher studies in London.", "By issuing the 'Carlyle Circular', which threatened to withdraw grants and recognition from educational institutions whose students participated in politics.", "By making political education compulsory in all schools.", "By inviting student leaders to the Viceroy's council."],
    correctAnswer: 1,
    explanation: "By issuing the 'Carlyle Circular'.",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-39',
    question: "Consider the following regarding the 'All India Muslim League' founded in 1906: 1. It was founded in Dacca under the leadership of Nawab Salimullah and Aga Khan. 2. It strongly supported the Swadeshi and Boycott movement. 3. Its primary objective was to promote loyalty to the British government and protect Muslim political rights. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statement 2 is incorrect. The Muslim League initially opposed the Swadeshi movement and supported the Partition of Bengal.",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-40',
    question: "Which revolutionary journal famously declared, \"The whole nation must be taught to kill... Every man should have a weapon\"?",
    options: ["Kesari", "Jugantar", "The Bengalee", "The Hindu"],
    correctAnswer: 1,
    explanation: "Jugantar",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-41',
    question: "The Swadeshi Movement significantly impacted the Indian economy. Which of the following was a notable achievement in the industrial sector during this period?",
    options: ["The establishment of the Tata Iron and Steel Company (TISCO) in 1907.", "The complete closure of all British textile mills in Manchester.", "The nationalization of all Indian railways.", "The banning of all foreign investments in India."],
    correctAnswer: 0,
    explanation: "The establishment of the Tata Iron and Steel Company (TISCO) in 1907.",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-42',
    question: "The 'Samyukta Samiti' and the 'Swadesh Bandhab Samiti' were examples of:",
    options: ["British intelligence units.", "Volunteer corps (Samitis) that engaged in social work, physical training, and political propaganda during the Swadeshi movement.", "Religious organizations aimed at converting the British to Hinduism.", "Secret societies manufacturing bombs in London."],
    correctAnswer: 1,
    explanation: "Volunteer corps (Samitis) for mass mobilization.",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-43',
    question: "Consider the following statements about Bal Gangadhar Tilak during the Era of Militant Nationalism: Statement-I: He was the first leader to recognize that the Indian National Movement must be based on a broad social base of the masses. Statement-II: He successfully organized the Ganapati and Shivaji festivals to bridge the gap between the educated elite and the common people. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 0,
    explanation: "Both Statement-I and Statement-II are correct.",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-44',
    question: "In the field of literature, the Swadeshi Movement was characterized by a surge in patriotic writings. Which of the following is correctly matched? 1. Amar Sonar Bangla \u2014 Rabindranath Tagore 2. Vande Mataram \u2014 Bankim Chandra Chatterjee (Used as the anthem of the movement) 3. Swadeshi Geethangal \u2014 Subramania Bharati How many of the above pairs are correctly matched?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three.",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-45',
    question: "The 'Morley-Minto Reforms' allowed for the first time:",
    options: ["The entry of an Indian into the Viceroy's Executive Council.", "The voting rights for all Indian women.", "The establishment of the Supreme Court of India.", "The direct election of the Viceroy."],
    correctAnswer: 0,
    explanation: "The entry of an Indian into the Viceroy's Executive Council (Satyendra Prasad Sinha).",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-46',
    question: "Why did the Swadeshi Movement begin to decline by 1908?",
    options: ["Because the British government granted Purna Swaraj.", "Due to severe government suppression, the split in the Congress, and the lack of an effective leader after Tilak's arrest and Aurobindo's retirement to Pondicherry.", "Because Indians realized that foreign goods were better.", "Because the Marathas launched a new war against the British."],
    correctAnswer: 1,
    explanation: "Government suppression, the split, and leadership vacuum.",
    chapterId: 11,
    difficulty: 'Moderate'
  },
  {
    id: '11-47',
    question: "Consider the following statements regarding the ideological shifts during the Swadeshi Movement: 1. The Extremists emphasized 'Atmashakti' (Self-reliance), which involved the social and economic regeneration of villages through indigenous efforts. 2. Aurobindo Ghosh advocated for 'Passive Resistance', which included the boycott of government schools, courts, and the refusal to pay taxes. 3. The Moderates viewed the boycott of foreign goods as a permanent political weapon to be used across India to achieve 'Purna Swaraj'. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 2 are correct. Statement 3 is incorrect; the Moderates viewed the boycott as a temporary measure restricted to Bengal to protest the partition, and they were far from demanding 'Purna Swaraj' (Complete Independence) at this stage.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-48',
    question: "With reference to the 'Surat Split' of 1907, consider the following: Statement-I: The Extremists wanted the 1907 session to be held in Nagpur and sought to include resolutions on Swadeshi, Boycott, and National Education. Statement-II: The Moderates shifted the venue to Surat to ensure that Tilak could not be elected as the President, as a local leader could not preside over a session in his own province. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 0,
    explanation: "Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I The venue shift was a tactical move by the Moderates to sideline the Extremist leadership, directly leading to the friction that caused the split.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-49',
    question: "Arrange the following events related to the rise of militant nationalism in the correct chronological order: 1. Foundation of the Anushilan Samiti in Calcutta. 2. The Alipore Conspiracy Case. 3. The attempt on the life of Magistrate Kingsford by Khudiram Bose and Prafulla Chaki. 4. The publication of 'New Lamps for Old' by Aurobindo Ghosh. Select the correct answer using the code given below:",
    options: ["4 \u2014 1 \u2014 3 \u2014 2", "1 \u2014 4 \u2014 2 \u2014 3", "4 \u2014 3 \u2014 1 \u2014 2", "1 \u2014 2 \u2014 4 \u2014 3"],
    correctAnswer: 0,
    explanation: "4 \u2014 1 \u2014 3 \u2014 2 'New Lamps for Old' (1893) -> Anushilan Samiti (1902) -> Muzaffarpur Bombings (April 1908) -> Alipore Conspiracy Case (May 1908).",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-50',
    question: "Consider the following pairs of Swadeshi-era Samitis and their leaders: 1. Swadesh Bandhab Samiti \u2014 Ashwini Kumar Datta 2. Anushilan Samiti (Dacca) \u2014 Pulin Das 3. Anti-Circular Society \u2014 Sachindra Prasad Bose 4. Dawn Society \u2014 Satish Chandra Mukherjee How many of the above pairs are correctly matched?",
    options: ["Only one pair", "Only two pairs", "Only three pairs", "All four pairs"],
    correctAnswer: 3,
    explanation: "All four pairs",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-51',
    question: "Regarding the 'Morley-Minto Reforms' (1909), consider the following statements: 1. The Act effectively increased the number of elected members in both the Imperial and Provincial Legislative Councils. 2. It introduced 'Separate Electorates' for Muslims, which was described by Lord Minto as sowing \"dragon's teeth.\" 3. The reforms granted the councils the power to pass resolutions on the budget and ask supplementary questions. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-52',
    question: "\"He was the first to interpret the Swadeshi Movement as a 'total' movement involving the boycott of all things British. He used the Ganapati and Shivaji festivals as a medium of political propaganda and was the first to suffer imprisonment for the sake of the country.\" The above description refers to:",
    options: ["Lala Lajpat Rai", "Bipin Chandra Pal", "Bal Gangadhar Tilak", "Aurobindo Ghosh"],
    correctAnswer: 2,
    explanation: "Bal Gangadhar Tilak",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-53',
    question: "With reference to the 'National Council of Education' (1906), consider the following: Statement-I: It was established to provide an education system on national lines\u2014literary, scientific, and technical\u2014under national control. Statement-II: The movement for national education was primarily a reaction to the 'Carlyle Circular' which forbade students from participating in the Swadeshi movement. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct and Statement-II is the correct explanation for Statement-I", "Both Statement-I and Statement-II are correct and Statement-II is not the correct explanation for Statement-I", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct"],
    correctAnswer: 0,
    explanation: "Both Statement-I and Statement-II are correct",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-54',
    question: "Consider the following regarding the participation of different social groups in the Swadeshi Movement: 1. The students participated in large numbers, defying government circulars and facing rustication. 2. The movement saw the first major participation of women from urban middle-class families in picketing and processions. 3. The Muslim peasantry of East Bengal overwhelmingly supported the boycott movement against British cloth. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 2 are correct. Statement 3 is incorrect; the Muslim peasantry was largely alienated due to the communal propaganda of the British and the landlord-tenant conflicts, where the landlords were often Hindu and the tenants Muslim.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-55',
    question: "The 'Shimla Deputation' (1906) led by the Aga Khan is significant in Indian history because it:",
    options: ["Demanded the immediate annulment of the Partition of Bengal.", "Led to the formation of the All India Muslim League and the demand for Separate Electorates for Muslims.", "Was a secret meeting to plan the assassination of Lord Curzon.", "Aimed at merging the Muslim League with the Indian National Congress."],
    correctAnswer: 1,
    explanation: "Led to the formation of the Muslim League and demand for Separate Electorates.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-56',
    question: "Consider the following statements regarding the 'Indian Society of Oriental Art' (1907): 1. It was founded by Abanindranath Tagore to promote indigenous art styles. 2. It offered scholarships to Indian students to study Western naturalism in London. 3. Nandalal Bose was the first recipient of the scholarship provided by this society. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 3 are correct. Statement 2 is incorrect; the society aimed to counter Western influence by promoting Pan-Asian and traditional Indian art forms.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-57',
    question: "The 1906 Calcutta session of the INC is considered a tactical victory for the Extremists because:",
    options: ["The Moderates were completely expelled from the party.", "Dadabhai Naoroji, as President, used the word 'Swaraj' and the session passed resolutions on Swadeshi, Boycott, and National Education.", "The British government immediately granted self-rule to India.", "Tilak was appointed as the permanent President of the Congress."],
    correctAnswer: 1,
    explanation: "Naoroji used 'Swaraj' and resolutions on Swadeshi/Boycott were passed.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-58',
    question: "Match the following regions with the leaders of the Swadeshi Movement there: 1. Punjab \u2014",
    options: ["Syed Haider Raza 2. Delhi \u2014", "Lala Lajpat Rai & Ajit Singh 3. Madras \u2014", "V.O. Chidambaram Pillai 4. Andhra \u2014", "Mutnuri Krishna Rao Select the correct code:"],
    correctAnswer: 0,
    explanation: "1-B, 2-A, 3-C, 4-D",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-59',
    question: "With reference to 'Aurobindo Ghosh', consider the following statements: 1. He edited the journal 'Bande Mataram' which became the voice of militant nationalism. 2. He advocated for 'Atmashakti' which emphasized the use of indigenous products and national education. 3. Following the Alipore Conspiracy Case, he retired from politics and moved to Pondicherry to pursue spiritualism. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 2,
    explanation: "All three",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-60',
    question: "The 'Carlyle Circular' (1905) was a tool used by the British government to:",
    options: ["Provide financial aid to Swadeshi schools.", "Threaten educational institutions with the withdrawal of grants and recognition if their students participated in the anti-partition movement.", "Mandate the teaching of the English language in all primary schools.", "Recruit Indian students for the British army."],
    correctAnswer: 1,
    explanation: "Threaten institutions to prevent student participation in politics.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-61',
    question: "Consider the following regarding the 'Tata Iron and Steel Company' (TISCO): Statement-I: Its establishment in 1907 was a hallmark of the Swadeshi spirit of industrial self-reliance. Statement-II: It was heavily funded by the British government to compete with German steel imports. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 1,
    explanation: "Statement-I is correct but Statement-II is incorrect TISCO was an indigenous venture by J.N. Tata, funded by Indian capital, embodying the Swadeshi ideal.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-62',
    question: "The concept of 'Passive Resistance' as defined by the Extremists involved: 1. Boycott of foreign goods. 2. Refusal to assist the British administration in any way. 3. Boycott of government schools and colleges. 4. Armed assassination of British officers. Select the correct answer using the code given below:",
    options: ["1, 2, and 3 only", "2, 3, and 4 only", "1 and 3 only", "All of the above"],
    correctAnswer: 0,
    explanation: "1, 2, and 3 only Passive resistance did not include armed assassinations; that was the domain of the revolutionary terrorists, not the mainstream Extremists like Tilak or Aurobindo.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-63',
    question: "With reference to 'V.O. Chidambaram Pillai', consider the following: Statement-I: He started the 'Swadeshi Steam Navigation Company' to challenge the monopoly of the British India Steam Navigation Company. Statement-II: His efforts were primarily supported by the wealthy British merchants of Madras. Which one of the following is correct in respect of the above statements?",
    options: ["Both Statement-I and Statement-II are correct", "Statement-I is correct but Statement-II is incorrect", "Statement-I is incorrect but Statement-II is correct", "Both Statement-I and Statement-II are incorrect"],
    correctAnswer: 1,
    explanation: "Statement-I is correct but Statement-II is incorrect",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-64',
    question: "The 'annulment' of the Partition of Bengal in 1911 was primarily intended to:",
    options: ["Reward the Extremists for their peaceful conduct.", "Curb the rising revolutionary terrorism and appease the Moderates.", "Punish the Muslims for their loyalty to the British.", "Transfer the capital to Dacca."],
    correctAnswer: 1,
    explanation: "Curb revolutionary terrorism and appease the Moderates.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-65',
    question: "Consider the following regarding the 'All India Muslim League' (1906): 1. Its objectives included promoting loyalty to the British government and protecting the political rights of Muslims. 2. It was initially led by the Aga Khan, Nawab Salimullah of Dacca, and Nawab Mohsin-ul-Mulk. 3. It passed a resolution in its first session supporting the Swadeshi movement and condemning the partition of Bengal. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statement 3 is incorrect; the League initially supported the partition and stayed away from the Swadeshi movement.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-66',
    question: "Which historian used the term 'Lightning Conductor' to describe A.O. Hume's role in the formation of the Congress?",
    options: ["Bipan Chandra", "Gopal Krishna Gokhale (in a contemporary sense)", "R.C. Majumdar", "S.N. Sen"],
    correctAnswer: 1,
    explanation: "Gopal Krishna Gokhale",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-67',
    question: "The 'Seditious Meetings Act' (1907) and the 'Indian Newspapers (Incitement to Offences) Act' (1908) were part of the:",
    options: ["Morley-Minto Reforms.", "Policy of 'Carrot and Stick' used by the British to suppress the Swadeshi movement.", "Montagu-Chelmsford Reforms.", "Ilbert Bill."],
    correctAnswer: 1,
    explanation: "Policy of 'Carrot and Stick'.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-68',
    question: "Consider the following statements regarding 'Lala Lajpat Rai' during the Swadeshi movement: Statement-I: He led the movement in Punjab and was deported to Mandalay along with Ajit Singh in 1907. Statement-II: He was a staunch Moderate who opposed the boycott of foreign cloth. Which one of the following is correct in respect of the above statements? A. Both Statement-I and Statement-II are correct B. Statement-I is correct but Statement-II is incorrect Answer: B. Statement-I is correct",
    options: ["Option A", "Option B", "Option C", "Option D"],
    correctAnswer: 0,
    explanation: "",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-69',
    question: "The 'Anti-Circular Society' was established by students in Bengal primarily to:",
    options: ["Organize the boycott of British salt.", "Provide alternative education to students who were expelled from government schools for participating in the Swadeshi movement.", "Carry out secret assassinations of British officials.", "Distribute free textbooks printed in London."],
    correctAnswer: 1,
    explanation: "Provide alternative education to expelled students.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-70',
    question: "What was the 'Federation Hall' in Calcutta (1905) intended to symbolize?",
    options: ["The absolute power of the British Viceroy.", "The unity of the two Bengals (East and West) despite the partition.", "The headquarters of the Muslim League.", "The first Stock Exchange of India."],
    correctAnswer: 1,
    explanation: "Symbol of the unity of the two Bengals.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-71',
    question: "\"He was a brilliant orator and the third of the 'Lal-Bal-Pal' trio. He popularized the concept of 'Passive Resistance' and was the editor of the journal 'New India'.\" This passage refers to:",
    options: ["Lala Lajpat Rai", "Bipin Chandra Pal", "Bal Gangadhar Tilak", "Aurobindo Ghosh"],
    correctAnswer: 1,
    explanation: "Bipin Chandra Pal",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-72',
    question: "Consider the impact of the Swadeshi Movement on Indian culture: 1. Use of traditional folk theatre like 'Jatras' for political propaganda. 2. Growth of patriotic poetry in vernacular languages (e.g., Rabindranath Tagore, Mukunda Das). 3. The absolute decline of all classical Indian dance forms. How many of the above statements are correct?",
    options: ["Only one", "Only two", "All three", "None"],
    correctAnswer: 1,
    explanation: "Only two Statements 1 and 2 are correct. The movement actually revitalized interest in Indian culture rather than causing a decline.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-73',
    question: "The 'Morley-Minto Reforms' were named after:",
    options: ["Two British revolutionary leaders.", "The Secretary of State for India and the Viceroy of India respectively.", "Two Indian leaders who negotiated with the Queen.", "The two architects who built the New Delhi capital."],
    correctAnswer: 1,
    explanation: "Secretary of State (Morley) and Viceroy (Minto).",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-74',
    question: "In the 1905 Banaras session of the INC, the Extremists led by Tilak wanted the Congress to:",
    options: ["Support the partition of Bengal.", "Extend the boycott movement beyond Bengal to the whole of India and target the entire British administration.", "Dissolve the Congress and join the British Parliament.", "Ban the use of Hindi in all sessions."],
    correctAnswer: 1,
    explanation: "Extend the boycott movement beyond Bengal.",
    chapterId: 11,
    difficulty: 'Hard'
  },
  {
    id: '11-75',
    question: "Consider the following regarding the 'Annulment of Partition' in 1911: Statement-I: It was announced during the Delhi Durbar by King George V. Statement-II: The Bihar and Orissa provinces were created out of Bengal, and Assam was made a separate province. Which one of the following is correct in respect of the above statements? A. Both Statement-I and Statement-II are correct B. Statement-I is correct but Statement-II is incorrect",
    options: ["Option A", "Option B", "Option C", "Option D"],
    correctAnswer: 0,
    explanation: "Both Statement-I and Statement-II are correct.",
    chapterId: 11,
    difficulty: 'Hard'
  },
];
